### ISSUE TITLE
Ebean loads @OneToMany associations using OUTER JOIN - Reopen

### ISSUE THREAD

**Issue by Chklang** [ebean-orm/ebean#1003]
Hi

I create a new issue because the #48 is close.
I don't understand. You says that "fixed into version 3.3.2" but in version 6.18.1 (used by playframework 2.5.x) there is again a "left outer join". My code : 

```
@Entity
@Table(name = "player")
public class Player extends Model {
	
	public static final Finder<Integer, Player> DAO = new Finder<>(Player.class);

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idplayer")
	private int idPlayer;

	@OneToMany(mappedBy = "player", targetEntity = Planet.class, cascade=CascadeType.ALL)
	private List<Planet> planets;
	
	@OneToMany(mappedBy = "player", targetEntity = PlayerResearch.class, cascade=CascadeType.ALL)
	private List<PlayerResearch> researchs;
}

@Entity
@Table(name = "planet")
public class Planet extends Model {
	
	public static final Finder<Integer, Planet> DAO = new Finder<>(Planet.class);

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idplanet")
	private int idPlanet;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "idplayer", referencedColumnName = "idplayer", nullable = true)
	private Player player;
}

@Entity
@Table(name = "player_research")
public class PlayerResearch extends Model {

	@EmbeddedId
	private PlayerResearchId idPlayerResearch;

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "idplayer", referencedColumnName = "idplayer", insertable = false, updatable = false, nullable = false)
	private Player player;

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "idresearch", referencedColumnName = "idresearch", insertable = false, updatable = false, nullable = false)
	private Research research;
}

@Embeddable
public class PlayerResearchId {

	@Column(name = "idplayer")
	private int idPlayer;

	@Column(name = "idresearch")
	private int idResearch;
}

lPlanet.getPlayer().getResearchs().forEach((PlayerResearch pPlayerResearch) -> {
```

`select t0.idplayer c0, t1.idplayer c1, t1.idresearch c2, t1.idplayer c3, t1.idresearch c4 from player t0 left outer join player_research t1 on t1.idplayer = t0.idplayer  where t0.idplayer = 1   order by t0.idplayer;`

instead of

`select t1.idplayer c1, t1.idresearch c2, t1.idplayer c3, t1.idresearch c4 from player_research t1 where t1.idplayer = 1   order by t1.idplayer;`

Why?

Because the "left outer join" return (1, null, null, null, null)" => Exception on setIdPlayer()

edit : I've added the Planet class because :
Player.DAO.byId().getResearchs() => It's ok but
Planet.DAO.byId().getPlayer().getResearchs() => Use join between Player and Research

**Comment by rbygrave** [comment]
#48 is a different issue to your one.  #48 is specifically about the subsequent lazy loading query (which can use inner join).

Your question is regarding the "origin query".  The reason the join is an outer join is because the many side can be 0.  That is, if we use an inner join and there are no research rows for a given player ... that player would then be excluded from the result.  With the outer join that player is included in the result (with an empty list of research).

I'll close this issue.  In general we want people to ask questions on the google group rather than via github.

Thanks, Rob.
