### ISSUE TITLE
Question: How to define quoted identifiers for schema or table name ?

### ISSUE THREAD

**Issue by thomasguo** [ebean-orm/ebean#1025]
I am using Ebean with mysql database.   One of my entity classes has been annotated with schema name and table name.  In the generated DDL(xxx-create-all.sql and xxx-drop-all.sql),  is like `create table centre.saas_tenant(...)`.  It cannot be executed because mysql asks to quote the schema name.  So it should be like  ```create table `centre`.saas_tenant``` .

### Steps to reproduce
Entity class:
```java
@Entity
@Table(schema = "centre", name = "tenant")
public class Tenant {
    String name;
}
```
Geneated ddl script:
```
create table centre.tenant (
  id                            integer auto_increment not null,
  name                          varchar(255),
  constraint pk_saas_tenant primary key (id)
);
```

**Comment by rbygrave** [comment]
As per the policy stated at: https://ebean-orm.github.io/support
You need to direct questions to the forum at: https://groups.google.com/forum/#!forum/ebean

**Comment by rbygrave** [comment]
Use backticks like:

```java
@Entity
@Table(schema = "`centre`", name = "tenant")
public class Tenant {
    String name;
}
```
... and Ebean translates the backticks into the appropriate open/close quotes based on the database platform.
