### ISSUE TITLE
Support GenerationType.Table

### ISSUE THREAD

**Issue by cablegunmaster** [ebean-orm/ebean#1026]
Dear Ebean github repository maintainer,

I got a question related to the JPA @generatedvalues , is the GenerationType.TABLE supported? Or will it be supported in the future?

## Expected behavior
a ID is generated based on a Table.
## Actual behavior
it refers to a sequence in the DB as default?
### Steps to reproduce
Generate a entity and save it to the DB.

//example data of some entity.
@TableGenerator(name = "VEHICLE_GEN", table = "ID_GEN", pkColumnName = "GEN_NAME", valueColumnName = "GEN_VAL", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "VEHICLE_GEN")
private Long id;
```java
```

```console
Sequence val not found.
```

**Comment by rbygrave** [comment]
As per the policy stated at: https://ebean-orm.github.io/support
You need to direct questions to the forum at: https://groups.google.com/forum/#!forum/ebean

**Comment by cablegunmaster** [comment]
asked question on: https://groups.google.com/forum/#!topic/ebean/GShgKEmao0c
