### ISSUE TITLE
ENH: Add a Slow query event listener ... to log or listen to queries that exceed some defined execution time

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1027]
Although slow queries can be monitored by the DB it can be beneficial to monitor these events in the application.

Add a SlowQueryEvent bean and SlowQueryEventListener interface that we can register via ServerConfig, along with a defined time to determine slow executing queries.

Ebean should also provide an implementation that logs slow queries to the application log.  Perhaps io.ebean.slowquery.

**Comment by lxholding** [comment]
Is a good idea! I need it!

**Comment by rbygrave** [comment]
For basic use specify `ebean.slowQueryMillis=500` via properties or ServerConfig.

Then the logs will contain warning entries for queries exceeding the slowQueryMillis.
```console
WARN  2017-10-03 14:49:40,008 [main] io.ebean.SlowQuery: Slow query warning - millis:821 rows:42825 caller[org.example.domain.DArticleTest.someQuery(DArticleTest.kt:13)] sql[select t0.id, t0.name, t0.brand, ... from product t0]
```

We can also register our own SlowQueryListener to handle/process slow query events.

Note that findEach / findEachWhile / findIterate queries all do no get warnings as they are expected to be larger queries.  The slowQueryMillis applies to all the other orm queries.
