### ISSUE TITLE
Consider adding "Automatic-Module-Name" to MANIFEST.MF for greater JPMS compatibility

### ISSUE THREAD

**Issue by fwgreen** [ebean-orm/ebean#1054]
Now that the final shape of the JPMS has been agreed on, it would be great if projects started the transition. This [blog post](http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html) has some practical approaches to module names.

**Comment by rbygrave** [comment]
Next step is to move the enums in ebean-annotation Platform, PersistBatch, TxIsolation, TxType ... these are in the `io.ebean`  package and they need to move to `io.ebean.annotation` (to avoid a package clash with Ebean itself).

**Comment by rbygrave** [comment]
This was changed in 10.4.5 but only usable in 11.1.1 (which the package changes to support java9).

Done, closing.
