### ISSUE TITLE
findSingleAttributeList doesn't store result in L2 query cache

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean#1060]
The findSingleAttributeList query is not stored in the query cache. We looked at the ebean code and it seems to be missing a putToQueryCache while it is actually trying to get the result from the query cache beforehand (in DefaultServer.findSingleAttributeList).

## Expected behavior

I expect a query with findSingleAttributeList to be cached in the query cache

## Actual behavior

The result is not cached

### Steps to reproduce

Use a findSingleAttributeList query with the query cache

**Comment by rbygrave** [comment]
Thanks, fixed in master.
