### ISSUE TITLE
findCount query is not cached in L2 query cache

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean#1061]
When using the findCount query the result is not cached in the query cache. While it could be useful to cache this information.

## Expected behavior

After a findCount query repeated queries should get count result from the query cache. 

## Actual behavior

findCount query is not cached in the query cache.

### Steps to reproduce

Try to cache any findCount query.

**Comment by rbygrave** [comment]
Thanks again, fixed in master.
