### ISSUE TITLE
Multi-tenant - Update statments should include tenantId in where clause

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1062]
For example,
```sql
update t_product set price=2500.00 where product_id=12345;
```
is not as safe as:
```sql
update t_product set price=2500.00 where product_id=12345 and tenant_id=5;
```

So I suggest, for all ebean-generated sql statements, the tenant_id filter condition will be added automatically by ebean.

**Comment by thomasguo** [comment]
Yes Rob. I am the one submitted this issue on google group initially.  Could we expect it to be fixed in next release?   Thanks.
