### ISSUE TITLE
Add Event Listeners capable of being notified for delete by id or delete by query

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1063]
Now the question is: when I delete by Id or using a query, there aren't any Event Listeners capable of being notified of it.

BeanPersistAdapter only get called when I pass an entity object.

BeanQueryAdapter is called before the query, but I can't tell if it is a FIND, UPDATE or DELETE from the query request.

I think it could be a new method on BeanPersistController and BeanPersistListener.

A "QueryType" on BeanQueryRequest would be useful too.

I think UPDATE has the same needs.

**Comment by smarg120** [comment]
hi, any workaround for this? i am playing with ebean in multi-tenancy(PARTITION) mode....and i found that when i delete by id, the current tenant is being ignored...so user of one tenant can delete objects of other tenants if he got the id...i tried to use BeanPersistAdapter to validate tenant manually, but discovered as well that it is not being called when deleting by id.....btw, i think that delete by id does not honor tenant is a bug by itself...

**Comment by rbygrave** [comment]
We have added a QueryType enum with FIND, UPDATE and DELETE.  This can then be used by BeanQueryAdapters.

```java
  @Override
  public void preQuery(BeanQueryRequest<?> request) {

    Query<?> query = request.getQuery();

    switch (query.getQueryType()) {
      case DELETE: {
        // do something interesting for a delete query
        query.where().raw("3=3");
        break;
      }
      case UPDATE: {
        // do something interesting for an update query
        query.where().raw("2=2");
        break;
      }
      case FIND: {
        query.where().raw("1=1");
        break;
      }
    }
  }
```

**Comment by rbygrave** [comment]
For `delete by  id` we have extended the existing BeanPersistController and BeanPersistAdapter with:

```java
void preDelete(BeanDeleteIdRequest request);
```
and added the associated BeanDeleteIdRequest
```java
package io.ebean.event;

import io.ebean.EbeanServer;
import io.ebean.Transaction;

/**
 * A request to delete a bean by Id value.
 */
public interface BeanDeleteIdRequest {

  /**
   * Return the server processing the request.
   */
  EbeanServer getEbeanServer();

  /**
   * Return the Transaction associated with this request.
   */
  Transaction getTransaction();

  /**
   * Returns the Id value of the bean being deleted.
   */
  Object getId();

}
```

**Comment by rbygrave** [comment]
So that covers the 2 cases and we can close this now.

**Comment by rbygrave** [comment]
Note that we will bump the minor version for this as we are changing the `event API`.
