### ISSUE TITLE
When performing a delete or update query the L2 bean cache for that type is not being invalidated. 

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean#1071]
## Expected behavior

When running the following query:

    int deleted = Ebean.createQuery(OCachedBean.class).delete();

I expect the bean cache to be invalidated for type OCachedBean.class.

## Actual behavior

The cache doesn't seem to be affected.

### Steps to reproduce

See pull request #1070

**Comment by rbygrave** [comment]
Fixed with the extra commit associated with #1070
