### ISSUE TITLE
query table entity or sql entity has no id throw NPE bug

### ISSUE THREAD

**Issue by yuanxuegui** [ebean-orm/ebean#1083]
## Expected behavior
When query table entity or sql entity，include NamedQuery which modified via code and RawSqlQuery which modified via code, findOne or findUnique should get result.
## Actual behavior
Throw NullPointerException.
### Steps to reproduce
`src/test/java/org/tests/rawsql/TestOrderReportTotal.java`
```java
   Query<OrderAggregate> q3 = Ebean.createQuery(OrderAggregate.class).setRawSql(rawSql);
   q3.where().eq("order_id", 1);

   OrderAggregate orderAggregate = q3.findUnique();
```
I already pull request #1082 to fix this the bug.

**Comment by rbygrave** [comment]
Thank you.  Yes, PR is now merged, closing.
