### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by toplinuxsir** [ebean-orm/ebean#1110]
Removed - please ask questions on the forum

**Comment by rbygrave** [comment]
Please read this:

GITHUB ISSUES ARE STRICTLY CONTROLLED FOR THIS PROJECT.

Refer to http://ebean-orm.github.io/support for the policies controlling the use of github issues.
Please post issues to the Ebean group https://groups.google.com/forum/#!forum/ebean first.

I am closing this issue.  You need to ask questions on the forum, thanks.

**Comment by rbygrave** [comment]
The expectation is that we want people to ask questions on the forum and not as issue in github.

We want to keep github issues focused on commits, feature requests, bugs.  I will now close off this ticket.

Thanks.
