### ISSUE TITLE
11.1.1 API change - moved PersistBatch, Platform, TxIsolation and TxType to io.ebean.annotation package

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1123]
For Java 9 modules we need to move  PersistBatch, Platform, TxIsolation and TxType in ebean-annotation into the io.ebean.annotation package.

This has the effect of needing a change to the enhancement (so ebean-agent, maven plugin etc).  This means we really need to move to the major version to 11.

**Comment by rbygrave** [comment]
Hi @rPraml , note that I am looking to get this in shortly.  Let me know what you want to get in first prior to this. Thanks.

**Comment by rPraml** [comment]
It's ok for me if you merge that in. I'm still fixing some tests on dbmigration-4 (I think I will split that PR in smaller ones)
