### ISSUE TITLE
DbMigration generate table name with lower case type?

### ISSUE THREAD

**Issue by someok** [ebean-orm/ebean#1134]
I use `DbMigration` to generate DDL, the table name in sql file are all lower case, but I expect it same as model define.

## Model:
```java
@Entity
@Table(name = "OK_ACTIVITY_LOG")
public class ActivityLog {
}
```

## SQL:
```sql
create table ok_activity_log ();
```

I think `DbMigration` should add a config property to control the table name case.

thinks!

**Comment by someok** [comment]
update:

The table name case is same with model when `DbMigration` generate modify sql:

```sql
alter table SN_SERVICE_NO add column logo_suffix varchar(150);
```

**Comment by rPraml** [comment]
This is related to #1265

**Comment by rbygrave** [comment]
I don't see the motivation for this.  I think this should be closed.
