### ISSUE TITLE
Mapping - Add support for @ElementCollection

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#115]
There is currently no support for the JPA2 mappings.

**Comment by antonsarov** [comment]
Any progress on this one? Or at least a more precise timeframe? Thanks

**Comment by rbygrave** [comment]
No progress per say.  I've pushed the related milestone back to June which
I think is realistic.

Currently the top priority is to update the documentation (and resolve any
bugs found in 4.5.x).

**Comment by luq-0** [comment]
What's the status on this, any progress?

**Comment by rbygrave** [comment]
No change in status.

**Comment by ClaudiaPF** [comment]
Any progress on this?

**Comment by talekardj** [comment]
Hi, any update on this feature ?

**Comment by rbygrave** [comment]
No update.  

People on Postgres will be looking to use @DbArray, anyone can look to use @DbJson ... and otherwise as a workaround it can be mapped as a normal @OneToMany.  If you are wanting to increase the priority you can explain your situation ... but yes there are few things ahead in priority terms.

**Comment by rPraml** [comment]
This breaks test cases with mysql / mariadb - see  #1356 for details.
The problem is the name `key` for dbKeyColumn

**Comment by rbygrave** [comment]
Thanks Roland. I've changed the default map key column name to mkey so we can avoid the issue by default - thanks!!
