### ISSUE TITLE
Mapping - Add support for JOINED and TABLE PER CLASS inheritance strategies

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#116]
These inheritance strategies are not supported.  Consider this in the 5.x timeframe.

**Comment by kbenhdech** [comment]
It seems that the inheritance with strategy 'TABLE_PER_CLASS' now works. Since which version is this the case ?
Thanks.

**Comment by rbygrave** [comment]
It should not work. Have you tested it?

**Comment by PhoenixRion** [comment]
Is SINGLE TABLE still the only supported inheritance strategy?

**Comment by rbygrave** [comment]
Yes. 

Note that in the absence of sponsorship for specific features the priorities are ElasticSearch integration followed by performance monitoring and then by mapping.

**Comment by ncphillips** [comment]
hey @rbygrave, I'm planning on taking a look at this issue. Would you be able to point me to a good starting place?

**Comment by rbygrave** [comment]
Hmm. I think the first thing would be to list the required changes.  So choose one of 'table per subclass' or 'joined' and then list the things that need to change to support that mapping (DDL, query, inserts, updates, deletes) and maybe pseudo code the behavior of each change?  

Then for each specific change (with a pseudo code description) I can help point you into the correct area in the code.

That might be a plan.

**Comment by randikaf** [comment]
Do you have a planned release for this issue?

**Comment by aprasadh** [comment]
Any updates on this issue?

**Comment by ajcamilo** [comment]
Will this feature be implemented in the near future?

Can I help in any way to implement this?

**Comment by rbygrave** [comment]
Near future. Well, no, in that there are other things that are currently a higher priority (documentation, gradle plugin, ebean-elastic, performance monitoring) so for me those other things need attention before this.

> Can I help in any way to implement this?
Do you mean funding the effort or actually implementing the code?

**Comment by ajcamilo** [comment]
I meant actually implementing the code. 

But I have no clue where to start. :disappointed:

**Comment by jcarloshorus** [comment]
Is there any way around this? I used @JoinColumn (simulating @SecondaryTable) but the changes made to columns with the table attribute set to the second table are not persisted.

If there is no form, I would like to collaborate with the implementation.

**Comment by jcarloshorus** [comment]
Hello, I would like to collaborate with the development of this isshue, since I depend on this functionality to implement a project which has entities with many inherited JOINED type;

I downloaded the github code, did some analysis and realized the following needs:

1) io.ebeaninternal.server.deploy.InheritInfo
add InheritanceType inheritanceType;

2) io.ebeaninternal.server.deploy.parse.DeployInheritInfo
line 115: info.setInheritanceType (ia.strategy ());

3) io.ebeaninternal.server.deploy.BeanProperty
to use the inherited boolean attribute
use the owningType attribute to infer the source table of the property

Rob, so I can cope with the implementation, I'd like you to guide me and if you can, that create a specific branch for that isshue !?

**Comment by IvanAR** [comment]
@rbygrave This is interesting for us too, could you help @jcarloshorus ?

**Comment by jcarloshorus** [comment]
@IvanAR I'm working on it (whenever i can) and I already did some improvements. Soon, I will commit so others can collaborate.

**Comment by sanuradhag** [comment]
Any updates?

**Comment by rbygrave** [comment]
I suspect not looking at the fork - https://github.com/jcarloshorus/ebean

For myself the priorities are still with other tasks such as performance monitoring and documentation (and I can't remember the last time anyone assisted with the documentation which is a big task that will take a lot of time).  In terms of donations and sponsorship there isn't anything there to adjust priorities or accelerate progress.

If there was assistance for documentation, donations or sponsorship that would help move things forward faster.

**Comment by rbygrave** [comment]
So marking this as a `Limitation` and closing this for now.

This has been open for a few years and has obtained no sponsorship to assist in the development effort.  I'm comfortable marking this as a known limitation and closing this makes it clearer that this is not on the roadmap.
