### ISSUE TITLE
How can I can table name based on the instance value.

### ISSUE THREAD

**Issue by Maghaen** [ebean-orm/ebean#1195]
I found MatchingNamingConvention can't do this. such as i have class , and has a month property, my table name is xxx_month, month is property value. it can't do this.  thanks.

**Comment by rbygrave** [comment]
Please note that questions should be posted to the forum and not logged as github issues as per the policy for this product.

Please refer to http://ebean-orm.github.io/support for the policies controlling the use of github issues.
Please post issues to the Ebean group https://groups.google.com/forum/#!forum/ebean first.

**Comment by rbygrave** [comment]
Closing, please post questions to the forum as is the policy for this project.
