### ISSUE TITLE
How to enhance ebean models in a jar

### ISSUE THREAD

**Issue by fandayrockworld** [ebean-orm/ebean#1203]
I collect all the public models into an independent project and deploy it on my NEXUS repo for that all projects can use it.
but how can I enhance models in this jar?

I use the agent like this:
```java
if (!AgentLoader.loadAgentFromClasspath("avaje-ebeanorm-agent",
				"debug=1;packages=apps.models.**")) {
    logger.info("avaje-ebeanorm-agent not found in classpath - not dynamically loaded");
}
```

thanks

**Comment by dastultz** [comment]
On Mon, Nov 6, 2017 at 8:44 AM, fjh <notifications@github.com> wrote:

> I collect all the public models into an independent project and deploy it
> on my NEXUS repo for that all projects can use it.
> but how can I enhance models in this jar?
>
Enhance them before you make the jar.

/Daryl

**Comment by rbygrave** [comment]
Refer to http://ebean-orm.github.io/docs/setup/enhancement

For maven users use the tile (which configures enhancement for both
src/main and src/test and brings in the code generator plugin) or use the
maven plugin directly.


Note that the versions mentioned in the documentation are slightly old now
and need updating.


Cheers, Rob.

**Comment by fandayrockworld** [comment]
Hi, @dastultz 

I have enhanced them before make the jar.
But it also:
```java
javax.persistence.PersistenceException: apps.models.system.SEmployee is NOT an Entity Bean registered with this server?
```
My ebean version is 6.1.1, also in 'org.avaje.ebeanorm ' age.

**Comment by dastultz** [comment]
You need to tell Ebean to look in the jar for the entities. Specify this
property:

ebean.search.jars=my-entities.jar

**Comment by fandayrockworld** [comment]
Hi, @dastultz

I also added. But wrong.

**Comment by fandayrockworld** [comment]
sorry, I checked my ebean.properties and spring.xml again, and found that I use spring.xml to assign the properties. And I modified the ebean.properties before. 
So, after I modified the spring.xml as below:
```xml
        <bean id="serverConfig" parent="defaultEbeanServerConfig">
		<property name="dataSource" ref="dataSource" />
		<property name="name" value="default" />
		<property name="ddlGenerate" value="false" />
		<property name="ddlRun" value="false" />
		<property name="defaultServer" value="true" />
		<property name="jars" value="trex-bean-0.0.6.jar" />
	</bean>
```

And also I removed the code below too:
```java
	if (!AgentLoader.loadAgentFromClasspath("avaje-ebeanorm-agent",
				"debug=1;packages=apps.models.**;jars=trex-bean-0.0.6-SNAPSHOT.jar")) {
		logger.info("avaje-ebeanorm-agent not found in classpath - not dynamically loaded");
	}
```
BTW:  The classes in trex-bean-0.0.6-SNAPSHOT.jar were enhanced before made the jar.

Then it works!

**Comment by rbygrave** [comment]
Please note that questions should be posted to the forum and not logged as github issues as per the policy for this product.

Please refer to http://ebean-orm.github.io/support for the policies controlling the use of github issues.
Please post issues to the Ebean group https://groups.google.com/forum/#!forum/ebean first.
