### ISSUE TITLE
Hope add search function on support page

### ISSUE THREAD

**Issue by reezhu** [ebean-orm/ebean#1208]
sometimes it's hard to find a specific hint on http://ebean-orm.github.io/ it will be wonderful if you can add such a function like global search.

**Comment by gimmebytes** [comment]
@reezhu 

Try using Google for that until @rbygrave comes up with an internal search page

e.g.

![grafik](https://user-images.githubusercontent.com/1862500/33311497-420bd19e-d425-11e7-8ea8-312b13f384cd.png)

**Comment by rbygrave** [comment]
Done.  Updated the documentation, still a lot to do in terms of re-organising the docs etc ... but we have integrated a search in the /docs section thanks to Algolia (so thanks to them for providing that service).

Closing.
