### ISSUE TITLE
Why does ebean filter out result Collection with id is null?

### ISSUE THREAD

**Issue by liudaomanbu** [ebean-orm/ebean#1210]
I have a Enterprise Class and a EnterpriseTarget Class.
Now i have a requirement that get EnterpriseTargets when EnterpriseTarget table don't have this Enterprise data.
So i use left join and left table is Enterprise.

```
SELECT
	enterprise_target.id AS id,
	enterprise. NAME ...
FROM
	enterprise
LEFT JOIN enterprise_target ON enterprise. CODE = enterprise_target.ent_code
WHERE...
```

Then i found the result of execute sql in navicat and the result of ebean is different.
I found the reason that ebean filter out result Collection with id is null by debug.

Can i cancel this filter?
If can't,can i only merge the EnterpriseTargets of select result and the EnterpriseTargets from Enterprise transform?

**Comment by rbygrave** [comment]
Hi @cao19920425 ... as per the policy stated at https://ebean-orm.github.io/support ... we ideally want questions posted to the google group at https://groups.google.com/forum/#!forum/ebean

Thanks

**Comment by rbygrave** [comment]
I'll close this, post on for forum for additional questions if you can.
