### ISSUE TITLE
org.joda.time.LocalDate fields in our models no longer serialized into strings

### ISSUE THREAD

**Issue by FrancisAni** [ebean-orm/ebean#1216]
After updating from Play 2.3 to Play 2.4 and updating ebean to version 4.6.3, our jodatime LocalDate fields are no longer serialized into strings.  

When stepping through the code, the ScalarTypeBaseDate.java jsonWrite method eventually converts our desired string into a long.  Is there a workaround for this?

**Comment by rbygrave** [comment]
Via ServerConfig you can set how DateTime types are serialised by JSON.

You can set:
```java
serverConfig.setJsonDateTime(JsonConfig.DateTime.ISO8601)
```
Or via properties: `ebean.jsonDateTime=ISO8601`

**Comment by rbygrave** [comment]
That is `io.ebean.config.ServerConfig`.  Hopefully you have a mechanism to configure that.

**Comment by rbygrave** [comment]
I'll close this assuming it answered your question.

**Comment by FrancisAni** [comment]
The JsonConfig.DateTime.ISO8601 property didn't end up working because that is only used in ScalarTypeBaseDateTime's jsonWrite method.  Joda's LocalDate uses ScalarTypeJodaLocalDate which extends ScalarTypeBaseDate instead of ScalarTypeBaseDateTime.

My tech lead told me to try something which ended up working.  We created our own custom ScalarTypeLocalDate which overrides the jsonWrite method.
```
public class CustomScalarTypeLocalDate extends ScalarTypeLocalDate {

    @Override
    public void jsonWrite(JsonWriter writer, String name, LocalDate value) throws IOException {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        writer.writeStringField(name, value.format(formatter));
    }
}

```
 This custom class can be in the same directory as the models.  We put it into a separate package called customscalartypes and adjusted our application.conf.
`
ebean.default=["models.*","customscalartypes.*"]
`
