### ISSUE TITLE
Add support to not generate FK Constraint when @JoinColumn(foreignKey=@ForeignKey(ConstraintMode.NO_CONSTRAINT))

### ISSUE THREAD

**Issue by evaristowb** [ebean-orm/ebean#1228]
Add support to not generate Fk Constraint. 

Even that I define @JoinColumn with no fk constraint, the DDL generated through migrations.

```java
@Entity
public class Company {

    @Id
    private UUID id;

}

@Entity
public class Professional {

    @Id
    private UUID id;

    @ManyToOne
    @JoinColumn(name = "company_id", 
        foreignKey = @ForeignKey(ConstraintMode.NO_CONSTRAINT), nullable = false)
    private Company company;

}
```

```sql
create table company (
  id                            uuid not null,
  constraint pk_company primary key (id)
}
create table professional (
  id                            uuid not null,
  company_id                    uuid not null,
  constraint pk_professional primary key (id)
);

alter table professional add constraint fk_professional_company_id 
foreign key (company_id) references company (id) on delete restrict on update restrict;
create index ix_professional_company_id on professional (company_id);
```

According to the previous issues #644, you asked the scenario that motivates it, my scenario is that I have a microservice architecture so I have to deal with eventual consistence via microservices sync process, it is import having a way to disable fk constraint creation in DDL but control the entity relationship because I navigate through the relationships in my business layer.

The index created is intended in order to favour the load.

**Comment by rbygrave** [comment]
Yes I understand this and yes we can look to make this change.

Note that this also relates to #323 which I have just updated. With that we will have the option for:

```java
// no constraint but still have an index created
@OneToMany
@DbForeignKey(noConstraint=true)
```

```java
// no constraint and no index created 
@OneToMany
@DbForeignKey(noConstraint=true, noIndex=true)
```

**Comment by rbygrave** [comment]
Note that in general we most often do not need `@JoinColumn` at all as long as the columns match the naming convention (which they generally do). This means that JPA putting the ForeignKey annotation on the JoinColumn is not so great IMO - one of the reasons to have add `@DbForeignKey` with #323 .
