### ISSUE TITLE
Mapping - Add support for OneToMany JoinTables

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#123]
Refer:
http://www.java2s.com/Tutorial/Java/0355__JPA/OneToManyJoinTableSetup.htm

Hi all,

On further investigation, I'm pretty sure that what I'm trying to do
is legit. It's a unidirectional oneToMany and I can see some examples
of using JPA to set it up:

http://www.java2s.com/Tutorial/Java/0355__JPA/OneToManyJoinTableSetup.htm
http://tadtech.blogspot.com/2007/09/hibernate-annotation-one-to-many-join.html

In Hibernate, for example, unidirectional appears to be the preferred
option.

I thought it might be that the Car had to specify all the details of
the join, so I tried this:
...

**Comment by konradr25** [comment]
Has anything changed? As far as I can see  version "8.4.1" still doesn't support OneToMany with JoinTable...

**Comment by rbygrave** [comment]
This specific issue is still open yes.

**Comment by rbygrave** [comment]
Done, closing.
