### ISSUE TITLE
Performance: Add support for a second read-only DataSource (for implicit query-only transactions) 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1232]
This provides us with 2 benefits:
- Performance improvement where we can use a read-only AutoCommit DataSource and avoid explicit calls to `commit()` at the end of a read-only transaction
- Ability to easily use Database read replicas (like AWS Aurora or any read replica setup via a second DataSource)

 Note that the read only DataSource is expected to use `autoCommit` `true` as that shows a nice performance boost in the profiling I have been running.  It is significant enough to suggest this will become the default setup in a future release (that we default to using 2 DataSources).

### Example 1
```java
// Set a second read only dataSource ...
// ... when you want to supply a DataSource rather than 
// ... get Ebean to configure it 
serverConfig.setReadOnlyDataSource(dataSource)
```

### Example 2
```java
// Get Ebean to create the read only DataSource automatically
// This will use config from dataSourceConfig
serverConfig.setAutoReadOnlyDataSource(true)
```

### Example 3
```java
// Get Ebean to create the read only DataSource automatically
serverConfig.setAutoReadOnlyDataSource(true)

// specify some specific configuration for it ...
DataSourceConfig readOnlyConfig = serverConfig.getReadOnlyDataSourceConfig();
readOnlyConfig.setUrl("read only specific url")
readOnlyConfig.setUrl("jdbc:postgresql://readOnlyNode1/...?targetServerType=preferSlave")

```

**Comment by dastultz** [comment]
Brilliant! We're going to need this soon!

**Comment by rbygrave** [comment]
## When is the read-only DataSource used?

When we execute a `Query` Ebean checks to see if there is a current transaction.  If no current transaction exists then Ebean creates what we call an `implicit transaction` ... when the Query is not a bulk update or delete query then Ebean knows that this transaction is only going to be used for executing a select statement (read only fashion).

So when Ebean is creating an `implicit transaction` to execute a `select` then it will use the read only DataSource if there is one defined. 

That is, we don't need to change the application code in order to use this read-only DataSource.

 
## Can we specify a Query to NOT use the read-only DataSource?

Not yet.  We probably need to add something like:
```java
query.setMasterDataSource(true)
```

**Comment by oexza** [comment]
Fantabuwonderific!!!!

**Comment by oexza** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/f5af17162e",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Peace is tired of keeping Fiverr a secret.
    

    
        Discover the easiest way to hire online freelancers and get 20% off your first order. From marketing to tech, complete all your projects on Fiverr. On budget. On time.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2018, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    
If you would like to unsubscribe and stop receiving these emails click here.
