### ISSUE TITLE
Throw explicit mapping error when an Enum is mapped to both ORDINAL and STRING

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1259]
So Ebean doesn't support mapping a single Enum type to both ORDINAL and STRING. 

This is generally because it makes the binding of the enum values path specific ... which makes the enum somewhat unusable for use with findNative() and RawSql and anywhere else we bind the type and don't know the `property path`.

What this change does, is detect when the same Enum is mapped in different ways and throws a reasonable exception to indicate that this is not supported.

### Steps to reproduce

```java

// where EAddressStatus is an Enum ...

@Entity
public class Foo {
  ...
  @Enumerated(EnumType.STRING)
  EAddressStatus status;

  @Enumerated(EnumType.ORDINAL)
  EAddressStatus otherStatus;

```

```console
Caused by: javax.persistence.PersistenceException: Error mapping property org.tests.model.embedded.EAddress.otherStatus - Error mapping Enum type:class org.tests.model.embedded.EAddressStatus It is mapped using 2 different modes when only one is supported (ORDINAL, STRING or an Ebean mapping)
	at io.ebeaninternal.server.deploy.parse.DeployUtil.setEnumScalarType(DeployUtil.java:123)
	at io.ebeaninternal.server.deploy.parse.AnnotationFields.readField(AnnotationFields.java:184)
	at io.ebeaninternal.server.deploy.parse.AnnotationFields.parse(AnnotationFields.java:116)
	at io.ebeaninternal.server.deploy.parse.ReadAnnotations.readInitial(ReadAnnotations.java:57)
	... 35 more
```

**Comment by nicolasblaye** [comment]
Hi @rbygrave , I have came across a problem that I think can be linked to this but I am unsure (the error is the same). I upgraded ebean from `10.4.x` to 11.15.4` via the `sbt-play-ebean` plugin. We have the following mapping.

```java
public enum CookieSyncingIntegrationType {
    @EnumValue("script")
    SCRIPT,
    @EnumValue("image")
    IMAGE,
    @EnumValue("iframe")
    IFRAME;

    @Override @DbEnumValue
    public String toString() {
        return name().toLowerCase();
    }
}

public class MyDummyClass {
    @Column(name = "cs_integration")
    @Enumerated(EnumType.String)
    private CookieSyncingIntegrationType csIntegration;
}
```


This used to work in the 10.x but it doesn't work anymore. Removing @Enumerated seems to do the trick. If this is expected, can you tell me why? I am curious to why this doesn't work anymore.

**Comment by rbygrave** [comment]
Only use 1 mapping (how an enum value is mapped to a DB value).

In the above you are using 3
- JPA @Enumerated
- Ebean @EnumValue
- Ebean @DbEnumValue

You should only use 1 of those (to specify how an enum value is mapped to a db value) and remove the other 2.
