### ISSUE TITLE
[Revert - No change] ENH: Make Transaction API Fluid such that we can set multiple thing like batchSize and label in a fluid fashion

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1263]
# Reverted by #1276 

THIS CHANGE HAS BEEN REVERTED BY #1276 in 11.12.1  ... it was deemed a bad idea in that it could option the option of resource leaking by chaining methods as part of `beginTransaction()` so we are going the more conservative route and reverting the fluid API style from Transaction.

## Example

```java
    Transaction transaction = server.beginTransaction()
      .setPersistCascade(false)
      .setBatchSize(10)
      .setBatch(PersistBatch.ALL)
      .setLabel("TestBatchInsertFlush.no_cascade");

```

**Comment by rPraml** [comment]
Hello Rob, I feel a bit unconfortable about your example.

I have the point of view, that "beginTransaction" (or anything that is closeable) should always be followed by `try`, or opened in a `try-with-resources` statement, if it is possible. So
```java
try (Transaction transaction = server.beginTransaction()) {
      transaction.setPersistCascade(false)
        .setBatchSize(10)
        .setBatch(PersistBatch.ALL)
        .setLabel("TestBatchInsertFlush.no_cascade");
}
```
ensures, that the transaction will be closed again, if one of the setters fails.

ok... it's not possible in your example but `setReadOnly` can fail or code will be changed in the future. Think about this example:
```java
    Transaction transaction = server.beginTransaction()
      .setPersistCascade(false)
      .setBatchSize(myAppConfig.getBatchSize())
      .setBatch(PersistBatch.ALL)
      .setLabel("TestBatchInsertFlush.no_cascade");
```
getBatchSize can fail, or myAppConfig can be null - in both cases you have a leaked transaction.

So, what do you mean? (maybe I'm too paranoid ;) )

Cheers
Roland

**Comment by rbygrave** [comment]
Hi Roland, I like your concern. I missed that consideration of resource leaking.  My original thought actually was triggered by ... Use of @Transactional followed by getting the current transaction and setting properties on the transaction (that are not available on the @Transactional annotation).

Anyway, your point is good.  We are only doing this for "syntactic sugar" reasons ... but in doing so we open up the chance of resource leaking.

So I'll review this but yes I am leaning towards backing out this change such we encourage safe use.

Cheers, Rob.

**Comment by rbygrave** [comment]
Pushed revert for 11.12.1.

Closing again.
