### ISSUE TITLE
Multi-tenant - partition mode - Delete by id does not include tenantId value in predicate

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1270]
When deleting a bean by Id value the predicate in the SQL delete statement should include the tenantId.

### Steps to reproduce

```java
Ebean.delete(Content.class, idValue);
```

```sql
delete from content where id = ?
```

## Expected behaviour

```sql
delete from content where id = ? and tenant_id = ?
```

**Comment by smarg120** [comment]
hi, thanks a lot

did you mean in expected behaviour:
delete from content where id = ? AND tenant_id=?

**Comment by rbygrave** [comment]
Yes I did :) ... fixing that now - thanks.

**Comment by rbygrave** [comment]
I have the fix running locally, I'll look to review it again tomorrow morning and merge it in then. We will very likely release 11.11.1 tomorrow.

Cheers, Rob.

**Comment by smarg120** [comment]
these are great news!

thank you

**Comment by simongodard** [comment]
Thank you very much Rob!It will greatly improve our queries 💯
