### ISSUE TITLE
ENH: Add DtoQuery ... such that we can map native SQL queries automatically into "DTO beans"

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1297]
## Expected behavior

Create beans with setter methods ... or "bean like" with constructors or "bean like" with constructors and setters.

The DtoQuery when executed will automatically map the JDBC ResultSet into the "beans" using JDBC meta data and bean property names.

The mapping is cached as a "dto query plan" so we only read perform the mapping when we first see the query for the given DTO bean and consequently we can just get the query plan and read the resultSet.

The DTO beans do not need to be registered or known to Ebean. It will read the bean property information at runtime and cache it as it does so.

### Examples

```java
    // 3 columns in the resultSet
  
    String sql = "select c.id, c.name, count(o.id) as totalOrders " +
      "from o_customer c " +
      "join o_order o on o.kcustomer_id = c.id " +
      "where c.name like :name " +
      "group by c.id, c.name";

    List<DtoCustomer> dtos = server().findDto(DtoCustomer.class, sql)
      .setParameter("name", "Rob")
      .findList();

```
- The resultSet has 3 columns
- We don't have a constructor that exactly has 3 arguments
- But we have more columns that our largest constructor

**Mapped by:**
We will map the resultSet above using the largest constructor (and only constructor in this case) + map the 3rd DB column which is `TOTALORDERS` to the setter method `setTotalOrder()`

```java
  public class DtoCustomer {

    final Integer id;

    final String name;

    int totalOrders;

    // constructor with 2 arguments ... 
    public DCust(Integer id, String name) {
      this.id = id;
      this.name = name;
    }

    @Override
    public String toString() {
      return "id:" + id + " name:" + name + " totalOrders:" + totalOrders;
    }

    public Integer getId() {
      return id;
    }

    public String getName() {
      return name;
    }

    public int getTotalOrders() {
      return totalOrders;
    }

    public void setTotalOrders(int totalOrders) {
      this.totalOrders = totalOrders;
    }
  }
```

**Comment by rbygrave** [comment]
## Invoke dynamic / Method handles

Note that we perform the mapping using `MethodHandle`s rather than reflection.  That does mean it expects the Constructor and Setter methods to have `public` access.

**Comment by rbygrave** [comment]
## firstRow / maxRows
We can use setRow() setMaxRows() to apply paging to the query.
```java
    String sql = "select id, name, 42 as totalOrders from o_customer where name like ?";

    List<DCust3> robs = server().findDto(DCust3.class, sql)
      .setParameter(1, "Rob")
      .setMaxRows(10)
      .findList();
```
```sql
select id, name, 42 as totalOrders 
from o_customer where name like ? limit 10; --bind(Rob)
```

**Comment by rbygrave** [comment]
## query.setRelaxedMode()

By default when performing the mapping, if we are not able to map a column to a property (setter method) then an exception is thrown.

Instead we can set `relaxed mode` on the query and that means it will effectively ignore/skip any column that it can't map. 

This is expected to be useful when there is potentially a large existing query and there is a desire to only map some of the columns into bean properties.

```java
   // we can map the first and last columns
   // ... but we can't map the something_we_cannot_map column

   String sql = "select id, '42' as something_we_cannot_map, name from o_customer";

    List<DCust2> list = server().findDto(DCust2.class, sql)
      .setRelaxedMode()
      .findList();
```

**Comment by rbygrave** [comment]
## query.setLabel("totalByMonth")

Note that in general it is a good idea to set a `label` on the queries. This can make is easier to relate query execution statistics back to the actual code and query.

**Comment by vnnv** [comment]
Very nice feature! Thanks a lot :)

**Comment by cchjgood** [comment]
Very nice feature! Thanks a lot :)
