### ISSUE TITLE
ENH: Add initial Cockroach DB support ... need to review JSON support

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1344]
Refer to https://www.cockroachlabs.com/

Still need to review:
- JSON type

**Comment by rbygrave** [comment]
Refer to https://github.com/cockroachdb/cockroach/issues/6583 .. for the status on `select for update`

**Comment by rbygrave** [comment]
Hmmm, kind of interesting because `optimistic locking` effectively doesn't work at `serialisable` isolation level ... we generally want to run at `read committed` isolation level for this reason (on MVCC databases at least).

We can simulate a real db lock (that we get via `select for update`) by using optimistic locking somewhat but ... we don't have automatic cleanup of the locks and we don't have the nice waiting features that are built into the `select for update` options.

**Comment by rbygrave** [comment]
Ok, so I think this is done (but expecting some movement with JSON type and expressions support).

Closing.

**Comment by 0xbaadf00d** [comment]
Next major version of cockroach (2.x) will be released at the end of March 2018. This new version be more compatible with PostgreSQL behaviour like any(), json_*(), ...

You can use preview build: https://www.cockroachlabs.com/docs/dev/install-cockroachdb.html
