### ISSUE TITLE
Postgres triggers for @History tables rely on current search_path

### ISSUE THREAD

**Issue by ksperling** [ebean-orm/ebean#1359]
Assume I've got my ebean-managed tables in schema `myapp`, including a table `foo` with `@History` enabled.

## Expected behavior

A statement like `update myapp.foo set ...` should work even if `search_path` is not set to `myapp`. In practice this happens for me when accessing the DB through pgAdmin.

## Actual behavior

Trigger function causes an error `ERROR:  relation "foo_history` does not exist.

### Steps to reproduce

- Set up ebean-managed DB with a `@History` table in a schema that's not the default for the user.
- Connect using e.g. psql and run an update on the history-enabled table using a qualified table name without setting `search_path` to that schema.

### Solution idea

The schema of the triggering table can be accessed within the trigger function via `TG_TABLE_SCHEMA`, which would allow the trigger to work correctly independently of the current `search_path`, so the current ```insert into foo_history``` statement could be replaced with something like ```execute format('insert into %I.foo_history ...', TG_TABLE_SCHEMA);```

**Comment by rbygrave** [comment]
How do you specify the schema?  Is it in the `@Table` annotation?

**Comment by ksperling** [comment]
In the JDBC URL, e.g. `jdbc:postgresql://172.28.128.6/postgres?currentSchema=myapp,extensions&user=bla&password=bla`.

The code and any generated DDL or migration scripts I have are schema agnostic and I can have multiple application environments on the same physical DB just by pointing them at a different schema name for example.

**Comment by ksperling** [comment]
I guess another option would be to try to determine the current schema at the point where the `create or replace function foo_history_version` DDL runs, i.e. to generate the function source code dynamically and bake the schema name in at that point, like so:

```
do language plpgsql $do$ begin execute format($ddl$
  create or replace function foo_history_version() returns trigger as $$
  begin
    if (TG_OP = 'UPDATE') then
      insert into %1$I.foo_history (sys_period,id, bla) values (tstzrange(lower(OLD.sys_period), current_timestamp), OLD.id, OLD.bla);
      NEW.sys_period = tstzrange(current_timestamp,null);
      return new;
    elsif (TG_OP = 'DELETE') then
      insert into %1$I.foo_history (sys_period,id, bla) values (tstzrange(lower(OLD.sys_period), current_timestamp), OLD.id, OLD.bla);
      return old;
    end if;
  end;
  $$ LANGUAGE plpgsql;
$ddl$, current_schema()); end $do$;
```

**Comment by ksperling** [comment]
A working version of the dynamic insert looks like this (need to pass in `OLD` via `using OLD`):

```
execute format('insert into %I.foo_history (sys_period,id, bla) values (tstzrange(lower($1.sys_period), current_timestamp), $1.id, $1.bla);', TG_TABLE_SCHEMA) using OLD;
```

Not sure which version is "better"; using `TG_TABLE_SCHEMA` feels in some sense more obvious as that's provided by PG for this kind of stuff, on the other hand the function is tied to a specific table anyway, so baking the schema in when the function is created avoids any runtime overhead / complexity. Presumably it also makes the code of the function itself look the same as if a schema name was supplied in some other way (is `@Table(schema="x")` supported?)

**Comment by rbygrave** [comment]
An alternative solution for the generated DDL to include an expression like `${schema}` and thus the tables, tiggers, procedures etc can all use fully qualified names.

Both Flyway and  Ebean DB Migration support using expressions.  I think it would be a matter of also making it easy to use when the `db-create-all.sql` is used.

This solution would have no runtime overhead and be usable for other DB's like MySql.

I'll ponder this some more.

**Comment by ksperling** [comment]
Ah, I wasn't aware of the placeholder support. I guess some code would be required to make `${schema}` automatically available from ebean config with fallback to the connection, so it doesn't have to be duplicated in the migration config settings. Other than that this sounds like a very neat solution.

**Comment by rbygrave** [comment]
Hi @ksperling ... what is the status of this issue now?  Do we need to re-visit how the DDL generation works wrt schema ?

Thanks, Rob.

**Comment by rbygrave** [comment]
I'll close this for now.
