### ISSUE TITLE
Consider support timeliness record

### ISSUE THREAD

**Issue by fengbaicanhe** [ebean-orm/ebean#1362]
Ebean is a fantastic orm solution, i found there is already support soft delete and draftable record, I think there is nice to have timeliness support.

For example, an advertisement have it's from date(when show) and deadline date(when invisible), when i query advertisement, it's nice to return all no deleted(or soft deleted), time valid advertisement.

Also, it's nice to have other apis like query recored by time range, or check is alredy have a record in a time range!

Thanks!

**Comment by fengbaicanhe** [comment]
Timeliness record is wildly used in enterprise system, like login account time control, product sale time control, promotion time control, coupon time control and so on

**Comment by rbygrave** [comment]
It is not clear what you are proposing here.  I suggest you start a discussion thread on the forum https://groups.google.com/forum/#!forum/ebean ... outlining exactly what you are hoping for with an example.  

Thanks, Rob.

**Comment by rbygrave** [comment]
We will close this ticket while we wait for more clear details on exactly what is being proposed here.  Once we have the details we can look to re-open at that point.

Cheers, Rob.
