### ISSUE TITLE
Lazy loaded child beans without @Ids are not attached to a parent bean

### ISSUE THREAD

**Issue by vkuzel** [ebean-orm/ebean#1381]
## Expected behavior

A Parent bean has an `@OneToMany` list of child beans. Child bean does not have an `@Id` field. A getter `Parent.getChildren()` should return list of child beans if there are any.

## Actual behavior

If an `@Id` field is not specified in child bean or child beans are not prefetched, children are loaded from database but not attached to a parent bean.

### Steps to reproduce

Let's have a schema...
```sql
CREATE TABLE airplanes (
  id INT PRIMARY KEY
);

CREATE TABLE passengers (
  airplane_id INT REFERENCES airplanes
);

INSERT INTO airplanes VALUES (1);
INSERT INTO passengers VALUES (1);
```

...and related beans...
```java
// Airplane.java
@Entity
@Table(name = "airplanes")
public class Airplane {

    @Id
    private int id;
    @OneToMany
    private List<Passenger> passengers;

    // Getters and setters are ommited...
}
// Passenger.java
@Entity
@Table(name = "passengers")
public class Passenger {

    @ManyToOne
    private Airplane airplane;

    // Getters and setters are ommited...
}
```

Following test should pass...
```java
@Test
public void airplaneTest() {
    Airplane airplane = ebeanServer.find(Airplane.class, 1);
    Assert.notEmpty(airplane.getPassengers(), "There are no passengers!");
}
```

...but it throws an error. According to log, Airplane and Passengers are loaded from database.
```console
15:02:00.621 [main] DEBUG io.ebean.SQL - txn[1007] select t0.id from airplanes t0 where t0.id = ?  ; --bind(1, )
15:02:00.621 [main] DEBUG io.ebean.SUM - txn[1007] FindBean type[Airplane] origin[BkO2fj.A.A] exeMicros[940] rows[1] bind[1, ]
15:08:13.209 [main] DEBUG io.ebean.SQL - txn[1008] select t0.airplane_id from passengers t0 where (t0.airplane_id) = any(?); --bind()
15:08:13.209 [main] DEBUG io.ebean.SUM - txn[1008] FindMany mode[+lazy] type[Passenger] origin[BkO2fj.A.A] load[path:passengers size:1] exeMicros[17621] rows[1] predicates[(t0.airplane_id) = any(?)] bind[]

java.lang.IllegalArgumentException: There are no passengers!
```

By observation I found:
* Adding `@Id` to the Passenger bean helps.
* Prefetching passengers by `Airplane airplane = ebeanServer.find(Airplane.class).fetch("passengers").where().idEq(1).findOne();` helps.
* Specifying eager fetching strategy on airplane -> passengers relation `@OneToMany(fetch = FetchType.EAGER)` does not help.

### Potential fix

The problem is in the `SqlTreeNodeBean.load()` which does not call `ctx.setLazyLoadedChildBean(localBean, lazyLoadParentId);` for child beans without `@Id`. So, Passengers are loaded from database then not attached to Airplane and thrown away.

```java
if (!readId || temporalVersions) {
  // a bean with no Id (never found in context)
  if (lazyLoadParentId != null && desc.isElementType()) { // In our case desc.isElementType() is false.
    ctx.setLazyLoadedChildBean(localBean, lazyLoadParentId);
  }
  return localBean;

} else {
  if (lazyLoadParentId != null) {
    ctx.setLazyLoadedChildBean(contextBean, lazyLoadParentId);
  }
  return contextBean;
}
```

**Comment by rbygrave** [comment]
> Child bean does not have an @Id field

What makes you think that is a valid mapping?  

JPA doesn't allow any entity beans to not have an `@Id` property.  Ebean allows it for `@Sql` / reporting type entity beans ... but otherwise an `@Entity` should have an `@Id` property so to me this is not a valid mapping.

What is the reason for not mapping an `@Id` property on the child bean?

Cheers, Rob.

**Comment by rbygrave** [comment]
On second look ... `CREATE TABLE passengers` ...  the passengers table does not have a primary key.  That suggests for this case maybe you are really looking to use `@ElementCollection` and not `@OneToMany` ?

Yes Ebean has support for `@ElementCollection` so yes you could look to do that.  My own personal feeling / opinion is that I get a very uneasy feeling deep in my gut when I see a DB Table without a primary key (and that is what you get with element collection).  For me the use of `@ElementCollection` could be legit on a DB that does not have support for array types - I'd never use it on Postgres.

I'd encourage people to think long and hard before you commit to using element collection and tables without a primary key.

**Comment by vkuzel** [comment]
Passengers table is just an over-simplyfied example created just for this bug report. In real life it is a non-updatable view (annotated with `@View`) that has relations to some other entities. `View { @ManyToOne private OtherEntity otherEntity }`

Since Ebean supports [entities without `@Id`](http://ebean-orm.github.io/architecture/compare-jpa) and treats these as read-only, my idea was to use this behaviour to attach some related view data to parent entity.

Anyway, I believe the real question here is:

* Should Ebean support this behaviour?
* Or, should it throw an error without failing silently? (actually running a query and then throwing fetched data away)

**Comment by rbygrave** [comment]
> that has relations to some other entities.

This is the key statement as I see it.  To have `relationships to other entities` then an entity really should have an Identity (so it should have a `@Id` property).

An `@ElementCollection` (in my words) is owned by an entity.  It does not have it's own identity (it's identity comes from the entity that owns it), it does not have its on life cycle (it can't be independently inserted, updated or deleted).

An Ebean `@Sql` entity does not have to have an `@Id` - it does not have to have an identity but that does mean that it should not have relationships to any other entities. 

If an entity has 'relationships' then it should have an identity and should have a `@Id` property.



> Should Ebean support this behaviour?

This is not a bug.  What that means is you need to provide justification that the added complexity of supporting it is out weighed by the benefit. 

You have to state why you are unable to find/derive/create an `@Id` property on passengers. 

Right now - I don't see the justification for supporting this no.

**Comment by vkuzel** [comment]
Ok, I am closing this.
