### ISSUE TITLE
Optional OneToOne with PrimaryKeyJoinColumn fail with EntityNotFoundException

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#1382]
## Expected behavior

Fetching a OneToOne with optional "extra" should set the extra to null if it does not exist

## Actual behavior
```
javax.persistence.EntityNotFoundException: Lazy loading failed on type:org.tests.model.onetoone.OtoUPrimeExtra id:e4fd0a89-bb1a-4fcc-ae1c-6b9db37081b7 - Bean has been deleted.
	at io.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:846)
	at io.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:815)
	at io.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:915)
	at org.tests.model.onetoone.OtoUPrimeExtra._ebean_get_extra(OtoUPrimeExtra.java:6)
	at org.tests.model.onetoone.OtoUPrimeExtra.getExtra(OtoUPrimeExtra.java:37)
```	

### Steps to reproduce

```java
  @Test
  public void insertWithoutExtra() {
    String desc = "" + System.currentTimeMillis();
    OtoUPrime p1 = new OtoUPrime("u" + desc);
    Ebean.save(p1);

    Query<OtoUPrime> query = Ebean.find(OtoUPrime.class).setId(p1.getPid());

    OtoUPrime found = query.findOne();

    if (found.getExtra() != null) {
      found.getExtra().getExtra(); // fails here, because getExtra should be null
    }
    assertThat(found.getExtra()).isNull();
  }
```

### Suggestions / ideas how to fix
Either perform a left join when the OtoUPrime bean is fetched (would affect performance) - or on the first `getExtra()` call, check if the bean is a reference bean. This could be done in the preGetter like this:
```java
  public void preGetter(int propertyIndex) {
    preGetterCallback(propertyIndex);
    if (state == STATE_NEW || disableLazyLoad) {
      return;
    }
    if (!isLoadedProperty(propertyIndex)) {
      loadBean(propertyIndex);
    }
    // Quick & Ditry hack to fix that particular problem (may have side effects!)
    Object obj = getOwner()._ebean_getField(propertyIndex);
    if (obj instanceof EntityBean ) { // TODO Check if it is Oto Optional
      if (((EntityBean)obj)._ebean_getIntercept().state == STATE_REFERENCE) {
        try {
          (((EntityBean)obj)._ebean_getIntercept()).loadBean(1);
        } catch (EntityNotFoundException enf) {
          getOwner()._ebean_setField(propertyIndex, null);
        }
      }
    }
    if (nodeUsageCollector != null) {
      nodeUsageCollector.addUsed(getProperty(propertyIndex));
    }
  }
```

**Comment by rbygrave** [comment]
I don't think this is a bug at this stage.

The `OneToOne` is a special one in that it is a `PrimaryKeyJoinColumn` ... and hence `found.getExtra()` does return a reference bean with that query (as it has a shared primary key value by definition/mapping).

So then failing with a EntityNotFoundException does seem like the correct behaviour.

Knowing that this is a `PrimaryKeyJoinColumn` we can change the query to instead be:
```java
    Query<OtoUPrime> query = Ebean.find(OtoUPrime.class)
      .setId(p1.getPid())
      .fetch("extra", "eid");
```
... and then the test passes as we explicitly include the left join (we take that cost) and `found.getExtra()` returns null.

Alternatively application code could change and catch EntityNotFoundException with the knowledge that it is accurately indicating that the associated OtoUPrimeExtra is indeed null.

The workaround above does not look legitimate to me.

**Comment by rPraml** [comment]
I created a PR for this issue with a possible fix/workaround - maybe this is more legitimate (to be honest, it is still a hack ;) 
Maybe I really catch the "EntityNotFoundException" in my application

**Comment by rbygrave** [comment]
> Maybe I really catch the "EntityNotFoundException" in my application

I think so. I believe it is the nature of `PrimaryKeyJoinColumn` ... there will not be a perfect workaround in Ebean (which doesn't know the context of what is trying to be achieved).  That is, I don't believe we want to _always_ do the left join ... and I believe any 'fix' after that is going to be a bit of a hack.

That is, I believe developers need to be aware if they are going to lazy load with `PrimaryKeyJoinColumn` and deal with the possible EntityNotFoundException - I think that will be better than Ebean trying to hide/deal with this issue in some way.

**Comment by rbygrave** [comment]
Hi @rPraml .. I am going to close this issue for now with the thought that the best approach is to catch EntityNotFoundException for this case (or for people to modify the query and explicitly add the join).

If you feel there is a better approach then we can open this back up and revisit.

Cheers, Rob.
