### ISSUE TITLE
Postgres @History table sys_period empty with multiple updates

### ISSUE THREAD

**Issue by ksperling** [ebean-orm/ebean#1400]
## Expected behavior

When a record in an `@History` table is updated multiple times within the same transaction (or if `current_timestamp` still returns the same value as during the previous transaction, but that's probably fairly unlikely), the corresponding history records should have valid `sys_period` values.

Of course generally it's preferable to only write each record at most once per transaction, but we have some corner cases where the same record gets written and then updated.

## Actual behavior

Postgres collapses any `[t,t)` (inclusive / exclusive range where lower = upper = t) into a canonical `empty` range. `lower()` and `upper()` both return `null` for this type of range.  The main problem is that these records therefore won't order correctly with respect to other history entries.

## Ideas

One simple solution that seems to work is to use a `[t,t]` (inclusive) range in this special case by replacing the `tstzrange` expression in the trigger function with
```
case when lower(OLD.sys_period) = current_timestamp then tstzrange(current_timestamp, current_timestamp, '[]') else tstzrange(lower(OLD.sys_period), current_timestamp) end
```

This makes all history entries order correctly with respect to changes from other transactions, and as long as there are 2 or less updates to the same row happening in the same transaction also within the transaction (For 3 or more updates more than one history row ends up with an identical `[t,t]` sys_period)

Another approach would be to not insert a history record at all when `lower(OLD.sys_period) = current_timestamp` but that seems somewhat dangerous. For our history tables we also use a `history_note` fields that's intended to act as a for each entry in the history table, and I'd rather not lose those even in the multiple-updates-in-a-transaction corner case.

**Comment by rbygrave** [comment]
Hmmm right.  Another option could be to not use the range type on the history table at all but instead go to just using 2 columns.  We would lose the special index option that we get with the range type and this sounds like a fairly tough option.

**Comment by ksperling** [comment]
Yeah, also a much bigger change in terms of migrating existing schemas and any code / queries potentially using the history tables.

**Comment by rbygrave** [comment]
> also a much bigger change in terms of migrating ...

Yes I hear you there - that option would be a blow alright so we need to be savvy of the impact here.

**Comment by ksperling** [comment]
The proposed fix to the trigger function is pretty straightforward though. Are you worried about causing issues when somebody has manually added a constraint to force non-overlapping sys_period?

It's somewhat annoying that it's not possible to get a guaranteed totally ordered non-overlapping history, but due to the discrete nature of  `current_timestamp` that's just not possible without adding something like an additional sequence number column.

**Comment by rbygrave** [comment]
```sql
create or replace function safe_tstz_range(startTs timestamptz, endTs timestamptz) returns tstzrange as $$
begin
  if (endTs::timestamptz <= startTs::timestamptz) then
    endTs = endTs + '1 microsecond';
  end if;
  return tstzrange(startTs, endTs);
end;
$$ LANGUAGE plpgsql;
```
```sql
select now(), now() + '1 second', safe_tstz_range(current_timestamp, now() + '1 second');
select now(), now() + '1 second', safe_tstz_range(current_timestamp, current_timestamp);
```
So the theory here is that we use `safe_tstz_range()` rather than just `tstzrange()` ... and this will slightly bump the range if/when current_timestamp has not moved. This should then cover the cases of many updates in the same transaction.

I haven't tried this in action yet, I should get to do that on the weekend.

**Comment by rbygrave** [comment]
i.e. Where we see `tstzrange(lower(OLD.sys_period), current_timestamp)` change to `safe_tstz_range(lower(OLD.sys_period), current_timestamp)`

**Comment by ksperling** [comment]
Hm yeah I guess that works too and keeps the ordering. Instead of having to manage a separate function just inlining an expression would probably be simpler: `tstzrange(lower(OLD.sys_period), greater(lower(OLD.sys_period) + '1 microsecond'), current_timestamp)`

I wish `current_timestamp` was actually unique across transactions and that all created/updated/history timestamps could be correlated with the transaction that made the change... But PG doesn't provide that uniqueness guarantee, and the current created/updated timestamp generators don't use `current_timestamp` anyway, so overall that seems like a pipe dream. So in that sense, fudging the `sys_period` timestamps is no worse than the discrepancies that already exist between `current_timestamp` and created/updated timestamps anyway.

So 👍 from me for that solution.

**Comment by rbygrave** [comment]
Yes. I'm feeling confident that this is the right approach (to 'fudge' the `current_timestamp` by a microsecond) specifically for this history purpose and specifically so that we get to keep the Postgres range `tstzrange` type in the `[)` form. I believe arkhipov/temporal_tables also do a similar thing. 

> just inlining an expression would probably be simpler

Ah yes - good point there.  That means we could just do that without having to manage the function which makes it a lot simpler in terms of DDL migrations.

**Comment by rbygrave** [comment]
> current created/updated timestamp generators don't use current_timestamp anyway

In the past I have thought about having that option of the created/updated timestamp using `current_timestamp`.  I'll have to revisit that again sometime (it seems like it would be a nice option to have).

**Comment by rbygrave** [comment]
Gone with declaring a lowerTs and upperTs ... and using `upperTs = greatest(lowerTs + '1 microsecond',current_timestamp);`
```sql
declare
  lowerTs timestamptz;
  upperTs timestamptz;
begin
  lowerTs = lower(OLD.sys_period);
  upperTs = greatest(lowerTs + '1 microsecond',current_timestamp);
  ...
```
