### ISSUE TITLE
Incorrect SQL when @Aggregation formula matches the property - sum(t0.sum(totalKms))

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1408]
### Steps to reproduce

```java
@Entity
@View(name = "d_machine_stats", dependentTables = "d_machine_stats")
public class DMachineStatsAgg {

  ...
  // totalKms ... is the same as the property name
  @Aggregation("sum(totalKms)")
  long totalKms;

```

```sql
-- incorrect sql here ... sum(t0.sum(...

select t0.machine_id, sum(t0.sum(totalKms)), sum(cost) 
from d_machine_stats t0 
where t0.date > ?  group by t0.machine_id
```
```console
javax.persistence.PersistenceException: Query threw SQLException:Column "TOTALKMS" not found; SQL statement:
```

**Comment by rbygrave** [comment]
So what we can do with this fixed is have a "Aggregation entity bean" ... which provides us a nice way to perform aggregation / group by / having type queries etc.

## Example
A normal entity bean that (many) columns we want to aggregate on - sum / max / min / count  
```java
@Entity
@Table(name = "d_machine_stats")
public class DMachineStats {

  @Id
  long id;

  @ManyToOne
  DMachine machine;

  LocalDate date;

  long totalKms;

  long hours;

  BigDecimal rate;

  BigDecimal cost;

  @Version
  long version;
```

We can create a similar "Aggregate entity bean" that is based on the same table but uses `@Aggregation` on many of the properties.

```java
@Entity
@View(name = "d_machine_stats", dependentTables = "d_machine_stats")
public class DMachineStatsAgg {

  @ManyToOne
  DMachine machine;

  LocalDate date;

  @Aggregation("sum(totalKms)")
  long totalKms;

  @Aggregation("sum(hours)")
  long hours;

  @Aggregation("max(rate)")
  BigDecimal rate;

  @Aggregation("sum(cost)")
  BigDecimal totalCost;

  @Aggregation("max(totalKms)")
  BigDecimal maxKms;
```

So this entity uses `@View` meaning it is `read only`.  The view refers to the table and not a view which is perfectly fine.  It doesn't have a `@Id` property ... we use this for `select group by` type queries.

Note that `@Aggregation` properties need to be explicitly specified in the `select()`

```java
    List<DMachineStatsAgg> result = Ebean.find(DMachineStatsAgg.class)
       .select("machine, totalKms, totalCost")
      .where().gt("date", LocalDate.now().minusDays(10))
      .findList();
```
```sql
select t0.machine_id, sum(t0.total_kms), sum(cost) 
from d_machine_stats t0 
where t0.date > ?  
group by t0.machine_id
```

Example with multiple columns to group by (the selected non-aggregation properties) and has a having clause

```java
 Ebean.find(DMachineStatsAgg.class)
      .select("machine, date, totalKms, totalCost")
      .where().gt("date", LocalDate.now().minusDays(10))
      .having().gt("totalCost", 10)
      .findList();
```
```sql
select t0.machine_id, t0.date, sum(t0.total_kms), sum(cost) 
from d_machine_stats t0 where t0.date > ?  
group by t0.machine_id, t0.date 
having sum(cost) > ?
```

**Comment by shubhamp-zeotap** [comment]
@rbygrave Hi Rob,

I have two follow up questions on this issue. Need your guidance.

1) Is it possible to include those other columns (or entity fields) in query's where clause which are not part of aggregation model DMachineStatsAgg but are present in the original DMachineStats model?

2) Will this scenario work if that particular column in the where clause (assuming point 1 is possible) is another entity bean calculated using @Formula and @Transient?

Basically something like this?

`
@Entity
@Table(name = "d_machine_stats")
public class DMachineStats {

  @Id
  long id;

  @ManyToOne
  DMachine machine;

  LocalDate date;

  long totalKms;

  long hours;

  BigDecimal rate;

  BigDecimal cost;

  @Version
  long version;

  @Formula(<formula definition goes here>)
  @Transient
  SomeEntityBean formulaBean;

`

Then we query it like this

`
List<DMachineStatsAgg> result = Ebean.find(DMachineStatsAgg.class)
       .select("machine, totalKms, totalCost")
      .where()
      .gt("date", LocalDate.now().minusDays(10))
      **.eq("formulaBean.propertyA", "someValue")**
      .findList();
`

Is this feasible?

**Comment by rbygrave** [comment]
> 1. ... which are not part of aggregation model DMachineStatsAgg but are present in the original DMachineStats model?

Maybe I don't understand correctly but ... we effectively 'copy' the properties we need onto DMachineStatsAgg.  We can do that via using a common superclass (`@MappedSuperclass`) on just have the same property on both beans (by name and type).


> 2. ...  is another entity bean calculated using @formula and @transient?

I don't know, it isn't clear to me what a formulaBean is.  Normally formula properties are scalar properties - it isn't clear why that isn't what you want to do.  You could provide a more clear example of what you are trying to achieve?

**Comment by shubhamp-zeotap** [comment]
Thanks, Rob! Let me explain step by step of what I am trying to achieve. Also please suggest better alternative wherever applicable.

1) I have two entity models A and B

A looks like this:

```
@Entity
@Table(name="tableA")
class A extends Model {
   
    @Id @Column(name="id")
    private Integer id;

    @Column(name="anotherId")
    private Integer anotherId;

    @ManyToOne
    @JoinColumn(name = "bid", referencedColumnName = "id", nullable = false)
    private B relatedModel; 
}

```

B looks like this:

```
@Entity
@Table(name="tableB")
class B extends Model {
 
    @Id @Column(name="id")
    private Integer id;

    @Column(name="name")
    private String name;
}
```

The data looks like this:

Table A:
```
id     anotherId           bid
1          1                1
2          1                2
3          1                3 
4          1                4
```

Table B:
```
id    name
1       A
2       B
3       C
4       D
```

I am trying to achieve the query like given below through Ebean but haven't been successful.

```
select A.anotherId, min(B.id) from table A left join table B on A.bid = B.id group by A.anotherId;
```

After execution, I wanted by my bean A to be populated like this (this is JSON representation of bean)

```
{
   "anotherId": 1
   "relatedModel": {
       "id": 1
      "name": A
   }
}
```

I am reading through all the documentation/articles of @aggregation bean, @formula but haven't been able to figure this out yet. For note, I am also looking to a solution which is not performance intensive as data in the given tables will be huge.

What I have tried until now is something like this:

```
        List<A> As = Ebean.find(A.class)
                .select("anotherId, min(bid)")
                .where().eq("anotherId", 1).findList();
```
This generates a  ```PersistenceException: Error loading on min(bid)```

Need your help ! Thanks again !

**Comment by rbygrave** [comment]
The above is good but this should really go into a new issue.  So create a new issue.
- The issue needs to include the sql that is generated (and the SQL needs to match the model that is included - if you are not using A and B then make sure the model included matches what you are running)  
- Include the full stack trace in the issue. 

Then we can state if this is a bug or not.  
Then we can create a failing test.
Then we can fix it.

**Comment by shubhamp-zeotap** [comment]
I have logged it here: https://github.com/ebean-orm/ebean/issues/1737. Thank you for your help!

**Comment by rbygrave** [comment]
Yup, perfect thanks @shubhamp-zeotap !!
