### ISSUE TITLE
Enhancement entity throws an exception when deserializing （hessian）

### ISSUE THREAD

**Issue by challengeof** [ebean-orm/ebean#1416]
The enhanced entity has the attribute EntityBeanIntercept and the EntityBeanIntercept has no default constructor.
The constructor is ： 
![image](https://user-images.githubusercontent.com/11530876/41211471-2bb5fca6-6d6a-11e8-8012-f927a7964806.png)
When hessian deserializes the selected constructor, it creates the required parameters for that constructor:
![image](https://user-images.githubusercontent.com/11530876/41211750-ef94b71a-6d6b-11e8-9352-0625edfa26d0.png)
As you can see, if the argument is not primitive, it is replaced with null; but unfortunately our constructor internally calls a method on this parameter, so a null pointer is thrown.
![image](https://user-images.githubusercontent.com/11530876/41211742-e1b5e524-6d6b-11e8-88e4-9221c22e2294.png)
So whether the EntityBeanIntercept class can provide a no-argument constructor？

**Comment by rbygrave** [comment]
This should be posted to the discussion forum and not as a github issue as per the policy for this project.

Refer: http://ebean-orm.github.io/support

**Comment by challengeof** [comment]
Ok I will transfer to Google group and turn close this issue.
