### ISSUE TITLE
No service implementation found for DbMigration?

### ISSUE THREAD

**Issue by gerhat** [ebean-orm/ebean#1446]
I am writing a sbt plugin for generating migrations automatically but I am stuck in this error:
`java.lang.IllegalStateException: No service implementation found for DbMigration?`
when calling `DbMigration.create` from scala.

I understand that the `ServiceLoader` cannot find an implementation of `DbMigration.class` to load but I can't figure out why.

Here is my code:

```scala
// build.sbt
libraryDependencies ++= Seq(
  "io.ebean" % "ebean" % "11.18.3"
)
```
```scala
// SbtMigrator.scala
import sbt._
import _root_.io.ebean.annotation.Platform
import _root_.io.ebean.dbmigration.DbMigration

object SbtMigrator extends AutoPlugin {
  object autoImport {
    val create_migration = taskKey[Unit]("Generate migration if required")
  }

  import autoImport._

  override lazy val projectSettings = Seq(
    create_migration := {
      val dbMigration = DbMigration.create
      dbMigration.setPathToResources("resources")
      dbMigration.setPlatform(Platform.MYSQL)
      dbMigration.generateMigration
    }
  )
}
```

**Comment by rbygrave** [comment]
For this project we ask that people post questions to the forum ... and that we use github issues for bugs and enhancements.  This policy is described at: http://ebean-orm.github.io/support

Do you want to post the question to the forum at: https://groups.google.com/forum/#!forum/ebean

Thanks, Rob.

**Comment by gerhat** [comment]
@rbygrave sorry.

Posted the question here:
https://groups.google.com/forum/#!topic/ebean/3wiovHG1V-E
