### ISSUE TITLE
ENH: Add FetchGroup ... as a mechanism to specify select() + fetch() separately from Query

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1460]
### FetchGroups

FetchGroup allows us to specify / define what part of the object graph to load separately from the Query itself.  We can then apply it to a query via `select(fetchGroup)`.

We can think of FetchGroup as the `select` + `fetch` part of a query which we can re-use and combine with other FetchGroups.

### Examples
A simple "select only" fetch group
```java
FetchGroup<Customer> fetchGroup = FetchGroup.of(Customer.class, "name, status");

query()
.select(fetchGroup)
...
```

A select + fetch FetchGroup ...
```java
FetchGroup fetch = FetchGroup.of(Customer.class)
  .select("name, status")
  .fetchQuery("contacts", "firstName, lastName, email")
  .build();

query()
.select(fetchGroup)
...
```
### Combining FetchGroups

We can combine FetchGroups in a nested fashion.  For example:

```java
FetchGroup<Contact> FG_Contacts = FetchGroup.of(Contact.class, "firstName, lastName, email");

FetchGroup<Customer> FG_Customer = FetchGroup.of(Customer.class)
  .select("name")
  .fetchQuery("contacts", FG_Contacts)
  .build();

query()
.select(FG_Customer)
...
```

**Comment by dastultz** [comment]
" which we can re-use and combine with other FetchGroups."

I haven't used the Query Beans type-safe querying yet so maybe this is addressed there. But it seems you should not be able to use a FetchGroup that was designed for an Invoice root with a Customer root. Should FetchGroup be typed (FetchGroup<Invoice>)?

**Comment by rbygrave** [comment]
> Query Beans type-safe querying 

As an FYI, my thought is that we could at some point in the future ... allow query beans to create a FetchGroup (in a type safe manor).  I'm not sure how practically useful that would be but I'll continue to ponder it.
