### ISSUE TITLE
Change stateless update on bean with no @Version property that updates 0 rows to throw EntityNotFoundException

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1471]
Currently when 0 rows are updated in this scenario there is no way to detect that.

### Steps to reproduce

The stateless bean update with no @Version property using an Id value that does not exist in the DB.

```java
    EBasic basic = new EBasic();
    basic.setId(999999999); // Where this Id value does not exist in the DB
    basic.setName("something");
    basic.setStatus(Status.ACTIVE);

    Ebean.update(basic);
```
This will now throw EntityNotFoundException

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Hi @rbygrave,

I would like to know if there is a way to disable this `EntityNotFound` exception for a specific `update`/`updateAll` query ?

For example in our context, we are updating stateless a column value of `user` table and if the `user` have been deleted (hard), we just want to ignore the update as the value have no meaning now. (asynchronous architecture)

N.B : We are updating multiple user at same time using `DB.updateAll` who call one by one each update.

Thanks in advance for your help.
Yours faithfully,
LCDP
