### ISSUE TITLE
Query plan capture

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1476]
Support the capture of query plans.
- We want to be able to capture plans in production
- We want to capture plans in the background (not impact foreground processing)
- We want to capture plans at appropriate times (on queries deemed slow with a sampling rate)

**Comment by rPraml** [comment]
Cool, it seems that this makes #1355 obsolete

**Comment by rbygrave** [comment]
# How to:

Turn it on via:
`serverConfig.setCollectQueryPlans(true)`


Obtain the query plans when desired / periodically:
```java
    QueryPlanRequest request = new QueryPlanRequest();

    List<MetaQueryPlan> plans = server().getMetaInfoManager().collectQueryPlans(request);
    for (MetaQueryPlan plan : plans) {
      // do interesting stuff with the query plan
      System.out.println(plan);
    }
```
