### ISSUE TITLE
OneToOne inserts with idType=SEQUENCE will fail

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#1480]
See the Test TestOneToOneImportedPkNative.findWithLazyOneToOne

## Actual behavior
The test fails on SqlServer (and if DB is manually set to idType=SEQUENCE) with `Duplicate column name "MASTER_ID"`

It will generate the wrong insert statement:

    insert into oto_bchild (master_id, child, master_id) values (?,?,?)

### Steps to reproduce
set `ebean.h2.idType=SEQUENCE` in ebean.properties
start the test

**Comment by rbygrave** [comment]
This is more the case of an incorrect mapping.  The mapping should use `@PrimaryKeyJoinColumn` ... rather than the `@JoinColumn(name = "master_id", referencedColumnName = "id")`

I'll update the test to reflect the proper mapping.
