### ISSUE TITLE
Resolve char to a `bytea` or other solution to handle `char` primitive in entity with Postgres

### ISSUE THREAD

**Issue by soberich** [ebean-orm/ebean#1532]
## Expected behavior
`char` primitive type in entity bean could be handled appropriately
## Actual behavior
With postgres you get the runtime exception when a `char` java primitive is used and NOT assigned to a specific character which resolves to `'\0'`.
### Steps to reproduce

```java
public class Bean {
    
    @Column(length = 1)
    private char ch;

    public char getCh() {
        return ch;
    }

    public Bean setCh(char ch) {
        this.ch = ch;
        return this;
    }
}
```

```console
ERROR:  invalid byte sequence for encoding "UTF8": 0x00
```

Which IS the limitation of Postgres BUT at ORM side when there is an explicit `char` type, I beleive it should be handled somehow. (and also maybe it is worth to implicitly assign column length to 1?)

Maybe it should be resolved to bytea (exactely only `char` primitive) or any other optimal solution.

EDIT:
Versions are
```groovy
String EBEAN_QUERY       = "11.24.1"
String EBEAN_QUERY_GEN   = "11.24.1"
String EBEAN_TEST        = "11.24.1"
String EBEAN             = "11.24.1"
```

**Comment by rbygraveClearpoint** [comment]
You can just use `String` in the meantime right?

**Comment by rbygrave** [comment]
You need to supply a failing test.  It is not clear what this issue is.  Thanks.

**Comment by rbygrave** [comment]
I'll close this for now.  If you supply a failing test case we can look to reopen it.
