### ISSUE TITLE
Ebean generates wrong ddl (datetime(6) vs timestamp) for H2 with `@History` annotation

### ISSUE THREAD

**Issue by soberich** [ebean-orm/ebean#1569]
## Expected behavior
Produces runnable ddl sql
## Actual behavior
produces SqlSyntaxException, please see (and run) the following repo.
###  see https://github.com/soberich/ebean_history_issue

**Comment by rbygrave** [comment]
Given `datetime(6)` is effectively an alias for `timestamp` it isn't clear what you think this bug is.

What exactly do you expect and why do you think `datetime(6)` is not correct?
Note that this hasn't got anything to `@History`

**Comment by soberich** [comment]
Ok, this was not adout `datetime(6)` I knew I maybe should just say "hey" the log says `SQLSyntaxException`.
I have adjusted the description.

**Comment by rbygrave** [comment]
Reproduces with upgrade to h2 version 1.4.197
