### ISSUE TITLE
Incorrect CamelCase conversion when number proceeds uppercase letter

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1573]
### Steps to reproduce

```java
    assertEquals(CamelCaseHelper.toUnderscoreFromCamel("hello1Id"), "hello1_id");
    assertEquals(CamelCaseHelper.toUnderscoreFromCamel("helloThere2Foo"), "hello_there2_foo");
```

**Comment by pgilmore** [comment]
Ouch that hurt :(

**Comment by rbygrave** [comment]
Yes, @pgilmore  it can hurt or people could use `@Column` ... do you want to provide more clarification on the hurt?  I guess you didn't go down the `@Column` path?

**Comment by pgilmore** [comment]
Just our own fault for not reading through the changelogs carefully enough. 

An the tests didn't catch it as they creates a new database where the naming was correct. 

We could use Column but the less annotations the better.
