### ISSUE TITLE
Ebean DDL ignores cascade property for foreign keys 

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#1575]
I'm not sure why this start to happen but it was ok before, I got sbt project (play framework project) using ebean as ORM framework, I do have `@OneToMany(cascade = CascadeType.ALL)` but generated code showing I have `on delete restrict on update restrict` instead, know I need to change that manually in DB console each time I recreate my database using generated script.

## Expected behavior

It must have cascade on update and delete instead of restrict.

## Actual behavior

I'm getting restrict on delete and update.

### Steps to reproduce

 I got the following entities, 

```java
@Entity
@Table(name = "products")
public class Product extends Model {

    @Id
    @Column
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Column(length = 256, nullable = false, unique = true)
    @Constraints.Required
    @Constraints.MinLength(2)
    @Constraints.MaxLength(256)
    private String name;

    @Column(length = 1000)
    @Constraints.MaxLength(1000)
    private String description;

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "product", cascade = CascadeType.ALL)
    @JsonManagedReference
    private Set<Project> projects;

// setters and getters
}


@Entity
@Table(name = "projects",
        uniqueConstraints = @UniqueConstraint(columnNames = {"product_id", "unique_key"}))
public class Project extends Model {

    @Id
    @Column
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @ManyToOne(targetEntity = Product.class, fetch = FetchType.LAZY, optional = false)
    @JsonBackReference
    private Product product;

    @Column(name = "unique_key",length = 40, nullable = false)
    @Constraints.Required
    @Constraints.MinLength(3)
    @Constraints.MaxLength(40)
    private String key;

    @Column(length = 256, nullable = false)
    @Constraints.Required
    @Constraints.MinLength(2)
    @Constraints.MaxLength(256)
    private String name;

// setters and getters
}

```

Generated lines:
```sql
create index ix_projects_product_id on projects (product_id);
alter table projects add constraint fk_projects_product_id foreign key (product_id) references products (id) on delete restrict on update restrict;
```

Using this plugin in: https://github.com/payintech/play-ebean
Version 18.11 so it is using:
**Ebean ORM**: 11.26.1
**Ebean Agent**: 11.26.1
**Ebean Migration**: 11.11.1

**Comment by rbygrave** [comment]
> I'm not sure why this start to happen but it was ok before

What does "ok before" mean?

Ebean has always been generating the `on delete restrict on update restrict` part for the foreign key and this is the correct DDL to generate for this case.

This FK DDL generated has nothing to do with the `@OneToMany(..., cascade = CascadeType.ALL)`

**Comment by almothafar** [comment]
OK, I think I got an old project and I see cascade present there, I'm 100% sure that was generated, but I don't know if that cascade part was generated or modified later, but I think it is generated, so this is why I said it was doing that before.

Anyway, if not, is it a feature to ask or there is something behind generating only restrict.

**Comment by rbygrave** [comment]
> Anyway, if not, is it a feature to ask or there is something behind generating only restrict.

Well, the cascade on `@ManyToOne` and `@OneToMany` ... could be described as "ORM cascade by reachablity" ... as in the ORM is walking the graph cascading the save or delete etc.  If we are using L2 caching then this also means the ORM knows what part of the L2 cache to invalidate etc.  

For controlling the database foreign key cascade we have the options of:

```java
@DbForeignKey(onDelete = ConstraintMode.CASCADE)

@DbForeignKey(onDelete = ConstraintMode.SET_NULL)

@DbForeignKey(onDelete = ConstraintMode.SET_DEFAULT)
```

If we want the database to have the foreign key cascade deletes then we don't really want the ORM to try and do the cascade (so the `@OneToMany` should probably only cascade `persist` and not `all`).

Does that make sense?

**Comment by almothafar** [comment]
Thanks for details, It does make sense, but sometimes I need to do DB maintenance manually, that cascade does make sense then, anyway I know about `@DbForeignKey(onDelete = ConstraintMode.CASCADE)` but as you can see there is nothing like that in `ConstraintMode` class:

![image](https://user-images.githubusercontent.com/13887564/50053292-21022e00-013b-11e9-93c4-bc4e393a7dbf.png)

![image](https://user-images.githubusercontent.com/13887564/50053302-66266000-013b-11e9-9aff-1c168d87eb17.png)

**Comment by almothafar** [comment]
Never mind, I have to import that manually `import io.ebean.annotation.ConstraintMode;`

**Comment by rbygrave** [comment]
Ok cool.  I'll close this issue then.

Thanks, Rob.
