### ISSUE TITLE
ClusterManager creates ClusterBroadcast even when config is not active

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean#1576]
## Expected behavior

When I set the "ebean.cluster.active" property to false I expect ebean to not start the cluster.

## Actual behavior

The cluster listening port is opened and it looks like some cluster stuff is active.

### Steps to reproduce

Include the cluster library and put the following in the ebean properties file:

```
ebean.cluster.active=false
ebean.cluster.localHostPort=127.0.0.1:9942
```

You will notice that when the server is started the port is in use.

Looks to me that it can be easily (?) fixed in io.ebeaninternal.server.cluster.ClusterManager by changing the constructor from:

```java
  public ClusterManager(ContainerConfig config) {
    ClusterBroadcastFactory factory = createFactory();
    if (factory != null) {
      broadcast = factory.create(this, config);
    } else {
      broadcast = null;
    }
  }
```

to:

```java
  public ClusterManager(ContainerConfig config) {
    ClusterBroadcastFactory factory = createFactory();
    if (factory != null && config.isActive()) {
      broadcast = factory.create(this, config);
    } else {
      broadcast = null;
    }
  }
```

**Comment by rbygrave** [comment]
Yes, quite right !!
