### ISSUE TITLE
Add support for using setDistinct (by excluding id property from generated sql)

### ISSUE THREAD

**Issue by KoenDG** [ebean-orm/ebean#158]
Most applications have an @Id setting for their ORM, meaning that any query coming from a finder will automatically add the id in to the query somehow.

Take this Query for instance: find.select("artist").setDistinct(true).findList();

Ebean will automatically add the id to the select, resulting in: "select distinct id, artist from musicDB"

If I want to find the distinct artists, I can't do that, since setDistinct only accepts a boolean and just slaps the DISTINCT statement right after the select at the start. Which then gets applied to the first parameter it finds, which will be the id.

And naturally, the ID will be distinct. 

If I want to get all the artists from a music library, but get the names only once, I would write: "select distinct artist from musicDB"

It feels wrong that there is only a method to set the "distinct" at the start of the query and not to a value that you might actually need to get.

If this isn't a bug, then surely I must be able to achieve the equivalent of "select distinct artist from musicDB" in an other way?

**Comment by backslash47** [comment]
The original fix is not working when specifying maxRows or firstRow, because the CQueryEngine adds id to order fields in this case.

I disabled this addition in case of distinct query. Please look at [this commit](https://github.com/backslash47/avaje-ebeanorm/commit/4d16cf9caac83ee2cffc9f9aca12f63c1640ed46) if it is ok to fix it this way.

**Comment by komajunjun** [comment]
@rbygrave , how can I exclude id property from generated sql?

**Comment by dastultz** [comment]
Please ask questions and engage in discussion in the Google Group, not
through the issue system.
