### ISSUE TITLE
insertAll/updateAll/saveAll is multiple execution, why not use batch?

### ISSUE THREAD

**Issue by deverlex** [ebean-orm/ebean#1590]
Hi, 

I don't understand why you are not using batch for saveAll/updateAll, insertAll.
Example: create **insert into values (...), (...)** replace for **insert into values (...), insrert into values (...)**

I detect using saveAll...very slow. Thanks

**Comment by rbygrave** [comment]
It does use JDBC batch.

Please ask questions on the forum at https://groups.google.com/forum/#!forum/ebean

Thanks.
