### ISSUE TITLE
ENH: Create io.ebean.DB as alias for Ebean and io.ebean.Database as alias for EbeanServer

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1624]
So instead of `Ebean` we can use `DB` ... and instead of `EbeanServer` we can use `Database`.

I think these are better names for people reading code making it more intuitive (especially for people relatively unfamiliar with Ebean) ... 

for example:
```java
// example 1
try (Transaction transaction = DB.beginTransaction()) {
  ...
}
```

```java
// examples ...
Customer customer = DB.find(Customer.class, 42)

DB.save(bean)


Customer customer = database.find(Customer.class, 42)

database.save(bean)

```
```java
// example 3
Database hrDb = DB.byName("hr");

List<Person> people = hrDb.find(Person.class)
  .where()...
  .findList();
```

This is expected to be a non-breaking change - we can still use Ebean and EbeanServer and we will support their use going forward but documentation will likely promote the use of DB and Database.

Edit: It won't be binary compatible though ... code will need a re-compile.

**Comment by corrspt** [comment]
Hey Rob,

I think this change is great, one thing about this is documentation. Since we don't have "versioned" docs, should every example in the documentation feature the examples like:

```java
Ebean 11.X. or up
Customer customer = DB.find(Customer.class, 42)
Ebean 11.X or down
Customer customer = Ebean.find(Customer.class, 42)
```

Or do you have some different idea in mind? (Wanted to know, so that when I get the time to provide more documentation examples, I know what to do :)

**Comment by rbygrave** [comment]
My opinion is that I'll look to just document the new/latest "style" with the thinking that doing that will be less confusing to new people looking to adopt Ebean.

In theory existing users will be able to understand and translate without much difficulty.

At least that is my current thinking.   Some of the documentation I've done in the past looks to me like it was "too much" so I'm sort of aiming for more succinct / easier to absorb documentation.

**Comment by corrspt** [comment]
I'm also fond of clear/succinct documentation, but I'm worried that people might get confused reaching to an example that they can't execute (and there's no easy way to know which is the correct way). 

But what about users that come from third-party integrations like (Play-ebean) which doesn't usually have the latest version of Ebean?

Maybe I'm overthinking and people are really upgrading Ebean, do you have download stats for previous/current version of ebean from maven central, or something?

Of course we could always put something in the "Troubleshooting" section or something like that, don't know.

**Comment by rbygrave** [comment]
> do you have download stats for previous/current version of ebean from maven central, or something?

Well, some parts not quite working on central stats today but ... 90% of people are on io.ebean which is the 10.x + 11.x range.  So to me that is great, most people can readily get to the most recent version for bug fixes and improvements as needed. 

> people might get confused reaching to an example that they can't execute 

Yes very true.  I figure we do our best and see how it reads and what feedback we get.  My view is that code wise `DB` and `Database` are much more intuitive for people reading the code so I think it is worth it.

**Comment by rbygrave** [comment]
> Play-ebean

Ideally we have a set of full stack examples that are maintained.  Play, Spring Boot, Javalin, SparkJava etc ... and some documentation that goes along with those.  Still, got to do the first things first and work towards that.
