### ISSUE TITLE
add "created_by_name" to BaseModel

### ISSUE THREAD

**Issue by weiwill** [ebean-orm/ebean#1636]
GITHUB ISSUES ARE STRICTLY CONTROLLED FOR THIS PROJECT.

Refer to http://ebean-orm.github.io/support for the policies controlling the use of github issues.
Please post issues to the Ebean group https://groups.google.com/forum/#!forum/ebean first.

## Expected behavior
  I want to and "created_by_name" "updated_by_name" to BaseModel
  Like the following code
  What can i do?
  Can I execute some code before executing create or update methods?

### Steps to reproduce

```kotlin
@MappedSuperclass
open class BaseModel : Model() {

  @Id
  var id: String? = null

  @Version
  var version: Long = 0

  @Column(name = "created_at")
  lateinit var createdAt: LocalDateTime

  @Column(name = "created_by")
  lateinit var createdBy: String

  @Column(name = "created_by_name")
  lateinit var createdByName: String

  @Column(name = "updated_at")
  lateinit var updatedAt: LocalDateTime

  @Column(name = "updated_by")
  lateinit var updatedBy: String

  @Column(name = "updated_by_name")
  lateinit var updatedByName: String
}
```

**Comment by rbygrave** [comment]
I think you are looking for the `@WhoCreated` and `@WhoModified` annotations.
Refer to: https://ebean.io/docs/features/who

**Comment by weiwill** [comment]
sorry, I mean create_by and create_by_name, but now only create_by(@WhoCreated)

Maybe I can implement it with @PrePersist and @PreUpdate

Current User Provider now returns the field ID. Can I return to the entity class and implement GeneratedWhoCreated by myself?

**Comment by rbygrave** [comment]
> sorry, I mean create_by and create_by_name, but now only create_by(@WhoCreated)

That isn't clear to me.  Can you be explicit.  Give an example.


> Current User Provider now returns the field ID. Can I return to the entity class

Yes, you can return reference beans and have something like:

```java
@WhoCreated
@ManyToOne(optional=false)
User userCreated;

@WhoModified
@ManyToOne(optional=false)
User userModified;
```
