### ISSUE TITLE
Cascaded update of fields on entity mapped with `@PrimaryKeyJoinColumn` behaviour

### ISSUE THREAD

**Issue by soberich** [ebean-orm/ebean#1650]
Cascaded update of fields on entity mapped with `@PrimaryKeyJoinColumn` works only if the
id of this entity is set to anything EXCEPT its id which it actually has.
Please checkout code.
there are 4 tests.
The 4th fails despite the 3rd succeeds.
[ebean_issue_.zip](https://github.com/ebean-orm/ebean/files/2958503/ebean_issue_.zip)
```console
./gradlew check
```

**Comment by rbygrave** [comment]
Hmmm. so:

```java
        //throws
        Aggregate.find.byId(1L).setDependent(new Dependent(1L, "nameupdated")).update();
```
```console
13:26:19.071 [main] DEBUG io.ebean.SQL - txn[1003] select t0.id, t0.name, t0.id from aggregate t0 where t0.id = ?  ; --bind(1, )
13:26:19.071 [main] DEBUG io.ebean.SUM - txn[1003] FindBean type[Aggregate] origin[8lSag.A.A] exeMicros[1122] rows[1] bind[1, ]
13:26:19.093 [main] DEBUG io.ebeaninternal.server.persist.DefaultPersister - Update skipped as bean is unchanged:ebean_issue.Aggregate@1
13:26:19.093 [main] DEBUG io.ebean.SUM - txn[1004] BatchControl flush [Dependent:101 i:1]
13:26:19.094 [main] DEBUG io.ebean.SQL - txn[1004] insert into dependent (id, name) values (?,?)
13:26:19.094 [main] DEBUG io.ebean.SQL - txn[1004]  -- bind(1,nameupdated)
13:26:19.098 [main] DEBUG io.ebean.TXN - txn[1004] Rollback error: io.ebean.DuplicateKeyException: Error when batch flush on sql: insert into dependent (id, name) values (?,?) stack0: io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:46) cause: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.DEPENDENT(ID) [1, 'name']"; SQL statement:
insert into dependent (id, name) values (?,?) [23505-198] stack0: org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1298)

io.ebean.DuplicateKeyException: Error when batch flush on sql: insert into dependent (id, name) values (?,?)

	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:46)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:219)
	at io.ebeaninternal.server.transaction.TransactionManager.translate(TransactionManager.java:246)
	at io.ebeaninternal.server.transaction.JdbcTransaction.translate(JdbcTransaction.java:698)
	at io.ebeaninternal.server.transaction.JdbcTransaction.batchFlush(JdbcTransaction.java:680)
	at io.ebeaninternal.server.transaction.JdbcTransaction.internalBatchFlush(JdbcTransaction.java:796)
	at io.ebeaninternal.server.transaction.JdbcTransaction.flushCommitAndNotify(JdbcTransaction.java:1005)
	at io.ebeaninternal.server.transaction.JdbcTransaction.commit(JdbcTransaction.java:1057)
	at io.ebeaninternal.server.core.DefaultServer.commitTransaction(DefaultServer.java:855)
	at io.ebeaninternal.server.core.BeanRequest.commitTransIfRequired(BeanRequest.java:61)
	at io.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:432)
	at io.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:408)
	at io.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1780)
	at io.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1772)
	at io.ebean.Model.update(Model.java:202)
	at ebean_issue.AppTest.updateOfDependentWithItsKeyFails(AppTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Now, the reason for the DuplicateKeyException is because an insert is being performed for the cascade persist of `new Dependent(1L, "nameupdated")`.

It "works" in the other cases where the Dependent Id value is not `1L` due to the `orphanRemoval = true`.  If we look at the logs for the other working cases we see delete from dependent and then insert from dependent.

## Thoughts
At this point I don't see a bug here in that the behaviour looks correct for the code I see.  

It looks like the intent is to perform an update against Dependent (update dependent's name). We would hope to see a `sql update` for that ... but instead with the code/approach in the test we see a `sql delete` + `sql insert` (for the working cases) and only a `sql insert` (for the non-working case resulting in the DuplicateKeyException).      

That is, if the intent is `update dependent` ... then we really shouldn't be using `sql delete` + `sql insert` to achieve that.

## This part here ...
This is fetching Aggregate (so the bean state for aggregate instance is "loaded").
This then sets a new instance of Dependent (so the bean state for that instance is "new").
```java
Aggregate.find.byId(1L).setDependent(new Dependent(1L, "nameupdated")).update();
```
It is not clear why this is not instead doing something like:
```java
Aggregate aggregate = Aggregate.find.byId(1L);
Dependent dependent = aggregate.getDependent();
if (dependent == null) {
  aggregate.setDependent(new Dependent(null, "nameupdated"));  // do NOT set the id value
} else {
  dependent.setName("nameupdated");
}
```

**Comment by rbygrave** [comment]
To say it another way ...

Although the code below works I don't think we should do "updates to dependent" in this manor.  I'd call it an abuse of `orphanRemoval = true`  (with each resulting in `sql delete` + `sql insert` on dependent)
```java
Aggregate.find.byId(1L).setDependent(new Dependent(-1L, "nameupdated1")).update();
Aggregate.find.byId(1L).setDependent(new Dependent(0L, "nameupdated2")).update();
Aggregate.find.byId(1L).setDependent(new Dependent(null, "nameupdated3")).update();
Aggregate.find.byId(1L).setDependent(new Dependent(2L, "nameupdated")).update();
```

**Comment by soberich** [comment]
Origially, the issue we discovered is this. 
"That "dependent" entity won't update."
E.g. if you have an entity which is marked as `PrimaryKeyJoinColumn` in one Entity it won't update unless:
1. You provide setters for its fields
2. You updated some hacky way from the Agregate - something like I showed in code.
See, the picture.
![image](https://user-images.githubusercontent.com/25544967/54280120-fb988b00-4596-11e9-8cf2-c7c875af3b20.png)
(N.B. In database the companyInn stays `old`)

but when I prepared that code I submitted I could not reproduce.
So, I only pointed out strange behaviour - but you explained it. 

As you see on screen shot, I create method where I call `r.update()`
but it does't update. 
Exactly same setup (Entity with final fields without setters) works perfectly for any other Entity annotated bean not envolved in OneToOne with `PrimaryKeyJoinColumn`.

**Comment by rbygrave** [comment]
> where I call r.update() but it does't update.

I don't see any code that makes any properties dirty (aka setters).  If it isn't "dirty" it will not perform an update. We use setters to make the beans "dirty" (unless we are doing stateless updates etc ... another story there).

>  it won't update unless: ... You provide setters for its fields

Yes. That is how we make the bean "dirty".  We call a setter on it with a value that is different to the current value.  The bean knows which properties were made dirty and includes them in the update set clause. If the bean isn't dirty ... then it won't update (unless we force dirty state on the bean).

> Exactly same setup (Entity with final fields without setters) works perfectly for any other Entity annotated bean

I'd suggest that you have a look at the SQL that is happening there.  Performing `sql delete` + `sql insert` (instead of a `sql update`) is not going to make us friends with the database as it gets busy maintaining changes to indexes that it really should not have to do.

**Comment by soberich** [comment]
In response to your message.
here is pojo
```java
@Entity
public class Debt extends Model {
    private static final long serialVersionUID = 1L;

    public static final Finder<Long, Debt> find = new Finder<>(Debt.class);

    @Id
    private final Long       id;
    private final Integer    yearsContracting;
    private final Year       yearOfLoss;

    public Debt(Long id, Long prospectId, Year yearOfLoss) {
        this.id               = id;
        this.yearsContracting = yearsContracting;
        this.yearOfLoss       = yearOfLoss;
    }

// just getters
```

Say we marshall it and unmarshall with Jackson with common JAX-RS. and just updated it upon receival.
```java
    @PUT
    @Path("/debts")
    public Debt updateDebt(@NotNull @Valid Debt debt) {
        return debtsService.save(debt).orElseThrow(NotFoundException::new);
    }
```
in service `debt.update();` executes update statement in sql.
because the field submitted changed.
Works perfectly.
BUT if we take Entity which is like Dependent.java from what I sended you - it is annotated with `PrimaryKeyJoinColumn` - it won't work! Everything is same except that fact.
I don't know how to explain else.

Here is another trick.
```java
Aggregate a = new Aggregate(null, "name", null).insert();
assertThat(notNull(), Dependent.find.byId(a.getId()); // where did this one come from??
assertTrue(new QDependent().id.eq(a.getId().findAll().size() == 0); // this is ok. but what about the one above??
```
OneToOne mapping we have nightmare with. With `PrimaryKeyJoinColumn` especially.
The behaviour of that JPA type of mapping in Ebean is a room for improovment. Unusable.
Please, tell what you think about that difference I tried to explain. Like the Debt entity is updated with no-problem, but the one involved in `PrimaryKeyJoinColumn` fails to update (now we use workaround introducing setters and removing final modifiers.
I hope, you now can see that it is inconsistent and it is not about setters as Debt class updates normally.

**Comment by rbygrave** [comment]
> Say we marshall it and unmarshall with Jackson with common JAX-RS. and just updated it upon receival.

This is a `stateless update`.  This is not a `normal update`.  Stateless update is a feature that Ebean has that no JPA vendor has to maybe there is some confusion.

Specifically when we call `update()` on a bean that is in `NEW` state ... a bean that wasn't loaded from the database then we are doing a stateless update.  That means that Ebean internally needs to make different choices about what is considered an insert and what is considered an update (as it can't rely on the bean state for that in the stateless update case).  

The test code we see at this point didn't do a stateless update.  It loaded Aggregate from the database via a find ... and then modified it by setting the new Dependent instance.  This is NOT a stateless update as we are calling update() on a bean that is in `LOADED` state.

This might be where some confusion is - this is subtle but important (in terms of understanding the issue and finding the correct solution).

If we are having a problem with a `stateless update` on a bean with a relationship to another with `@PrimaryKeyJoinColumn` ... that might be the case but the test code I've seen to date didn't do that (it was a normal update).

Does that make sense?

Do you want to update the test code such that it is actually doing a stateless update?


> OneToOne mapping we have nightmare with

It could be we are mis-communicating.  No JPA vendor has "stateless updates" so maybe this is also part of the confusion.

**Comment by soberich** [comment]
Thank you Rob.
Thank you being very helpful.
So, what about my last comment.
Let's say, we remove everything from the table... to narrow all the things down - what about this behaviour.
> Here is another trick.
```java
Aggregate a = new Aggregate(null, "name", null).insert();
assertThat(notNull(), Dependent.find.byId(a.getId()); // where did this one come from??
assertTrue(new QDependent().id.eq(a.getId().findAll().size() == 0); // this is ok. but what about 
the one above??
```
?

**Comment by soberich** [comment]
I'll close this one to make one clean issue with failing test provided in a minute.
