### ISSUE TITLE
Ask container to get ObjectMapper instance if run in context, particularly Spring

### ISSUE THREAD

**Issue by soberich** [ebean-orm/ebean#1662]
That said,
It is hard to have a bunch of methods and to manually configure Ebean, just because you need to configure ObjectMapper - (which is very common).

There could be a mechanism to wether:
1. reference custom ObjectMapper class (with public default constructor) and instantiate (but please with MethodHandles). Like it is done with CurrentUserProvider.
2. provide a hook like some processor which will configure ObjectMapper, like in [Swagger here](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/api/ObjectMapperProcessor.java).
3. provide more options like SerializationFeatures and SerializationFeatures, also provide an option like `findAndRegisterModules: Boolean` - that one is self-descriptive. 
4. Detect if we run in spring and obtain that - could be done with only `javax.inject.Named` and `javax.inject.Inject` annotations.
The latter two are preferable and easier in implementation (and de-facto more standard).

**Comment by rbygrave** [comment]
> It is hard to have a bunch of methods and to manually configure Ebean, just because you need to configure ObjectMapper

This is not clear to me.  Can you clarify what is hard / not easy?  To me it is not clear what the problem is. Thanks.

**Comment by soberich** [comment]
These lines could be avoided.
```java
    @Bean
    @Profile({ TEST, DEVELOPMENT })
    public DatabaseConfig configDev(ObjectMapper mapper) {
        return getDatabaseConfig(mapper, dataSource, DEVELOPMENT);
    }

    @Bean
    @Profile(PRODUCTION)
    public DatabaseConfig configProd(ObjectMapper mapper) {
        return getDatabaseConfig(mapper, dataSource, PRODUCTION);
    }

    private DatabaseConfig getDatabaseConfig(ObjectMapper mapper, String name) {
        DatabaseConfig config = new DatabaseConfig();
        config.setDefaultServer(true);
        config.setRegister(true);
        config.setName(name);
        config.loadFromProperties();
        config.setObjectMapper(mapper);
        return config;
    }

    @Bean
    public Database database(DatabaseConfig config) {
        return DatabaseFactory.create(config);
    }
```

**Comment by rbygrave** [comment]
These lines can be avoided by using a ServerConfigProvider (especially if the ObjectMapper can be provided by a singleton which is often the case).   Hmmm.

**Comment by soberich** [comment]
It looks better, but I it is the same essentially. So, you hook not Spring but Ebean itself.
I meant config props:
```yaml
jackson:
    serialization:
        indentOutput:            true
        writeDatesAsTimestamps:  false
    deserialization:
        useBigIntegerForInts:    true
        failOnUnknownProperties: false
```
It is not essential, as many other things, but it does show more maturity or smth like that to framework. It could be - "you have to configure all in Java code", or "you may use yaml config for all". But now it is a kind of in the middle of smthing. Not here, not there. That's why I raised it. Maybe it could help if Ebean authors see what drags attention, may be usefull / worthy and not hard to implement at the same time.

**Comment by rbygrave** [comment]
> Maybe it could help if Ebean authors see what drags attention

Absolutely, it is really good to see tickets like this etc and work through these issues. It highlights the parts of documentation and examples that are missing for one.

The actions should be something like:
- Add some documentation on ServerConfigProvider use
- Build and update examples showing configuration setup for Spring boot, Javalin etc

These things all take time etc.

That all said, there might be a better way to configure ObjectMapper than what is currently provided.  It would be good to review spring boot example project(s) to see if there is a better option.

I'd absolutely encourage people to create tickets like this and for us to work though common issues, especially where the documentation and examples are not great or missing.

I apologise for being slow on this - just really busy at the moment (at initial production rollout on the project I'm on right now).

Cheers, Rob.
