### ISSUE TITLE
Q: seedsql in 2.7 ignored? - Resolution:  ebean.ddl.seedSql is case sensitive

### ISSUE THREAD

**Issue by kornale** [ebean-orm/ebean#1664]
It seems that seedsql in the test-ebean.properties file is ignored in the latest version.
I'm using play framework 2.7.0 with ebean plugin 5.0.1

## Expected behavior
should load sql file into database

## Actual behavior
does not load sql

### Steps to reproduce

plugins.sbt:
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.7.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "5.0.1")

test-ebean.properties:
ebean.ddl.seedsql=seed.sql

Try to create test which requires content of see.sql

**Comment by rbygraveClearpoint** [comment]
Can you tell us what the actual version of Ebean is that you are using?  What is the version of the `io.ebean : ebean` dependency?

**Comment by kornale** [comment]
![image](https://user-images.githubusercontent.com/5165714/55326960-4c5e1e00-5489-11e9-804d-8e9612633993.png)

**Comment by rbygrave** [comment]
Right so ebean version is `11.33.2`.

Actually it looks like instead of `ebean.ddl.seedsql` ... this should instead be `ebean.ddl.seedSql` with the uppercase `S` on `Sql`. 

I suspect you are upgrading from an older version of Ebean.  Is that correct?

**Comment by kornale** [comment]
Yes I migrated from an older version, and using uppercase S solved the problem.
Thanks

**Comment by rbygrave** [comment]
Cool.  Closing.
