### ISSUE TITLE
java.time test cases fails under java 11

### ISSUE THREAD

**Issue by tobias-** [ebean-orm/ebean#1725]
## Expected behavior
`mvn clean test` should always return ok irregardless of jvm version.

## Actual behavior

Fails because SimpleDateFormat SSS (millisecond) parses microseconds as an int that can be larger than 999, thus adding seconds and minutes to the result. At worst, it can add 999 seconds or around 16 minutes to the time.

### Steps to reproduce

Look at PR #1724 which just adds java11 (openjdk) to the travis build (and another test case to show what happens)

```console
Expecting:
  <2019-05-27T07:49:33.718>
to have same year, month, day, hour, minute and second as:
  <2019-05-27T07:47:36.117718>
but had not.
```

**Comment by rbygrave** [comment]
Merged #1724  , Fixed with https://github.com/ebean-orm/ebean/commit/385cc76e349a50600b76fa3dc2cf9a7fc8ea9109
