### ISSUE TITLE
like predicate includes collate with a binary collation ? e.g.  like ? collate Latin1_General_BIN 

### ISSUE THREAD

**Issue by zhaofengdeng** [ebean-orm/ebean#1734]
## Expected behavior

console is
```sql
select count(*) from hscn_dealer t0 where t0.name like ? ; --bind(bob)
```

## Actual behavior

console is 
```sql
select count(*) from hscn_dealer t0 where t0.name like ? collate Latin1_General_BIN ; --bind(bob)
```

### Steps to reproduce

```java
public class Test {
	public static void main(String[] args) {
	        ExpressionList<Customer> el = Ebean.find(Customer.class).where();
	        el.like("name", "bob");
        	System.out.println(el.findCount());
	}
}

```

**Comment by rbygrave** [comment]
Hi, this looks like: https://github.com/ebean-orm/ebean/issues/1695

Are you using Ebean 11.39.1 ?  If not can you upgrade to that version and check if that gives you the behavior you expect?

Thanks, Rob.

PS:  This ticket / issue is well done - good work !

**Comment by zhaofengdeng** [comment]
Special thanks to the author for his answers
