### ISSUE TITLE
Wrong SQL generated when using @DiscriminatorColumn and @DiscriminatorValue on the same entity

### ISSUE THREAD

**Issue by shubhamp-zeotap** [ebean-orm/ebean#1741]
## Actual behavior

This is my model using Inheritance with @DiscriminatorColumn and @DiscriminatorValue on the same entity

```
@Data
@Entity
@Table(name = "segments")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@AllArgsConstructor
@NoArgsConstructor
@Inheritance
@DiscriminatorColumn(name = "product_type")
@DiscriminatorValue("target")
public class PartialSegment extends Model {

    @Id
    @Column(name = "id")
    private Long id;

    @NotNull
    @Index
    @Column(name = "segment_id_zat")
    private Long segmentIdZat;

    @Index
    @ManyToOne
    @JoinColumn(name = "segment_status_id", referencedColumnName = "status_id", nullable = false)
    private SegmentStatus status;

    @NotNull
    @Column(name = "product_type", nullable = false, columnDefinition = "varchar(255) default 'target'")
    String productType = "target";

    public static final Finder<Long, PartialSegment> find = new Finder<Long, PartialSegment>(PartialSegment.class);
}
```

When I try to query the table using this model like this:
```
        List<PartialSegment> segments = Ebean.find(PartialSegment.class)
                .select("segmentIdZat")
                .fetch("status")
                .where().eq("segmentIdZat", 108L).findList();

```

These are the SQL statements generated:

```
[debug] io.ebean.SQL - txn[1001] select t0.product_type, t0.id, t0.segment_id_zat, t1.status_id, t1.status, t1.country_ids from segments t0 join segment_status t1 on t1.status_id = t0.segment_status_id  where t0.segment_id_zat = ?; --bind(108)
[debug] io.ebean.SQL - txn[1002] select t0.product_type, t0.id, t0.segment_id_zat, t0.product_type, t0.segment_status_id from segments t0 where t0.id = any(?); --bind(Array[10]={18478,14602,30469,33899,3266,24982,1245,...})
[debug] io.ebean.SQL - txn[1003] select t0.product_type, t0.id, t0.segment_id_zat, t0.product_type, t0.segment_status_id from segments t0 where t0.id = any(?); --bind(Array[10]={1254,4772,11687,24532,24533,13199,5630,15932,...})
```

Issues here are as follows:

1) The where product_type = 'target' clause is missing which was expected as per @Inheritance
2) The select statement in SQL query is always having t0.product_type even though I have explicitly selected only segmentIdZat and status (not sure if this is expected)

Also, I am not sure why the last 2 queries have search Ids divided between them (there are 20 ids in total for 108 segmentIdZat). @rbygrave Is this something Ebean does by default? Though It works correctly as a single query if I am setting disableLazyLoading to true.    

## Expected behavior

@rbygrave Is this expected? As per this reference https://docs.jboss.org/hibernate/jpa/2.1/api/javax/persistence/DiscriminatorValue.html it looks like a valid use case to put both @DiscriminatorColumn and @DiscriminatorValue on the same entity.

I have a workaround though (at a cost of an extra class/model). If I model my entity like this, it is working fine:

```
@Entity
@Inheritance
@Table(name = "segments")
@DiscriminatorColumn(name = "product_type")
public class BaseSegment extends Model {
}
```

```
@Data
@Entity
@Table(name = "segments")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@AllArgsConstructor
@NoArgsConstructor
@Inheritance
@DiscriminatorValue("target")
public class PartialSegment extends BaseSegment {

    @Id
    @Column(name = "id")
    private Long id;

    @NotNull
    @Index
    @Column(name = "segment_id_zat")
    private Long segmentIdZat;

    @Index
    @ManyToOne
    @JoinColumn(name = "segment_status_id", referencedColumnName = "status_id", nullable = false)
    private SegmentStatus status;

    @NotNull
    @Column(name = "product_type", nullable = false, columnDefinition = "varchar(255) default 'target'")
    String productType = "target";

    public static final Finder<Long, PartialSegment> find = new Finder<Long, PartialSegment>(PartialSegment.class);
}
```

The generated SQL has the correct where clause but the issue 2 still persists.

```
[debug] io.ebean.SQL - txn[1001] select t0.product_type, t0.id, t0.segment_id_zat, t1.status_id, t1.status, t1.country_ids from segments t0 join segment_status t1 on t1.status_id = t0.segment_status_id  where t0.product_type = 'target'  and t0.segment_id_zat = ?; --bind(108)
```

**Ebean Version: 11.40.1**

**Comment by rbygrave** [comment]
> it looks like a valid use case to put both `@DiscriminatorColumn` and `@DiscriminatorValue` on the same entity.

For Ebean it currently only supports inheritance mapping to a single table.  The implication is that there should only be one discriminator column for the inheritance tree - so hence Ebean maybe expects `@DiscriminatorColumn` on the common superclass.  Are we looking to specify multiple different `@DiscriminatorColumn`?  It is not clear to me why we'd want to specify a discriminator column on the `PartialSegment` entity (rather than the common superclass).

**Comment by shubhamp-zeotap** [comment]
> so hence Ebean maybe expects @DiscriminatorColumn on the common superclass. Are we looking to specify multiple different @DiscriminatorColumn

No, in this use case, there would be **only one** DiscriminatorColumn (productType) and I wanted to make PartialSegment entity as the root of the hierarchy (this would be the common superclass).

> It is not clear to me why we'd want to specify a discriminator column on the PartialSegment entity (rather than the common superclass)

As being the root of the hierarchy and product_type column defaulting to the value 'target' I wanted to keep the PartialSegment entity queryable, and hence added **@DiscriminatorValue(value = 'target')** to it. 

A little motivation for this came from the [Oracle](https://docs.oracle.com/javaee/5/api/javax/persistence/DiscriminatorValue.html) JPA doc which quotes 

> The discriminator value, if not defaulted, should be specified for each entity class in the hierarchy

Also, please let me know your thoughts about these

> The select statement in SQL query is always having t0.product_type

> why the last 2 queries have search Ids divided between them

**Comment by rbygrave** [comment]
> The select statement in SQL query is always having t0.product_type even though I have explicitly selected only segmentIdZat and status (not sure if this is expected)

That is expected.

In this case the type being queried has sub-types ... so when Ebean is internally reading the ResultSet and turning those into beans ... it needs to determine the type of the bean it is loaded per row.  It does that by reading the discriminator column (`t0.product_type`).

> Though It works correctly as a single query if I am setting disableLazyLoading to true.

Well that is all expected right.  We don't see the code that is iterating and reading those beans but it's reading one of the properties that isn't loaded hence it is invoking lazy loading.

So this is all working as expected as I see it.

**Comment by rbygrave** [comment]
I'll close this.  I believe this is working as expected.  Re-open if that isn't the case.
