### ISSUE TITLE
When using @PrimaryKeyJoinColumn, FK constraint generation cannot be disabled

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#1743]
I have a O2O relation that maps on ID column, so @PrimaryKeyJoinColumn() should be perfect for this
```java
public class Entity1 {
        ...
	@OneToOne
	@PrimaryKeyJoinColumn()
	private Entity2 entity2 = new Entity2();
}
```
In my case, both entities may exist as their own, so I have to create & save an entity2 before entity1 exists in database, but this is prevented by a FK constraint generated by ebean.
I tried adding `@DbForeignKey(noConstraint = true)` or `@PrimaryKeyJoinColumn(foreignKey = @ForeignKey(value = ConstraintMode.NO_CONSTRAINT))`, but this has no effect.

## Expected behavior
When using @PrimaryKeyJoinColumn, it should be able to disable FK constraint generation  with the `@DbForeignKey` (or `@ForeignKey`) annotation.

## Actual behavior
None of the annotations is honored, a FK constraint is always generated

## Possible fix
```diff
diff --git a/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java b/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
index 5c19323b4..45c4adace 100644
--- a/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
+++ b/src/main/java/io/ebeaninternal/server/deploy/BeanDescriptorManager.java
@@ -1732,6 +1732,9 @@ public class BeanDescriptorManager implements BeanDescriptorMap {
 
   private void addPrimaryKeyJoin(DeployBeanPropertyAssocOne<?> prop) {
 
+    if (prop.getForeignKey() != null && prop.getForeignKey().isNoConstraint()) {
+      return;
+    }
     String baseTable = prop.getDesc().getBaseTable();
     DeployTableJoin inverse = prop.getTableJoin().createInverse(baseTable);
```
This will, at least give me control, if FK constraint should be generated or not (it does not add full support for `@DbForeignKey` (onDelete / onUpdate). Maybe it would be better to support only  `@ForeignKey` in this case which is not yet parsed from the @PrimaryKeyJoinColumn annotation yet.

@rbygrave what do you think would be the better option here?

**Comment by rbygrave** [comment]
`BeanPropertyAssocOne.hasForeignKey()` looks more like what would be good to use  in ModelBuildPropertyVisitor.

I'll have a look at that option.

**Comment by rbygraveClearpoint** [comment]
I think the PR - https://github.com/ebean-orm/ebean/pull/1745 ... will be close

**Comment by rPraml** [comment]
yes #1745 solves my problem

**Comment by rbygrave** [comment]
Closing with PR #1745 merged.
