### ISSUE TITLE
Compiling error when use io.ebean.tile:enhancement:11.4x.x

### ISSUE THREAD

**Issue by ooknight** [ebean-orm/ebean#1757]
When I execute "mvn clean package", I got error :
X is not abstract and does not override abstract method _ebean_getFieldIntercept(int) in EntityBean

this is my demo project 
[demo-bean.zip](https://github.com/ebean-orm/ebean/files/3395517/demo-ebean.zip)

java : jdk-1.8.0.211.x64
maven : 3.6.1

**Comment by rPraml** [comment]
Same as #1755

**Comment by rbygrave** [comment]
Effectively a duplicate of #1755 ... so closing as a duplicate (fix for 1755 has been merged).
