### ISSUE TITLE
Change such that db-create-all.sql and db-drop-all.sql generated files go into target (maven) or build (gradle) directories 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1763]
Hi @dastultz  @rPraml  and anyone else interested.

I think the generated ddl files `db-create-all.sql` and `db-drop-all.sql` should go into the target or build directory if they exists.

I think this makes sense.  Any reason for these files to still be generated into the current directory?  Anyone want to keep the current behaviour for some reason?

For myself I think this is just one of the things where I like to look at the ddl and check it and happy to .git ignore it etc ... but maybe most people expect it to go into the target or build directory.  It is probably odd that those files are there and that is probably confusing as it isn't clear then that those files are re-generated all the time.

Thanks for any feedback.  Otherwise I'll look to change those generated ddl files to go into the target or build directories.

Cheers, Rob.

**Comment by rPraml** [comment]
We do not really need these files.
Our applications use dbmigration
We only sometimes build "preview-jar" apps with ddl-generate and ddl-run enabled. So the scripts are written in current dir.
So maybe the files can also go into temp dir.

**Comment by rbygrave** [comment]
My thought is that if `target` or `build` doesn't exist then it will stick with putting them into the current directory.
