### ISSUE TITLE
hava sqlException with database table name

### ISSUE THREAD

**Issue by econaz** [ebean-orm/ebean#1779]
my database table name include "-",example "employee-table",and execute throw sqlException, how to resolve it

**Comment by rbygrave** [comment]
If you surround the table name in backticks ` ... then it will use quoted
identifiers for the given database platform.

So using @Table(name="`employee-table`")  ... should do the trick.


Just to share an opinion - to me it is unhealthy to promote the case that
you must use quoted identifiers.  I think SQLServer folks are the only
people who truely push that but they then push to use it everywhere on
every table and column name.  I'm old school Oracle so I don't like that
much :)

We want to be in the position where in some future time we can replicate
data across different databases without too much effort in my view it's
better to use safe table and column names from that perspective.


Cheer, Rob.

**Comment by econaz** [comment]
oh,thank you,i resove it
