### ISSUE TITLE
ENH: Add truncate(Class<?>... types)  ?  ... truncate(String... tables)  ?

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1782]
I'm thinking it would be good from a testing perspective.  We shouldn't really be using `truncate()` in main code but we certainly could/should be using it for tests rather than `delete()` queries.

Any thoughts?  Anyone think we shouldn't do this?  

```java

// In test code we could do ...

 // entity bean types
DB.truncate(Order.class, OrderDetail.class);

// tables
DB.truncate("orders", "order_detail"); 
```

**Comment by frensjan** [comment]
I'm from the "we're all grown-ups here" camp ... 👍.

**Comment by jnehlmeier** [comment]
I am unsure if I would use that during tests. I tend to use transactions and never really commit data to the DB, so after rollback is it always empty. I also reset sequences between tests so database id columns always have same numbers. There are also tables containing core data that doesn't need to be touched at all between test classes / methods. So sometimes truncate might work, sometimes not.

But I like the API and I guess some people might find it useful.

**Comment by rbygrave** [comment]
> never really commit data to the DB

We should create a junit4 runner and junit5 runner that uses the new `ForTests.RollbackAll` ... https://github.com/ebean-orm/ebean/issues/1760

**Comment by jnehlmeier** [comment]
Just used the new truncate method and noticed that it adds cascade by default.

`[main] DEBUG io.ebean.SQL - truncate table some_table cascade`

Seems a little dangerous? Given that SQL TRUNCATE does not have that many parameters, maybe add an API to configure them?

https://www.postgresql.org/docs/12/sql-truncate.html

**Comment by rbygrave** [comment]
It would seem dangerous if truncate() was used in production code as opposed to test code.  For me I've only been intending truncate() for testing ... but maybe you are right there.

What we could do is have `truncate()` mean `truncate restrict` and more explicit `truncateCascade()` use cascade if it supported by the database.

I don't think we need to offer more like 'restart identity' in that people can always use `db.sqlUpdate()` to execute whatever they like and I don't know how widely supported that is across database's.

**Comment by jnehlmeier** [comment]
Yeah I am currently using `db.sqlUpdate` with 'truncate table ... restart identity restrict`. It is used for importing (and replacing) CVS data into a database table and I really want an error raised by the DB in anyone ever creates a foreign key for that table. That's why `cascade` felt a little dangerous for me :)
