### ISSUE TITLE
Bean gets replaced on json deserialization with primitive 'null' id

### ISSUE THREAD

**Issue by frensjan** [ebean-orm/ebean#1785]
When loading json into a bean, (child) beans get replaced when they have a primitive (e.g. long) typed identifier that is 0.

## Expected behavior
When deserializing beans without identifier, the should be loaded 'correctly'.

## Actual behavior
Beans with a uninitialised / 0 primitive identifier get 'clobbered' because they are looked up in the current persistence context.

### Steps to reproduce
Given a model like:
```java

@Entity
public class MyBean {
    ...

    @OneToMany(cascade = CascadeType.ALL)
    @JoinTable
    private List<BeanToSerializeChild> related;

    ...
}

@Entity
public class BeanToSerializeChild {

    @Id
    @GeneratedValue
    public long id;

    @Column
    private String value;

    ...
}
```

The following test fails:
```java
String json = ("" +
        "{ 'related': [" +
        "  { 'value': 'a' }," +
        "  { 'value': 'b' }" +
        "] }"
).replaceAll("'", "\"");

BeanToSerialize bean = database.json().toBean(BeanToSerialize.class, json);
assertEquals(bean.getRelated().get(0), new BeanToSerializeChild("a"));
assertEquals(bean.getRelated().get(1), new BeanToSerializeChild("b"));
```

The culprit is probably in io.ebeaninternal.server.deploy.BeanDescriptorJsonHelp#jsonReadProperties:
```java
Object id = desc.beanId(bean);
if (id != null) {
  // check if the bean has already been loaded
  contextBean = readJson.persistenceContextPutIfAbsent(id, bean, desc);
}
```

Maybe it is a matter of something along the lines of ```if (id != null && id != 0) ...```. But I don't know ebean inside-out enough to estimate the consequences.

The workaround obviously is to use ```Long``` instead of ```long```.

**Comment by rbygrave** [comment]
> The culprit is probably 

Exactly right.

> Maybe it is a matter of something along the lines of ...

Exactly.  We have a static method for this - DmlUtil.isNullOrZero() ... fix uses that.
