### ISSUE TITLE
Q: Does spring multi-environment configuration not support

### ISSUE THREAD

**Issue by weiwill** [ebean-orm/ebean#1805]
- application.yml
- application-dev.yml
- application-prod.yml

if datasource.db... in application-dev.yml. It throw Exception  io.ebean.datasource.DataSourceConfigurationException: DataSource user is null?

and datasource.db... in - config/application.yml The same exception will be thrown

**Comment by rbygrave** [comment]
Correct.  Configuration is not aware of Spring environment, it is not supported.

**Comment by weiwill** [comment]
So is there any way to set up multiple datasource. db for dev / prod?

**Comment by rbygrave** [comment]
Use spring to wire the properties for the datasource.  Isn't that what you are going to do?  Did you have something else in mind?

**Comment by weiwill** [comment]
At present, only datasource.db... can be placed in application. yml.
I hope I can put them in application-dev.yml and application-prod.yml.
When spring.profiles.active = dev, I can use the datasource set in application-dev. yml.

**Comment by rbygrave** [comment]
You can review how you want to do it and submit a PR for consideration.

This should be closed though.  No, we don't support Springs multiple environment properties file loading.

**Comment by weiwill** [comment]
I used the following code to achieve the desired effect

The configuration of datasource.db can be placed in application-dev.yml

```kotlin
@Configuration
class EbeanServerConfig {

    @Value("\${datasource.db.username}")
    internal var username: String? = null
    @Value("\${datasource.db.password}")
    internal var password: String? = null
    @Value("\${datasource.db.databaseUrl}")
    internal var databaseUrl: String? = null
    @Value("\${datasource.db.databaseDriver}")
    internal var databaseDriver: String? = null

    @Bean
    fun ebeanServer(): EbeanServer {
        val config = ServerConfig()
        val dataSourceConfig = DataSourceConfig()
        dataSourceConfig.username = username
        dataSourceConfig.password = password
        dataSourceConfig.url = databaseUrl
        dataSourceConfig.driver = databaseDriver
        config.dataSourceConfig = dataSourceConfig
        return EbeanServerFactory.create(config)
    }
}
```
