### ISSUE TITLE
Whan paging over query with @Aggregation ( grouping by) wrong total count is calculated

### ISSUE THREAD

**Issue by pnartowski** [ebean-orm/ebean#1810]
When using query with grouping by ( @Aggregation(sum(...)) ) for retrieve paged list wrong total count is calculated.

When watching SQLs generated by such query, query which retrieve data is built correctly where as query for counting total doesn't use grouping by and this lead to bigger total count then number of retrieved rows.

## Expected behavior
Correctly calculated total count for paged list.

## Actual behavior
Total count is bigger then expected and is equal to total number of rows without grouping by.

### Steps to reproduce

```
@Entity( ... )
class Car {
   private String brand;

   private int sold;
  
  @Aggregation("sum(sold)")
   private int totalSold;

  ...
}

query()
.select("brand, totalSold")
.setFirstRow(0)
.setMaxRows(100)
.findPagedList();

```

**Comment by rbygrave** [comment]
I think I should be able to look at this and reproduce over the next couple of days.
Thanks, Rob.

**Comment by pnartowski** [comment]
Thanks Rob
