### ISSUE TITLE
Update query with maxRows does not include the limit in the generated SQL

### ISSUE THREAD

**Issue by BrettCao** [ebean-orm/ebean#1831]
## Expected behavior
update limit invalid
### Steps to reproduce

```java
query.exception_status.eq(0)
  .document.isNotNull
  .cpCode.eq(cpCode)
  .setMaxRows(500)
  .asUpdate().set("batch_no", batchNo).update()
```

```sql
-- sql update should go here 
```

**Comment by BrettCao** [comment]
query.exception_status.eq(0).document.isNotNull.cpCode.eq(cpCode).setMaxRows(500).asUpdate().set("batch_no", batchNo).update()

**Comment by rbygrave** [comment]
This issue is not clear or understood. The statement `update limit invalid` is not clear.  

Please update this ticket so that it is clear and can be understood.  If there is SQL involved then please include the SQL in the ticket.

Thanks, Rob.

**Comment by BrettCao** [comment]
I can't use setMaxrows to limit the number of updates

**Comment by rbygrave** [comment]
Given your example: 
- What would be the SQL update generated for Postgres.
- What would be the SQL update generated for Oracle.

**Comment by rbygrave** [comment]
Note: https://asktom.oracle.com/pls/apex/asktom.search?tag=update-top-n-row-of-a-select

People should note that this is not really a great approach / thing to do.  People should strongly look at the design of what they are doing before they take the approach of using a limit in an update statement.

**Comment by rbygrave** [comment]
Note that this is not strictly supported by all databases.  MySql uses LIMIT clause on simple updates, H2 and Postgres etc use a sub-query.
