### ISSUE TITLE
ebean.properties的ebean.search.jars=test.jar failure

### ISSUE THREAD

**Issue by zhaofengdeng** [ebean-orm/ebean#1850]
### Steps to reproduce

```java
  // TestModel is in the test.jar.
//ebean version is 11.22.5 

List<TestModel> list = Ebean.find(TestModel.class).findList();
System.out.println(list.size());
```

```console
  //
Exception in thread "main" javax.persistence.PersistenceException: com.util.TestModel is NOT an Entity Bean registered with this server?
```

**Comment by rbygrave** [comment]
There is no `ebean.search.jars` property any more.

Instead have a ebean.mf manifest file with the package(s) that contain entity classes or register the entity beans via `serverConfig.addClass()`

Ideally you upgrade Ebean to `12.1.x` as well.

https://ebean.io/docs/introduction/manifest
