### ISSUE TITLE
Q: When associating queries, can there be no associated entities?Because I don't need entity data.关联查询时，可以没有关联实体？因为我不需要实体数据

### ISSUE THREAD

**Issue by zsmome** [ebean-orm/ebean#1856]
GITHUB ISSUES ARE STRICTLY CONTROLLED FOR THIS PROJECT.

Refer to http://ebean-orm.github.io/support for the policies controlling the use of github issues.
Please post issues to the Ebean group https://groups.google.com/forum/#!forum/ebean first.

### Steps to reproduce

```java
  // some java code
```

```console
  // some logging output
```

**Comment by rbygrave** [comment]
Your question is not clear enough for me to understand.  Can you please
provide an example to help clarify what you mean. Thanks.

**Comment by rbygrave** [comment]
I'll close this question for now.  Re-open this issue when you improve the question / maybe add an example etc.  Thanks.
