### ISSUE TITLE
@PreUpdate is not working with .update()

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#1860]
Simply, I got bean to save, which have JSON as string, so when I save the bean I get it as string and store it, and when I fetch it, I revert it as a map (or can be JSON as for example), so I got `@PrePersist`, `@PreUpdate` and `@PostLoad` to do that, the problem is that all of them working fine except with `update()` is not calling `@PreUpdate` part, while `.insert()` and `.save()` do call `@PrePersist`, and `@PostLoad` called when I fetch the bean!

## Expected behavior
When I do `.update()`, `@PreUpdate` should be called.

## Actual behavior
When I do `.update()`, `@PreUpdate` is ignored.

### Steps to reproduce

```java
@Entity
@Table(name = "products")
public class Product extends Model {
    @Id
    @Column
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(length = 256, nullable = false, unique = true, name = "name")
    @Constraints.Required
    @Constraints.MinLength(2)
    @Constraints.MaxLength(256)
    private String name;

    @Column(length = 1000)
    @Constraints.MaxLength(1000)
    private String description;

    @Column(length = 1000)
    @JsonIgnore
    private String properties;

    @Transient
    private Map<String, Object> options;

    @PrePersist
    public void prePersist() throws IOException {
        if (this.options != null) {
            this.setProperties(new ObjectMapper().writeValueAsString(this.options));
        }
    }

    @PreUpdate
    public void preUpdate() throws IOException {
        if (this.options != null) {
            this.setProperties(new ObjectMapper().writeValueAsString(this.options));
        } else {
            this.setProperties(null);
        }
    }

    @PostLoad
    public void postLoad() throws IOException {
        if (this.properties != null && !this.properties.isEmpty()) {
            ObjectReader reader = new ObjectMapper().readerFor(Map.class);
            this.setOptions(reader.readValue(this.properties));
        }
    }

    // .. setters and getters
}
```

Then:
```java
final Map<String, Object> options = new HashMap<>();
options.put("option1", "option value");

final Product product = new Product()
       .setName("Test")
       .setDescription("this is a test")
       .setOptions(options)
       .insert(); // .prePersist() triggering

Ebean.find(Product.class).where().idEq(1)
       .findOne()
       .setName("Product X")
       .update(); // .preUpdate() is not triggering
```

Right now, I did this silly workaround for it: 

```java
    @Override
    public void update() {
        try {
            preUpdate();
        } catch (IOException e) {
            // I do some exception handling here
        }
        super.update();
    }
```

**Comment by rbygrave** [comment]
>             this.setProperties(new ObjectMapper().writeValueAsString(this.options));

ObjectMapper is a **very expensive** object to new up.  You do not want to do the above but instead have a shared ObjectMapper instance (private static final ObjectMapper mapper = ....)

**Comment by almothafar** [comment]
@rbygrave thank you for pointing to this, but I have this just as an example, I do some cleanup and refactor to an old project, so is it the issue here?

**Comment by rbygrave** [comment]
I haven't tried to reproduce yet.  I suspect this test case will not reproduce though - you are sure this reproduces right?

**Comment by rbygrave** [comment]
Have a look at the test I've just added - this issue does not reproduce.

**Comment by rbygrave** [comment]
Adding in "other" property that is set on `preUpdate()` and all working as expected - issue not reproduced.

**Comment by almothafar** [comment]
@rbygrave Well, I tried to be close to the code in the real project, as for example, I'm not using `Ebean.update()`, didn't try that to be honest, but in the code, it is querying for an existing record, check if it is null or not, then update it.

Anyway, if you didn't get the issue, I'll provide a small project that reproduces the problem, well, I'll provide it anyway ASAP once I finish a critical task in my hands right now.

**Comment by rbygrave** [comment]
Ok, closing for now.  Reopen when you have the failing test case - ta.

**Comment by almothafar** [comment]
@rbygrave OMG, my bad, I think I got the problem, I'm changing "@Transient" property in the project, and that does not trigger the update 🙃

**Comment by rbygrave** [comment]
Ah cool ... nice to find the issue !!
