### ISSUE TITLE
out of order nextId() sequence generation

### ISSUE THREAD

**Issue by turbospaces** [ebean-orm/ebean#1869]
I have seen `PlatformIdGenerator.nextId()` might return out of order  sequence value, at least this is easy reproducible with H2, and probably other databases. In my test, method returned 1..20 values, then 41, and then 21..22..23 up to 40. This is inconsistent behaviour as such, and i think root cause for that is this method

```
@Override
  public Object nextId(Transaction t) {
    synchronized (monitor) {

      int size = idList.size();
      if (size > 0) {
        maybeLoadMoreInBackground(size);
      } else {
        loadMore(allocationSize);
      }

      return idList.remove(0);
    }
  }
```  
And this peace of code
```
private void loadMore(int requestSize) {
    List<Long> newIds = getMoreIds(requestSize);
    synchronized (monitor) {
      idList.addAll(newIds);
    }
  }
```

Since  
 `protected final ArrayList<Long> idList = new ArrayList<>(50);`
is not SortedSet, it might happen that thread which loads ids in background might take time, and since that main current thread will load ids.

This peace is not synchronised
`List<Long> newIds = getMoreIds(requestSize);`  

I think simplest fix would be to change idList to SortedSet

**Comment by rbygrave** [comment]
Ok.

Note that I think we need to be a little careful here in that if we use something like Oracle RAC there isn't a strict guarantee that sequences are returned in order (due to the spread across the cluster).  In theory we need to try and not write anything that has such a strict requirement on sequence order.
