### ISSUE TITLE
Cidr type stored as INET (instead of CIDR) + named as Cdir (typo)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1880]
Refer to https://github.com/ebean-orm/ebean-types/issues/2

The Cidr type with Postgres is currently stored as `INET` where it should be stored as `CIDR`, plus is it incorrectly named as Cdir ???? (my bad).

This change:
- Renames the type from Cdir -> Cidr
- Fixes the type mapping such that it maps to the Postgres `CIDR` type 

With this issue I deem that Cdir didn't work to be useful so I'm making this change in a breaking way such that anyone using Cdir will fail compile and hopefully come here.

**Comment by Kars-de-Jong** [comment]
Found two more `Cdir` occurrences in comments.

**Comment by rbygrave** [comment]
Thanks, found them !!!
