### ISSUE TITLE
Q: serverConfig.addClass(),how to refresh ebeanServer?

### ISSUE THREAD

**Issue by ricardo0624** [ebean-orm/ebean#1887]
code repo : [gitee](https://gitee.com/david0624/learn-ebean)
main pers.apricot.Portal

![gitee eban](https://user-images.githubusercontent.com/12064877/70677886-695f1800-1ccb-11ea-80d5-cc7207360197.png)

ebean version:12.1.5

# backgroud

in my business, When create a table ,The app is runing and no need to stop,I need support dynamic create  class and add this entity bean,So I create my own classLoader, load the class,but I already have a ebean server ,is there something function in ebeanserver like refresh,So I can avoid to create multi ebeanserver.

thanks for your help! Ebean is really great

**Comment by rbygrave** [comment]
> is there something function in ebeanserver like refresh,So I can avoid to create multi ebeanserver.

No there is not.

I suspect it would not be easy to support such a feature in that there is a reasonable amount of meta data read (mapping annotations and such) and this occurs in multiple phases as generally entity beans relate to each other.   I guess the dynamically defined class doesn't actually relate to anything ... has no `@OneToMany` or `@ManyToOne` etc.

**Comment by ricardo0624** [comment]
thank you。
ok，if there is not.
Should I create a new ebean server,and in this way,what should I care about and how to close last ebean server?

**Comment by rbygrave** [comment]
> how to close last ebean server?

Call the `shutdown()` method.

> new ebean server,and in this way,what should I care about

Yes.  I don't know of anything specific to care about per say.

**Comment by ricardo0624** [comment]
@rbygrave thanks a lot.
I will create a new ebean server and use it instead of the old ebean server.and I will `shutdown()` the old ebean server

**Comment by ricardo0624** [comment]
`ebeanServer.shutdown(false, false);`
I need to reuse the datasource and no need to deregister driver.
