### ISSUE TITLE
Indexes names, like index, unique, primary and foreign keys does not honor ebean.allQuotedIdentifiers 

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#1897]
It was something and noted in #1896, just to keep issues separated, but I think index for tables should be honoring the value of `ebean.allQuotedIdentifiers`, since I see it does not get any effect of the value if it was true or false.

## Expected behavior

The generated script that creates the keys should follow the "convention" and get quoted if `ebean.allQuotedIdentifiers` the value is true, like: `[ix_Labs_AddressID]`, `[fk_Labs_AddressID]`, `[pk_Labs]` 

```sql
create index [ix_Labs_AddressID`] on [dev].[Labs] (addressid);
alter table [dev].[Labs] add constraint [fk_Labs_AddressID] foreign key (addressid) references [dev].[Addresses] ([AddressID]);
```

## Actual behavior

Currently, it is created all with small letters and without quotes:

```sql
create index ix_labs_addressid on [dev].[Labs] (addressid);
alter table [dev].[Labs] add constraint fk_labs_addressid foreign key (addressid) references [dev].[Addresses] ([AddressID]);

```

### Steps to reproduce

Can use the same entities in  #1896 

It could be minor for me, but I see it is clearly an issue for some cases?

I need to double-check the unique key, but pretty sure it is the same scenario.

**Comment by rbygrave** [comment]
> just to keep issues separated

Yes, it's good to keep them separate as you have done - nice !!

**Comment by rbygrave** [comment]
Improved DDL taking into account `ebean.allQuotedIdentifiers=true`

```sql
create table [Labs] (
  [LabID]                       integer identity(1,1) not null,
  [Name]                        nvarchar(50) not null,
  [AddressID]                   numeric(19),
  constraint [pk_Labs] primary key ([LabID])
);

create index [ix_Labs_AddressID] on [Labs] ([AddressID]);
alter table [Labs] add constraint [fk_Labs_AddressID] foreign key ([AddressID]) references [Addresses] ([AddressID]);

```

**Comment by rbygrave** [comment]
Additionally, thank you @almothafar  for your donation.  I have included you in the list of silver sponsors - Thanks !!
