### ISSUE TITLE
Parameter in subquery cannot be assigned

### ISSUE THREAD

**Issue by zhaofengdeng** [ebean-orm/ebean#1901]
### Steps to reproduce

```java
  // some java code
```
//SQLXML select id from **** where no like :firstApplicant 
ExpressionList<Order> el = Ebean.find(Order.class).where();
Query<Order> subQuery=Ebean.createNamedQuery(Order.class, "searchOrderIdByFirstApplicant").
				select("id").where().query();
//parameter firstApplicant is nameSql
 el.orderBy("updateTime,id desc").setParameter("firstApplicant", "%" + firstApplicant + "%").findList();
```console
  // some logging output
Query threw SQLException:“:”附近有语法错误
```

**Comment by rbygrave** [comment]
There is not sufficient information in this issue.  You need to show the query for "searchOrderIdByFirstApplicant"

**Comment by rbygrave** [comment]
@zhaofengdeng  Can you say why this issue was closed?  Did you find a solution?
Thanks, Rob.
