### ISSUE TITLE
SingleAttributeQueries with child selection only does not work with autoTune=false (e.g. Views)

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#1902]
## Expected behavior
we have a query with `.select("").fetch("child", "attribute").setCountDistinct(true).findSingleAttributeList()` on a view.

## Actual behavior
the query produces wrong result on a view, but works on a table.
The problem was, that all properties of the root-bean were selected.

Possible fix:
https://github.com/FOCONIS/ebean/commit/849a768a62aeb327c16f94151f363fb6e1b1c6b2

## Test
sorry, no test yet - setting `.setAutoTune(false)` does not trigger the bug.
would require to build a test like `findSingleAttributeList_with_join_column` on a view.

Cheers
Roland

Cheers
Roland

**Comment by rbygrave** [comment]
The possible fix looks good to me.

**Comment by rPraml** [comment]
not yet fixed, see #1908
