### ISSUE TITLE
Change findStream() to close resources without needing try-with-resources

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1905]
When developers use findStream() without closing the stream this will leak resources.  I think this is too likely to happen so this changes the findStream() implementation to fetch all the results and close resources before returning the stream.

Note that we still should use try-with-resources for findLargeStream().

## Expected behavior
Allow code like this below (without try with resources) and for it not to leak resources.
```java
    Stream<Customer> stream = DB.find(Customer.class).findStream();

```

Note that we still should use try with resources for findLargeStream() ... noting that maybe it is better to use findEach() or findEachWhile() instead which ensure the resources are closed.

```java
// using try with resources
try (Stream<Customer> stream = DB.find(Customer.class)
    .findLargeStream()) {
    ...
}
```

**Comment by jnehlmeier** [comment]
Personally I don't like it because you now have no performance gain compared to a usual `findList().stream()` call that you could always do. 

IMHO the primary use for `findStream()` is to provide a better implementation than `findList().stream()` which SHOULD NOT copy all found results into a list first before creating a stream. Thats because the terminal operation of a stream does the copying usually as well.

The Stream javadoc clearly states that streams based on IO channels usually need closing and you can document it in `findStream` as well.

Maybe you should keep the previous implementation of `findStream` and instead introduce `findListAsStream` which does simply delegate to `findList().stream()` or use JavaDoc on `findStream()` to tell users to use `findList().stream()` if they don't want to close streams at the cost of having data copied once into a list.

**Comment by rbygrave** [comment]
> now have no performance gain compared to a usual

Have you tried to measure a performance gain here though?  The potential extra cost of this change is approximately an extra ArrayList.add() per row/entity.  This is going to be really hard to detect a cost difference .

It could even be that `findList().stream()` is better/faster given that it more aggressively reads the resultSet and releases the JDBC resources. 

> the terminal operation of a stream does the copying 

The use of stream `filter()` [and `map()`] in our SQL/JDBC case isn't going to be a real performance gain though - it would have no performance impact either way in our case.  The difference comes down to an extra ArrayList.add() per row/entity.

I'll revert this back if we can demonstrate a performance gain / difference.

> and instead introduce findListAsStream

We still have `findLargeStream()` and imo the better `findEach()` / `findEachWhile()`.

**Comment by rbygrave** [comment]
> SHOULD NOT copy all found results into a list first before creating a stream. Thats because the terminal operation of a stream does the copying usually as well.

Just some points on this to outline my thinking for our JDBC/SQL case.

- We should always prefer query predicates rather than stream `filter()` to reduce the results
- We should always prefer query projection rather than stream `map()` to reduce the result projection
- As soon as we execute the query `findStream()` our app is holding JDBC resources and the DB is sending results to the JDBC buffer.  The app/Ebean's job at this point is to read the results from that JDBC buffer as fast as it can and close those JDBC resources which also frees up the related database resources.
- ArrayList.add() is fast and cheap relatively speaking 

> The Stream javadoc clearly states

Maybe I'm being too conservative / too untrusting.

**Comment by rbygrave** [comment]
## Background note:   

By "default" Postgres and MySQL at the JDBC level return all results back to the client.  That is they don't "buffer" and wait for resultSet.next() but just "send it all".  This is unlike Oracle which will by default will buffer results (from memory 100 rows or something like that).

When we use findIterate, findEach, findLargeStream ... Ebean will tell Postgres and MySql JDBC to use a buffer - please don't send us all the results but buffer them and get more on demand as the client consumes them.

--------------
So in the context of Postgres and MySql only (and without doing anything like query.setBufferFetchSizeHint()) then:

findList().stream() ... will pull everything aggressively (does not buffer)
findStream() ... (as it was before using QueryIterator) would actually trigger the use of JDBC buffering for Postgres and MySql. 

So when I said above that the difference was just a ArrayList.add() ... that wasn't correct.  For Postgres and MySql at least, there was also the difference is also in the underlying JDBC buffering used. 

This makes me think that we should revert this commit back.  That findStream() should go back to internally using QueryIterator 

... and this means we just need to make sure people use `try with resources` with findStream() - that I was being too conservative / not trusting enough.

**Comment by rbygrave** [comment]
This change is now in a PR.  At this stage the plan is not to merge the PR and leave findStream() working as currently meaning we need to make sure we use `try with resources` to ensure the stream is closed.

**Comment by rbygrave** [comment]
Closing - not pushing this change - leaving it as it was.
