### ISSUE TITLE
PostgresPlatform (9+) does not support IdType.IDENTITY?

### ISSUE THREAD

**Issue by jnehlmeier** [ebean-orm/ebean#1917]
## Expected behavior

Entities using `@GeneratedValue(strategy = GenerationType.IDENTITY)` should not produce  suspicious log entry for Postgres 9+.

## Actual behavior

```
INFO  io.ebean.internal.DefaultContainer: DatabasePlatform name:KUNDE platform:postgres
INFO  i.e.server.deploy.BeanDescriptorManager: Explicit Identity on package.someEntity but not supported by DB Platform - ignored
```

### Steps to reproduce

Create a `DatabaseConfig` and set `PostgresPlatform` for Postgres 9+ and use `@GeneratedValue(strategy = GenerationType.IDENTITY)` in entities.

### Possible solution

Seems like that `Postgres8Platform` which extends `PostgresPlatform` does call the super constructor and then `dbIdentity.setSupportsIdentity(true)`. However the constructor of `PostgresPlatform` itself does not configure identity support and thus defaults to `false`.

Given that both platforms support sequence and identity I think 
```
    this.dbIdentity.setSupportsSequence(true);
    this.dbIdentity.setSupportsIdentity(true);
```
should be moved from `Postgres8Platform` constructor to `PostgresPlatform` constructor.

**Comment by rbygrave** [comment]
The suggested fix above is correct.  Effectively we need to move `this.dbIdentity.setSupportsIdentity(true);` to `PostgresPlatform`.
