### ISSUE TITLE
BeanPersistRequest.getUpdatedValues() is empty in BeanPersistAdapter.postUpdate

### ISSUE THREAD

**Issue by wanno-drijfhout** [ebean-orm/ebean#1919]
## Expected behavior

We derive a class from `BeanPersistAdapter` and override method `postUpdate(BeanPersistRequest<?> request)`. In that method, we want to inspect the updates that were persisted via `request.getUpdatedValues()`. We need to have both the updated property names and their _values_.

This worked in Ebean 7.5.1.

## Actual behavior

`request.getUpdatedValues()` always yields an empty map in Ebean 11.45.1. I haven't managed to pinpoint the commit that changed the behavior.

### Steps to reproduce

1. In `DefaultPersister.update(PersistRequestBean<?> request)` there's a call to `request.executeOrQueue()` which starts the process.
2. In `PersistRequestBean.postExecute()`, a call is made to `intercept.setLoaded()`. Until then, `getUpdatedValues()` contains values.
3. After `intercept.setLoaded()`, the `getUpdatedValues()` is empty (because all dirty flags have been reset).
4. In `DefaultPersister.update(PersistRequestBean<?> request)` there's a call to `request.completeUpdate()`. This will call `postUpdateNotify()`, then `postUpdate()` which then calls our custom `BeanPersistAdapter`.

**Comment by wanno-drijfhout** [comment]
(By the way: would you prefer if I prepare a test case for this scenario? Or are the problem and solution obvious to you already with the description as-is?)

**Comment by rbygrave** [comment]
Yes it is a good description but yes we need a failing test case to ensure we don't have a regression in future.

If you can prepare a failing test that would be great.

**Comment by wanno-drijfhout** [comment]
> If you can prepare a failing test that would be great.
Ok. Expect something later this week 👍. Thank you!

**Comment by wanno-drijfhout** [comment]
While writing the test case for your master branch, the problem seemed to disappear. I'm quite certain my problem (at version 11.45.1) is solved by #1844 (which is only introduced in version 12.1.2). That PR removed the "delayed postUpdate" notifications and (indeed) delaying those notifications would cause my problem as well.

I'm currently working out how to upgrade to version 12. There's a breaking change from 11.45.1. to 12.1.2 (i.e., #1833 removed `unregisterBean(..)`). We can close this issue for now; I can reopen it later if the problem persists in the most recent Ebean version.

**Comment by rbygrave** [comment]
Ok cool.
