### ISSUE TITLE
Ebean-enhancer for Gradle

### ISSUE THREAD

**Issue by khomich** [ebean-orm/ebean#195]
Hi there,

Just fyi, I was looking for a working gradle plugin to serve my project. Unfortunately I havn't found. So I created [my own](https://github.com/khomich/gradle-ebean-enhancer). It seems to be working pretty well with Java, Groovy and Scala. 

If you think it may be useful for Ebean community please give me recommendations how to finish my work or just do a fork.

**Comment by IvanAR** [comment]
up, we need this too

**Comment by rbygrave** [comment]
Released as https://github.com/ebean-orm-tools/ebean-gradle-plugin

**Comment by rbygrave** [comment]
PS: Thanks very much khomich for your efforts.  The ebean-gradle-plugin is largely based on your own plugin so thanks for that.

Cheers, Rob.
