### ISSUE TITLE
L2Cache, Inheritance and Lazy-Loading loads the parent Class not the Child

### ISSUE THREAD

**Issue by Marc2017** [ebean-orm/ebean#1973]
#1908  Expected behavior

When an inherited Bean (child) is (lazy)-loaded and the L2Cache is turned on, the behavior should be the same as when L2Cache is turned off - and the child-bean should be returned.

## Actual behavior

When an inherited Bean (child) is (lazy)-loaded and the L2Cache is turned on, the parent-bean is returned when the cache is hit.

See:
https://groups.google.com/forum/?nomobile=true#!topic/ebean/yuOfJVJqs1Q

### Steps to reproduce

I created a reproducable example:

https://github.com/Marc2017/example-minimal

(You can run CustomerMain.java (edit mysql connection in application.properties and execute sql script to create schema) or Run the "CustomerTest" (i think it uses h2).

The Model Classes respresents: "Customer has Address has Street" where Customer and Street have a Parent and all classes are subclassing BaseModel.

The critical thing is here:

---

//=========================================================================
// 2 - Read Data (no Cache)
//=========================================================================
reloadCustomer(server, customer, false);  //returns Street -> OK
reloadCustomer(server, customer, false);  //returns Street -> OK

//=========================================================================
// 3 - Read Data (L2-Cache ON)
//=========================================================================
reloadCustomer(server, customer, true); //returns Street -> OK
reloadCustomer(server, customer, true); //returns StreetParent -> NOT OK

---

which produces this output:

Class of Street (Cache on: false): class org.example.domain.Street | Cache Hit: 0
Class of Street (Cache on: false): class org.example.domain.Street | Cache Hit: 0
Class of Street (Cache on: true): class org.example.domain.Street | Cache Hit: 0
Class of Street (Cache on: true): class org.example.domain.parent.StreetParent | Cache Hit: 0

Tha last Line is the "Cache-Hit" and does not return "Street" but "StreetParent" - which is wrong.

(I´m not sure why "Cache Hit" is 0 in the last line, should be >0 - in my real world application this is counting)

**Comment by rbygrave** [comment]
The test passes?  
What needs to change such that the test fails?

---
Er, note that this doesn't run via maven ... hits a new bug with the ebean-maven-plugin.  I'm logging an issue and will look to release a 12.1.14 version that fixes that.

**Comment by Marc2017** [comment]
Hi Rob,

please get latest commit. 
I included the assertion-calls, now the test fails.

thanks, best regards
Marc

**Comment by rbygrave** [comment]
Effectively this bug was that for `@Inheritance` types that are references (Street/StreetParent) Ebean loses / did not keep the discriminator value in the L2 cache.  So coming out of the L2 cache the subtype was wrong.

The fix/change is for these types to keep the discriminator value + id value.  So now ebean can pull these out of L2 cache knowing the type (and also not having to hit the db to determine the type etc).
