### ISSUE TITLE
Loading properties from ebean.properties is deprecated. Please migrate to use application.yaml or application.properties instead.

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#1975]
With the latest update, I'm starting to get a warning about deprecated file:

```console
[warn] i.a.c.l.Loader - Loading properties from ebean.properties is deprecated. Please migrate to use application.yaml or application.properties instead.
```

I did add `application.properties` and seems is working, but still, I'm getting that warning.

I think the warning started from this change: https://github.com/ebean-orm/ebean/pull/1894

**Comment by rbygrave** [comment]
Did you remove ebean.properties ?  All the properties moved over to application.properties and ebean.properties was removed ?

**Comment by almothafar** [comment]
Yes, absolutely.

**Comment by rbygrave** [comment]
So maybe
- Go to Loader line 209 and 210 
- Put break points on both lines:
- Determine why loadProperties("ebean.properties", source) is returning true ?

```java
    if (loadProperties("ebean.properties", source)) {
      log.warn("Loading properties from ebean.properties is deprecated. Please migrate to use application.yaml or application.properties instead.");
    }
```

The inputstream for ebean.properties will be not null ...

**Comment by almothafar** [comment]
My bad always blame you first 😅😅: 

Here we go: 
![image](https://user-images.githubusercontent.com/13887564/77254175-24526680-6c68-11ea-8d3c-e78029bb1833.png)

**Comment by rbygrave** [comment]
No worries :)
