### ISSUE TITLE
ENH: Add support for Postgres GIS types such as Geometry

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#198]
As per https://groups.google.com/forum/#!topic/ebean/jzUAzECT4VY

e.g. Hibernate GeometryUserType

@Type(type = "org.hibernatespatial.GeometryUserType")
public Geometry the_geom;

**Comment by rbygrave** [comment]
Also notes from #239 which is considered a duplicate.

>>>

It would be nice that ebean supports geometric datatypes from Postgres. Those are listed on the following URL:
http://www.postgresql.org/docs/9.4/static/datatype-geometric.html

These are functions to be used with the previous datatypes.
http://www.postgresql.org/docs/9.0/static/functions-geometry.html

**Comment by antonini** [comment]
Actually Postgis is an extension that need to be activated. 
Geometric datatypes are native support from PostgreSQL since the  9.0 version.

**Comment by rbygrave** [comment]
Ok, so those are 2 different sets of datatypes then so should be treated as
a separate enhancement.

We can reopen the other issue then.

Thanks, Rob.

**Comment by pavei** [comment]
Hi,

I'm starting use Postgis with Play Framework. How can i do it?

Thanks

**Comment by rbygrave** [comment]
This is an enhancement request so ... you can't 'do it' until the feature
is supported.

If you want to help get the feature supported then you can produce examples
in java using jdbc on how the various GIS types are used (insert and
query).  I can probably take it from there to support the feature.

**Comment by pavei** [comment]
Is there any workaround?

I dont want use JPA

Att,
Vinicius Pavei

2015-12-02 20:52 GMT-02:00 Rob Bygrave <notifications@github.com>:

> This is an enhancement request so ... you can't 'do it' until the feature
> is supported.
>
> If you want to help get the feature supported then you can produce examples
> in java using jdbc on how the various GIS types are used (insert and
> query). I can probably take it from there to support the feature.
>

**Comment by rbygrave** [comment]
*> Is there any workaround?*

Well you can always using JDBC directly so yes that is a workaround.

**Comment by pavei** [comment]
How can i create a Scalar Type for a Postgis Point?

**Comment by pavei** [comment]
How can i create a custom type?

**Comment by rbygrave** [comment]
There are plenty of examples in the source. You could look at ScalarTypePostgresHstore, ScalarTypeURL ... what is a good example to base from depends on the type (is it immutable etc).

If you want to help get the feature supported then you can produce examples
in java using jdbc on how the various GIS types are used (insert and
query).  I can probably take it from there to support the feature.

**Comment by rbygrave** [comment]
FYI: The built in ScalarTypes are found in package com.avaje.ebeaninternal.server.type;

**Comment by rbygrave** [comment]
The initial support for this is in release 8.6.1

This does not yet include common where expressions such as "contains" but includes support for DDL handling and registering scalar types (and module ebean-postgis will have the scalar types required to support the postgis types and geolatte types for Point, Polygon, LineString, MultiPoint, MultiPloygon and MultiLineString).

**Comment by rbygrave** [comment]
Actually I'll close this (such that it goes against the version/milestone) and create new issues for where clause expression support etc.

**Comment by mutovkin** [comment]
@rbygrave Which ticket tracks the implementation of the "where" clause?

**Comment by mutovkin** [comment]
@rbygrave It actually does not look like there is any way to use the new Postgis support to actually serialize/de-serialize Geography Point records yet. Am I right?

**Comment by rbygrave** [comment]
> Which ticket tracks the implementation of the "where" clause?

There isn't one yet. That is on hold until after Multi-Tenant support is in (as we can use the raw() expressions well enough at the moment).

>  new Postgis support to actually serialize/de-serialize Geography Point records yet

As JSON?  No.  Otherwise, yes.  Refer:
https://github.com/ebean-orm/ebean-postgis
https://github.com/ebean-orm/wip-postgis-test
