### ISSUE TITLE
MariaDb - add support for @History using their native SQL instead of triggers

### ISSUE THREAD

**Issue by iadded45** [ebean-orm/ebean#2004]
MariaDb are now supporting Temporal tables based on sql2011 natively - will be great if ebean supports it.
In addition they support the application time and update/delete using the PERIOD FOR which no ORM supports - and its a great feature because it enables bi-temporal tables. If that can be supported as well - it will be a great addition.
https://mariadb.com/resources/blog/temporal-tables-part-1/

**Comment by iadded45** [comment]
After testing History using MariaDB - i see 2 things we should address 
1 - When adding versioning to a table - MariaDB will not allow that table to be modified (alter table - add/remove column) - unless a "system_versioning_alter_history" parameter is set to true. Do we have a way to set db parameters ?
2 - For MariaDB - the syntax for adding/removing versioning is simple :
ALTER TABLE t ADD SYSTEM VERSIONING;
ALTER TABLE t DROP SYSTEM VERSIONING;
Fetching the start & end dates can be done using 
SELECT *, ROW_START, ROW_END FROM t (row_start and row_end will not be visible in select * only queries)

It is possible to use the same syntax as used today for SQL Server :
ALTER TABLE t ADD COLUMN ts TIMESTAMP(6) GENERATED ALWAYS AS ROW START,
              ADD COLUMN te TIMESTAMP(6) GENERATED ALWAYS AS ROW END,
              ADD PERIOD FOR SYSTEM_TIME(ts, te),
              ADD SYSTEM VERSIONING;
which will create those synonym columns with the given names (and drop will be same as SQL Server - need to drop period + columns before droping versioning).
In this case the columns will be visible in select * queries.

I'm not sure which of the options is best.
The current solution - adding the synonym column names is more aligned with what's done for SQL Server - but on the other hand - ROW_START and ROW_END will exists on any versioned MariaDB table - even if not generated from ebean - so maybe its a more generic solution (i assume that for tables with a lot of history - users will need to add partitioning to the history - and each will define a different policy for that - so it makes sense it will be done using external db migration scripts).

Here is the MariaDB doc with all details 
https://mariadb.com/kb/en/temporal-data-tables/

**Comment by rbygrave** [comment]
> 2. .. ALTER TABLE t ADD SYSTEM VERSIONING; ALTER TABLE t DROP SYSTEM VERSIONING;

We should use this and that just means we have `row_start` and `row_end` (so the only issue there is if there is a name clash which I think is unlikely and avoidable in any case).

> 1. "system_versioning_alter_history" parameter is set to true

Not sure. It is not clear to me if that can be set programmatically. Do you have something/an example that shows that?

**Comment by rbygrave** [comment]
Also refer to https://github.com/ebean-orm/ebean-test/issues/38 - `ebean-test : Add useLegacyDatetimeCode=false to default JDBC URL`

**Comment by rbygrave** [comment]
Also refer https://mariadb.com/kb/en/mariadb-connector-j-130-release-notes/    `useLegacyDatetimeCode`

**Comment by iadded45** [comment]
Thank you Rob – I managed to work in UTC by setting it on the ebean server config

**Comment by iadded45** [comment]
Thanks for making the change on the DDL – I will test it today
Regarding the parameter – it can be set on a session – but I think it would be best to modify it in the database config.
For Ebean – maybe just writing this as a comment in documentation should be enough

**Comment by rbygrave** [comment]
Ok, we can say this ticket is part of 12.3.5 which I'll release. 

We have an outstanding question of how to deal with `system_versioning_alter_history` (add as a comment or document or generate into the DDL or all of those etc)
