### ISSUE TITLE
Dto instance id fields are not populated when queried using DtoQuery (and no select clause is specified)

### ISSUE THREAD

**Issue by skenny** [ebean-orm/ebean#2015]
## Expected behavior

When querying entities with @Id fields using DtoQuery the Dto class `id` field should be populated.

## Actual behavior

The DtoQuery generated SQL statement does not include the `id` column in the select clause, so the id field is not populated in the Dto instance.

### Steps to reproduce

```java
@Entity
@Table(name = "test_entities")
public class TestEntity {

	@Id private Long id;
	private String label;

	public Long getId() { return id; }
	public void setId(Long id) { this.id = id; }

	public String getLabel() { return label; }
	public void setLabel(String label) { this.label = label; }

}

public class TestDto {

	private Long id;
	private String label;

	public Long getId() { return id; }
	public void setId(Long id) { this.id = id; }

	public String getLabel() { return label; }
	public void setLabel(String label) { this.label = label; }

}

@Component
public class TestEntityDao {

	@Autowired protected Database database;

	public List<TestEntity> allEntities() {
		return database.find(TestEntity.class).findList();
	}

	public List<TestDto> allDtos() {
		return database.find(TestEntity.class).asDto(TestDto.class).findList();
	}

}
```

Querying using both methods:

```
List<TestEntity> testEntities = testEntityDao.allEntities();
List<TestDto> testDtos = testEntityDao.allDtos();
```

Results in the following collections:
![image](https://user-images.githubusercontent.com/320055/82678313-c6b6a800-9c1f-11ea-85ab-0f6ef0b7bdc6.png)

The generated SQL queries are as follows:

```console
2020-05-22 11:25:40,119 txn[] select t0.id, t0.label from test_entities t0; --bind()
2020-05-22 11:25:40,132 txn[] select t0.label from test_entities t0; --bind()
```

**Comment by rbygrave** [comment]
Note that it is particularly important to note that when we specify a select clause (which is the expected normal case) then we should and must explicitly include the `@Id` property or not.

This issue/confusion only occurs when no select clause is specified (the select all properties case) which is not really expected per say (we could just use the entity bean in that case for example).
