### ISSUE TITLE
Q: Adding 2 unique keys in case there is one column is nullable? (handling sql server specific limitation)

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2030]
I have case that I have 3 columns and there is 1 

### Steps to reproduce

```java

@Entity
@Table(name = "Topic", schema = "alerts", uniqueConstraints = {@UniqueConstraint(columnNames = {"Type", "TopicKey", "Criteria"})})
public class Topic extends Model {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id")
    private Integer id;

    @Constraints.Required
    @Formats.NonEmpty
    @Column(name = "Type", length = 15, nullable = false, updatable = false)
    private AlertType type;

    @Column(name = "TopicKey", nullable = false, updatable = false)
    @Index
    private String key;

    @Column(name = "Criteria", updatable = false)
    private String criteria;

}
```

Creates:
```
create unique nonclustered index [uq_Topic_Type_Topic_Criteria] on [alerts].[Topic]([Type],[TopicKey],[Criteria]) where [Criteria] is not null;
```
Which is correct, but I need `Type` and `TopicKey` to be unique if `Criteria` is null, I tried to do 
```java
@Table(name = "Topic", schema = "alerts", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"Type", "TopicKey", "Criteria"}),
        @UniqueConstraint(columnNames = {"Type", "TopicKey"})
})
```

That created:

```sql
create unique nonclustered index [uq_Topic_Type_Topic_Criteria] on [alerts].[Topic]([Type],[TopicKey],[Criteria]) where [Criteria] is not null;
alter table [alerts].[Topic] add constraint [uq_Topic_Type_Topic] unique  ([Type],[TopicKey]);
```

You can see the second index does not create a condition if "Criteria" is null.

So I did that manually, 

```sql
create unique index uq_topic_type_topic  on alerts.Topic (Type, TopicKey) where [Criteria] IS NULL
```

but maybe it is nice to have it by default or if I do second unique with the same columns excluding one it should be reversed?

For sure I'm using the latest ebean, and SQL Server 2017/2019

**Comment by rbygrave** [comment]
> but maybe it is nice to have it by default 

I'll say no. SQL Server has some limitations and sometimes it is good for Ebean to hide those limitations and sometimes not. I think this is a SQL Server limitation that Ebean should **_not_** hide.

When people see this limitation then that could prompt then to change their design (e.g. make Criteria not nullable - for example).  This is a unique index so is very important on medium to large tables and just creating extra indexes is not something we want Ebean to do.  

With Ebean we can use `@Index` to add database platform specific indexes including functional indexes etc. My expectation is that with Ebean we can use this to handle ANY database specific index needs and that would include dealing with SQL Server limitations like this one.

Reference:
https://ebean.io/docs/mapping/extensions/dbindex

Does that make sense?

**Comment by almothafar** [comment]
@rbygrave It does make sense, I opened the ticket pretty sure it is not doable, But just hope for an idea that I didn't have yet, actually I was thinking about making `Criteria` is not nullable, but it will need some work to do from my end in the backend too.

So I decided to create a new index for now, but what I was thinking about if I have second unique that already defined in the first one excluding the nullable column.

I do understand there is a limitation, but just try my luck if you have better idea than what I have.

Thanks.

**Comment by rbygrave** [comment]
Yeah cool. For myself I'd probably look to try and get Criteria to be non nullable. Having to have 2 unique indexes just to deal with this sql server specific issue has a cost factor and would niggle me design wise. 

I'll close this then.

**Comment by rbygrave** [comment]
> not doable

Remembering that just because something **_can_** be done doesn't mean it **_should_** be done :)
