### ISSUE TITLE
Using @AttributeOverrides breaking generated SQL (when override nullable and no column name)

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2044]
It seems overriding `@Embedded` with `@AttributeOverrides` not working at all for SQL generation, I'm not sure if I have to move this ticket to ebean-migration or it is OK to open it here, but I have this issue when I have evolution script generated for my play project

## Expected behavior
Generated script should be something like:

```sql
create table [dbo].[LocationSchedulePreference] (
  [Id]                          integer identity(1,1) not null,
  [LocID]                       integer null,
  [LabCode]                     nvarchar(50) null,
....
);
```

## Actual behavior
Currently, it is generating invalid wrong SQL

```sql
create table [dbo].[LocationSchedulePreference] (
  [Id]                          integer identity(1,1) not null,
                                nvarchar(50) not null,
....
);
```

### Steps to reproduce

This is my `@Embeddable` class

```java
@Embeddable
public class SampleLocationId implements Serializable {
    @Column(name = "LocID", nullable = false)
    private Integer locationId;

    @Column(name = "LabCode", nullable = false, length = 50)
    private String labCode;
}
```

Then added `@Embeddable` as property to any bean:
```java
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "labCode", column = @Column(nullable = true)),
            @AttributeOverride(name = "locationId", column = @Column(nullable = true))
    })
    private SampleLocationId location;

```

Without  `@AttributeOverrides` it is working fine but it is not null, but I want it nullable in this case.

**Comment by almothafar** [comment]
Oh wait it is even more critical: 

In query itself like 

```java
DB.find(LocationSchedulePreferenceData.class).findList()
```

I get the query with column names missing:

```console
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Incorrect syntax near ','. Bind values:[Array[2]={1030-4,1030-7}] Query was:select t0.[Id], t0.[LCProjectID], t0.[Deleted], t0., t0., t0.[SLID] from [dbo].[LocationSchedulePreference] t0 where t0.[LCProjectID] in (?,?) and t0.[Deleted] = 0
```

You can see `t0., t0.,`

**Comment by rbygrave** [comment]
I suspect the issue here is that Ebean is currently expecting 
- `@AttributeOverrides` to override column names (and not handling the case where it is not)  
- Not expecting `@AttributeOverrides` to override nullable the attribute

**Comment by almothafar** [comment]
The issue even happens if I want to override anything not only nullable, so the existence of that annotation with whatever you want to override `length` as for example, and effecting query generating not only migration script.

**Comment by rbygrave** [comment]
>  whatever you want to override length as for example

Yes, fixing that as well.

> and effecting query generating not only migration script.

It is effectively the same issue/bug. That is fixed by this change such that the db column is not overridden to empty string.

**Comment by almothafar** [comment]
@rbygrave I just tried the new version, the column names are there (so this part of issue fixed), but overrides do not apply.


```java
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "labCode", column = @Column(nullable = true)),
            @AttributeOverride(name = "locationId", column = @Column(nullable = true))
    })
    private SampleLocationId location;
```

```java
@Embeddable
public class SampleLocationId implements Serializable {
    @Column(name = "LocID", nullable = false)
    private Integer locationId;

    @Column(name = "LabCode", nullable = false, length = 50)
    private String labCode;
}
```

Script generated:

```sql
create table [dbo].[LocationSchedulePreference] (
  [Id]                          integer identity(1,1) not null,
  [LocID]                       integer not null,
  [LabCode]                     nvarchar(50) not null,
....
);
```

**Comment by rbygrave** [comment]
That is because ... `@Column(nullable = true)` ... for `@Column` is defaults to nullable true. That means it is impossible to detect it is defaulting or was set explicitly.

`@Column(nullable = true)` and `@Column()` ... are the same.  

For overrides we can't effectively detect that a column is explicitly desired to be `nullable = true` via `@Column`.

**Comment by rbygrave** [comment]
We might instead need an extension to the standard annotation.  Something like:
```java
@AttributeOverride(name = "locationId", nullable = true)
```
Where there is a `nullable` attribute on `@AttributeOverride` and true means "override this column to be nullable".  That might be confusing.

**Comment by almothafar** [comment]
Yeah that's clear I have many fields with default, It is not only about nullable, but I also have other fields like `updateable` or maybe fields like `length=255`, extend standard annotation works I think! but maybe with something like 

```java
@AttributeOverride(name = "locationId", forceColumn = @Column( nullable=true))
```

```java
@AttributeForceOverride(name = "locationId", column = @Column( nullable=true))
```

So in this way, we take whatever the value is, yet we have still default value issue of `@Column`, if you want to use your own `@AttributeOverride` version it might help for avoid conflicts with default values.

There some of my ideas.

**Comment by jnehlmeier** [comment]
> That is because with the `@Column(nullable = true)` overrides does not detect it has been explicitly set because for `@Column`
> nullable attribute defaults to true. That means it is impossible to detect if it is defaulting or was set explicitly - we can't tell by reading the annotation value.
> 
> So `@Column(nullable = true)` and `@Column()` ... are effectively the same.
> 
> For overrides we can't effectively detect that a column is explicitly desired to be `nullable = true` via `@Column`.
> 
> Note that we can and do detect the opposite, a nullable=true has override to nullable=false.

Why would you need to detect anything? Isn't it that the specified column annotation is a replacement for the original?

So something like
```java 
@AttributeOverrides({
  @AttributeOverride(name = "labCode", column = @Column()),
  @AttributeOverride(name = "locationId", column = @Column())
})
```
basically means "use default behavior for labCode and locationId fields".

So in the given example above the correct way would be
```java
@AttributeOverrides({
  @AttributeOverride(name = "labCode", column = @Column(name = "LocID")), 
  @AttributeOverride(name = "locationId", column = @Column(name = "LabCode", nullable = true, length = 50)) 
})
```
The column name should not switch to default behavior so it needs to be repeated, nullable is now changed to the default value of true (either implicit or explicit), and length of 50 must be repeated since the default would be 255 and that's undesired.

I can't see anything in the JPA spec that requires making a diff between the original `@Column` definition and the definition provided through `@AttributeOverride`.

**Comment by jnehlmeier** [comment]
> I can't see anything in the JPA spec that requires making a diff between the original `@Column` definition and the definition provided through `@AttributeOverride`.

The JavaDoc of `@AttributeOverride.column` says

_(Required) The column that is being mapped to the persistent attribute. The mapping type will remain the same as is defined in the embeddable class or mapped superclass._

Personally I understand it as "this column should be used to map the attribute". It does not mean you can override single attributes of the column annotation itself with some semi-intelligent diff'ing going on.

**Comment by rbygrave** [comment]
> some semi-intelligent diff'ing going on.

That is what Ebean is doing. 


>  It does not mean you can override single attributes of the column annotation itself with some semi-intelligent diff'ing going on.

Hmmm, yeah I can see that interpretation now - darn.

So, I've probably interpreted this wrong. I _think_ this in effect only applies to the `nullable` attribute (wrong interpretation). I don't think there is an issue with the other attributes like name, length, precision etc. 

Q: Can we change it? 
I think so yes.

**Comment by rbygrave** [comment]
Ok, changed such that nullable always taken from the override `@Column`
