### ISSUE TITLE
About @JoinColumn(unique = true) or @Column(unique = true) column with @SoftDelete 

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2045]
I got records in a table like this:

![image](https://user-images.githubusercontent.com/13887564/90021347-caefe000-dcb9-11ea-92d7-3e8d22e79afc.png)

As you can see I got a column for soft delete, but I want to create a unique key for `SLID`, the generated script is adding a normal unique key in the table like this:

```sql
create table [dbo].[Table1] (
  [Id]                          integer identity(1,1) not null,
  [SLID]                        integer,
....
  [RecordModifiedDate]          datetimeoffset not null,
  [Version]                     integer default 1 not null,
  [Deleted]                     integer default 0 not null,
);
....
create unique nonclustered index [uq_Table1_SLID] on [dbo].[Table1]([SLID]) where [SLID] is not null;
.... 
alter table [dbo].[Table1] add constraint [fk_Table1_SLID] foreign key ([SLID]) references [dbo].[Table2] ([SLID]) on delete set null on update set null;
```

Which is totally fine "for now", the problem is when I delete the record and add a new record later for the same `SLID` it will start to make an exception about the unique key on the database, I'm not that expert as you :) but I believe maybe if there is `@SoftDelete` there should be a condition added here like:

```sql
create unique nonclustered index [uq_Table1_SLID] on [dbo].[Table1]([SLID]) where [SLID] is not null and [Deleted] = 0;
```

## Expected behavior

If the column is nullable:
```sql
create unique nonclustered index [uq_Table1_SLID] on [dbo].[Table1]([SLID]) where [SLID] is not null and [Deleted] = 0;
```

if not nullable

```sql
create unique nonclustered index [uq_Table1_SLID] on [dbo].[Table1]([SLID]) where [Deleted] = 0;
```

## Actual behavior
If the column is nullable:
```sql
create unique nonclustered index [uq_Table1_SLID] on [dbo].[Table1]([SLID]) where [SLID] is not null;
```
if column is not null
```sql
create table [dbo].[Table1] (
  [Id]                          integer identity(1,1) not null,
  [SLID]                      integer not null,
....
  [Deleted]                     integer default 0 not null,
  constraint [uq_LocationSchedulePreference_SLID] unique ([SLID]),
);
```

**Comment by rbygrave** [comment]
> but I believe maybe if there is @SoftDelete there should be a condition added here like:

Hmmm. I believe this can really go both ways meaning that there will be cases where the unique constraint is intended to not include the softDelete column and other cases (like this one) where the intention is to include the softDelete column.

I believe you have a good workaround in that you could use `@Index` and do it all explicitly that way.

I am not sure that we should change the treatment of this such that unique always includes the softDelete column.  Even though that would be valid for some cases it won't be valid for all. I think this is why we should keep the existing behaviour.

Thoughts or comments?

**Comment by almothafar** [comment]
@rbygrave I was thinking in the same way you mentioned, so it is not really a problem but I think it might be something that can be solved in a different way, sorry if that sound dump, but maybe we can do include by default unless there is a specific value for `@SoftDelete(something=true)` annotation? where something is a correct wording for what can be done?

Sorry for my language is not helping me much today!

**Comment by rbygrave** [comment]
> my language is not helping me much today

No that's all good - I understand what you are saying. We can leave this open and think about it for a little bit.  See if anyone else has some thoughts on it as well.

Cheers, Rob.

**Comment by rbygrave** [comment]
I think we can close this at this stage.  I'm happy enough with the current approach and workaround.
