### ISSUE TITLE
@UniqueConstraint:  Array constants have to be specified using the `Array(...)' factory method

### ISSUE THREAD

**Issue by cyrilfr** [ebean-orm/ebean#2046]
I'm using the `@UniqueConstraint` annotation on a User model:

```
@Table(
    name = "users",
    uniqueConstraints = @UniqueConstraint(
        columnNames = { "building_id", "pin" }
    )
)
```
This model is part of a Play Framework 2.7 project with Java 13.
When I want to build the project, I get an error:
```
[error] /app/models/common/User.java:25:27: Array constants have to be specified using the `Array(...)' factory method
[error]     uniqueConstraints = @UniqueConstraint(
[error]                           ^
```
According to [this page](https://www.objectdb.com/api/java/jpa/UniqueConstraint), it should be correct.

**Comment by cyrilfr** [comment]
I just had to write:
```
@Table(
    name = "users",
    uniqueConstraints = {
            @UniqueConstraint(
                    columnNames = { "building_id", "pin" }
            )
    }
)
```
This is nowhere in the doc...

**Comment by rbygrave** [comment]
ok cool.  Note that `@UniqueConstraint` can also target the class like:

```java
@Entity
@Table(name = "users")
@UniqueConstraint(   columnNames = { "building_id", "pin" } )
public class Users {
 ...
}
```

I'll close this then.  Happy to take documentation PR's for people keen to improve the documentation.

Thanks, Rob.
