### ISSUE TITLE
.findVersionsBetween() for PG and MySql... should use inclusive/exclusive  and it is instead is exclusive/exclusive

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#2058]
When using Ebean 12.3.9, Postgresql 10.7 and `@History` annotations:

```java
@Embeddable
public class Key {
  public String partner;
  public UUID identifier;
}

@History
@Entity
public class Obj extends Model{
  @EmbeddableId
  public Key key;

  public String data;
}

Table specification:
```sql
CREATE TABLE obj (
  partner varchar,
  identifier uuid,
  sys_period tstzrange,
  constraint pk_obj primary key (partner, identifier)
);
```

We generate queries similar to below when using .findVersionsBetween():  
```sql
select lower(t0.sys_period), upper(t0.sys_period), t0.partner, t0.identifier, t0.data
from obj_with_history t0 
where t0.partner = ? and t0.identifier = ? 
and lower(t0.sys_period) > ? and lower(t0.sys_period) < ? 
order by lower(t0.sys_period) desc;
--bind(phoenix,926fdd76-dd84-42ad-8bb9-0c61a889013e,2020-09-14 14:47:22.883,2020-09-16 14:47:22.883)
```

However, we will typically not find the current value of the row with that SQL query, as we are not being properly range constrained.  The correct query would be this for Postgresql when using the tztsrange column support:

```sql
select lower(t0.sys_period), upper(t0.sys_period), t0.partner, t0.identifier, t0.data
from obj_with_history t0 
where t0.partner = ? and t0.identifier = ? 
and t0.sys_period && tstzrange(?, ?)
order by lower(t0.sys_period) desc;

--bind(phoenix,926fdd76-dd84-42ad-8bb9-0c61a889013e,2020-09-14 14:47:22.883,2020-09-16 14:47:22.883)
```

The work around we are using currently is to apply the range logic directly and use .findVersions() instead:

```java
query.where.raw("t0.sys_period && tstzrange(?, ?)", startTimestamp, endTimestamp);
query.findVersions().forEach(ve -> { ... });
```

At minimum, the documentation for .findVersionsBetween() should indicate which type of temporal querying is actually used on the underlying DbPlatform (inclusive start and end, inclusive start/exclusive end, contained by start/end, etc)

Ideally, I would think with the name .findVersionsBetween() and looking at the common DB platforms, the expectation is inclusive start/exclusive end, which appears to be the most commonly supported implementation for SQL2011 temporal tables.

**Comment by rbygrave** [comment]
> Ideally, ... .findVersionsBetween() ... expectation is inclusive start/exclusive end, which appears to be the most commonly supported implementation for SQL2011 temporal tables.

Yes I agree.  

> lower(t0.sys_period) > ? and lower(t0.sys_period) < ? 

Currently it is exclusive/exclusive here ... and yes I'd say that is a bug.  Looking at the code history it was added with #384 and always been exclusive/exclusive - darn !!!

**Comment by hindmanj** [comment]
The existing logic is wrong for a range overlaps comparison anyway. Not only is it exclusive/exclusive, it is ignoring the upper bound on sys_period.  The correct logic would be something more like this:

```sql
lower(t0.sys_period) < endTimestamp
AND (upper(t0.sys_period) IS NULL OR upper(t0.sys_period) >= startTimeStamp)
```

**Comment by rbygrave** [comment]
Thanks @hindmanj for Postgres with this fix we have:

```sql
and lower(t0.sys_period) < ?    -- endTimestamp
and (upper(t0.sys_period) >= ? or upper(t0.sys_period) is null)   -- startTimeStamp
```
and this lines up with MS Sql Servers documentation so I think we are good with this fix.
