### ISSUE TITLE
Optimization: Double joins in generated SQL query on the same table is not necessary 

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2087]
I'm not sure if this is a problem or not, but I feel double join in not necessary in this case, as first, it does` left join`, and then `join` on the same table for where clause:

Also, side question, do we need `order by`?

## Expected behavior

SQL generated
```sql
select distinct t0.[ULID],
                t0.[LocationName],
                t0.[Latitude],
                t0.[Longitude],
                t1.[ProjectID],
                t1.[Latitude],
                t1.[Longitude],
                t1.[ULID]
from [dbo].[LocationsUnique] t0
         left join [dbo].[SubLocations] t1 on t1.[ULID] = t0.[ULID]
where t1.[ProjectID] in (?,?)
order by t0.[ULID]; --bind(Array[2]={project-a,project-b})
```

## Actual behavior

SQL generated (formatted)
```sql
select distinct t0.[ULID],
                t0.[LocationName],
                t0.[Latitude],
                t0.[Longitude],
                t1.[ProjectID],
                t1.[Latitude],
                t1.[Longitude],
                t1.[ULID]
from [dbo].[LocationsUnique] t0
         left join [dbo].[SubLocations] t1 on t1.[ULID] = t0.[ULID]
         join [dbo].[SubLocations] u1 on u1.[ULID] = t0.[ULID]
where u1.[ProjectID] in (?,?)
order by t0.[ULID]; --bind(Array[2]={project-a,project-b})
```

### Steps to reproduce

Ebean:
```java
DB.find(UniqueLocationData.class)
                .setDisableLazyLoading(true)
                .fetch("locations")
                .where()
                .in("locations.projectId", List.of(projectIds))
                .findList()
```

Entities:

```java
@Entity
@Table(name = "LocationsUnique", schema = "dbo")
public class UniqueLocationData extends Model {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ULID")
    private Integer id;

    @Column(name = "LocationName", length = 80)
    private String locationName;

    @Column(name = "Latitude", length = 20)
    private String latitude;

    @Column(name = "Longitude", length = 20)
    private String longitude;

    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH}, mappedBy = "uniqueLocation", fetch = FetchType.EAGER)
    private List<SubLocationData> locations;
}

@Entity
@Table(name = "SubLocations", schema = "dbo")
public class SubLocationData extends Model {

    @Column(name = "ProjectID", length = 20, updatable = false, nullable = false)
    private String projectId;

    @Column(name = "Latitude", length = 20)
    private String latitude;

    @Column(name = "Longitude", length = 20)
    private String longitude;

    @ManyToOne(optional = true, cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @DbForeignKey(onDelete = ConstraintMode.SET_NULL)
    @JoinColumn(name = "ULID")
    private UniqueLocationData uniqueLocation;
}
```

**Comment by rbygrave** [comment]
> I'm not sure if this is a problem or not, but I feel double join in not necessary in this case, as first, it does left join, and then join on the same table for where clause:

It is not a problem and it is expected to have both joins in cases like this where we have a predicate and fetch on a "ToMany path".

The ToMany path in this case is `locations` - it is a OneToMany directly off the root.
The predicate is `.in("locations.projectId", List.of(projectIds))`
The fetch is `.fetch("locations")`

The design here is that predicates apply to the _root_ (in this case predicates restrict the UniqueLocationData rows/beans returned) and that fetch executes _independently_ of that (that there is no behaviour difference if the fetch was there or not - no difference if we use lazy loading or fetch wrt the graph that is loaded).

In the case of "ToMany" paths if we just used a single join then we are applying the predicate/filter on both the root (UniqueLocationData) and the collection (locations) and that would be a different result when compared to if the fetch was not there at all and the locations were lazy loaded.

That is, we can use _fetch_ or not (lazy loading) and we don't get a difference in the result wrt the graph loaded.

This is why to restrict/filter/apply a predicate on a ToMany path like locations we use filterMany https://ebean.io/docs/query/filterMany

Whenever we see a `u` table alias we know that that join is for a predicate on a ToMany path and is only used to restrict the rows returned on the root.

Whenever we see a `t` table alias we know that join can be used by both predicates and fetch (all ToOne paths we see only the `t` table alias used).

Does that make some sense?

**Comment by almothafar** [comment]
Thanks for your time and explanation, I appreciate that really.
