### ISSUE TITLE
Q: how to close read-only transaction when use repository.findById()?

### ISSUE THREAD

**Issue by HelloWorldHelloPKU** [ebean-orm/ebean#2096]
I just want to change the default performance that read-only transaction will be automatically added to repository.findById() method。when use spring-data-jpa,i can change this by @EnableJpaRepositories(enableDefaultTransactions = false).
How can i do this with ebean?

**Comment by rbygrave** [comment]
Setup Ebean with a read-only datasource ... and then it will automatically use that read-only datasource for any query that executes  without an existing current transaction.

If you are using Ebean's DataSource (preferred) then we just need to do:
```
ebean.autoReadOnlyDataSource=true
```

programmatically:

```
databaseConfig.setAutoReadOnlyDataSource(true);

// or

databaseConfig.setReadOnlyDataSource(DataSource)

// or 
databaseConfig.setReadOnlyDataSourceConfig(DataSourceConfig)
```


```java
  /**
   * Set the read only DataSource.
   * <p>
   * Note that the DataSource is expected to use AutoCommit true mode avoiding the need
   * for explicit commit (or rollback).
   * <p>
   * This read only DataSource will be used for implicit query only transactions. It is not
   * used if the transaction is created explicitly or if the query is an update or delete query.
   */
  public void setReadOnlyDataSource(DataSource readOnlyDataSource) 
```

**Comment by rbygrave** [comment]
If you are using Ebean's DataSourceConfig then it comes with a **_readOnlyUrl_** property.  So typically we use this is where the only difference between the main DataSource and the read-only DataSource is the url.

**Comment by HelloWorldHelloPKU** [comment]
Even if I use a read-only datasource, read-only queries  are just being forwarded to it. Implicit query only transactions are still createad. Can the transaction be cancelled completely?

**Comment by rbygrave** [comment]
It uses autoCommit transactions.  That means there is no need for extra explicit commit() ... can save around 15%.

**Comment by rbygrave** [comment]
Pool is autoCommit=true, readOnly=true

**Comment by rbygrave** [comment]
I'll close this then.
