### ISSUE TITLE
[12.5.2] NullPointerException when I try to commit transaction

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2109]
I'm just posting this here as I'm still debugging the issue, but with the new version 12.5.2 I start to have NullPointerException when I do commit, with previous versions AFAIK was no problem at all.

### Steps to reproduce

```java
        final Database defaultDB = getDefaultDatabase();
        final Transaction txn= defaultDB.beginTransaction();
        try {
            txn.setBatchSize(2000);
            txn.setBatchMode(true);
            txn.setGetGeneratedKeys(false);
            txn.setPersistCascade(false);
            defaultDB.insertAll(beans, txn);
            txn.commit(); // <-- here is null pointer fires
        } catch (Exception ex) {
            txn.rollback();
            logger.error(ex.getMessage(), ex);
        } finally {
            txn.end();
        }
```

```console

[error] - [                    ] i.e.s.t.JdbcTransaction - Error closing connection,
java.lang.NullPointerException: null,
	at io.ebeaninternal.server.transaction.JdbcTransaction.deactivate(JdbcTransaction.java:900),
	at io.ebeaninternal.server.transaction.JdbcTransaction.commit(JdbcTransaction.java:1040),
	at io.ebeaninternal.api.ScopeTrans.commitTransaction(ScopeTrans.java:136),
	at services.basic.EbeanBaseRepository.lambda$insertAll$3(EbeanBaseRepository.java:56),
	at io.ebeaninternal.api.ScopedTransaction.commit(ScopedTransaction.java:110),
	at services.basic.EbeanBaseRepository.insertAllBeans(EbeanBaseRepository.java:142),
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source),
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48),
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
```

It is happening a lot, I'm now deploying the previous version to see if that issue comes again or it is only with 12.5.2!

**Comment by rbygrave** [comment]
What doesn't look right with the code above is that I don't see `Transaction txn = database.beginTransaction()` there?

Where does the transaction begin?  Perhaps update the code above if it is missing.

Looking at JdbcTransaction.java:900 and JdbcTransaction.java:1040 ... I'm wondering if there is a prior exception occurring.  Is there a exception occurring just before this NPE ?

Thanks, Rob.

**Comment by almothafar** [comment]
Oh sorry deleted it by mistake, updated the code, and I can confirm it is still happening with version 12.5.1.

There are no other exceptions that happened before, nothing just these lines, and regarding the database, it is SQL Server, and the driver is https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/8.4.1.jre11

**Comment by almothafar** [comment]
![image](https://user-images.githubusercontent.com/13887564/99722917-13d5e280-2aba-11eb-8d25-4d4db2b4a442.png)

I got a super stable hand as you see lol
 Line 142:

![image](https://user-images.githubusercontent.com/13887564/99723039-4aabf880-2aba-11eb-8544-7cfdeae43b1f.png)

**Comment by rbygrave** [comment]
```
	at services.basic.EbeanBaseRepository.insertAllBeans(EbeanBaseRepository.java:142),
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source),
```
I think we should change this to use `createTransaction()` rather than `beginTransaction()` ... such that the transaction doesn't go into ThreadLocal scope [given the use of akka here].

**Comment by rbygrave** [comment]
As a style note, generally we can move to use a "try with resources" for the transaction (and remove the finally block with `txn.end()`) ... but I wouldn't suggest making that style change until we confirm using 'createTransaction()` solves the issue.

**Comment by almothafar** [comment]
@rbygrave I'm not really sure if I need to detach that from LocalThread, I mean what is it make any difference? and how you handle ending the transaction? I was not doing that and I faced a few issues about transactions not ended and the table stayed locked, so that's why I did try/catch and `txn.end()` and that's what solved my problem, and tbh I didn't see that issue in MySQL and PG, but MSSQL is just a headache for me.

The problem now, that issue didn't happen in development, and not happening in the testing/staging servers which are mocking production, but happens in the production server only :/ 

What I'm doing that is just test solutions on the production like A LEGEND 😆

**Comment by rbygrave** [comment]
JdbcTransaction:900 - `connection.close();` ... so the NPE says that the connection is null.  There is only 1 place the connection is set to null - line 906.  `deactivate()`

That is, the steps to reproduce will not reproduce this issue - there is something else in play which is effecting the execution in prod which is why the "test in prod" is going on.  Using `beginTransaction()` means that the transaction is accessible via ThreadLocal and that isn't necessary and should be changed to completely remove that chance.

**Comment by almothafar** [comment]
@rbygrave with `createTransaction()` the issue still there:

![image](https://user-images.githubusercontent.com/13887564/100336703-2a5ecb00-2fdf-11eb-8b58-3b42dc162afa.png)

I noticed that it is random too, it is not happening always, just a few times, yesterday happened like 10 times in my log file, in less than 24 hours, also I noticed another version of the same issue where I see more details:

![image](https://user-images.githubusercontent.com/13887564/100337205-c2f54b00-2fdf-11eb-9056-d066c1fa66bf.png)

Note I'm using 12.6.1 as well 😬

**Comment by rbygrave** [comment]
Note that as I see it, it is good for the actual stack trace as text to be
in the github issue as that makes it searchable for future users (vs image
which isn't so searchable)

**Comment by almothafar** [comment]
@rbygrave I agree, I usually do that but as I posted the stack in the ticket I didn't make efforts to do that later as the console box that I'm using a little annoying with getting strings out of it.

I'll try to post the stack trace next time, as currently, console cleared.

**Comment by almothafar** [comment]
I'll close it for now, as I believe it is not related to Ebean, something sounds odd with DB connection, also I found a part of the code responsible for "Transaction is Inactive"...
