### ISSUE TITLE
Q: Does ebean support orm.xml for entity mappings?

### ISSUE THREAD

**Issue by crgardner** [ebean-orm/ebean#2111]
Does ebean support mappings other than @Entity annotations? 

This link

https://www.playframework.com/documentation/2.7.1/JavaEbean

seems to indicate that at one time, orm.xml was supported.

"Note that Ebean will also make use of a conf/orm.xml file (if present), to configure <entity-mappings>."

If this is still supported, how do you get it to work? I created an orm.xml and placed it several areas under resources in my project, but cannot get ebean to find it.

**Comment by crgardner** [comment]
Sorry, the full quote was 

"Note that Ebean will also make use of a conf/orm.xml file (if present), to configure entity-mappings.

**Comment by rbygrave** [comment]
No, Ebean does not read orm.xml file.

Ebean can read named queries from a ebean.xml but that is for named queries
only and not mapping.

With Ebean mapping must be done via annotations on the entity beans.

Cheers, Rob.

**Comment by rbygrave** [comment]
I'll close this question.
