### ISSUE TITLE
Adding a new list of children to @OneToMany with orphanRemoval true does not delete existing orphans

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2127]
I'm not sure if you consider this as an issue or not, but for me, it is a little annoying, I have a parent bean which has a list of children with `@OneToMany` relation, so when I update the list of children with totally new a new list, old children stay there, so let say I have "Company" and list of "Employees"

```java
@Entity
@Table(name = "Company", schema = "dbo")
public class Company extends Model {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id")
    private Integer id;

    @Column(name = "Name")
    private Integer name;

    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH}, mappedBy = "request", orphanRemoval = true)
    private List<User> employees;
}
```

```java
@Entity
@Table(name = "User", schema = "dbo")
public class User extends Model {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id")
    private Integer id;

    @Column(name = "Name")
    private Integer name;

    @ManyToOne(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @JoinColumn(name = "CompanyId")
    @DbForeignKey(onDelete = ConstraintMode.CASCADE)
    private Company company;
}
```

so when first when I do:

```java
User employee1 = new User().setName("Employee 1");
User employee2 = new User().setName("Employee 2");
List<User> employees = new ArrayList<>();
employees.add(employee1);
employees.add(employee2);

Company company = new Company().setName("My Company").setEmployees(employees);
company.insert();
```

I get everything in the table correct, users inserted with company id and everything, but not if I get that company back, and add "a new list", old employees stay in that table:

```java
User employee1 = new User().setName("Employee 1");
User employee3 = new User().setName("Employee 3");
List<User> employees = new ArrayList<>();
employees.add(employee1);
employees.add(employee3);

Company company = DB.find(Company .class).eq("name", "My Company").findOne();
company.setEmployees(employees);
company.update();

```
I get in the database
```
1        Employee 1
2        Employee 2
3        Employee 1
4        Employee 3
```

## Expected behavior
To have 2 employees:
```
3        Employee 1
4        Employee 3
```

## Actual behavior
Users just stack up:
```
1        Employee 1
2        Employee 2
3        Employee 1
4        Employee 3
```
This is could be true behavior if I merge list not just define totally a new list like:

```java
Company company = DB.find(Company .class).eq("name", "My Company").findOne();
company.getEmployees().addAll(employees);
company.update();
```
But this is not the case here, especially that I thought `orphanRemoval = true` will solve the problem, but it is not.

Sorry if that sound like a silly question for a newbie, but this is how I was doing it in the very old days (version 11.x), it is something similar to what I wanted to describe here https://github.com/ebean-orm/ebean/issues/1977 

Now to work around this, I have to get all employees, delete them and add a new one, if adding new employees failed then I lose the old and new one.

I'm not sure if I'm doing it wrong already?

**Comment by rbygrave** [comment]
> I'm not sure if I'm doing it wrong already?

Well, IF the desire is to truely replace all the children each and every update then ... yes this is looks like a bug.

Noting the reason this hasn't been identified as a bug before is probably because deleting and inserting all the "children" produces a lot of database churn and generally people are looking to either "merge children" or "append children".

Also noting that Ebean has "merge" feature built in via `database.merge(bean)` and `database.merge(bean, MergeOptions)` ... which takes the work out of the "merge children" case (handles the identification of children to insert, update, delete etc, allows for declaring how deep in the graph the merge goes).  

> what I wanted to describe here #1977

Ok. My thought is that UserRole is mapping to a bridge/intersection table and that then maybe explains the desire to "delete all" "insert all" rather than "merge" - ok, hmmm.

**Comment by rbygrave** [comment]
So at this point I think this is a bug. 

The description of the bug is all good but just for future readers and to aid understanding ... "Employee" as the child type is possibly not a great example per say to aid understanding.  Perhaps a better example of a child type where this is an expected use case is where the child type maps to a intersection/bridge table (explicit mapping of a many to many).  In these cases we are much more expecting to perform a delete/insert rather than update.

**Comment by almothafar** [comment]
> IF the desire is to truely replace all the children each and every update then
Yes, that's what I'm trying to do.

> My thought is that UserRole is mapping to a bridge/intersection table and that then maybe explains the desire to "delete all" "insert all" rather than "merge" 

As I said that what I was doing before, in issue #1977 I was merging manually by looking into the existing relationship and maintaining it if that relationship is no more exist I remove it from the list, and create a new relationship and then let ebean do the job (what I expected is: beans with Id to keep, beans missing should be deleted, beans without Id should be added), but with versions after 11.45.x I start to query the database, delete manually what I don't want to stay, and add manually what I want to add.

I got some codes just to work around this issue like:

```java
// Start transaction
Ebean.deleteAll(childrenToDelete, txn);
Ebean.insertAll(childrenToInsert, txn);
Sometimes Ebean.updateAll(childrenToUpdate, txn);
// End txn

```
> Noting the reason this hasn't been identified as a bug before

Maybe most people of those using it doing the same thing already, but yesterday I have to write code as fast as I used to in the past and that didn't work so I thought it is a chance to bring it here instead of just silently work around it this time, I have different tables than just company and employees, it is just quick example of what I'm trying to do instead of posting the real business that I'm doing.

I got a lot of TODOs and FIXMEs in my code waiting for issues to get fixed here and there in other libraries around lol... 

P.S: I wish I can give some time to contribute PRs instead of just spam issues here! that should help me to understand ebean more and pay back some of the time saved using ebean, but sadly I'm not allowed to "waste" my time on something not directly "beneficial" in my current company's view...

**Comment by rbygrave** [comment]
Reverting this "fix" due to test case #2141 - need to re-open and find a better fix.

**Comment by rbygrave** [comment]
Applying a new fix based on EntityBeanIntercept preSetterMany setting the changed state on the many property and using that in SaveManyBeans (to detect when the orphan removal takes place on vanilla bean collections / not BeanCollection types like java.util.ArrayList)

**Comment by almothafar** [comment]
@rbygrave this issue is back with version 12.7.1 and 12.7.2

**Comment by rbygrave** [comment]
@almothafar  The test for this passes.  This implies that you might be looking at a different issue.  First step is a failing test (well, review the test for this and compare with the scenario you have with a view to create a failing test?)
