### ISSUE TITLE
@Encrypted can't be used in custom SQL query

### ISSUE THREAD

**Issue by hoffmanwang** [ebean-orm/ebean#2143]
## Expected behavior
I use DB.findDto to execute custom SQL statement, Entity fields annotated with @Encrypted should be decrypted. 
## Actual behavior
The select result is not decrypted. My database is MySQL 5.7
### Steps to reproduce

My Dto entity

```
@Data
public class AbcDto {
    @Id
    private Integer id;

    @Encrypted
    private String name;

    @Encrypted
    private String remark;
}
```

My Select:

```
public List<AbcDto> getBySQL(QueryAbc queryAbc){
        String sql="SELECT * FROM abc";
        List<AbcDto> abcDtoList=DB.findDto(AbcDto.class,sql).findList();
        return abcDtoList;
}
```

My result:

```
[
    {
        "id": 1,
        "name":"�Z4A��.��c 0�",
        "remark": "�B9�Bp�V��ݩ��5�"
    }
]
```

If I change my select like below:

```
public List<AbcDto> getBySQL(QueryAbc queryAbc){
        List<AbcDto> abcList=new QAbc().name.contains(queryAbc.getName()).asDto(AbcDto.class).findList();
        return abcList;
    }
```

The select result is right:

```
[
    {
        "id": 1,
        "name": "wsh",
        "remark": "wshwsh"
    }
]
```

**Comment by rbygrave** [comment]
You do not say if this is using client side or server side encryption?  Which is being used?  

In short there is no intention of DTO queries supporting this as we tend to want to use server side encryption which requires interesting sql generation.   The expectation is to use normal orm query and only select/fetch what we need and then map that result.

**Comment by hoffmanwang** [comment]
I use server side encryption. 

So, server side encryption won't support custom SQL query. I need to modify the custom SQL query

**Comment by rbygrave** [comment]
If you perform the query as an ORM query, and show us that orm query plus the generated sql that query creates.  Then frame your question again.  What we will see the the generated sql is the decryption function plus bind parameter for decryption (and then we can talk about that in comparison to a DtoQuery with supplied SQL / as opposed to a DtoQuery that uses an ORM query to generate the SQL).

Can you do that?  I think that will help wrt showing the 2 possible paths forward.

**Comment by rbygrave** [comment]
I'll close this for now, awaiting the generated sql and orm query.
