### ISSUE TITLE
 Assignment by reflection did not succeed

### ISSUE THREAD

**Issue by onlycp** [ebean-orm/ebean#2150]
## Expected behavior

The save failed when modifying an entity's properties by reflection. If the obj. Field method is used, it can be successful

### Steps to reproduce

```java
        // Assignment by reflection did not succeed
        ReflectUtil.setFieldValue(dbEntity, "enUs", "abc123")
        // Assignment by reflection succeed
        dbEntity.enUs = "efg123"
//        dbEntity.enUs = "enus"
        // save
        dbEntity.update()
```

**Comment by onlycp** [comment]
![image](https://user-images.githubusercontent.com/2275837/105785928-fe4bd000-5fb6-11eb-8708-9466c00142cc.png)
Breakpoint debugging, returned here

**Comment by rPraml** [comment]
This won't work.
Ebean rewrites the bytecode in your class.
Every variable access will be replaced by an internal getter/setter.
If you do a `enUs = "foo"`, the ebean class transformer will change this to `_ebean_set_enUs("foo")`
This _ebean_setter informs ebean, which fields are changed and must be updated.

If you do that by reflection, you bypass this mechanism and ebean thinks, the bean has not changed. 
If you invoke the the setter, it will work.

You also may take a lookt at the `java.beans.Introspector.getBeanInfo(beanClass);`:
find the property-descriptor for your property and invoke the "write" method.

**Comment by onlycp** [comment]
OK, Tks
