### ISSUE TITLE
fetch on findNative does not fetch all the specified collections

### ISSUE THREAD

**Issue by bkempe** [ebean-orm/ebean#2184]
## Expected behavior

`fetch` on `findNative` should behave consistently, i.e. fetch all the specified collections (like `fetchQuery` does). 
(Or, `fetch` on `findNative` should be disallowed.)

## Actual behavior

```java
findNative(Parent.class, sql)
            .fetch("firstCollection")
            .findList()
```
does not fetch `firstCollection`

```java
findNative(Parent.class, sql)
            .fetch("firstCollection")
            .fetch("secondCollection")
            .findList()
```
only fetches `secondCollection`

### Steps to reproduce

https://github.com/ebean-orm/ebean/pull/2183

### Environment
Ebean 12.7.2

### Workaround
use `fetchQuery`

**Comment by rbygrave** [comment]
When using nativeSql we can think of that as using our provided SQL for the "root query".  As such Ebean can't look to modify that to add SQL JOIN for `fetch()`.  

That is, the effective fix for this is to automatically convert `fetch()` to `fetchQuery()` when using `findNative()`.

----

This is a pretty nice feature where we can use nativeSql for the "root query" building the root level beans and then we can augment those beans with related beans using `fetchQuery()` just like Ebean can do with normal orm queries.  In this way Ebean can "add to the graph" using these "secondary queries" (which we also describe as "query joins"). This works equally for large queries like `findEach()` and `findStream()` as well triggering secondary queries in batches of 100 parents as we iterate through the root level beans.

Another way of thinking about this is that in terms of the "root sql query" and that with nativeSql we are swapping out the Ebean generated SQL with our own provided SQL (and secondary queries / fetchQuery / findEach etc works the same way for both).
