### ISSUE TITLE
DDL generation of nullable columns expected with nullable Embedded containing  non null properties

### ISSUE THREAD

**Issue by alexrm84** [ebean-orm/ebean#2220]
## The following classes are available:
@Entity
class ClientEntity(
@Id val id: UUID,
var externalId: ExternalId? = null,
@Embedded var data: Client?,
) 
@Embeddable
data class Client(
val fullName: String,
val isAlive: Boolean = true,
) 

## Expected DDL generation behavior
create table client (
id uuid not null,
external_id varchar(255),
full_name varchar(255),
is_alive boolean default false,
constraint pk_client primary key (id)
);

## Actual DDL generation behavior
create table client (
id uuid not null,
external_id varchar(255),
full_name varchar(255) not null,
is_alive boolean default false not null,
constraint pk_client primary key (id)
);

Link to the group discussion https://groups.google.com/g/ebean/c/4uWc2_CnmvU

**Comment by rbygrave** [comment]
Note: The fix for this issue is that for scalar properties of Embedded beans, in terms of DDL they can only be Non null if the Embedded bean property is also Non null.  The fix introduces a allowNonNull flag to the visitScalar() method to take this into account.
