### ISSUE TITLE
Map.keySet() modifications are not recognized and thus no queries executed.

### ISSUE THREAD

**Issue by jnehlmeier** [ebean-orm/ebean#2223]
## Expected behavior

Modifying a Map indirectly through entrySet(), keySet(), values() should trigger queries, e.g. Map.keySet().retainAll(...) should result in delete queries if keys have been removed.

## Actual behavior

Seems like BeanMap currently only tracks modifications for entrySet() and values() but not for keySet().

```java
  @Override
  public Set<K> keySet() {
    init();
    if (isReadOnly()) {
      return Collections.unmodifiableSet(map.keySet());
    }
    // we don't really care about modifications to the ketSet?
    return map.keySet();
  }
```

So I would say "Yes, we do care about modifications to the keySet!" :smile: 

### Steps to reproduce

```java
  // Answers for an assessment indexed by some answer identifier (not the primary key)
  @OneToMany(mappedBy = "assessment", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
  @MapKey(name = "identifier")
  private Map<String, Answer> answers;
```

We now have some visitor code that collect answer identifiers from a different model hierarchy and finally wants to modify the `answers` field using these collected identifiers. With JPA we do `answers.keySet().retainAll(idsCollectedByVisitor)` and see delete queries but with EBean nothing happens as `keySet` modification is not recognized.

**Comment by rbygrave** [comment]
Do you want to add a PR with a failing test case?  Perhaps extending an existing test would be ok.  Do you want to have a crack at that?
