### ISSUE TITLE
Automatically determining join columns and ignoring PrimaryKeyJoinColumn.name Id warning when I want to use Id as a foreign key

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2226]
The problem simply is I'm getting a warning while the code itself is working just fine, that warning is about using `@PrimaryKeyJoinColumn` to the custom column name and referenced column name to use `Id` of the child modal as a foreign key with the parent.

So I have 2 Models, one called `Inputs` and the other called `Calculations`, with `@OneToOne` relation, so `Calculations` is the result of `Inputs` and I want both to have the same Id, I'm not sure if that is not best practice (well, to be honest, I think it is maybe not a good idea?) but I wanted that to avoid confusion while maintaining data, so id 2 should be always 2 in another table.

Let's assume I have these models:

```java
@Entity
@Table(name = "Calculation", schema = "dbo")
public class CalculationsData extends Model {
    @Id
    @Column(name = "Id", nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @OneToOne(optional = false, cascade = CascadeType.ALL)
    @DbForeignKey(onDelete = ConstraintMode.CASCADE)
    @PrimaryKeyJoinColumn(name = "Id", referencedColumnName = "Id")
    private InputsData inputs;
}
```

```java
@Entity
@Table(name = "Input", schema = "dbo")
public class InputsData extends extends Model {
    @Id
    @Column(name = "Id", nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @OneToOne(optional = false, fetch = FetchType.EAGER, orphanRemoval = true, mappedBy = "inputs")
    private CalculationsData calculations;
}
```

The warning that I get:

```console
[warn]  -  i.e.s.d.p.AnnotationAssocOnes - Automatically determining join columns and ignoring PrimaryKeyJoinColumn.name Id on models.CalculationsData.inputs
[warn]  -  i.e.s.d.p.AnnotationAssocOnes - Automatically determining join columns and Ignoring PrimaryKeyJoinColumn.referencedColumnName Id on models.CalculationsData.inputs

```

If I remove `@PrimaryKeyJoinColumn`, the warning solved, it will create a new column (from the DDL generator) and the code will not be working, If I keep it, the code works even the warning is mentioning that it is "Ignoring" it?

**Comment by rbygrave** [comment]
> @PrimaryKeyJoinColumn(name = "Id", referencedColumnName = "Id")

What the warning is trying to say is that the `name` and `referencedColumnName` attributes are being ignored.  That is, we can instead just leave those attributes default to empty (Ebean will determine them based on the primary key column name) so:

`@PrimaryKeyJoinColumn`

I'll try to improve those warning messages.

**Comment by rbygrave** [comment]
Improved the log message and dropped to INFO level. Closing.

Cheers, Rob.
