### ISSUE TITLE
Documentation for type Enum has empty page

### ISSUE THREAD

**Issue by comradeHsu** [ebean-orm/ebean#2227]
https://ebean.io/docs/mapping/type/enum

**Comment by rbygrave** [comment]
Ok, thanks for this.  I have updated the documentation and added in appropriate links to use of `@Enumerated` and `@DbEnumValue`.  

Let me know if that all reads ok.  I'll close this for now.  Reopen if there is some improvement that should be made here.

Cheers, Rob.
