### ISSUE TITLE
ebean + SQLite keeps file locked

### ISSUE THREAD

**Issue by Leyren** [ebean-orm/ebean#2229]
GITHUB ISSUES ARE STRICTLY CONTROLLED FOR THIS PROJECT.

Refer to http://ebean-orm.github.io/support for the policies controlling the use of github issues.
Please post issues to the Ebean group https://groups.google.com/forum/#!forum/ebean first.

## Expected behavior
I am using ebean together with SQLite. In this context, I tried shutting down the database with `DB.getDefault().shutdown(true, true);` and tried deleting the database file afterwards. (Also I was hoping to register a new default afterwards)

## Actual behavior
The database file still exists. And even if I wait for a longer period of time, the file just stays locked. When trying to register a new default database after that, it fails with an IllegalStateException as it already exists. As it stands I seem unable to delete the database file programmatically.

### Steps to reproduce
Effectively described above.

**Comment by rbygrave** [comment]
Have you checked the SQLite documentation wrt deleting the database file?  Can you link to the documentation?

**Comment by rbygrave** [comment]
Hi @Leyren  I'll close this for now.  Reopen if you have an update etc.
