### ISSUE TITLE
Auto-tune does not work / throws RuntimeException (Regression from 12.7.1)

### ISSUE THREAD

**Issue by bkempe** [ebean-orm/ebean#2236]
## Expected behavior

Auto-tune/Profiling should not throw an exception / ProfileManager#createProfileOrigin succeeds.

## Actual behavior

ProfileManager#createProfileOrigin throws RuntimeException

### Steps to reproduce

It looks like tests were commented out in [October 2020](https://github.com/ebean-orm/ebean/commit/d113ddc525464bfd7f17f17ca9a671183c226992)
but any usage of auto-tune/profiling will throw the RuntimeException.

That is, because [createProfileOrigin](https://github.com/ebean-orm/ebean/blob/f341ff0167cd6838b27039267c05558952d03723/ebean-autotune/src/main/java/io/ebeaninternal/server/autotune/service/ProfileManager.java#L69) calls toString on OrmQueryDetail, which [does not have an overridden toString anymore since February 2021](https://github.com/ebean-orm/ebean/commit/8ac54678562c8783ed673b0ad3f0bc1d27193ed1#diff-11c3c9b1953762b4d158ee5b0ab2851b5121944726394cf6a97742880f0d8cd9L110).
This means that the default Java toString is being used, which calls hashCode, which [throws the exception](https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/querydefn/OrmQueryDetail.java#L121)

**Comment by rbygrave** [comment]
Fixed with the above but ideally we get a test on ProfileManager for this but leaving that for another day at this stage.
