### ISSUE TITLE
Select with disjunction of expressions over OneToOne relationship missing join clause

### ISSUE THREAD

**Issue by bkempe** [ebean-orm/ebean#2238]
## Expected behavior

The generated SQL for a select statement with disjunction of expressions over a OneToOne relationship should contain the join clause for the table

## Actual behavior

Join clause is missing for generated SQL

### Steps to reproduce

See test in https://github.com/ebean-orm/ebean/pull/2237/files to illustrate and replicate the behavior
This used to work fine in 12.6.5 of EBean.

**Comment by rbygrave** [comment]
**Background:**

- This issue was introduced in 12.9.0 #2230
- Noting that #2230 Was added to fix #2145
- Noting that there might be a better fix for 2145 (underlying the join is being added twice and the second time is suppressed but the soft delete predicate wasn't being suppressed)
