### ISSUE TITLE
Mapping - Add / review support for @IdClass

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#225]
From google group:

I updated to the latest version of Ebean and am now getting 

play.api.UnexpectedException: Unexpected exception[IllegalStateException: Issue with bean com.lifetouch.lps.entity.BatBatchDetail. Ebean does not support multiple @Id properties. You need to convert to using an @EmbeddedId. Please email the ebean google group if you need further clarification.]

The relevant classes are

public class BatBatchDetailKey
{
   public Integer batchId;
   public Integer batchSeq;
}

@Entity
@IdClass(BatBatchDetailKey.class)
public class BatBatchDetail
{
   @Id
   public Integer batchId;
   @Id
   public Integer batchSeq
}

**Comment by mightyzero** [comment]
Is there an update on this issue?

**Comment by rbygrave** [comment]
No. No update.

**Comment by rbygrave** [comment]
### example
```java
@Embeddable
public class BEmbId {

  private UUID siteId;
  private UUID userId;

  public BEmbId(UUID siteId, UUID userId) {
    this.siteId = siteId;
    this.userId = userId;
  }
  // plus equals() / hashCode() / getters ...

```

#### Mapping to `scalar` `@Id` properties 

```java
@Entity
@IdClass(BEmbId.class)
public class BSiteUserD {

  @Id
  private UUID siteId;

  @Id
  private UUID userId;

  private BAccessLevel accessLevel;

  @Version
  private long version;
...
```

#### Mapping to `@ManyToOne` `@Id` properties

```java
@Entity
@IdClass(BEmbId.class)
public class BSiteUserE {

  @Id
  @ManyToOne
  private final BSite site;

  @Id
  @ManyToOne
  private final BUser user;

  private BAccessLevel accessLevel;

  @Version
  private long version;
...
```
