### ISSUE TITLE
setParameter cannot assigning the value when paramater in selecting section of query

### ISSUE THREAD

**Issue by bsanjaasuren** [ebean-orm/ebean#2255]
Hello, I have a problem on to setting a paramater in the selecting section of a query. 

It is not replacing the paramater and giving me syntax error on :numberParamater.

EBean
`query.setParameter("numberParamater",7);`

SQL Query
`
SELECT (s.created_at < current_date - interval :numberParamater) as new
FROM table;
`

**Comment by rbygrave** [comment]
This issue does not reproduce.  Can you provide a failing test (ideally using H2).

```java
  @ForPlatform(Platform.H2)
  @Test
  public void selectFunction() {

    String sql = "select length(?)";
    final Long val = DB.sqlQuery(sql).setParameter("NotVeryLong").mapToScalar(Long.class).findOne();
    assertThat(val).isEqualTo(11);

    String sql2 = "select length(:val)";
    final Long val2 = DB.sqlQuery(sql2).setParameter("val", "NotVeryLong").mapToScalar(Long.class).findOne();
    assertThat(val2).isEqualTo(11);
  }
```

```console
12:40:07.466 [main] DEBUG io.ebean.SQL - select length(?); --bind(NotVeryLong)
12:40:07.557 [main] DEBUG io.ebean.SQL - select length(?); --bind(NotVeryLong)
```

**Comment by rbygrave** [comment]
I'll close this for now.  Please re-open with a failing test case.  Thanks.
