### ISSUE TITLE
Refactor BindHash: Using MD5 to avoid collisions

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2261]
I noticed, that Ebean still uses hashCode for bindHash computation,

This has a risk of collisions. especially if the prime factor 92821 plays a role (which was introduced in #869)

## Expected behavior

same queries with different bind values must not hit the cache.

## Actual behavior

query with different bind values may hit the cache, but should not.

### Steps to reproduce

The query `q.between("prop", 0, 92821)` and `q.between("prop", 1, 0)` will have the same hash
because of: 
https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/expression/BetweenExpression.java#L52

### Possible solution

I've fixed this in Ebean 11: https://github.com/FOCONIS/ebean/commit/1344f790577c687359db589ec856baa9b2c0c70d
Maybe you can take a look at it. Especially if you think, if the algorithm should be configurable (https://github.com/FOCONIS/ebean/commit/1344f790577c687359db589ec856baa9b2c0c70d#diff-fdfd7023c25af12fa4d0bc1104850a905c18eaffdb90c1577111e2162f39fc60R299) or if we should use MD5 as default
If you want, I can port this change to 12

**Comment by rbygrave** [comment]
> If you want, I can port this change to 12

Yes please. This does look like a nice improvement.
