### ISSUE TITLE
Transaction postCommit Callback not invoked when the active transaction has no database writes

### ISSUE THREAD

**Issue by pkalodimas** [ebean-orm/ebean#2262]
## Expected behavior
I registered a transaction callback to the active transaction. It is expected that the callback postCommit methods should be called when the transaction is committed.

## Actual behavior
The transaction callback is never called.

### Steps to reproduce
I actually did some debugging and I realized that this issue appears only when the active transaction has no database writes. When the same code is updating something on the database, the transaction callback is called.

I did one trick and the issue was solved after that. I added the following code before registering the callback.
transaction.addModification("table", false, true, false);

**Comment by rbygrave** [comment]
Test case:

```java
  @Test
  public void test_whenNoDbWrite() {
    try (Transaction txn = DB.beginTransaction()) {
      DB.register(new MyCallback());
      txn.commit();
    }

    assertEquals(1, countPreCommit);
    assertEquals(1, countPostCommit);
    assertEquals(0, countPreRollback);
    assertEquals(0, countPostRollback);
  }
```
