### ISSUE TITLE
Use of default timezone for OffsetDateTime offsets problematic for unit tests and presentation layer

### ISSUE THREAD

**Issue by simontankersley** [ebean-orm/ebean#2264]
It is common to use the OffsetDateTIme type for representing date times. However, when using postgres with ebeans any asserts in unit tests on OffsetDateTime are dependent on the default timezone of the system. Also if you are passing the OffsetDateTime all the way through to your presentation layer then the offset output again depends on the default timezone of the system given different results depending where you run program.

This has been tracked to this line. It would be great to have control over which timezone gets used without having to change the system timezone.

https://github.com/ebean-orm/ebean/blob/f8e54be9a60ef9ad51d94980fe2bd20ddc623d81/ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeOffsetDateTime.java#L49

**Comment by rbygrave** [comment]
We can specify the explicit timezone to use on DatabaseConfig.
See https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java#L1305

JDBC bind and read via:
https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/type/DataBind.java#L167
https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/type/RsetDataReader.java#L159

There could be an issue in JSON marshalling/unmarshalling or something else like that but ultimately we need to come up with a failing test case.

**Comment by simontankersley** [comment]
I tried setting the explicit timezone and while that does appear to affect the Timezone object got by [ScalarTypeBaseDateTime#read(DataReader)](https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeBaseDateTime.java#L92) this is still gets pass to [ScalarTypeOffsetDateTime#convertFromTimestamp(Timestamp)](https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeOffsetDateTime.java#L44), which ends up calling [ScalarTypeOffsetDateTime#convertFromInstant(Instant)](https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/type/ScalarTypeOffsetDateTime.java#L49), which ends up calling:

```
return OffsetDateTime.ofInstant(ts, ZoneId.systemDefault());
```

The offset put into the OffsetDateTime added to the bean depends on the timezone of the system.

I can put together a project with unit tests showing the problem, is that enough?

**Comment by rbygrave** [comment]
> I can put together a project with unit tests showing the problem, is that enough?

Yes.  How are you going with that.  It looks like we need the DataTimeZone zoneId to get to ScalarTypeOffsetDateTime

**Comment by simontankersley** [comment]
Please see demo here: https://github.com/simontankersley/demo_ebean_issue_2264

You can observe the behaviour running:

```
gradle -i clean build
```

You will get an output like:

```
DemoTest > testWithUTC() STANDARD_ERROR
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
    SLF4J: Defaulting to no-operation MDCAdapter implementation.
    SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.

DemoTest > timeWithEST() FAILED
    org.opentest4j.AssertionFailedError: expected: <Z> but was: <-05:00>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at demo_ebean_issue_2264.DemoTest.timeWithEST(DemoTest.java:57)
```

**Comment by rbygrave** [comment]
Notes: 

I ultimately adjusted the test to set the `ebean.dataTimeZone` system property as well (in order to confirm the fix).

```java
        System.out.println("Configure Ebean to use this ZoneId "+ timeZoneToUse.getID());
        System.setProperty("ebean.dataTimeZone", timeZoneToUse.getID());

```

I could simulate the issue in unit tests in Ebean by having ScalarTypeOffsetDateTime use the ZoneId of the system when it was created (and have it created before changing the system zone).  Then we get the fix by passing the ZoneId to use to ScalarTypeOffsetDateTime when it is created based on  `ebean.dataTimeZone` (rather than the current system zoneId).

**Comment by rbygrave** [comment]
Also thank you @simontankersley  for the example failing test.  I know it is a bit of a pain but it is nice to confirm the fail and confirm the fix etc (and helped me simulate the fail in unit tests).
