### ISSUE TITLE
DDL files not generated since 12.7.1 version (ebean-ddl-generator is now a dependency of ebean-test, since version 12.7.1)

### ISSUE THREAD

**Issue by elhoce** [ebean-orm/ebean#2285]
## Expected behavior

ddl files must be generated in target or build directory

## Actual behavior
since version 1.2.7.1 dll files wasn't generated.

### Steps to reproduce
take or made a project with ebean version 12.6.7 max.
enable ddl generation DataSourceConfig setDdlGenerate(true);
run it dlls files will be generated.

update ebean version to 12.7.1 min
delete dll files in target or build directory
rerun the application.

**Comment by rbygrave** [comment]
# Actions:

- Add ebean-ddl-generator (typically only as a **test** dependency).
- Or add ebean-test as a test dependency (which will then transitively bring in ebean-ddl-generator)

I believe the app hit this issue as it does not have ebean-test as a test dependency.


# Release 12.7.1

If we look at https://github.com/ebean-orm/ebean/releases/tag/ebean-parent-12.7.1

We see at the bottom:

### Dependency changes
#2162 - Change ebean artifact such that ebean-ddl-generator is a dependency of ebean-test and ebean-autotune optional dependencies


I believe the issue we are hitting here is that _ebean-ddl-generator_ is a dependency of _ebean-test_ and not a required dependency of _ebean_.  I believe this app does not have a dependency on _ebean-test_ (which is ok, that is a valid way to go as well). _We need to make sure ebean-ddl-generator is in the test classpath._


# So why did we do this?

The majority of apps do not need ebean-ddl-generator and it's transitive dependencies (JAXB) in the main classpath. These are only needed for testing.

Having broken Ebean into sub-modules separating out the ddl generation into  _ebean-ddl-generator_ we were able to make this change with the benefit that we reduce the size of dependencies that the app needs when it is built and deployed - it doesn't need ebean-ddl-generator or JAXB in the main classpath.

**Comment by rbygrave** [comment]
I presume you are all good @elhoce ?  I'll close this issue, re-open if you didn't get sorted.
