### ISSUE TITLE
ENH: Explicit option for fast-failing or not fast-failing (skipDataSourceCheck DatabaseConfig option)

### ISSUE THREAD

**Issue by jnehlmeier** [ebean-orm/ebean#2291]
Usually connection pools have an option for fail fast behavior. That means at the time of pool creation the pool checks wether or not the database is alive. If fail-fast is true then pool creation would fail, otherwise pool creation succeeds but getConnection() calls from a client will timeout since the pool continuously tries to acquire a database connection internally until it succeeds.

We would like Ebean to have an explicit fail-fast option as well because we want the app to be more resilient against an offline db. As we use Guice and create io.ebean.Database instances as eager singletons during deployment, we have to do some ugly workaround in order to make sure that deployment succeeds with an offline db (see below).

Currently Ebean has different fail-fast behavior based on the TenantMode. Basically when Ebean is in TenantMode.DB / DB_WITH_MASTER if behaves like fail-fast = false. In all other modes if behaves like fail-fast = true because if tries to check autoCommit during io.ebean.Database creation to issue a warning if autoCommit is true. That means during io.ebean.Database creation ebean will call DataSource.getConnection() which will fail if DB is offline and thus may fail deployment.

With the above in mind we currently use an ugly workaround and configure databases that are usually TenantMode.NONE with TenantMode.DB and basically don't use a tenantId internally when providing the datasource to ebean. It looks weird and always requires explanations. Thats why I would prefer having an explicit ebean option wether or not database creation should be fail-fast or not.

IMHO when an application is deployed, the ORM should start just fine, the connection Pool should start just fine, but executing actual work should fail until DB is online again. Basically the deployment of an application should not depend on wether or not all other services are reachable at that time. Instead the application must handle that situation gracefully and "repair" itself once services come back online.

**Comment by rbygrave** [comment]
> when an application is deployed, ... but executing actual work should fail until DB is online again.

Well I am kind of thinking that is not the Kubernetes thinking. In K8s the application is only rolled out when it passes the readiness probe and not being able to do work means it should not pass the readiness probe.

That said, I can understand the desire to have this as an explicit option like  `skipDataSourceCheck`.

**Comment by rbygrave** [comment]
This is the same feature you were after @rPraml  @jonasPoehler ?

**Comment by rbygrave** [comment]
Added a `skipDataSourceCheck` configuration option for DatabaseConfig. Setting this to true will skip that check on the DataSource and I believe that is the behaviour we are looking for in this case.

**Comment by jnehlmeier** [comment]
> > when an application is deployed, ... but executing actual work should fail until DB is online again.
> 
> Well I am kind of thinking that is not the Kubernetes thinking. In K8s the application is only rolled out when it passes the readiness probe and not being able to do work means it should not pass the readiness probe.

Well I would say, it depends. The readiness probe ensures that no traffic will be routed to the pod. I think this is useful for web services or internal micro services but not so much for a user facing application that also has some UI. For example think of a login application. Should it be unreachable if the database is down? I don't think so. It should load just fine and serve traffic just fine. However you can not login and thus get an error message. I think that is true for most user facing UI applications since they rarely have dependencies that stop them from providing an UI in a meaningful way.


> That said, I can understand the desire to have this as an explicit option like `skipDataSourceCheck`.

Thanks for adding it directly to 12.11.1!

**Comment by rPraml** [comment]
@rbygrave Yes, this goes in the same direction, but we have done more as only `skipDataSourceCheck`. The problem is, that the DB-Migration has to be run, when DB comes up.
In summary, we have
- added a flag to the config (which mainly is the same as `skipDataSourceCheck`)
- added a `Database.initDatabase()` which runs the migration

This is done in this PR: https://github.com/FOCONIS/ebean/commit/d0e5484dd7a82d206311f0876880e1578815557a
