### ISSUE TITLE
Support Geometric types of Postgres

### ISSUE THREAD

**Issue by antonini** [ebean-orm/ebean#239]
It would be nice that ebean supports geometric datatypes from Postgres. Those are listed on the following URL:
http://www.postgresql.org/docs/9.4/static/datatype-geometric.html

These are functions to be used with the previous datatypes.
http://www.postgresql.org/docs/9.0/static/functions-geometry.html

**Comment by rbygrave** [comment]
This is a duplicate of #198 

I'll close this one for now leaving the original 198 open.

**Comment by rbygrave** [comment]
Ok, not considering this a duplicate as separate types from #198

**Comment by rbygrave** [comment]
Also note the example for Postgis is at: https://github.com/ebean-orm-examples/example-postgis

**Comment by rbygrave** [comment]
Closing.  I'm unlikely to progress this myself until I need it.
