### ISSUE TITLE
Minor issue with application starting up logging "ebean version: unknown"

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2414]
It is just a simple issue, in logging with recent updates from ebean (I'm using 12.12.1 and 12.12.2), the logger shows unkiwn for the version of ebean that is used.

### Steps to reproduce

```console
[info]  - [                    ] - io.avaje.config - Loaded properties from [resource:application.yaml] 
[info]  - [                    ] - io.ebean - ebean version: unknown
[info]  - [                    ] - io.ebean.core - Started database[default] platform[SQLSERVER17] in 1509ms
```

**Comment by rbygrave** [comment]
I don't see this issue reproducing?  Are you still seeing this issue?

**Comment by almothafar** [comment]
@rbygrave yes I still see it

**Comment by rbygrave** [comment]
Sorry @almothafar  I still have not reproduced.  Can you create an example app that reproduces this for me?

**Comment by almothafar** [comment]
@rbygrave I'll close this then, i don't work with play framework anymore as I changed my Job
