### ISSUE TITLE
Ebean-elastic set generateMapping=true,the mapping file is not automatically generated

### ISSUE THREAD

**Issue by ulyChou** [ebean-orm/ebean#2430]
## Expected behavior
Automatically generates mapping files
## Actual behavior
The mapping file is not automatically generated
### Steps to reproduce
set application.yaml,es connection successful.
```java
ebean:
  docstore:
    url: http:192.168.1.152:9200
    active: true
    dropCreate: true
    generateMapping: true
    elasticVersion: 7.5.2
```
```
@DocStore
@Entity
@Table(name = "order_test")
class OrderTest(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null
) : Model() {
    companion object Find : OrderFinder()
}
```
```console
2021-10-31 18:07:09.014 ERROR 117980 --- [           main] i.e.elastic.index.EIndexService          : docStore.pathToResources [src/main/resources] does not exist?
```

**Comment by rbygrave** [comment]
> docStore.pathToResources [src/main/resources] does not exist?

It looks like it needs a `pathToResources` property set in the yaml file? Have a look at the example below. If we set an explicit `pathToResources` does this work?  Or do we still see the message like `docStore.pathToResources [src/main/resources] does not exist?`

https://github.com/ebean-orm/ebean-elasticsearch/blob/master/src/test/resources/application-test.yaml

**Comment by ulyChou** [comment]
I am currently running a subproject, and when I change the address to an absolute path it will start normally
