### ISSUE TITLE
PagedList.getPageIndex() returns wrong result

### ISSUE THREAD

**Issue by GiannisMP** [ebean-orm/ebean#2453]
Let's say you call 
`query.setFirstRow(X).setMaxRows(10).findPagedList() `

## Expected behavior
The expected page index should be:
For setFirstRow(0- 9) -> 0 
For setFirstRow(10-19) -> 1
For setFirstRow(20-29) -> 2
etc..

## Actual behavior
For setFirstRow(0) -> 0
For setFirstRow(1-10) -> 1
For setFirstRow(11-20) -> 2
etc..

**Comment by rbygrave** [comment]
Can you be more explicit, this issue is not sufficiently clear/explicit.  That is, show an example in terms of code and the expected behavior in terms of code with asserts plus perhaps generated sql (expected vs actual).

Thanks, Rob.

**Comment by GiannisMP** [comment]
Sorry by offset I meant setFirstRow. I have been thinking it for some time. 
If you do for example
`query.setFirstRow(5).setMaxRows(10).findPagedList().getPageIndex()`
you will get 1. I would expect to get 0 since the results start from the page 0. 
But I guess you return the page index of the page results get to. Technically the results are both on the 0 and 1 page.
It's more of a philosophical question the more I think about it.

**Comment by rbygrave** [comment]
The design thinking behind PagedList is that we have a fixed maxRows (e.g. max 10) and are "paging"  - page 0, 1, 2, 3 ..

With that thinking the expectation is that _firstRow_ would be a multiple of _maxRows_.  So in the case of maxRows of 10 we would expect firstRow to be 0, 10, 20, 30, 40 ...

That is, `query.setFirstRow(5).setMaxRows(10).findPagedList()` is odd in that **5** isn't an expected starting position for a "page".

**Comment by GiannisMP** [comment]
Yes you are right this is not a normal use case. It just seemed odd to me the way the page index was calculated.
Anyway, I am closing this issue.
Thanks for the clarification.
