### ISSUE TITLE
extend new database type

### ISSUE THREAD

**Issue by FCCloud** [ebean-orm/ebean#2455]
I want to use ebean to link a new database type. How can I extend it。

**Comment by rbygrave** [comment]
Typically you define a platform for it via https://github.com/ebean-orm/ebean-annotation/blob/master/src/main/java/io/ebean/annotation/Platform.java#L6

Then create a DatabasePlaform for it, extending https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/config/dbplatform/DatabasePlatform.java#L26

You can look at the others to see examples like for example: https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/config/dbplatform/postgres/PostgresPlatform.java

To support DDL generation you need to extend PlatformDdl.
To have it auto detect based on jdbc meta data then look at DatabasePlatformFactory.

**Comment by rbygrave** [comment]
I'll close this for now.  Re-open if needed.
