### ISSUE TITLE
BeanPersistController and Cascade

### ISSUE THREAD

**Issue by geo-m** [ebean-orm/ebean#2458]
Hi, i am using a BeanPersistController to maintain a table of nested sets, with reference to parent as a FK as well.

Due to the cascade on the relation, when i delete a folder, all child folders are deleted. However i am interesting in running the left/right recalculations only when the root bean that triggered the cascade is in postDelete(), because the rest are redundant.

Is there a way to identify in the controller that the bean in pre/postDelete is the first bean and not a result of cascade? 

Thank you. Ebean is awesome so far by the way

EDIT: Forgot to mention i have found SpiTransaction.depth() but i am not sure if it is a safe api

**Comment by rbygrave** [comment]
> found SpiTransaction.depth() but i am not sure if it is a safe api

It might do for now but it isn't officially public.

An alternative (also not officially public) is ...

**Comment by rbygrave** [comment]
Where `isRecurse()` might be better named something like `isCascade()`

**Comment by geo-m** [comment]
That would be great, although i do understand it is a rare case. Would using depth = 0 for now be a reliable way to identify the root bean?

**Comment by rbygrave** [comment]
> it is a rare case

Yeah maybe but I can see the utility value in adding a `isCasade()` so I've gone and prepared the PR for it.

> Would using depth = 0 for now be a reliable way

I'd prefer we didn't use it.  It is very close to `isCascade()` but for example when we start we might go "up" to a ManyToOne, then back to starting level and then "down" to a OneToMany ... so all in all I think it is best if we keep depth as an internal detail.

So I believe `isCascade()` is really a lot more what we want here.

**Comment by rbygrave** [comment]
FYI: 

In terms of releasing 12.13.2 I've been trying to release since yesterday but oss.sonatype.org is swamped at the moment. So kind of nice timing in terms of getting this into 12.13.2. Hopefully I can get that out shortly (today / tomorrow).

**Comment by geo-m** [comment]
Thanks a lot for the quick merge

**Comment by geo-m** [comment]
It looks like manually calling Flags.isRecurse is always false on deletions, even with cascade. I took a look and i think this is set only in DefaultPersister::createRequestRecurse, which only happens for inserts and updates

**Comment by rbygrave** [comment]
Ok, darn.

**Comment by rbygrave** [comment]
> Flags.isRecurse is always false on deletions, even with cascade

Logged as #2472
