### ISSUE TITLE
Oracle - column alias - Ebean generates invalid sql query when upgrade from 12.8.0 to version 12.13.1

### ISSUE THREAD

**Issue by nguyenminhtuanfit** [ebean-orm/ebean#2473]
## Expected behavior
select tteammessage.aprocesstype, NVL2(tteammessage.amessage, (tteammessage.amessage).getClobVal(), NULL) as amessage, tteammessage.anteid, tteammessage.alstupditftypcde, tteammessage.alstupdusrcde, tteammessage.alstupddtetme
  from TTEAMMESSAGE )
## Actual behavior
select ....  t0.aprocesstype c19, 
 NVL2(t0.amessage, (t0.amessage).getClobVal(), NULL) **as amessage c20**, t0.anteid c21, t0.alstupditftypcde c22 from TTEAMMESSAGE t0
### Steps to reproduce

```java
 @Lob
    @Basic(fetch = FetchType.EAGER)
    **@Formula(select = "NVL2(${ta}.amessage, (${ta}.amessage).getClobVal(), NULL) as amessage")**
    @Column(name = AMESSAGE)
    private XmlType amessage = XmlType.NULL_VALUE;
```
In version 12.13.1 adding   this.columnAliasPrefix = "c" in class OraclePlatform  may cause the issue

**Comment by rbygrave** [comment]
With this fix we are introducing an Oracle12Platform for the case where we desire column alias. We don't think we need column alias for Oracle18c and greater.
