### ISSUE TITLE
Does ebean have feature like @ColumnTransformer in Hibernate

### ISSUE THREAD

**Issue by comradeHsu** [ebean-orm/ebean#2482]
My entity has a field and it's create by function of database, but i don't know how to handle this problem.

**Comment by rbygrave** [comment]
I think you need to explain your use case more.  Some people using Hibernates `@ColumnTransformer` for encryption/decryption but Ebean has built in support for that which should be used instead.  For the read only case Ebean has `@Formula`.

Can you clarify what this use case is more explicitly?

Thanks, Rob.

**Comment by comradeHsu** [comment]
Yeah. I used PostgeSQL with PostGIS, and i have a geography field. it's create by PostGIS's function.
```SQL
ST_SetSRID(
        ST_MakePoint({longitude}::numeric,{latitude}::numeric)
```
The parameters longitude and latitude originate the another field in my entity. That field is just a string about gps, it can be converted to parameters through database functions，but i really don't know how to handle this problem in Ebean.
Thanks, Daniel.

**Comment by rbygrave** [comment]
I see, a "derived" field then, a bit of denormalisation.  This field is being computed/populated on insert and update rather than just using a `@Formula` to compute it on select/read.

**Comment by comradeHsu** [comment]
yeah, it seems that the problem cannot be dealt with in Ebean?

**Comment by rbygrave** [comment]
No, we don't have a feature where we can use a database formula to populate a column for ORM insert/update.  Instead today you'd look to use a db trigger to populate that column OR use sql instead (e.g. use Ebean `SqlUpdate`).

An issue in getting Ebean to do that is that unlike Hibernate, Ebean has partial object support meaning that the bean can be populated with for example just longitude and not longitude _and_ latitude so we'd need some rules to control that behavior around partially populated beans that don't have all the necessary properties loaded.

**Comment by comradeHsu** [comment]
Yes i see. I thought of this matter, that field doesn't need loaded, so it isn't a simple requirement. Thanks very much for your reply!
