### ISSUE TITLE
ebean-test has hardcoded "localhost" instead of the docker container's hostname

### ISSUE THREAD

**Issue by jairovsky** [ebean-orm/ebean#2487]
#### Expected behavior
I work on projects where the CI processes (e.g. gradle maven etc.) run inside docker containers. When using ebean-test, my expectation was that ebean would be able to automatically detect the hostname of the database container and connect to it.

#### Actual behavior
ebean-test always expects the db servers to be accessible via `localhost`. Examples:
https://github.com/ebean-orm/ebean/blob/7cfecb83a91621b49abe0d597ed41d7b08c6eb22/ebean-test/src/main/java/io/ebean/test/config/platform/MySqlSetup.java#L16
https://github.com/ebean-orm/ebean/blob/7cfecb83a91621b49abe0d597ed41d7b08c6eb22/ebean-test/src/main/java/io/ebean/test/config/platform/PostgresSetup.java#L16

Since my tests are already running inside a container, `localhost` will refer to the container of the gradle/mvn/etc process, not the host machine, thus making it impossible to establish a connection to the database.

#### Steps to reproduce
* Create a dummy ebean application
* Configure the tests:
```yaml
ebean:
  test:
    platform: mysql
    ddlMode: dropCreate
    dbName: asdf
    username: admin
    password: admin
```
* Package the project in a docker image and run it. The image CMD will be something along the lines of `./gradlew test` or `./mvnw test` depending on the project config. It's necessary to pass `/var/run/docker.sock` as a volume to make Docker accessible from within the container.
* ebean will be able to start a mysql container, try to connect to it for a few seconds and then fail the tests.

Example log showing that ebean tries to connect to `localhost`
```console
Caused by:
                    java.lang.ExceptionInInitializerError
                        at io.ebean.DB.<clinit>(DB.java:66)
                        at com.picpay.atlas.persistence.configuration.PersistenceTestSetup.database(PersistenceTestSetup.kt:48)
                        at com.picpay.atlas.persistence.configuration.PersistenceTestSetup$$EnhancerBySpringCGLIB$$ea5b36d0.CGLIB$database$0(<generated>)
                        at com.picpay.atlas.persistence.configuration.PersistenceTestSetup$$EnhancerBySpringCGLIB$$ea5b36d0$$FastClassBySpringCGLIB$$f1073658.invoke(<generated>)
                        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
                        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
                        at com.picpay.atlas.persistence.configuration.PersistenceTestSetup$$EnhancerBySpringCGLIB$$ea5b36d0.database(<generated>)
                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
                        ... 176 more

                        Caused by:
                        java.lang.RuntimeException: io.ebean.datasource.DataSourceInitialiseException: Error initialising DataSource with user: admin url:jdbc:mysql://localhost:4306/atlas error:Communications link failure

                        The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
                            at io.ebean.DbContext.<init>(DbContext.java:56)
                            at io.ebean.DbContext.<clinit>(DbContext.java:23)
                            ... 188 more

                            Caused by:
                            io.ebean.datasource.DataSourceInitialiseException: Error initialising DataSource with user: admin url:jdbc:mysql://localhost:4306/atlas error:Communications link failure

```

Is this by design?
Can ebean support this?
Would it be difficult to implement? If not, I think I can contribute with a PR.

**Comment by rbygrave** [comment]
>  Would it be difficult to implement? 

I am not sure.

> If not, I think I can contribute with a PR.

Yeah cool.

> Is this by design?

It is more a case that for all the CI environments used so far have:
- Either provided the database separately (so then ebean-test connects to that and doesn't start a database container at all) 
- Or not been Docker-In-Docker

It would be nice to support this if we can.
---
https://www.cloudsavvyit.com/14114/how-to-connect-to-localhost-within-a-docker-container/

> Docker Desktop 18.03+ for Windows and Mac supports host.docker.internal as a functioning alias for localhost. Use this string inside your containers to access your host machine.

Does using `host.docker.internal` work ?

**Comment by jairovsky** [comment]
hmmmm.. probably. I need to check with the infrastructure team. Thanks for the suggestion.

Anyway, I think I'll be able to dig into ebean's codebase throughout the week to see what can be done.

**Comment by rbygrave** [comment]
We should be able to test using `host.docker.internal` as the host name by explicitly specifying the `url` like below:

```yaml
ebean:
  test:
    platform: mysql
    ddlMode: dropCreate
    dbName: asdf
    username: admin
    password: admin
    mysql:
      url: jdbc:mysql://host.docker.internal:4306/asdf
```

**Comment by jairovsky** [comment]
yes, yes. The thing is `host.docker.internal` apparently only comes by default on Mac and Windows. At least in my tests on linux I needed to `docker run ... --add-host="host.docker.internal:host-gateway"` for it to work, hence why I'll need to check if can do this in my CI environment.

**Comment by rbygrave** [comment]
From docker forums - https://forums.docker.com/t/how-to-reach-localhost-on-host-from-docker-container/113321
> ... For Docker running on Linux I have used 172.17.0.1 which is the Docker-host in Docker’s default-network.

So I am currently thinking:


### Add detection of running in a docker container and running os
- Detect if ebean-test is running in a docker container.  The simple initial way to check this is by the existence of file `/.dockerenv`
- Detect the os platform. If linux use `172.17.0.1` and otherwise `host.docker.internal`

### Support and explicit `host` setting
Add the ability to explicitly specify `${host}` rather than just fixed `localhost`. I don't think this is ideal for local dev + CI, but might be useful for testing build setup.


So when no `host` is explicitly set, ebean-test will detect if it's running in docker and which os is being used and then use  `172.17.0.1` or `host.docker.internal` rather than `localhost`.

**Comment by rbygrave** [comment]
So in theory in the Ubuntu CI build ... `url: jdbc:mysql://172.17.0.1:4306/asdf` ... would work.

**Comment by rbygrave** [comment]
Are you able to confirm if `172.17.0.1` works?  If so I'll merge that PR and the next release might "just work"

**Comment by jairovsky** [comment]
I tested with this config:
```yaml
ebean:
  test:
    useDocker: true
    shutdown: stop
    platform: mysql
    ddlMode: dropCreate
    dbName: atlas
    username: admin
    password: admin
    mysql:
      port: 3306
      url: jdbc:mysql://172.17.0.1:3306/atlas
```

Looking at the logs it does connect but there's a problem:
```
Caused by:
java.sql.SQLException: Access denied for user 'admin'@'172.17.0.1' (using password: YES)
```
At least for mysql, it seems that some tweak needs to be done on the grants. Didn't test with other databases.

---
Side note: I've worked on projects where `172.17.xxx.yyy` was already reserved by the company's network and to avoid conflict, developers needed to configure their docker daemons with another subnet. It's an edge case but it can happen.

**Comment by rbygrave** [comment]
ok cool.

I am thinking the PR #2488 is "close".  As in, if we fix the connection permissions issues with MySql it might work (except for those cases where  docker daemons use another subnet and maybe some other cases we don't know about yet).  Maybe, in those cases an explicit `host` could be used ... maybe we have a `dockerHost` property given that we only want to use this property when ebean-test detects it is running in docker.

So allow use to specify an explicit CI / "In Docker" host called `dockerHost`. ebean-test could use that when ebean-test detects it is running in docker. This could then handle the cases where `172.17.0.1` does not work.

```
ebean:
  test:
    useDocker: true
    shutdown: stop
    platform: mysql
    ddlMode: dropCreate
    dbName: atlas
    username: admin
    password: admin
    mysql:
      port: 3306
      dockerHost: <something other than 172.17.0.1>
#      dockerHost: 172.17.0.1
#      url: jdbc:mysql://172.17.0.1:3306/atlas
```

```

**Comment by rbygrave** [comment]
> SQLException: Access denied for user 'admin'@'172.17.0.1' (using password: YES)

This is a problem on the ebean-test-docker side. It is assuming `localhost` when executing the admin sql commands.

**Comment by rbygrave** [comment]
The fix for this issue requires ebean-test-docker version 4.4 with https://github.com/ebean-orm/ebean-test-docker/issues/62

**Comment by jairovsky** [comment]
hey nice
I think will be able to test it next week.
Thanks for the quick response, Rob.
