### ISSUE TITLE
Is it possible to disable auto configuration / startup?

### ISSUE THREAD

**Issue by jairovsky** [ebean-orm/ebean#2489]
This is more of a question, not a bug so I think it doesn't fit the expected/actual behavior template.

So, in the docs it states that ebean can automatically read configuration from common files like `application.properties` or we can configure it programmatically. In the projects I work, most of the configuration is done programmatically within the Spring environment (`@Configuration` `@Bean` etc.). We also use Spring Boot, which reads `application.properties` too.

The problem: to maintain consistency in the project and prevent configuration bugs we want to configure ebean programmatically, but since we use spring boot and `application.properties`, ebean is reading `application.properties` before Spring.

Is it possible to disable ebean auto configuration while using `application.properties` for spring boot?

One use case is that, in integration tests, we use testcontainers to set up services like mysql and rabbitmq, and then we override the properties (database/rabbitmq hosts and ports) via `System.setProperty`, but since ebean loads `application.properties` using avaje-config, it doesn't pick up changes made through `System.setProperty`. The tests run in docker-in-docker so the database/rabbitmq urls can't be hardcoded ahead of time in a properties file.

**Comment by rbygrave** [comment]
> most of the configuration is done programmatically within the Spring

Yes, that's the common case.  You'd be creating Ebean's Database instance programmatically there. When you do, don't call `databaseConfig.loadFromProperties()` to not load application.properties.


> Is it possible to disable ebean auto configuration while using application.properties for spring boot?

Yes.   See https://ebean.io/docs/intro/configuration/#programmatic

Effectively **_don't_** call [DatabaseConfig.loadFromProperties()](https://ebean.io/apidoc/12/io/ebean/config/DatabaseConfig.html#loadFromProperties()) ... and Ebean will not load properties.

> One use case is that, in integration tests, we use testcontainers

Noting that Ebean has it's own docker test integration that you can use. I'd argue it is better to use than testcontainers in a number of ways. Just adding docker-in-docker support at the moment.

**Comment by jairovsky** [comment]
I figured that a spring configuration class was calling an ebean repository a little too early, triggering ebean's auto configuration.

Closing as it was a problem in the application.
