### ISSUE TITLE
ManyToMany entities' relations are not saved.

### ISSUE THREAD

**Issue by pkalodimas** [ebean-orm/ebean#2503]
The entities' ManyToMany relations are not saved when the entities are saved. This issue does not appear on version 11.x.x. The framework is used with, is Spring boot v2.5.6.

For Example, there are 2 entities.
```java
class Project extends Model {
  ...
  @ManyToMany
  @JoinTable(name = "project_file_join",
    joinColumns = @JoinColumn(name = "projectId", referencedColumnName = "id"),
    inverseJoinColumns = @JoinColumn(name = "fileId", referencedColumnName = "id")
  )
  private List<File> files;
}

class File extends Model {
  ...
  @ManyToMany(mappedBy = "files")
  private List<Project> projects;
}

```
When the following code is running:
project.files.add(someFile);
project.save();

What is expected is that project.files.size() == 1 and a row insertion in project_file_join table
What happens is  tha project.files.size() == 0 and nothing is added in project_file_join table

**Comment by rbygrave** [comment]
1. Make sure you format the code with triple ` ```java ... ``` ` ... so that we then see use of generics etc
2. `private List files;` should instead be `private List<File> files; `
3. `private List projects;` should instead be `private List<Project> projects;`

Plus:
The test code does not look valid as `project.files` is field access on a private field.  So I'd suggest you change the "following code is running" into an actual failing test that creates the Project instance and populates it etc.

**Comment by rbygrave** [comment]
The thought is that you might need specify cascade persist like `@ManyToMany(cascade=PERSIST)` ... if the expectation is that `someFile` is expected to be persisted.

**Comment by pkalodimas** [comment]
The problem is that no insertions are applied in table `project_file_join`. So the ```java @ManyToMany(cascade=PERSIST)``` will not do anything. I tries it.

**Comment by rbygrave** [comment]
You need to update the test code so that we know what the code is actually doing.  You can't use field access etc so the test code does not yet make sense.

**Comment by rbygrave** [comment]
Even better would be to fork example-minimal - https://github.com/ebean-orm-examples/example-minimal ... and create a failing test case

**Comment by rbygrave** [comment]
I'll close this for now.  Re-open with a failing test case etc.  Thanks, Rob.
