### ISSUE TITLE
Script runner does not work with file system path

### ISSUE THREAD

**Issue by BdN3504** [ebean-orm/ebean#2507]
## Expected behavior
Running [ScriptRunner.run("/path/to/sql/script.sql")](https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/ScriptRunner.java#L26) should work.
## Actual behavior
Execution fails with [IllegalArgumentException("resource is null?");](https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/core/DScriptRunner.java#L54) 
### Steps to reproduce

```kotlin
import io.ebean.Database
class Example (
    private val database: Database
){
    database.script().run("/path/to/sql/script.sql")
}
```
To make use of the Scriptrunner, I have to pass the path as a URL:
```kotlin
    database.script().run(Path.of("/path/to/sql/script.sql").toUri().toURL())
```

**Comment by rbygrave** [comment]
Well, another view is that you are looking for an enhancement request for Scriptrunner such that it has `run(Path path)`.

That is, `.run("/path/to/sql/script.sql")` expects the given string path to be a **_resource path_** and not a file system path.  So in fact it is behaving as intended.

Do you want to have a try at submitting a PR to add support for `run(Path path)` ?

**Comment by BdN3504** [comment]
Ah, sorry I misread the documentation then. So by resource path a path relative to the resources folder is meant, right? I'll see if I can find the time to submit a PR.
