### ISSUE TITLE
Split DBPlatform into multiple platforms

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2514]
IBM provides three different versions of DB2

- DB2 LUW (there is also a docker container available)
- DB2 for I (IBM iSeries / as400)
- DB2 for z/OS

They are slightly different in some sql statements, so the current DB2Platform is split into
 
- `DB2LuwPlatform`
- `DB2ForIPlatform`
- `DB2ZosPlatform`

All of them are supporting table names up to 128 chars. As there are currently only automatic tests for `db2luw`. So `db2fori` and `db2zos` are basicly untested.

There is also a 4th platform `DB2LegacyPlatform` that tries to provide backward compatibility to ebean users, that are already using DB2 with an older db-layout and cannot migrate. Note that this platform tries only to keep db-layout compatibility and may not provide all functionalities. It is recommended to migrate to an other platform

When Ebean starts with DB2 detected ... and no explicit platform choice is made Ebean will fail to start asking you to chose the preferred platform (`db2luw`, `db2fori`, `db2zos` or `db2legacy`).

**Comment by rbygrave** [comment]
Cool, I think we can close this one now.
