### ISSUE TITLE
H2 Array Support seems incomplete

### ISSUE THREAD

**Issue by rvowles** [ebean-orm/ebean#2530]
## Expected behaviour

@DbArray
private List<String> values;

or private Set<Enum> values;

## Actual behaviour

The array is generating as a plain array without a data type, it needs the data type. If I force the data type via column definition it is ignored, if i just use the column definition it fails to serialise (for obvious reasons :-) )

Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table cs_org_member (\000a  id                            uuid not null,\000a  cs_person_id                  uuid,\000a  cs_org_id                     uuid,\000a  roles                         [*]array,\000a  constraint idx_org_members unique (cs_person_id,cs_org_id),\000a  constraint pk_cs_org_member primary key (id)\000a)"; expected "IDENTITY, BIGSERIAL, SERIAL, data type"; SQL statement:
create table cs_org_member (
  id                            uuid not null,
  cs_person_id                  uuid,
  cs_org_id                     uuid,
  roles                         array,
  constraint idx_org_members unique (cs_person_id,cs_org_id),
  constraint pk_cs_org_member primary key (id)
) [42001-210]

### Steps to reproduce

```java
  // some java code
```

```console
  // some logging output
```

**Comment by jonasPoehler** [comment]
Maybe have a look at this change: https://github.com/ebean-orm/ebean/pull/2501/files#diff-a389d3a536380b523de5ecb26e97eda16dc6d9fab4a7be13b93cebdb3cd05b48R24
Support for H2 Version 2 was added just days ago and previous versions of H2 would not disallow arrays without a specific element type.

**Comment by rbygrave** [comment]
To add to the comment from Jonas.

The next version of Ebean 12.15,0 supports H2 2.x and uses H2 2.1.210 via https://github.com/ebean-orm/ebean/pull/2501

There were a number of changes in H2 from 1.4.x to 2.x including array types, sequence syntax and integer type.  I am thinking your app is using H2 2.x (due to all the security vulnerabilities) and that isn't working with existing Ebean. So yes, looking to get Ebean 12.15.0 released shortly.

**Comment by rvowles** [comment]
Ah,  thanks - I looked for an issue around it and didn't find one, so I figured I better raise it :-)

**Comment by rbygrave** [comment]
Just released 12.15.0, should be fixed with that.  Re-open if needed.  

Cheers :)
