### ISSUE TITLE
DB2 reorg table support

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2556]
When tables/columns are altered, you might need a `CALL SYSPROC.ADMIN_CMD ('REORG TABLE ${table} ')` after certain statements (e.g. dropping a column, changing data type, ...)

Ebean currently supports auto-generation of migration scripts, that works well in ~95% of the cases, but not for DB2.
In order to generate also working scripts for DB2, we added a "needsReorg" set, that stores the tables that require a reorg (protoype is here: https://github.com/FOCONIS/ebean/blob/master/ebean-ddl-generator/src/main/java/io/ebeaninternal/dbmigration/ddlgeneration/platform/BaseTableDdl.java#L94)

In short
- you can do as many `alter table`  on the tables (some alter require a reorg, other not)
- you have to do a `reorg table` if you have done an alter, that requires a reorg before
  - adding indices
  - accessing data via index

Unfortunately, ebean currently writes the DDL scripts per column in the following order:

```sql
-- prealter of column1
-- alter table1 colum1
-- reorg table1
-- postalter of column1

-- prealter of column2
-- alter table1 colum2
-- reorg table1
-- postalter of column2

-- create all indices
```

This order is not optimal, because you might need two reorgs. 
So I think it would be a good idea to change the order to write all prealter, alters, reorgs and postalters
```sql
-- prealter of column1
-- prealter of column2
-- alter table1 colum1
-- alter table1 colum2
-- reorg table1
-- postalter of column1
-- postalter of column2

-- create all indices
```
@rbygrave This problem is a bit DB2 specific, what do you generally think about this change?

**Comment by rbygrave** [comment]
Yeah, I'm ok with it.  Noting that ebean-ddl-generator should generally only be a test scope dependency so adding this sort of DB2 specific handling is ok.

**Comment by rbygrave** [comment]
@rPraml I think we can close this now due to #2596
