### ISSUE TITLE
ENH: Support different ColumnDefinition for different database platforms

### ISSUE THREAD

**Issue by NSzemenyei** [ebean-orm/ebean#2559]
Hi @rbygrave ,

with db2 we have the problem, we define columns as ```blob``` (without length):

Java Code:

```java
  public class ReportResult(
  ...
  @Lob
  private File fileContent;
  ...
  )
```

generated init migration:

```java
  create table report_result(
  ...
  file_content      blob,
  ...
  )
```
In this case we can only save a file that is not bigger as 1 MB (default size of db2 blob).
We would like to define the columnDefinition for a field more precise: different length for different platforms.

We would like to create a new annotation (e.g. DbColumn?) which uses the ```javax.persistence.@Column``` as a base and can be defined for every platform different:

```java
  public class ReportResult(
  ...
  @Lob
  @DbColumn(columnDefinition = "blob(64M)", platform = Platfrom.DB2)
  // for all other platforms default generated type
  private File fileContent;
  ...
  )
```

What do you think about it?

**Comment by NSzemenyei** [comment]
I tried to implement the new annotation, but it would be a huge modification. The xmls of the column definitions had to be also modified (list of platform-columnDefinition pairs) and lot of code in ebean.

We designed a new proposed solution which has only small code changes in ebean but it "redefines" the usage of ``` @Column ```. (It's backward compatible)

Example:
```java
 @Column(columnDefinition = "db2;blob(64M);sqlserver,h2;varchar(227);varchar(127)")
  String description;
```
Using the pattern
```java
 @Column(columnDefinition = "PLATFORM1;DEFINITION1;PLATFORM2;DEFINITON2;DEFINITON-DEFAULT")
```

We use semicolon as separator because it's very unlikely that it would be used for column definition.

You can check the ebean code change here: https://github.com/FOCONIS/ebean/commit/3d83c6bd0e2bcca6fc04f73ce08983266b9df636 

What do you think about this?

**Comment by rbygrave** [comment]
I like it - nice approach !!

**Comment by NSzemenyei** [comment]
Thank you! I opened a PR for it: https://github.com/ebean-orm/ebean/pull/2563

**Comment by rbygrave** [comment]
Closing with the merged PR.  Nice work !!
