### ISSUE TITLE
Async local caches may be updated too late

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2592]
In #2590 we wrote a [test](https://github.com/ebean-orm/ebean/pull/2590/files#diff-c17b163a36047c2e56e8f1acfcaa36e127d83b5b627bb52e483a5947e1e88ca3R97), that got wrong test data, when async caches are used

## Expected behavior
1. fetch bean by id with bean cache enabled
2. update the bean
3. fetch bean by id with bean cache enabled again
4. get bean with updated data in step 2

## Actual behavior
1. fetch bean by id with bean cache enabled
2. update the bean
3. fetch bean by id with bean cache enabled again
4. get old bean with same data as in step 1

### Steps to reproduce

See https://github.com/ebean-orm/ebean/pull/2590/files#diff-c17b163a36047c2e56e8f1acfcaa36e127d83b5b627bb52e483a5947e1e88ca3R97

The problem can be fixed by adding some delay between step 2 and 3 or enable foreground cache update.

### General idea

Implement a proxy, that handles the async updates and wait if cache is accessed again.
```java
class AsyncServerCache implements ServerCache {
    private ServerCache delegate; // can be DefaultServerCache or HzCache or ...
    private static int LOCK_SPREAD = 32;
    private Lock[] arrayOfLocks = new Lock[LOCK_SPREAD]; // hold some locks
    
 
   public void get(Object id) {
       Object key = tenantAwareKey.key(id);
       try {
          getLock(key).lock(); // block here, until cache update is executed (or return null)
          return delegate.get(key);
       } finally {
          getLock(key).unlock();
       }
   }


   public void put(Object id, Object value) {
       Object key = tenantAwareKey.key(id); 
       // passing the tenant key, would not require the BackgroundExecutorWrapper
       // we can also remove tenantAwareKey from the HzCache

       getLock(key).lock(); 
       backgroundExecutorWrapper.submit(() -> {
           delegate.put(id, key);
           getLock(key).unlock(); 
      })
   }
  private Lock getLock(Object key) {
       arrayOfLocks[key.hashCode() % LOCK_SPREAD]
  }
}
```
This is a draft and has still some conceptual problems
- a ReentrantLock is lockable multiple times from the same thread (so this might be replaced by a counter or something else)
- We may have a lot of puts in a batch update, this means, we have a lot of runnables in the scheduler

**Comment by rbygrave** [comment]
Well, the design wrt the L2 cache is to **_use and expect "eventual consistency"_** and moving away from "eventual consistency" to being _transitionally read consistent_ suggests that use case should instead to NOT use the L2 cache for that case but instead use the database.

That is, the database provides "transactional read consistency" and trying to emulate that in the L2 cache would involve complexity or compromise - my view is that Ebean does NOT do this - we use L2 cache when we are happy with "eventual consistency" and use the database when we need "transactional read consistency".

The database will do a better job of "transactional read consistency" than anything we would try to do.

**Comment by rbygrave** [comment]
In terms of tests, either have the L2 cache updates occur in the foreground or add sleeps into the foreground - that is the expectation.

**Comment by rPraml** [comment]
I understand, it works as designed. We use foreground updates now and as far as I understand the hazelcast documentation, there are async update options and replication strategies, so that ebean doesn't have to wait until all nodes are in sync.
You can close this issue.

**Comment by rbygrave** [comment]
Yes.  As I see it we are talking about "transactional read consistency" (what databases provide) vs "eventual consistency" (what the Ebean L2 cache provides and is similar to "replication lag").

If we wanted the Ebean L2 cache to have "transactional read consistency" we'd have to use either _Locking_ or _MVCC_ to try and achieve that. As I see it, that is similar to "Ebean L2 Cache trying to be a database" in that both paths to providing "transactional read consistency" are huge efforts with lots of compromises and approximately the size of _"lets create a database"_ (so no we are not going there).  

Instead we say, let the database do the job the database is built to do which is to provide "transactional read consistency".  Let the Ebean L2 cache provide "Eventual consistency only" (similar to replication lag) which is technically simple and often useful but not perfect (just like "replication lag").  For use cases that need "transactional read consistency" we use the database to provide that.

Closing :)
