### ISSUE TITLE
Why properties using Java client encryption can NOT be used in WHERE clauses？

### ISSUE THREAD

**Issue by Coley5** [ebean-orm/ebean#2599]
Given a property with client side encryption like:

```java
@Entity
class User {
  ...
  @Encrypted(dbEncryption = false)
  private String email;

}
```
### Question - Can we use the `eq` operator in a query like:

```java
User user = DB.find(User.class)
  .where()
  .eq("email","[xxxx@xx.xx](mailto:xxxx@xx.xx)")
  .findOne();
```

### Answer - Yes, the query will work

Yes, the above will work, we can use client side encryption properties in where clauses of queries with the `EQ` operator.

The documentation needs updating to more accurately reflect this.

**Comment by Coley5** [comment]
After the account information is encrypted in the account information table, WHAT should I do if I need to query the account information

**Comment by rbygrave** [comment]
Well, the column holds the encrypted value (basically raw bytes).  To use that in a predicate of a WHERE clause when we use client side encryption then ... we would have to bind the encrypted value and that _could_ work but realistically only for the `=` operator.  Other operators like `>`, `<` etc wouldn't really work meaningfully with the encrypted values (raw bytes).

Are you trying to use the `=` operator in a where clause predicate?  What are you trying to do?

In the docs - https://ebean.io/docs/features/encryption ... it says "Properties encrypted with client/application encryption can NOT be used in where and order by clause. " which I think is reasonable _BUT_ if we can obtain the encrypted value in application code we could do a `select ... where my_client_encrypted_column = ?` and bind the encrypted value.

**Comment by Coley5** [comment]
ex:
class User{
     @Encrypted(dbEncryption = false)
     private String email;
     private String password;
}

After encryption, I still want to use the eq query, but I can't use the following query statement

DB.find(User.class)
                    .where()
                    .eq("email","xxxx@xx.xx")
                    .findOne();

**Comment by Coley5** [comment]
Yes, is it possible to provide extended interfaces to encrypted modules？

**Comment by Coley5** [comment]
If I want to make some changes to the source code from a release version, which branch should I choose? 
thanks.

**Comment by rbygrave** [comment]
> is it possible to provide extended interfaces to encrypted modules？

I don't know what you mean. You will need to be more explicit.

>  from a release version, which branch should I choose?

You'll need to create a branch off a tag.

**Comment by rbygrave** [comment]
> After encryption, I still want to use the eq query, but I can't use the following query statement

Actually you can.  See this test case https://github.com/ebean-orm/ebean/blob/master/ebean-test/src/test/java/org/tests/basic/encrypt/TestEncryptClientSide.java#L28 ... those 3 properties use client side encryption.

So for example: 
```
DB.find(User.class)
.where()
.eq("email","[xxxx@xx.xx](mailto:xxxx@xx.xx)")
.findOne();
```
Will work just as you are wanting it to.

**Comment by Coley5** [comment]
I rewrote the ScalarTypeEncryptedWrapper.class some methods in the class, using base64 string to store the encrypted data, can use eq querying encrypted data
```
public class ScalarTypeEncryptedWrapper<T> implements ScalarType<T>, LocalEncryptedType{
      // ...
    @Override
    public Object localEncrypt(Object value) {
        String formatValue = wrapped.format(value);
        byte[] bytes = dataEncryptSupport.encryptObject(formatValue);
        String baseEncodeValue = Base64.getEncoder().encodeToString(bytes);
        return baseEncodeValue.replaceAll("[\\s*\t\n\r]", "");
    }

    @Override
    public T read(DataReader dataReader) throws SQLException {
        String readerString = dataReader.getString();
        if(readerString == null || readerString.length()<1){
            return null;
        }
        readerString = readerString.replaceAll("[\\s*\t\n\r]", "");
        String formattedValue = dataEncryptSupport.decryptObject(Base64.getDecoder().decode(readerString));
        if (formattedValue == null) {
            return null;
        }
        return wrapped.parse(formattedValue);
    }

    @Override
    public void bind(DataBind b, T value) throws SQLException {
        if(value == null){
            b.setNull(byteArrayType.jdbcType);
        }else{
            byte[] encryptedValue = encrypt(value);
            String base64EncryptedValue = Base64.getEncoder().encodeToString(encryptedValue);
            b.setString(base64EncryptedValue);
        }
    }

     // ...
}
```

**Comment by rbygrave** [comment]
I don't know why you are doing that. The encrypted data should stay in bytes and be stored in bytes - **_not_** String / varchar ?  Is this column mapping to varbinary / binary column?

If you provide a failing test case we go from there but as it stands your change does not look correct.

**Comment by Coley5** [comment]
Since the encrypted data in my business scenario still needs to be queried by EQ, the encryption function provided by eBean cannot use EQ query after encryption

**Comment by rbygrave** [comment]
> the encryption function provided by eBean cannot use EQ query after encryption.

Yes it can. This is how the tests pass in **_TestEncryptClientSide_** that was referenced above.  If you have a failing test then you should look to provide the failing test case. You could either look at TestEncryptClientSide and extend it with a failing test case or produce a separate minimal example of a failing test case ... noting that TestEncryptClientSide already effectively does the test you have here.

Have you looked at TestEncryptClientSide?  How is it different to your failing test?

**Comment by rbygrave** [comment]
I'll close this.  I'm fairly sure the issue here was the use of `varchar` db column type instead of `varbinary/binary` db column type.

I have updated the documentation at: https://ebean.io/docs/features/encryption to make it clear that the `eq` operator is allowed with client side encrypted properties.
