### ISSUE TITLE
I can't exclude some entities that don't require querybean generation

### ISSUE THREAD

**Issue by yukunyi** [ebean-orm/ebean#2625]
## Expected behavior
I need the querybean plugin to be able to specify the packages to scan, not all of them.
## Actual behavior
I've tried many ways but can't do it

**Comment by rbygrave** [comment]
We need an explanation of **_why_** this is an issue.  What is the issue/impact of having more query beans generated than is needed.

**Comment by rbygrave** [comment]
Hello @yukunyi ... are you going to provide an update on this?
