### ISSUE TITLE
Add support for Mysql geometry type

### ISSUE THREAD

**Issue by ginger9brain** [ebean-orm/ebean#2668]
It would be nice that ebean supports geometric data types of Mysql 8. 
https://dev.mysql.com/doc/refman/8.0/en/spatial-type-overview.html

**Comment by rbygrave** [comment]
We need JDBC examples for the types showing how they are used via JDBC (PreparedStatement binding), then we could create a module similar to ebean-postgis to supports it.

**Comment by rbygrave** [comment]
Looks like no real interest in this to me.  We need JDBC examples to get started and no one is interested in providing those so I think we should just close this for now.

If someone gets interested they can add a comment and look to re-open this issue etc.
