### ISSUE TITLE
Missing implementation of loadIgnore in ScalarTypePgisBase

### ISSUE THREAD

**Issue by lukas-lt** [ebean-orm/ebean#2670]
## Expected behavior
Increased reader position (reader.incrementPos(1);)
## Actual behavior
Does nothing
### Steps to reproduce
Fetch eagerly a collection of two parent beans having common child bean with field of Point type. You will see that loading second parent bean will fail on loading version because of wrong position of the reader.

**Comment by rbygrave** [comment]
Darn !!  Thanks for spotting that.
