### ISSUE TITLE
Add documentation how to release Ebean in own (non nexus) repository with maven-deploy-plugin

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2680]
## Expected behavior

We need to release ebean and deploy it to our own repository, without "hacks", that we've added to our pom.xml
https://github.com/FOCONIS/ebean/blob/master/pom.xml#L163
This repo is only accessible on our company network and runs https://archiva.apache.org/ as repository manager.
It seems, that it does not work with nexus-staging-maven-plugin, so we need to switch back to maven-deploy-plugin

## Actual behavior

These are the steps we take to build a release

1. As a first step, we add "FOCx" to version number with
`mvn versions:set  -DgenerateBackupPoms=false -DnewVersion=13.6.0-FOC1-SNAPSHOT`
This command already has the problem, that it does not change the version of querybean-generator in `tests/test-java16/pom.xml`
Probably, because this is only for java16 and we use java17 - It's not a big deal, I change that manually.
2. `mvn release:prepare` runs without problems
3. `mvn release:perform` quits with an error in `nexus-staging-maven-plugin`

```
[INFO] [INFO] Inspecting build with total of 49 modules...
[INFO] [INFO] Installing Nexus Staging features:
[INFO] [INFO]   ... total of 48 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
...
[INFO] [ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.12:deploy (injected-nexus-deploy) on project ebean-parent: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.12:deploy failed: Server credentials with ID "ossrh" not found! -> [Help 1]
```
As workaround, I can 
```
cd target/checkout
mvn clean source:jar install org.apache.maven.plugins:maven-deploy-plugin:deploy -DskipTests
```
after that command.

This fails somewhere in "test-java16" with
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-cli) on project test-java16:
Deployment failed: repository element was not specified in the POM inside distributionManagement element or
in -DaltDeploymentRepository=id::layout::url parameter
```
but these are only tests and the rest was deployed sucessfully to the repository.

While I could disable the nexus-staging plugin with these lines in the ebean-agent: https://github.com/FOCONIS/ebean-agent/blob/master/ebean-agent/pom.xml#L147, this seems not to work in ebean itself (maybe I've to add it in each module)
See: https://stackoverflow.com/questions/50509571/replace-nexus-staging-maven-plugin-with-maven-deploy-plugin

Basically what I need is
- either to disable the nexus-staging-maven-plugin in https://github.com/avaje-pom/java11-oss/blob/master/pom.xml#L64 (profile, which is enabled by default or sth)
- or get the plugin working with archiva
- or deploy ebean to maven central (unfortunately, I've no experience, what I need to do that and it seems that we cannot use io.ebean as artifact id - but changing that to de.foconis.ebean or something should be as easy as adding FOCx to the version)
- or get all of our changes into official release ;)

Maybe, you have some tips, what's the best way to proceed here

the version info of maven and java:
```bash
# mvn --version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/apache-maven
Java version: 17.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.10.102.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

**Comment by rbygrave** [comment]
>  disable the nexus-staging-maven-plugin in ...

That would be the easiest option by the looks and seems like the conceptually right thing to do.  Move the plugin under the `release` profile (and maybe that profile should only be renamed to `central` and only activated manually).

**Comment by rbygrave** [comment]
Modified the parent pom such that `nexus-staging-maven-plugin` and `distributionManagement` are now under a "central" profile.  Should resolve this issue.  I'll do a similar change for ebean-agent.

I think that means we can close this.  Re-open if this doesn't work for your case.
