### ISSUE TITLE
After one entity aggregates another entity, replication is unsuccessful

### ISSUE THREAD

**Issue by meloanthony7** [ebean-orm/ebean#2699]
1.The TypeStageData entity aggregates GeoMate
@Setter
@Getter
@Entity
public class TypeStageData implements Serializable {
    public String id;
    public String name;
    public String stage;
    public GeoMate mate;
}

@Setter
@Getter
@Entity
public class GeoMate implements Serializable {

    public String type;
    public Long count;
}
2.The mate property is empty when a custom sql statement is assigned.
entity class="com.rsc.alpha.entity.graphy.TypeStageData"
        <raw-sql name="getCount"
            <column-mapping column="type" property="mate.type"
            <column-mapping column="stage" property="stage"
            <column-mapping column="count" property="mate.count"
            <column-mapping column="dg.id" property="id"
            <column-mapping column="name" property="name"
            <query
                select
                dg.type_id as type,dg.stage_ as stage,count,dg.id,e.name_ as name
                from
                (select distinct count(*)
                over(partition by g.type_id,g.stage_) as count,
                max(g.correlate_id)
                over(partition by g.type_id,g.stage_) as id,
                g.stage_,g.type_id
                from gis_base g where g.correlate_type_=:corType) dg
                left join
                e_submission as e
                on dg.id=e.id
            </query
        </raw-sql
    </entity
3.The java query is as follows.
 List<TypeStageData> list = db.createNamedQuery(TypeStageData.class, "getCount")
            .setParameter("corType", CorrelateTypeEnum.valueOf("DEMAND")).findList();
    
  String s = new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(list);
  System.out.println(s);
4.The results are as follows
[ {
  "id" : "101472745478917",
  "name" : "测试1",
  "stage" : "SUBMIT",
  "mate" : null
}, {
  "id" : "101472745478917",
  "name" : "测试1",
  "stage" : "APPROVE_L1",
  "mate" : null
}, {
  "id" : "101472745478917",
  "name" : "测试1",
  "stage" : "SUBMIT",
  "mate" : null
}, {
  "id" : "101474337180165",
  "name" : "admin2_项目1",
  "stage" : "APPROVE_L2",
  "mate" : null
} ]

**Comment by meloanthony7** [comment]
<column-mapping column="type" property="mate.type"/>
            <column-mapping column="stage" property="stage"/>
            <column-mapping column="count" property="mate.count"/>
            <column-mapping column="dg.id" property="id"/>
            <column-mapping column="name" property="name"/>

**Comment by rbygrave** [comment]
Can you fork https://github.com/ebean-orm-examples/example-minimal ... and create a failing test / reproduce the problem there?

**Comment by rbygrave** [comment]
I'll close this for now.  Re-open when you have a failing test case?
