### ISSUE TITLE
why @TenantId must use io.ebean.annotation.Transactional ?

### ISSUE THREAD

**Issue by liubinduo** [ebean-orm/ebean#2729]
[like question](https://github.com/ebean-orm/ebean/issues/2043#issue-674890789)

**Comment by rbygrave** [comment]
> TenantMode.PARTITION

PARTITION mode could be supported. What that would require is a change to `SpringJdbcTransactionManager` to have `CurrentTenantProvider` like TransactionFactoryTenant ... and for it to obtain the current tenantId and set it to the SpringJdbcTransaction when it is created.

**Comment by rbygrave** [comment]
Like this: https://github.com/ebean-orm/ebean/pull/3368
