### ISSUE TITLE
Migration dropColumn change does not drop the generated foreign key

### ISSUE THREAD

**Issue by geo-m** [ebean-orm/ebean#2735]
## Expected behavior
When removing a column with a reference such as `@OneToOne`, the corresponding foreign key (which was generated because of this column in the first place) should be deleted as well.

## Actual behavior
The column can not be deleted because of the existence of the foreign key.

### Steps to reproduce
1. Create a simple model of two classes with a relationship between them

2. Run the migration code
`DBMigration dbMigration = DBMigration.create();
 dbMigration.setPlatform(...your platform);
 dbMigration.generateMigration();`

3. Remove the relationship column

4. Run another migration

5. Set dbMigration.generatePendingDrop(previous version);

6. Inspect the resulting 1.2_dropsFor_1.1.sql, it should only contain a drop column statement, and not a drop foreign key statement

7. Running the sql with the MigrationRunner or DDLRunner will fail

**Comment by rbygrave** [comment]
Fixed by https://github.com/ebean-orm/ebean/pull/2933
