### ISSUE TITLE
Problems with findSingleAttributeList - queries and oneToMany relations

### ISSUE THREAD

**Issue by AlexWagner** [ebean-orm/ebean#2746]
Hi there.
I added some tests for findSingleAttributeList in Class TestQuerySingleAttribute.
Focus are queries on oneToMany relations (Query on customer, oneToMany-Field: orders.status)

some queries don't work as they produce invalid sql
some queries deliver wrong result

See PR in our fork: https://github.com/FOCONIS/ebean/pull/68

**Comment by rbygrave** [comment]
I'd ask to focus on 1 thing / 1 failing test and generally include an assert on the expected SQL and for a case where the SQL is not what is expected put a comment in for what the invalid SQL produced is.  

Can you pick one failing case and produce a PR for that?

**Comment by rbygrave** [comment]
I think we have resolved those now. I'll close this.
