### ISSUE TITLE
Second fetch inside transaction doubles the fetched @OneToMany rows  when .setLoadBeanCache(false)

### ISSUE THREAD

**Issue by indrekluuk** [ebean-orm/ebean#2748]
## Expected behavior
When fetching the same data again with .setLoadBeanCache(false) then the fetched @OneToMany rows should be the same. These two requests should not affect each other.
## Actual behavior
Fetching the same data again inside a transaction doubles the fetched @OneToMany rows. 

### Steps to reproduce

I added two failing tests to same project I used for the last bug report:
https://github.com/indrekluuk/ebean-fetch-bug

1. 
EbeanFetchTwiceInsideTransactionBugTest.testFetchSameItemTwiceInTransaction_withBeanCache()

I am not actually sure if this first failing test is expected behaviour or a bug.

If some entity is fetched previously then all the future requests ignore all the added fetches to that entity if the same item is requested again.

This test demonstrated why I set .setLoadBeanCache(false) in my project. Because it creates confusing situations where I think data should be fetched but it actually isn't, becase half-fetched item of the same entity is already cached.

3. EbeanFetchTwiceInsideTransactionBugTest.testFetchSameItemTwiceInTransaction_withoutBeanCache()

But when bean cache is disabled then fetching the same data again doubles the fetched @OneToMany rows. My expectation is that if there is no caching then each request should be completly separate. Even if they are inside the same transaction.

**Comment by rbygrave** [comment]
I think you should outline what we are trying to archive here with this use case.  What is the motivation for performing the same query twice here (are we looking to get a fresh copy of the data from the database or some other purpose).

Generally, if we are performing the same query a second time in a transaction [or said differently as - we want to "re-fetch" some entity beans that we have already fetched] we want to use **_"query scoped persistence context"_** - https://ebean.io/docs/query/option#persistenceContextScope  

That is, we want to build a second version of some entity bean(s) that we already have but we desire a "fresh copy" from the database. A query using `.setPersistenceContextScope(QUERY)` will use it's own persistence context (it will not use the _transaction scoped persistence context_ that is scoped with the transaction).

Executing the same query a second time inside a transaction without using `.setPersistenceContextScope(QUERY)` doesn't make much sense in that all those beans are already loaded [the beans are all in the transaction scoped persistence context] so we are somewhat making the database do work (execute the query) for no good reason. It will be important to understand the reason/motivation for executing the query twice here. What were we trying to achieve with the second query?

**Comment by indrekluuk** [comment]
Sometimes I need to save stuff in transaction that are decoupled from each other

For example:
```
  @Transactional
  public void saveSomething() {
    updateOneThing();
    saveAnotherThing();
  }

```
Where updateOneThing() and saveAnotherThing() can also be used as stand alone methods but internally they both fetch some overlapping entities.

---

Couldn't the query automatically ingnore cached entities that have less information fetched than the next query needs?

--- 

I tried and after setting .setPersistenceContextScope(QUERY) it works exaclty as expected. 
Thanks for that!

I will add to application.yaml
```
ebean:
  persistenceContextScope: QUERY
```

Do I understand correctly that ".setLoadBeanCache(false)" is not necessary anymore if persistenceContextScope = QUERY?

The benefit of the request optimization is not worth the cost of the confusion if query fetch is not working as expected.
Specially if updateOneThing() and saveAnotherThing() separately work perfectly but when we put them together then it starts to fail.

**Comment by jnehlmeier** [comment]
> ...they both fetch some overlapping entities

That is interesting. I don't use EBean everywhere in my app, but I do have (JPA) code that loads the same entity type with various `WHERE` conditions and each query batch/join fetching data to save subsequent queries on `getXY` calls. The same database row can be selected in multiple of these queries. This all happens in the same transaction. 

So this would also cause this issue if I would rewrite it using EBean, possibly in JPA mode (no explicit save() calls)?

**Comment by rbygrave** [comment]
>  internally they both fetch some overlapping entities.

Well, the test case was _the same query_ executed twice fetching a toMany path into a List (and I suspect there might be an issue with de-duplication on the "add to list part" for this case - I haven't actually run the test case yet).

Is the actual application code executing the same query twice or is it executing 2 different queries that have overlap? (I'm trying to understand if the test case is representative of the application code).

> if the cached entity contains less information

We need to be careful with the term "cached entity".  There is the persistence context and L2 cache, we should be specific about what it is we are talking about. The persistence context is specifically there to de-duplicate instances (aka "consistent object graph construction" and yes it acts like a cache as a side effect but that is not its core purpose which is to de-duplicate instances).  The L2 cache is truely built for the sole purpose of caching.

I'm thinking you are not using L2 caching at all - do you have any `@Cache` annotation on any of these entities? I'm thinking this is all about the persistence context and understanding what that is, why it's there etc.

> .setLoadBeanCache(false)

If there was no `@Cache` then this didn't do anything at all.  This method is about the use of the L2 cache, and I'm suspecting you are not using the L2 cache.  For example, in the test case code it is meaningless as there is no L2 caching going on there.

**Comment by rbygrave** [comment]
## Definitely a bug here

Running the test, there is some bug related to the `setDisableLazyLoading(true)`.  For example, removing that flag and the test passes.  This is due to something in SqlTreeloadBean.postLoad() related to not setting `ebi.setFullyLoadedBean(true)` (setting setDisableLazyLoading(true) has the odd effect of not setting the fully loaded state on the bean - a bug itself).

Ultimately there is a performance optimisation in SqlTreeLoadManyRoot in the line `manyProp.addBeanToCollectionWithCreate(contextParent, detailBean, load.isContextBean());` ... where it only does the "is already loaded in the collection" check when `load.isContextBean()` is true ... but that isn't true due to upstream issue around `setDisableLazyLoading(true)` messing with  `ebi.setFullyLoadedBean(true)`.

That's a long winded way of saying - **_definately a bug_**.  We can reproduce using `setDisableLazyLoading(true)`. I'm not sure yet if we can hit this same bug it some other way yet (partially loaded bean being reloaded with a collection ... might also reproduce this issue).  

What ebean should be doing: _Do the "is already in collection" check if it's a context bean or we are reloading a partial._

**Comment by indrekluuk** [comment]
The second failing test (EbeanFetchTwiceInsideTransactionBugTest.testFetchSameItemTwiceInTransaction_withoutBeanCache)
that demonstrates that @OneToMany row count doubles in the list was a "request by ID" in our actual code too. Very similar to the test case I constructed.

The actual process was.
1. Created a new invoice document with document rows.
2. Read the document from the database to generate an Excel report.

In this specific case the second request didn't have to be inside the transaction. We moved it out, and the situation was fixed. 
But I reported it as a bug since I thought doubling the rows like that can not be expected behavior.

---

But about the other situation where sub-items were not fetched if the same entity was fetched before.
Yes, I don't have @Cache for table entities. All the table entities only have @Entity and @Table

It was a while back, so I don't remember exactly. It might have been "request by ID," as in the test.
(EbeanFetchTwiceInsideTransactionBugTest.testFetchSameItemTwiceInTransaction_withBeanCache)
Then I was able to fix it by adding ".setLoadBeanCache(false)"

The first test also passes if I add ".setLoadBeanCache(false)" to the requests.

So .setLoadBeanCache(false) does have an affect on the queries even if there is no @Cache on the entities.

**Comment by rbygrave** [comment]
## First bug - .setLoadBeanCache(false) ... sets CacheMode.PUT

The first bug hit here is that `.setLoadBeanCache(false)` actually sets the `CacheMode.PUT` rather than say OFF. 

The effect of this, is to force the query to be executed against the database even though the bean would be found in the persistence context. The test case passes when this is not used because the second query is a findOne by Id, ebean deems it should check the persistence context first, does so, finds the bean and the second query never executes.

**Comment by rbygrave** [comment]
## Second bug - setDisableLazyLoading(true) ... does not set fully loaded state [fully loaded bean scenario]

We can reproduce by having both `.setDisableLazyLoading(true)` and `.setBeanCacheMode(CacheMode.PUT)` (or ON).

The use of `.setBeanCacheMode(CacheMode.PUT)` forces the second query to execute against the database (like a refresh). The `.setDisableLazyLoading(true)` executes a part of the code that will skip setting the fully loaded state.  When the fully loaded state is set then the detail bean doesn't go into Mode.LAZYLOAD_BEAN (and load.isContextBean() is true).

That is, this test case and fix is for the fully loaded bean scenario.  We have a 3rd bug to deal with for the partially loaded bean scenario.   

```java
    try (Transaction txn = DB.beginTransaction()) {
      OMVertex first = DB.find(OMVertex.class)
        .setDisableLazyLoading(true)
        .fetch("related")
        .where().eq("id", master.getId())
        .findOne();

      assertThat(first.getRelated()).hasSize(1);

      OMVertex second = DB.find(OMVertex.class)
        //.setLoadBeanCache(true)
        .setBeanCacheMode(CacheMode.PUT)
        .setDisableLazyLoading(true)
        .fetch("related")
        .where().eq("id", master.getId())
        .findOne();

      assertThat(second.getRelated()).hasSize(1);
    }
```

**Comment by rbygrave** [comment]
## Third bug - partially loaded bean scenario

In this scenario, the first query loads the "detail" bean as a partially loaded bean (not all it's properties will be fetched). This means the second query when it gets to that bean will go into Mode.LAZYLOAD_BEAN.  

The fix here is that `load.isContextBean()` should return true for this case (the second query is 'reloading' a partially loaded bean that was already in the persistence context).

To test this, the first query must only partially load the detail bean.
```java
    try (Transaction txn = DB.beginTransaction()) {
      OMVertex first = DB.find(OMVertex.class)
        .setDisableLazyLoading(true)
        .fetch("related", "name") // load a partially loaded bean
        .where().eq("id", master.getId())
        .findOne();

      assertThat(first.getRelated()).hasSize(1);

      OMVertex second = DB.find(OMVertex.class)
        .setBeanCacheMode(CacheMode.PUT) // force query to hit database
        .setDisableLazyLoading(true)
        .fetch("related")
        .where().eq("id", master.getId())
        .findOne();

      assertThat(second.getRelated()).hasSize(1);
    }
```
