### ISSUE TITLE
notIn(<query>) missing as an option

### ISSUE THREAD

**Issue by rvowles** [ebean-orm/ebean#2771]
## Expected behavior

this should be valid:

    QDbLogin()
      .person.id.notIn(
        QDbPerson().select(QDbPerson.Alias.id).setDistinct(true).memberOf.disabled.isFalse.query()
      ).delete()

but the expr().notIn(_name, query) is not surfaced, whereas it is for isIn. 

Ideally in PBaseValueEqual.java the notIn option for a query should be added I think?

## Actual behavior

Unavailable.

**Comment by rbygrave** [comment]
This was only just added/merged into 13.6.6

via: https://github.com/ebean-orm/ebean/pull/2757

... so should be all good in 13.6.6

**Comment by rvowles** [comment]
Ah, sorry! I did search for an issue, did not search latest code.

**Comment by rbygrave** [comment]
No worries. Yeah, it was a _PR only_ so wouldn't come up in an issue search per say ... which isn't super great really.

Anyway, I'll close this as sorted in 13.6.6.
