### ISSUE TITLE
Ebean should support also IN for local encrypted properties.

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2774]
While the current [documentation ](https://ebean.io/docs/features/encryption) is very clear, that **EQ** (and only EQ) is supported for encrypted properties, I noticed, that **IN** is currently not supported (which is semantically only a concatenation of multiple EQ queries)
So the documentation is right here ;)

I ponder if all exact match queries ("eq","ne","in","notIn") should work for encrypted properties? I see no technical reason, why they should not.

What do you think?

## Expected behavior
```
found = Ebean.find(EBasicEncryptClient.class)
      .where()
      .in("description", "goodbye")
      .in("status", EBasicEncryptClient.Status.TWO)
      .in("dob", today) // <-- throws a Data Conversion error
      .findOne();
```
should work

**Comment by rbygrave** [comment]
The implementation detail for this to do database side (using database functions) probably isn't conducive to _IN_. 

Have you looked at how this could be done with _IN_ (especially on non-Postgres dbs that don't have array binding)?  Everything is doable but my impression is that this would probably be messy implementation wise.
 
Do you need this functionality?

**Comment by rbygrave** [comment]
Oh, are you saying ONLY for client side encryption support this case?

**Comment by rPraml** [comment]
Yes, I meant client side encrypted properties.

I can check, if it will also work with server side encryption.

**Comment by rPraml** [comment]
closed. See #2872
