### ISSUE TITLE
Illegal fetch size when using most recent MariaDB driver

### ISSUE THREAD

**Issue by Wooza** [ebean-orm/ebean#2782]
Using [`setFetchSize(Integer.MIN_VALUE)`](https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/query/CQuery.java#L317) (introduced by #56) is not allowed according to the documentation of [`setFetchSize`](https://docs.oracle.com/en/java/javase/18/docs/api/java.sql/java/sql/Statement.html#setFetchSize(int)):

It seems that older MariaDB drivers (<3.x.x) accepted `Integer.MIN_VALUE` for compatibility reasons, however the new major driver version was apparently rewritten from scratch to closely follow the JDBC specs and thus raises an exception when called with `Integer.MIN_VALUE`.

According to the [documentation](https://mariadb.com/kb/en/about-mariadb-connector-j/#streaming-result-sets) the proper solution is to use `setFetchSize(1)`.
My current workaround is to stick with the older driver but I would really like to update.

**Comment by rbygrave** [comment]
Do you want to submit a PR that bumps the jdbc driver the tests are using for MariaDB ?  (that will then reproduce the problem)
