### ISSUE TITLE
ebean version unknow. When running the springboot packaged application

### ISSUE THREAD

**Issue by lakxtxue** [ebean-orm/ebean#2786]
Hi Rob,

I reported this on google groups, maybe the post got flooded, so I'll post it again here.

I'm using ebean integration with springboot and everything has been fine, but recently I found a small problem, I found the log printed by the console:
ebean version: unknown
This problem only occurs when the application is packaged as a jar package and run.

This is a simple demo to reproduce the problem:

https://github.com/lakxtxue/ebean-version-unknown.git

===============================================================================

After my test, I found that it is normal in version 12.12.0, and the log began to appear in version 12.12.1
ebean version: unknown

**Comment by rbygrave** [comment]
Yes, I did see it but I misunderstood the meaning.

I think you are saying this is broken in 13.6.5 / latest and was introduced in 12.12.1.

**Comment by rbygrave** [comment]
Fix via just suppressing the log message when we can't read it. We don't really care if we can't read it etc.
