### ISSUE TITLE
SQL Anywhere: invalid escape character on like expression

### ISSUE THREAD

**Issue by monaheinz** [ebean-orm/ebean#2798]
## Expected behavior
I want to use the like expression with a sql anywhere database.

## Actual behavior
`javax.persistence.PersistenceException: Query threw SQLException:[Sybase][JDBC Driver][SQL Anywhere]Invalid escape character ''`

```java
  Expression e = Expr.like("column1" "div%");
  query().where().add(e).findList();
```

```console
  javax.persistence.PersistenceException: Query threw SQLException:[Sybase][JDBC Driver][SQL Anywhere]Invalid escape character ''
```

The Expression results in the following SQL where statement:
```sql
where t0.column1like ? escape'' 
```

For default behavior `escape` should be set to `~` or left empty in `SqlAnywherePlatform`
```java
protected String likeClauseRaw = "like ? escape'~'";
```

**Comment by rbygrave** [comment]
Thanks. Gone with the ansi default option of no escape clause (as opposed to escape with ''). Added a test to show the platform differences.
