### ISSUE TITLE
setNestedUseSavepoint act globally and not only for the current transaction level

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [ebean-orm/ebean#2814]
## Expected behavior

When we use `setNestedUseSavepoint`, we expect to have savepoint used only for the code present in the current try-with-ressource transaction.

## Actual behavior

When we use `setNestedUseSavepoint`, it seems that the boolean flag is set on the main outer transaction. Overriding the behavior for caller.

### Steps to reproduce

```java
  public void doSomething() {
     try (Transaction transaction = DB.beginTransaction()) {   -- (2)
        transaction.setNestedUseSavepoint();
        // This is clearly intended to be in a savepoint
        try (Transaction nestedTransaction = DB.beginTransaction()) {
            [... Some persistence code ...]
            
            nestedTransaction.commit();
        }
        
        transaction.commit();
     }
  }
  
  public void main() {
    try (Transaction transaction = DB.beginTransaction()) {   -- (1)
      doSomething();
      
      // We did not expect this transaction to run in nested savepoint
      try (Transaction transaction = DB.beginTransaction()) {
        [... Other code...]
      }
    }
  }
```

Yours faithfully,
LCDP

Edited by Rob: Added (1) and (2)

**Comment by rbygrave** [comment]
> it seems that the boolean flag is set on the main outer transaction

Note that (1) and (2) are effectively have the same underlying transaction.  So (2) will be a SpiTransactionProxy that delegates to the same underlying transaction of (1).  

Hmmm, maybe there is a possible "fix" here by only setting the flag on the proxy ...

**Comment by AntoineDuComptoirDesPharmacies** [comment]
@rbygrave Absolutely agree with you.
And you are right, I was hesitating creating this ticket as a "Bug" or "Feature Request" because the current behavior, even if unexpected, is still logic according to the fact that we are calling `setNestedUseSavepoint` on a proxy of the main transaction.
