### ISSUE TITLE
How to force the ebean master-slave library to read the master library?

### ISSUE THREAD

**Issue by lyhseven** [ebean-orm/ebean#2817]
How to force the ebean master-slave library to read the master library

**Comment by rbygrave** [comment]
I think by "library" you mean "database".

If we create an explicit transaction via database.beginTransaction() ... Then a query executed will use that transaction and that will use the "master database" (or more accurately use the main java.sql.DataSource).

Does that answer your question?  Do you have a code sample to perhaps explain your question better?

**Comment by rbygrave** [comment]
Hi @lyhseven   I'll close this for now.  If you want to clarify the question further then please feel free to reply back and do that etc.
