### ISSUE TITLE
Add code generator to create entity beans from an existing DB schema 

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#284]
Ebean initially have a code generator (2006 so 8+ years old now and not maintained).  

This ticket would be about resurrecting that code generator ... to generate entity beans from DB schema.

The old code can be obtained from:
http://sourceforge.net/projects/ebeanorm/files/ebean/old%20releases/0.9.0/ebean-0.9-all.zip/download

**Comment by rbygrave** [comment]
Right now the priorities are documentation followed by JPA2 mapping support.  So unless there is a lot of demand this issue will not get addressed until after those 2 things (so realistically that is probably 6 months or so away).

**Comment by costa974** [comment]
+1

**Comment by icode** [comment]
+1

**Comment by JunNakamura** [comment]
+1

**Comment by Hassaan-Hassaan** [comment]
+1

**Comment by hofmanndavid** [comment]
+1

**Comment by adewaleafolabi** [comment]
+1

**Comment by rbygrave** [comment]
I see the +1 and thumbs up etc ... but the reality is that I can't see myself doing this work to add this tooling.  

If people really desire this feature then they are welcome to state their case ... or look to sponsor the development ... or contribute the feature themselves.

For me, I don't see this feature being developed and feel it is "false advertising" leaving this ticket open etc. Closing and marking as "won't fix".
