### ISSUE TITLE
How to get the auto-incrementing primary key id of the data just inserted

### ISSUE THREAD

**Issue by xuewenzhang** [ebean-orm/ebean#2846]
### Steps to reproduce

```java
  // some java code
```

```console
  // some logging output
```

**Comment by rbygrave** [comment]
If we have:
```java
Customer customer = new Customer();
customer.set ...
database.save(customer)

// return the auto-increment primary key id
long id = customer.getId();
```
Then we note that we just do `customer.getId()` and than returns the auto-increment value (also known as `Identity`).

If we are using JDBC batch, then it also works. If we try to read the Id property that will automatically trigger a jdbc batch fush(). So the code we see above will work with JDBC batch as well.

The way to **_NOT_** get the auto-increment pk value is to turn it off on the transaction via `transaction.setGetGeneratedKeys(false)`. 

If that does not answer the question can you show some code that explains the question more. 
Thanks.

**Comment by rbygrave** [comment]
I'll close this for now.  You can add more details to the question and reopen if required.
