### ISSUE TITLE
DbMigration for pg create sql diffrent  from mysql

### ISSUE THREAD

**Issue by spinachomes** [ebean-orm/ebean#2848]
## Expected behavior
the audit prepertis are extent from super class,and DbMigration for mysql is:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/24352696/192128772-eedaf7c1-5f41-4cfa-9ec5-a5b61ebca924.png">

## Actual behavior
but for postgres is:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/24352696/192128783-f9a32e84-02ad-450c-b1b3-641b6fe5c5ba.png">

I think the sql for mysql is more suitable for most people

**Comment by rbygrave** [comment]
The Postgres DDL for create table has ordering applied to it based on column type such that it optimizes how Postgres physically stores it.  We actually do care about this Postgres specific detail for tables that get **_really big_**. 

So yeah, its there for that reason.

**Comment by rbygrave** [comment]
I'll close this assuming that this answers the question.
