### ISSUE TITLE
Query beans: UpdateQuery - Add support field aliases when updating, ie. set() methods using type properties

### ISSUE THREAD

**Issue by 107236074** [ebean-orm/ebean#2849]
I hope code like this:
## Expected behavior
    new QReminds().id.in(idList)
                .asUpdate()
                .set(QReminds.Alias.readState, RemindsReadState.READ)
                .update();

## Actual behavior

dont't like this :

    new QReminds().id.in(idList)
                .asUpdate()
                .set("read_state", RemindsReadState.READ)
                .update();

### Steps to reproduce

```java
  // some java code
```

```console
  // some logging output
```

**Comment by spinachomes** [comment]
can use QReminds.Alias.readState.toString()

**Comment by 107236074** [comment]
> can use QReminds.Alias.readState.toString()

yes can use  ,but But this code is not pretty

**Comment by rbygrave** [comment]
This will be supported by the linked PR once it's merged.
