### ISSUE TITLE
@DbArray - improve bind logging, non-null arrays auto bind null to [] so improve bind logging to reflect that

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#2856]
So for non-nullable DbArray like:

- `@DbArray(nullable=false)`
- `@NotNull @DbArray`
- `@Column(nullable=false) @DbArray`

... the behaviour of these is to bind a null value as empty array automatically. **_However,_** the bind logging didn't reflect that so this fix just improves the bind logging for this case so that it better reflects what is actually happening.

**Comment by serg1236** [comment]
@rbygrave is it possible to turn off the automatic binding null values to empty arrays?

**Comment by rbygrave** [comment]
Yes, see the instructions here:
https://github.com/ebean-orm/ebean/issues/2855

At some point in the future we will make it the default behavior.
