### ISSUE TITLE
PersistenceException: RuntimeException: database platform "sqlserver16" is not known?

### ISSUE THREAD

**Issue by PromanSEW** [ebean-orm/ebean#2860]
## Expected behavior

I want to connect to MS SQL Server, and I got error which links to #1340
I created `ebean.properties` with
```properties
ebean.databasePlatformName = "sqlserver16"
```
## Actual behavior
Exception:
```
PersistenceException: RuntimeException: database platform "sqlserver16" is not known?
	at DatabasePlatformFactory.create(DatabasePlatformFactory.java:58)
```

How to fix this error?
I use Play Ebean

**Comment by PromanSEW** [comment]
I tried "sqlserver" and "sqlserver17" also but unsuccessfully

**Comment by rbygrave** [comment]
Which version of Ebean is this?  

If this is a new version of Ebean then check if `ebean-platform-sqlserver` is included as a dependency in the classpath or module-path. It will be included if there is a dependency on `io.ebean:ebean` as that is a composite that includes all the platforms - `ebean-platform-sqlserver`, `ebean-platform-postgres`, `ebean-platform-mysql` etc.


You could look to put a breakpoint into DatabasePlatformFactory and SqlServerPlatformProvider in the locations below and confirm that that are being called.

https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/core/DatabasePlatformFactory.java#L66-L72

https://github.com/ebean-orm/ebean/blob/master/platforms/sqlserver/src/main/java/io/ebean/platform/sqlserver/SqlServerPlatformProvider.java#L21-L23

https://github.com/ebean-orm/ebean/blob/master/platforms/sqlserver/src/main/java/io/ebean/platform/sqlserver/SqlServerPlatformProvider.java#L26-L37

**Comment by PromanSEW** [comment]
I use `io.ebean:ebean:13.10.0` with agent the same version

**Comment by PromanSEW** [comment]
I can try provide repro if you have SQL Server db for test connection

**Comment by rbygrave** [comment]
> if you have SQL Server db for test connection

`ebean-test` via `ebean-test-containers` gives us docker container databases that run SqlServer (and Postgres, MySql, MariaDB, Oracle, Yugabyte, DB2, Hana, Cockroach). 

We can configure its use via application-test properties like: https://ebean.io/docs/database/sqlserver/
We can use it programmatically like: https://ebean.io/docs/database/sqlserver/#starting

So yes, programmatically creating a test database is easy (for anyone using ebean-test-containers).

> I use io.ebean:ebean:13.10.0

So `ebean-platform-sqlserver` should be in the classpath (dependency tree). All that is required is to confirm that by checking the dependency tree and then also confirm that SqlServerPlatformProvider is in fact being service loaded (is there something weird in the classpath preventing SqlServerPlatformProvider from being service loaded).

> I can try provide reproducible case

Cool. Probably a silly question but does this mean you can't attach a debugger? I'm wondering why you are not putting a break point into DatabasePlatformFactory and SqlServerPlatformProvider and stepping through the code- if you did that then you can see for yourself what is happening? Do you have to invoke everything through sbt command line?

**Comment by PromanSEW** [comment]
![debug1](https://user-images.githubusercontent.com/5219866/196598544-ad037878-de30-4e71-8a93-933b0271e453.jpg)
![wtf](https://user-images.githubusercontent.com/5219866/196598559-5e9ca6b7-2e75-4707-98e6-75c6de284d52.jpg)

WTF is going here?

**Comment by PromanSEW** [comment]
OK, I see that quotes are unneeded

**Comment by rbygrave** [comment]
Oh rats !!!
