### ISSUE TITLE
Query Beans: Support more TQProperty's as target value for inRangeWith()

### ISSUE THREAD

**Issue by jnehlmeier** [ebean-orm/ebean#2873]
## Expected behavior

```java
new QEntity()
  .name.eq("test")
  .spec.validFrom.inRangeWith(QEntity.Alias.spec.validTo, QEntity.Alias.someDate)
  .findList();
```

## Actual behavior

`raw()` is required, which isn't type-safe.

```java
new QEntity()
  .name.eq("test")
  .raw("spec.validFrom <= someDate AND (spec.validTo > someDate OR spec.validTo IS NULL)")
  .findList();
```

This issue does not just exist for `inRangeWith` but with nearly all comparison methods. Whenever you need to compare something you have joined, you need to fallback and use `raw()`.

**Comment by rbygrave** [comment]
I think this makes more sense with **_someDate_** as the initial property like:

```java
var e = QEntity.alias();

new QEntity()
  .name.eq("test")
  .someDate.inRangeWith(e.spec.validFrom, e.spec.validTo)
  .findList();
```

Hmmm.

**Comment by rbygrave** [comment]
Ok, I went with `.someDate.inRangeWith(e.spec.validFrom, e.spec.validTo)`  ... as I think that will make better sense.  Hopefully that is a good call as I'm keen to release soon.
