### ISSUE TITLE
Encryption support is limited to Varchars and Dates

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2878]
Currently, there is only support for
- varchars
- dates

Ebean is prepared to encrypt also timestamps, but there is no code, that initalizes [timestampEncryptFunction](https://github.com/ebean-orm/ebean/search?q=timestampEncryptFunction)

This does not match to the documentation : (See https://ebean.io/docs/features/encryption supported types)

There is currently NO support for `int` or `Integer`

@rbygrave this is currently not an issue for us, but should be mentioned/corrected in the documentation

**Comment by rbygrave** [comment]
Can you update the documentation for me?

**Comment by rbygrave** [comment]
Docs updated, will close for now then.
