### ISSUE TITLE
Encryption does not work on primitives

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2879]
While writing tests for #2774 I found some bugs/issues in `@Encrypted`
## Expected behavior
```java
  @Encrypted(dbLength = 20)
  private int myInt;
```
should work

## Actual behavior
NPE in https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/deploy/parse/AnnotationFields.java#L389
The problem is, that the property has not yet a scalarType here, because it is invoked with `null` here and the correct scalarType is set too late.
```
    if (propertyType.isEnum() || propertyType.isPrimitive()) {
      return new DeployBeanProperty(desc, propertyType, null, null);
    }
```

### Workaround

Use `Integer` - nevertheless, this does also not work. See #2878

@rbygrave this is also not an issue for us, so feel free to close this, if you do not plan to work on encryption support the next time

**Comment by rbygrave** [comment]
Closing, See #2878
