### ISSUE TITLE
test entities don't get enhanced after upgrade to 13.6.5

### ISSUE THREAD

**Issue by Incanus3** [ebean-orm/ebean#2889]
Sorry to bother again, but after resolving #2888 we encountered another problem with the upgrade to 13.6.5.

## Expected behavior

enhance test entities correctly

## Actual behavior

`DatabaseFactory.create()` call fails with `BeanNotEnhancedException`

### Steps to reproduce

* I've created (acually reused again) a minimal repo with a simple test to reproduce this problem - https://github.com/Incanus3/ebean-test/blob/main/ea/db/src/test/kotlin/cz/sentica/qwazar/ea/db/TestEntityEnhancementTest.kt
* this test uses an entity defined not in the `main` source root, but in the `test` one

### Notes

* this used to work for us correctly (as opposed to `testFixtures`, which never seemed to work) up till the version 13.6.4, but after upgrading to 13.6.5 (and kotlin 1.7) the test entity no longer gets enhanced
* this actually works when using kotlin 1.6
* same as for #2888 this works when ebean enhancement is enabled in idea, but doesn't work through gradle plugin only
* I've tried to add the `kaptTest` line here https://github.com/Incanus3/ebean-test/blob/main/ea/db/build.gradle.kts#L21 even though this wasn't needed before, but I thought it might be
* I've increased the ebean debug level to 5 (as suggested by @jnehlmeier in the previous issue) and compared the compilation output - it seems that after the upgrade, no classes from the `test` source root (except for the generated `_Ebean$ModuleInfo`) are even considered for enhancement any more

**Comment by Incanus3** [comment]
just for completeness, the query beans and `_Ebean$ModuleInfo` seem to be generated correctly and the `entity-packages` value in `ebean-generated-info.mf` is also correct. it's only the entity enhancement itself that seems broken.

**Comment by Incanus3** [comment]
maybe I found the source of the problem - shouldn't this line https://github.com/ebean-orm-tools/ebean-gradle-plugin/blob/master/src/main/groovy/io/ebean/gradle/EnhancePlugin.groovy#L112 also check for `'compileTestKotlin'`? that would explain why this works with kotlin 1.6, because there the task still subclasses `AbstractCompile`.

**Comment by Incanus3** [comment]
btw the fact that `compileTestFixtures(Java|Kotlin|...)` isn't in `supportedCompilerTasks` (and the kotlin variant also in the check mentioned in my previous comment) also explains why enhancement doesn't work for test fixtures, right?

**Comment by Incanus3** [comment]
I checked this by adding the ebean-gradle-plugin to my local buildSrc and making the aforementioned change there and it indeed fixes the problem. This can be seen in this branch https://github.com/Incanus3/ebean-test/compare/main...fix-test-fixture-enhancement-locally and specifically this commit https://github.com/Incanus3/ebean-test/commit/d6bba453576fb3420d1eb2f4249d5d750eb9b2b1, which fixes the test

**Comment by Incanus3** [comment]
I have also opened a PR here https://github.com/ebean-orm-tools/ebean-gradle-plugin/pull/34

**Comment by jnehlmeier** [comment]
Yes that seems to be the reason. Generally the Gradle plugin needs some love to support configuration avoidance and to make it iterate through all source sets to configure them (then `java-text-fixture` plugin would have worked).

**Comment by Incanus3** [comment]
ok, so is there anything else I can do at this stage, or is my PR acceptable as it is for now?

**Comment by Incanus3** [comment]
btw before this gets fixed and released in upstream, is it ok if I temporarily add the plugin source code to our (commercial) project's buildSrc, or does that somehow break the licensing laws? I'll of course keep the license file there, but I don't see any authoring comments in the source files.

**Comment by rbygrave** [comment]
> is it ok if I temporarily add the plugin source code to our (commercial) project's buildSrc

Yes you can, its standard Apache2 license and yes you can copy and redistribute source with the usual Apache2 license restrictions on copyright, patent, etc.
https://github.com/ebean-orm-tools/ebean-gradle-plugin/blob/master/LICENSE

In a similar way of thinking you can have and maintain your own private fork or public fork.

**Comment by Incanus3** [comment]
ok, thanks for the reply. and I see you've already merged my PR, so thanks again. btw, do you already have some timeline for the 13.10.2 release?

**Comment by rbygrave** [comment]
Fixed with ebean-gradle-plugin 13.10.2 via https://github.com/ebean-orm-tools/ebean-gradle-plugin/pull/34

**Comment by rbygrave** [comment]
> timeline for the 13.10.2 release?

Just released. Should be in central in about 15 minutes.

**Comment by Incanus3** [comment]
you're amazing. just upgraded and everything works like a charm. the local buildSrc copy of the patched plugin didn't even make it to master ;). also appreciate the platforms added to the BOM. thanks again so much for the great work you're doing.

**Comment by rbygrave** [comment]
Thanks. It's great to get positive feedback and know that people appreciate the work that goes into this project.

Cheers, Rob.
