### ISSUE TITLE
Environment parameter to control data seeding

### ISSUE THREAD

**Issue by strat1971** [ebean-orm/ebean#2892]
### Discussed in https://github.com/ebean-orm/ebean/discussions/2891

<div type='discussions-op-text'>

<sup>Originally posted by **strat1971** November 17, 2022</sup>
Hi Rob
I am migrating an ebean setup from version 11. It was setting a placeholder name value pair in the DbMigrationConfig which would then be passed the environment name to a repeatable migration stored procedure to control which data is inserted for testing. Now that DbMigrationConfig is gone I can't do that. How would you recommend doing that in version 12?</div>

**Comment by strat1971** [comment]
Update: I am now upgrading to 13.10.1.

**Comment by rbygrave** [comment]
The properties ultimately end up in `io.ebean.migration.MigrationConfig` which is part of the ebean-migration module.
https://github.com/ebean-orm/ebean-migration/blob/master/ebean-migration/src/main/java/io/ebean/migration/MigrationConfig.java#L20-L21

If MigrationConfig is not being configured explicitly in application code it will be automatically configured by "ebean-migration-auto" (`io.ebean.migration.auto.AutoMigrationRunner`) which will call the `load(Properties)` method and get to https://github.com/ebean-orm/ebean-migration/blob/master/ebean-migration/src/main/java/io/ebean/migration/MigrationConfig.java#L477

Refer to ebean DefaultServer which does this:
https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java#L310-L326

And this is how the properties are read: https://github.com/ebean-orm/ebean-migration/blob/master/ebean-migration/src/main/java/io/ebean/migration/MigrationConfig.java#L504-L514

So I'd expect you'll have something like:
 `ebean.migration.placeholders=a=1;b=2;c=foo`

**Comment by rbygrave** [comment]
ok cool, closing.
