### ISSUE TITLE
IDE Plugin support for VS Code?

### ISSUE THREAD

**Issue by luoxiaopeng** [ebean-orm/ebean#2901]
There is only a Ebean Enhancement 11 plugin for Java in VS Code plugin market, 
after install this plugin, run/build is working, but write code without IDE prompt.
I miss some import packages? Any support for VS Code? Thank you.

**Comment by rbygrave** [comment]
Where is the source code for that plugin?
Have we contacted the author of that plugin about it's maintenance?  
Does the author want to contribute that plugin to be more officially part of Ebean?

**Comment by rbygrave** [comment]
The source for this plugin is at: https://github.com/Shabirmean/vscode-ebean-enhancement-ext

This project appears to have **_no license specified_**. Probably the first thing is to contact the owner of that project and ask if they can specify a license that is applied to that plugin. Depending on the license someone might be interested to take a closer look at it and see if it can be updated.

**Comment by luoxiaopeng** [comment]
OK, Thank you for you reply, I will try to look into this plugin sourcecode.

**Comment by rbygrave** [comment]
Ok. Note that I have logged a ticket with that project to see if they will apply an open source licence to it such that others can look to fork and maintain it.

I think we can close this issue for now.
