### ISSUE TITLE
How to fetch property with @Basic(fetch = FetchType.LAZY)

### ISSUE THREAD

**Issue by spinachomes** [ebean-orm/ebean#2913]
## Expected behavior
can fetch the basic lazy field in select sql
## Actual behavior
get an error
### Steps to reproduce

```java
    new QProcessApply().setId(id).fetch("applyJson").findOne();

    @Column(nullable = false)
    @DbJsonB
    @Basic(fetch = FetchType.LAZY)
    private ObjectNode applyJson;

```

```console
  javax.persistence.PersistenceException: Invalid path applyJson
```

**Comment by rbygrave** [comment]
Use .select("applyJson") rather than fetch().

The reason being that the applyJson property is at the root level here. We use fetch() when the property path is a ManyToOne, OneToMany, ManyToMany, OneToOne.

**Comment by spinachomes** [comment]
thanks
