### ISSUE TITLE
Support jakarta.persistence.Entity / Spring Boot 3 ?  [Refer to linked discussion]

### ISSUE THREAD

**Issue by luoxiaopeng** [ebean-orm/ebean#2920]
I create a gradle project with SpringBoot 3.x,  I find ebean only scan javax.persistence.Entity，not scan jakarta.persistence.Entity.
When I use jakarta.persistence.Entity, DbMigration will say no changes detected, and querybean will not generate this QXXXEntity.
source code: https://github.com/luoxiaopeng/test_ebean.git

Is this right?

**Comment by luoxiaopeng** [comment]
I find spring-data-rest 3.x not support javax, and ebean not support jakarta.
so I back to spring boot 2.x

**Comment by rbygrave** [comment]
Refer to the discussion at: https://github.com/ebean-orm/ebean/discussions/2839

>  not scan jakarta.persistence.Entity

Note that `jakarta.persistence` is not relevant as that is dependency of Ebean and not spring boot 3. Ebean will continue to use `javax.persistence` with spring boot 3 and that will not be an issue.

**_However_**, **_JAXB is a real issue_** as discussed at https://github.com/ebean-orm/ebean/discussions/2839

**Comment by rbygrave** [comment]
@luoxiaopeng - If you could add a comment to that discussion on what you plans are with Spring Boot 3 in terms of timeframe etc plus whether you have looked at the JAXB dependencies in the applications you are looking to migrate to Spring Boot 3.

Feedback there would be useful in terms of when we look to deal with the JAXB issue.

Thanks, Rob.

**Comment by rbygrave** [comment]
I'll close this for now. Discussion continuing at https://github.com/ebean-orm/ebean/discussions/2839

**Comment by rbygrave** [comment]
I'll re-open this, with the view that people might see it and head off to the discussion and add comments there.
