### ISSUE TITLE
querying by `@Convert`ed properties doesn't seem to work

### ISSUE THREAD

**Issue by Incanus3** [ebean-orm/ebean#2944]
I have an `@Entity` with a property of our domain `Address` type that should be serialized to string when written to db and deserialized when read from it. I tried to use the `@Converter` and `@Convert` annotations along with a custom-defined converter (tried both `javax.persistence.AttributeConverter` and `io.ebean.config.ScalarTypeConverter`), but when I try to run a query with a where condition for this field, I get the "class cz.sentica.qwazar.domain.Address cannot be cast to class io.ebean.bean.EntityBean" error from `findList()`

## Expected behavior
I think the query builder should run the object given to it through the domain-to-db mapping method (`convertToDatabaseColumn` for `AttributeConverter`, `unwrapValue` for `ScalarTypeConverter`) and use that in the sql.

## Actual behavior
ebean tries to cast the domain object into `EntityBean` in `io.ebeaninternal.server.expression.SimpleExpression.addBindValues` and (obviously) fails.

### Steps to reproduce

```kotlin
// the converters

@Converter
class AddressConverter : AttributeConverter<Address, String> {
    override fun convertToDatabaseColumn(attribute: Address): String = attribute.serialize()
    override fun convertToEntityAttribute(dbData: String): Address = Address.parse(dbData)
}

// OR

@Converter
class AddressConverter : ScalarTypeConverter<Address, String> {
    override fun getNullValue(): Address = NULL_ADDRESS
    override fun unwrapValue(beanType: Address?) = (beanType ?: nullValue).serialize()
    override fun wrapValue(scalarType: String?) = scalarType?.let { Address.parse(it) } ?: nullValue
}

// the entity

@Entity
class DatabaseAuditTrace(
    @Id
    override var gid: String = "",

    @Convert(converter = AddressConverter::class)
    override var resource: Address = NULL_ADDRESS,
}

// the query

QDatabaseAuditTrace(database).where().resource.equalTo(address).findList()
```

```console
class cz.sentica.qwazar.domain.Address cannot be cast to class io.ebean.bean.EntityBean (cz.sentica.qwazar.domain.Address and io.ebean.bean.EntityBean are in unnamed module of loader 'app')
java.lang.ClassCastException: class cz.sentica.qwazar.domain.Address cannot be cast to class io.ebean.bean.EntityBean (cz.sentica.qwazar.domain.Address and io.ebean.bean.EntityBean are in unnamed module of loader 'app')
	at io.ebeaninternal.server.expression.SimpleExpression.addBindValues(SimpleExpression.java:76)
	at io.ebeaninternal.server.expression.DefaultExpressionList.addBindValues(DefaultExpressionList.java:640)
	at io.ebeaninternal.server.expression.DefaultExpressionRequest.<init>(DefaultExpressionRequest.java:37)
	at io.ebeaninternal.server.query.CQueryPredicates.prepare(CQueryPredicates.java:195)
	at io.ebeaninternal.server.query.CQueryBuilder.buildQuery(CQueryBuilder.java:332)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:338)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:123)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:406)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1410)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1389)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1485)
	at io.ebean.typequery.TQRootBean.findList(TQRootBean.java:1641)
	at cz.sentica.qwazar.auditing.repositories.DatabaseTraceRepository.findAllByResource(DatabaseTraceRepository.kt:55)
	at cz.sentica.qwazar.auditing.services.DatabaseAuditService.makeTrace(DatabaseAuditService.kt:53)
```

Is there some additional step I need to do to be able to use the domain object in a query, or is this an unexpected behavior?

**Comment by Incanus3** [comment]
I would also understand if the generated `QDatabaseAuditTrace.resource` query attribute was of a string type and I'd have to serialize the `Address` I'm giving to it myself, but that's also not the case.

**Comment by Incanus3** [comment]
BTW we're using ebean version 13.10.2, I can try to upgrade if this is something that changed recently.

**Comment by rbygrave** [comment]
The querybean generator produces in generated-sources a class called `EbeanEntityRegister`. In the source code for that class we should see a method called `otherClasses()` and that will have the list of AttributeConverters that it has found and that will be registered with Ebean.

In the ebean-querybean tests we have 3 AttributeConverter and the generated code looks like:

```java
@Generated("io.ebean.querybean.generator")
@ModuleInfo(...)
public class EbeanEntityRegister implements EntityClassRegister {

  /**
   * Register AttributeConverter etc
   */
  private List<Class<?>> otherClasses() {
    List<Class<?>> others = new ArrayList<>();
    others.add(org.example.domain.otherpackage.GenericTypeAttributeConverter.class);
    others.add(org.example.domain.otherpackage.PhoneAttributeConverter.class);
    others.add(org.example.domain.otherpackage.ValidEmailAttributeConverter.class);
    return others;
  }

  /**
   * Entities with no @DbName
   */
  private List<Class<?>> defaultEntityClasses() {
    List<Class<?>> entities = new ArrayList<>();
    entities.add(org.example.domain.ACat.class);
    entities.add(org.example.domain.ADog.class);
    ...

```

**Comment by rbygrave** [comment]
The test that performs the query using the attribute converter value is:
https://github.com/ebean-orm/ebean/blob/master/ebean-querybean/src/test/java/org/querytest/QCustomerTest.java#L855-L864

I suspect `AddressConverter` is not being registered with ebean, and so I suspect when we look at the generated `EbeanEntityRegister.otherClasses()` method we will not see `AddressConverter.class` there.

If that is the case, then the question is why is the `AddressConverter.class` not there.

**Comment by rbygrave** [comment]
If the converter in the same project as `DatabaseAuditTrace` and compiled along with `DatabaseAuditTrace`  then the querybean-generator should find it and add it into the generated `otherClasses()` method. If not then we need to register the converter with ebean explicitly via `DatabaseConfig.addClass()`

**Comment by Incanus3** [comment]
Hi, yeah, the converter is in the same project, I just tested and it does appear in `EntityBeanRegister.otherClasses()`.

**Comment by rbygrave** [comment]
Are you able to put it into an example project so that I can run / debug it to see why the AttributeConverter is not getting registered? 

 e.g. Create a fork/PR of https://github.com/ebean-orm-examples/example-minimal that I can clone and run

**Comment by Incanus3** [comment]
Yeah, I'll definitely try that.

**Comment by Incanus3** [comment]
ok, I've moved the relevant code to a testing repo and wrote a test for the reported behavior, but it works correctly in the report. I've also updated ebean in the mean time, so I guess there are two possibilities here - either the ebean upgrade fixed the issue, or it's something specific to our project's setup. I'll try this in our project with updated ebean and if it still fails there, I'll try to isolate the problem there. thanks for your patience.

**Comment by Incanus3** [comment]
Ok, I managed to isolate this problem from our project pretty well, [here](https://github.com/Incanus3/qwazar-test-conversion) is the repo. the offending test is [here](https://github.com/Incanus3/qwazar-test-conversion/blob/main/backend-apps/auditing/src/test/kotlin/cz/sentica/qwazar/auditing/DatabaseAuditTraceAddressConversionTest.kt). I've also created another entity without conversion and a passing test for it [here](https://github.com/Incanus3/qwazar-test-conversion/blob/main/backend-apps/auditing/src/test/kotlin/cz/sentica/qwazar/auditing/EntityWithoutConversionTest.kt) to make sure there is no bigger problem with the configuration.

**Comment by rbygrave** [comment]
WRT the second issue I don't see that Database [null] was not found? anymore but instead have:

```
Caused by: cz.sentica.qwazar.auditing.address.Address$CouldNotBeParsed: Artifact:test/Test could not be parsed as Address: resource type Artifact must have 2 identifier segments
	at app//cz.sentica.qwazar.auditing.address.Address$Companion.parse(Definitions.kt:103)
	at app//cz.sentica.qwazar.auditing.models.AddressConverter.convertToEntityAttribute(DatabaseAuditTrace.kt:12)
	at app//cz.sentica.qwazar.auditing.models.AddressConverter.convertToEntityAttribute(DatabaseAuditTrace.kt:9)
	at app//io.ebeaninternal.server.type.AttributeConverterAdapter.wrapValue(AttributeConverterAdapter.java:35)
	at app//io.ebeaninternal.server.type.ScalarTypeWrapper.read(ScalarTypeWrapper.java:128)
	at app//io.ebeaninternal.server.deploy.BeanProperty.readSet(BeanProperty.java:536)
	... 104 more
```

**Comment by rbygrave** [comment]
Using an identifier of `"foo.Test"` rather than `"Test"` and all the tests pass fine (when the AddressConverter is registered).

**Comment by rbygrave** [comment]
The `Database [null] was not found?` was being thrown because ... the resourceAddress was not being treated correctly as a ScalarType, and hence was not loaded properly from the database, and then `println(reloaded.resourceAddress)` invokes lazy loading, and that fails because ... in `TestAuditingPersistenceConfiguration` we have `isDefaultServer = false`.

That is a ebean `null` database name is synonymous with the ebean "default server" ... and that wasn't registered.  Registering that by removing the `isDefaultServer = false` and we get a more reasonable error when the AttributeConverter isn't registered.

I'll look to improve that error message when the ebean default server is not registered.

**Comment by Incanus3** [comment]
@rbygrave thanks a lot for you're investigation, improvements you did to make these mistakes easier to find, and your hard work on this great tool in general. I had no idea the converters have to be included in the `DatabaseConfig.classes` list, but I guess it does make sense. I just did the fixes you described (sorry about the Address parsing error, since I got stuck on the converter problem, I missed this issue) and can confirm that it does indeed fix the tests. We're actually not using the `classes` configuration attribute in production (we use `packages` instead), but we are using it in some tests, because in some of them, for some reason, if we use `packages` the test entities don't get enhanced or registered (I don't really remember now). I'll probably try to isolate that problem and create an issue for it as well, when I got some spare time, but it's not really bugging us that much.
Once again, many thanks and great respect for your work.

**Comment by rbygrave** [comment]
> `classes` configuration attribute in production (we use `packages` instead)

Yes, note that we generally want to move away from using `packages` as that results in some class path scanning and we prefer the more explicit approach and no scanning (faster, more efficient, more compatible with anyone wanting to use Graal native image).

For applications using query beans, a side effect of that is that it generates the `EbeanEntityRegister` with the entity classes and attribute adapters listed explicitly - it does this with the view that we can use this and not have to manually list them all ourselves or use class path scanning at all so we really want this to work well. 

That is, for applications using query beans we should not have to specify `packages` or `classes` at all.

**_However_**, I see in [DatabaseConfig.isAutoLoadModule()](https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java#L3402-L3404) that we currently _ONLY_ load these classes from the generated `EbeanEntityRegister` when `classes.isEmpty()` and we should remove that condition.

If that `classes.isEmpty()` check was not there, then the AttributeConverter would have been registered and we would not have hit this issue in the first place.

This PR - https://github.com/ebean-orm/ebean/pull/2995 will add the change such that ebean would instead **_combine_** the classes registered via the generated `EbeanEntityRegister` and the explicitly registered ones.  We need to use DatabaseConfig.setLoadModuleInfo(false); to not load and register the classes from the generated `EbeanEntityRegister`.


> can confirm that it does indeed fix the tests.

Great. We can look to close this issue then. #2995 has a behaviour change so I think we need a minor version bump to merge that.


> thanks a lot for you're investigation, improvements ... this great tool in general

Thanks a lot for that.  It isn't always easy and I really appreciate the feedback.


Cheers, Rob.

**Comment by Incanus3** [comment]
Hi,
I'm a bit confused by your last response. At the beginning you say

> note that we generally want to move away from using `packages` ... and we prefer the more explicit approach and no scanning

from which I'd assume we should be using `classes` instead of `packages`, but then you say

> for applications using query beans we should not have to specify `packages` or `classes` at all

how would that work, if I don't specify either, but you don't want to do class path scanning? or do you mean that the `classes` configuration would be generated automatically at compile (or rather kapt) time? I haven't tried right now, but at least in the past, if we set `isDefaultServer = false` (which we need to, since we have more than one `Database`), and didn't specify either, it didn't register the entities.

**Comment by rbygrave** [comment]
> classes configuration would be generated automatically at compile (or rather kapt) time?

Yes. It's in the generated `EbeanEntityRegister.java`

> which we need to, since we have more than one Database

The expectation is that we'd be using `@DbName` on the entities that are specific to a database.  See https://ebean.io/docs/multi-database/

Those docs look like they need improvement, but the generated `EbeanEntityRegister.java` handles multiple named databases. So add the `@DbName` and look at the generated code. This also impacts the query bean generation to use the "named databases"- meaning we can use the default constructor on the query beans and use the appropriate named database (and not have to use the constructor that takes a Database instance).

**Comment by Incanus3** [comment]
we are using the `@DbName` annotation on all our entities, but we still had problems when neither `classes`, nor `packages` were specified. this was with ebean 12 though, so I'll try again and let you know, if I have any problems. thanks for your patience and have a nice day.
