### ISSUE TITLE
Add support for specifying select clause of RawSQL query

### ISSUE THREAD

**Issue by buchtajz** [ebean-orm/ebean#2946]
# Rob Edit:

This is NOT a bug, Ebean never supported specifying a select clause on a RawSql query.

This is a change adding support for specifying the select clause on RawSql. The side-effect of this change is that `findCount` will look to produce different sql than before by only including the Id column/property in the select clause - it will only do this IF the Id column/property is mapped in the RawSql query and otherwise should produce the same query as before.

-----------

## Expected behavior

query.select().asDto() working as in older ebean version (we was used 11.x)

## Actual behavior
query.select().asDto()   ignores select parameter and returned entity is query basic class instead of Dto class

final sql query is 

`select id, name, anniversary, city from (select c.id ...`

should be 
`select count(1) as count, sum(id) as sum from (select c.id ...`

### Steps to reproduce
We dynamically create Report java classes based on user specified SQL query.
So I simplify it to this example RawQuery.

```java
    RawSql rawSql = RawSqlBuilder.parse("select id, name, anniversary, city from (select c.id, c.name, c.anniversary, a.city from o_customer c left join o_address a ON a.id = c.billing_address_id order by c.id) w").create();

    var query = DB.find(SampleReport.class);
    query.setRawSql(rawSql);
    query.setMaxRows(10);

    List<SampleReport> list = query.findList(); // this returns 4 rows, ok works fine
    assertNotNull(list);

    String sumSql = "COUNT(1)::Long AS count, SUM(id) AS sum";

    //query.select(sumSql);   // tried both versions
    query.select(FetchGroup.of(SampleReport.class, sumSql));
    query.asDto(QuerySumResponse.class);

    var countSum = query.findOneOrEmpty().orElseThrow();
    // generates exception, see bellow

    // commented for compile error due class conflict
    //assertThat((countSum instanceof QuerySumResponse));  

```

```console
  javax.persistence.NonUniqueResultException: Unique expecting 0 or 1 results but got 4
```

**Comment by buchtajz** [comment]
Unit test pull request
[https://github.com/ebean-orm/ebean/pull/2947](https://github.com/ebean-orm/ebean/pull/2947)

**Comment by rbygrave** [comment]
Can you tell me exactly which version of Ebean 11.x that this worked in?

**Comment by buchtajz** [comment]
Hi, 11.17.5 worked

**Comment by buchtajz** [comment]
Hi, we used forked 11.17.2-SNAPSHOT with some patches. I found a patch for this issue created before my contract begin.

I changed #2947 to include this patch.

**Comment by rbygrave** [comment]
> we used forked 11.17.2-SNAPSHOT with some patches.

Ok. So Ebean never did support specifying the select() on a RawSql query.  The support for this only existed in a forked version of ebean (and I'm pretty confident that they didn't ever try to contribute that back into Ebean).

Is that right? 

If so then we need to start by understanding the problem or getting some understanding of why this isn't a DtoQuery.

**Comment by buchtajz** [comment]
> Ok. So Ebean never did support specifying the select() on a RawSql query. The support for this only existed in a forked version of ebean (and I'm pretty confident that they didn't ever try to contribute that back into Ebean).
> 
> Is that right?

Yes. It looks like ebean never did support select on RawSQL. And now we switch to actual Ebean version, a try to contribute.

> 
> If so then we need to start by understanding the problem or getting some understanding of why this isn't a DtoQuery.
I describe it inaccurately. asDto alone works well, but there is problem with select() - so then asDto() can't work.

When you look to pull request #2947, there is patch adding select() support for RawSQL. And with this patch, asDto works.

It looks like this patch breaks some other test with RawSQL and findCount(). But the function is not broken, i thing.

```
java.lang.AssertionError: 
Expecting actual:
  "select count(*) from ( select id from o_order o ); --bind() --micros(126)"
to start with:
  "select count(*) from ( select o.id, o.order_date, o.ship_date from o_order o"
```

**Comment by rbygrave** [comment]
PR for this - https://github.com/ebean-orm/ebean/pull/2996

**Comment by rbygrave** [comment]
I have changed the title and edited the description to better describe what is going on here:
- Adding a new feature where we can specify the select clause on RawSql query
- Change in behaviour of findCount on a RawSql query when the Id property is mapped (query only includes the Id property/column)
