### ISSUE TITLE
[ebean-test] - Default ebean.test.registerTestTenantProvider = false ... by default not auto register a test TenantProvider

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#2968]
Prior to this change the default was for ebean-test to automatically register a `CurrentTenantProvider` to use for testing. The issue with this is that some features like L2 cache work slightly differently with multi-tenant use / when a `CurrentTenantProvider` is used.

The better default for ebean-test is to NOT automatically register a `CurrentTenantProvider` and instead for multi-tenant applications to enable this explicitly via:

#### application-test.properties
```properties
ebean.test.registerTestTenantProvider=true
```  

or 

#### application-test.yaml
```yaml
ebean:
  test:
    registerTestTenantProvider: true
```

**Comment by rvowles** [comment]
@rob-bygrave the documentation still says that this is automatically registered by default, as does the UserContext class itself, do you want a PR to update the documentation in the appropriate places?

**Comment by rob-bygrave** [comment]
Yeah, I'd love a PR @rvowles
