### ISSUE TITLE
@ElementCollection does not use batched lazy loading

### ISSUE THREAD

**Issue by GithubUser8080** [ebean-orm/ebean#2973]
Creating a model such as

```
Item {
  @ElementCollection
  List<String> aliases;
}
```

And fetching a list of Item using Query::findList, then accessing .getAliases(), Ebean loads each item with a new query, instead of batching and using IN according to the way it works with OneToMany relationships

**Comment by rbygrave** [comment]
This is not the case, element collection uses the same batch lazy loading mechanism as ToMany collections.  

A test that covers this is: https://github.com/ebean-orm/ebean/blob/master/ebean-test/src/test/java/org/tests/model/elementcollection/TestElementCollectionBasicSet.java#L58-L63

You could review that test or provide a complete test that shows the issue. Note that a good way to do that is to provide a PR / Branch from  https://github.com/ebean-orm-examples/example-minimal

**Comment by rbygrave** [comment]
I'll close this for now.  Re-open it or add a comment and we can look at it further.  Thanks.
