### ISSUE TITLE
Can I get get sql from QUser? / DB2 LUW 9.7 support for the eq. of limit/offset

### ISSUE THREAD

**Issue by sola1tmy** [ebean-orm/ebean#3016]
## Which platform and version do I use
I'm using db2 9.7 LUW, and 13.15.2

## Main question
Now I want to make a pageRequest.The generated sql **fetch next 10 rows only** is not work in this version of db2.
I know support for old version is alway not a good idea.
So I'm trying to make an expression to do pagination, I tried this

```
    val subQuery = QUser().generatedSql
    DB.findNative(QUser::class.java, 
         """
             select * from ( 
                 select row_number() over() rn, a.* from ($subQuery)  a)
             ) where a rn<=10 and rn >0
         """
    )
```
Of course it doesn't work, because the doc said generatedSql will only available after execute.
So is there any other way to make the query easier.

**Comment by sola1tmy** [comment]
I test some in out test environment.There has two issues now.
1. In db2luw9 this code can't work, so the pull request now need some edit
```
select row_number() over() rn, a.* from (select * from foo) a where rn > 10
```
below can work.
```
select * from (select row_number() over() rn, a * from (select * from foo) a) where rn > 10
```

2. I have change the code as the second way, so that it can make query well.But mapping become error,  all value went to next field, so I guess **rn** should be int the end.

I will try more these days. And if need, I will make a pull request.

**Comment by rbygrave** [comment]
I have merged https://github.com/ebean-orm/ebean/pull/3017 into master and will be in the next release. I'll close this issue. Open a new issue if required.
