### ISSUE TITLE
Postgis with cache is not working

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [ebean-orm/ebean#3026]
## Expected behavior
I have class with Postgis fields:
```java
public class Robot {
    @Column(name = "id", unique = true, nullable = false)
    private long id;
    ...
    @Column(name = "position") @Basic(fetch = FetchType.EAGER)
    private Point position;
    ...
}
```
when I load this bean by Id (second time):
```java
private Database db;

db.find(Robot.class, id);
```
`position` field is null but it is present in database.

## Actual behavior
Column/field in database with valid not null value is returned as `null` if queried for second time (from cache).

### Steps to reproduce
Start Ebean with enabled cache (default) and get something from database with postgis Point value that is not null.
For the first time it will return valid (not null) value.
For the second time it will return null because of Ebean cache.

I tried to find what is wrong by debugging, but it seems that call:
```
DefaultServer.findId:1028
DefaultServer.find:930
DefaultServer.find:920
```
returns bean from cache without filled `position` value `DefaultServer`:
```java
  private <T> T findId(Query<T> query, @Nullable Transaction transaction) {
    SpiQuery<T> spiQuery = (SpiQuery<T>) query;
    spiQuery.setType(Type.BEAN);
    if (SpiQuery.Mode.NORMAL == spiQuery.getMode() && !spiQuery.isForceHitDatabase()) {
      // See if we can skip doing the fetch completely by getting the bean from the
      // persistence context or the bean cache
      T bean = findIdCheckPersistenceContextAndCache(transaction, spiQuery, spiQuery.getId());
      if (bean != null) {
        return bean;
      }
    }
```
Ebean returns bean from `findIdCheckPersistenceContextAndCache`.

I checked `DefaultServerCache` and it show position as null:
![image](https://user-images.githubusercontent.com/7201935/231700740-3ba18323-153a-441a-a4ec-62690302b692.png)

I also checked put call to cache `DefaultServerCache.java`:
```java
  @Override
  public void put(Object key, Object value) {
    map.put(key, new SoftReference<>(new CacheEntry(key, value)));
    putCount.increment();
    if (mutationCounter.incrementAndGet() > trimOnPut) {
      runEviction();
    }
  }
```
and data that is put here is **always** without `position` field (`position==null`):
![image](https://user-images.githubusercontent.com/7201935/231704389-5ffd28f0-521d-4b8d-9d40-4182ddec7d52.png)

![image](https://user-images.githubusercontent.com/7201935/231704479-8719e6d5-1c93-45fb-9655-a51094edf493.png)

It seems that `CachedBeanDataFromBean.extract` is not processing PostGIS value.
```java
    final boolean dirty = ebi.isDirty();
    for (BeanProperty prop : desc.propertiesNonMany()) {
      if (dirty && ebi.isDirtyProperty(prop.propertyIndex())) {
        data.put(prop.name(), prop.getCacheDataValueOrig(ebi));
      } else if (ebi.isLoadedProperty(prop.propertyIndex())) {
        data.put(prop.name(), prop.getCacheDataValue(bean)); // This returns null for not null value
      }
    }
```
`BeanProperty.cacheDataConvert` for not null Postgis Point value returns null:
```java
  private Object cacheDataConvert(Object value) {
    if (value == null || scalarType.binary()) {
      return value;
    } else {
      // convert to string as an optimisation for java object serialisation
      return scalarType.format(value);
    }
  }
```
`scalarType` is `ScalarTypePgisPoint` and `ScalarTypePgisBase.formatValue` function is:
```java
  @Override
  public String formatValue(T value) {
    return null;
  }
```
and this is the problem.

Not sure if `ScalarTypePgisBase.binary()` should be set to `true` or this issue requires to implement `formatValue` and `parse` in  `ScalarTypePgisBase`.

When I disable cache:
```java
conf.setDisableL2Cache(true);
```
then this does not occurs.

**Comment by rob-bygrave** [comment]
`formatValue()` should probably return the WKT string value rather than null.  Do you want to try doing that?

**Comment by Ryszard-Trojnacki** [comment]
>Do you want to try doing that?
Sure. I will prepare pull request in the next week.
