### ISSUE TITLE
Ebean generating too many transactions

### ISSUE THREAD

**Issue by sjaanus** [ebean-orm/ebean#3061]
Using Play farmework 2.7 and Ebean plugin version 5.0.2, that should put me on Ebean 11.39.x.

Ebean is generating me 10s of transactions ending like this.

```
....
where t0.id = any(Array[10]={230430,230431,230432,230433,230434,230435,230436,230437,230438,230439});
where t0.id = any(Array[10]={230440,230441,230442,230443,230444,230445,230446,230447,230448,230449});
where t0.id = any(Array[10]={230450,230451,230452,230453,230454,230455,230456,230457,230458,230459});
where t0.id = any(Array[10]={230460,230461,230462,230463,230464,230465,230466,230467,230468,230469});
where t0.id = any(Array[10]={230470,230471,230472,230473,230474,230475,230476,230477,230478,230479});
...
```

I have set up configuration like following, but still batch size 10 items as one transaction. Do I need to configure something else?

```
public class EbeanStartupConfig implements ServerConfigStartup {
	public void onStart(ServerConfig serverConfig) {
		serverConfig.setQueryBatchSize(100);
	        serverConfig.setDatabaseSequenceBatchSize(100);
		serverConfig.setLazyLoadBatchSize(100);
	}
}

**Comment by rbygrave** [comment]
> 10s of transactions 

Note that terminology wise these are **queries** and not **transactions**

> serverConfig.setLazyLoadBatchSize(100);

It looks like these queries are lazy loading queries - we can't be 100% sure of that without more information.  You could confirm that by increasing the "Summary" logging for `io.ebean.SUM` to `TRACE` which would log the type of query (+lazy, +query etc).

Assuming these are lazy loading queries then `serverConfig.setLazyLoadBatchSize(100);` should have increased the batch size to 100 from 10.  The other option is to change the query to eagerly fetch this path that is being lazy loaded.

> Ebean 11.x

Ideally you have some plan in place to upgrade to a later version of Ebean.

**Comment by sjaanus** [comment]
I was using transactions, because of `txn` keyword I thought they are being ran in a transaction.

```
[debug] 2023-05-19 20:27 io.ebean.SQL - txn[4574] select t0.id, t0.name, ...... where t0.id = any(?); --bind(Array[10]={230311,230312,230313,230314,230315,230316,...})
[debug] 2023-05-19 20:27 io.ebean.SUM - txn[4574] FindMany mode[+lazy] type[PeriodMeter] origin[Djkzk-.A.A] lazyLoadProp[meterType] load[path:meters.null batch:10] exeMicros[262] rows[10] predicates[t0.id = any(?)] bind[Array[10]={230311,230312,230313,230314,230315,230316,...}]
[debug] 2023-05-19 20:27 io.ebean.SQL - txn[4575] select t0.id, t0.name,.... where t0.id = any(?); --bind(Array[10]={230321,230322,230323,230324,230325,230326,...})
[debug] 2023-05-19 20:27 io.ebean.SUM - txn[4575] FindMany mode[+lazy] type[PeriodMeter] origin[Djkzk-.A.A] lazyLoadProp[meterType] load[path:meters.null batch:10] exeMicros[270] rows[10] predicates[t0.id = any(?)] bind[Array[10]={230321,230322,230323,230324,230325,230326,...}]
```

This is with extra logs.

**Comment by rob-bygrave** [comment]
> `mode[+lazy]`

So yes this is lazy loading

> `lazyLoadProp[meterType]`

The lazy loading was triggered by treading the meterType property.

You could look to modify the query to fetch the meterType property - so fetching it eagerly rather than lazily.

**Comment by sjaanus** [comment]
@rob-bygrave 
I'm facing an issue where I have tens of different queries, and I want to avoid fetching them eagerly all the time due to the significant amount of rework involved.

My goal is to optimize the batch size increase, but I'm wondering if it's possible that I might be unintentionally modifying a parallel configuration object that my connection is not utilizing? Is there possiility to verify the configuration I am changing is the one ebean is using?

**Comment by rob-bygrave** [comment]
>  unintentionally modifying a parallel configuration object that my connection is not utilizing

I don't think so.  The configuration change that is above looks like the correct change.

Were you able to debug this [probably via using a debugger and adding in break points] and find out why a batch size of 10 was still being used?

**Comment by rbygrave** [comment]
No update on this?  I'll close this for now, if we get an update we can reopen and further investigate perhaps.
