### ISSUE TITLE
Can I disable Ebean's enhancement check?

### ISSUE THREAD

**Issue by zacker330** [ebean-orm/ebean#3105]
## Expected behavior
Use Ebean  with Bazel. 

## Actual behavior

When I use Ebean, then compile the codes, I got:
```
io.ebean.config.BeanNotEnhancedException: Bean class com.example.incident.IncidentPriority is not enhanced? Check packages specified in ebean.mf.
```

I notice that the enhancemant of Ebean tools is for enhancing entity's query function. But I don't use this function. Can I disable Ebean's enhancement check?

Thanks.

**Comment by rob-bygrave** [comment]
> Can I disable Ebean's enhancement check?

No, in that Ebean uses enhancement for the entity beans as well.  It does this to support dirty checking and lazy loading on entity beans.


Applications can use the ebean agent to perform the enhancement at runtime using `-javaagent` command line.

With IntelliJ plugin, it adds the `-javaagent` option to the command line.  See the images at: https://ebean.io/docs/getting-started/intellij-idea

`-javaagent:/home/rob/.ebean/ebean-agent-13.19.0.jar`

**Comment by zacker330** [comment]
> > Can I disable Ebean's enhancement check?
> 
> No, in that Ebean uses enhancement for the entity beans as well. It does this to support dirty checking and lazy loading on entity beans.
> 
> Applications can use the ebean agent to perform the enhancement at runtime using `-javaagent` command line.
> 
> With IntelliJ plugin, it adds the `-javaagent` option to the command line. See the images at: https://ebean.io/docs/getting-started/intellij-idea
> 
> `-javaagent:/home/rob/.ebean/ebean-agent-13.19.0.jar`

Thanks very much.
