### ISSUE TITLE
after build success，The location of ebean-generated-info.mf is wrong

### ISSUE THREAD

**Issue by ruizhang81** [ebean-orm/ebean#3139]
i have a springboot project
<img width="402" alt="image" src="https://github.com/ebean-orm/ebean/assets/3723124/0e66a075-7d33-4bbd-bd68-7a8b9f9df011">

api project is  boot project like this
<img width="879" alt="image" src="https://github.com/ebean-orm/ebean/assets/3723124/7616e84d-ad49-4900-af20-c3eb2dd95541">

bean project has many Entities
<img width="716" alt="image" src="https://github.com/ebean-orm/ebean/assets/3723124/a5010d80-bd38-488d-85b9-300d6bc198b2">

after build success,the ebean-generated-info.mf file in there
<img width="635" alt="image" src="https://github.com/ebean-orm/ebean/assets/3723124/b69c7e4a-e43c-4b5a-88e5-81c185f0411c">

I think the ebean-generated-info.mf file should be here
<img width="359" alt="image" src="https://github.com/ebean-orm/ebean/assets/3723124/b7667b30-6805-41e4-bdbf-12794f6ae666">

**Comment by rbygrave** [comment]
No, I think it is where it should be.

The entity beans are in the `bean` module and not the `api` module.  So the ebean generated code is **_also_** in the `bean` module and hence it ends up in the bean-1.0.0.jar.

So no, I think it is exactly in the correct place.

**Comment by ruizhang81** [comment]
thanks
