### ISSUE TITLE
EBean 12 not following the cascade hierarchy during delete

### ISSUE THREAD

**Issue by tbee** [ebean-orm/ebean#3185]
We have the following setup of 4 entities with cascade ALL:

```java
@Entity
@Table(name = "jw_beschikking")
public class Beschikking {
    @OneToMany(mappedBy = "beschikking", cascade = CascadeType.ALL)
    private Set<ProductToegewezen> toegewezenProducten;
}

@Entity
@Table(name = "jw_product_toegewezen")
public class ProductToegewezen  {
    @OneToMany(mappedBy = "toegewezenProduct", cascade = CascadeType.ALL)
    private Set<MeldingAanvangProduct> meldingenAanvangProduct;

    @OneToMany(mappedBy = "toegewezenProduct", cascade = CascadeType.ALL)
    private Set<MutatieProduct> mutatiesProduct;
}

@Entity
@Table(name = "jw_melding_aanvang_product")
public class MeldingAanvangProduct { }

@Entity
@Table(name = "jw_mutatie_product")
public class MutatieProduct { }
```

## Expected behavior

```java
DB.delete(beschikking)
```

On EBean 7 this results in the following delete statements:

```sql
delete from jw_melding_aanvang_product where (productToegewezenObjectId) in (?)
delete from jw_mutatie_product where (productToegewezenObjectId) in (?)
delete from jw_product_toegewezen where objectId  in (?) 
delete from jw_beschikking where objectId=? and version=?
```

These delete statements follow the cascade ALL correctly, bottom up, making sure no foreign keys cause problems. Perfect.

## Actual behavior
On EBean 12 the following delete statements are seen:

```sql
delete from jw_melding_aanvang_product where objectId=?
delete from jw_product_toegewezen where objectId=?
```

The  jw_mutatie_product is missing and thus the database causes problems. This is in exactly the same code base, only the EBean 7 statements are "sed"ed into their EBean 12 equivalents.

If the collections in ProductToegewezen are swapped in order in the source, it's the other table in the delete statement. 

As always there is more to it; complex code is happening, some more legal than others. But it works under EBean 7, so something has changed / is optimized in EBean 12 to make it not follow the cascade all hierarchy. It would be nice to get some pointers where to look.

**Comment by rbygrave** [comment]
The mapping all looks as expected, and yes I'd expect the same 4 delete statements.

Are you able to clone or fork https://github.com/ebean-orm-examples/example-minimal ... and put a test case in there that reproduces the issue?

Probably looking to see if it reproduces against latest 13.x first and go from there.

**Comment by rbygrave** [comment]
I've created a branch in example-minimal with this model (I think) - https://github.com/ebean-orm-examples/example-minimal/pull/12/files

It does not reproduce against latest 13.x master branch.

**Comment by rbygrave** [comment]
FYI: I modified the version in the pom testing 12.1.1, 12.8.0 and 12.16.1 ... and they all passed the test.  (With 12.1.1 the query bean code needed to be commented out).

So maybe check that branch and see if that is somehow different to the use case you have.

**Comment by tbee** [comment]
I expect EBean to work correctly on the minimal example, it is something in our surrounding code that causes this. So that is why the question is: has there anything noteworthy changed in EBean between 7 and 12 (can't get to 13 yet because of java version) that is related to this behavior where we should look at? 

In the meantime I'm going to try and remove stuff to see if I can find what makes this happen.

**Comment by tbee** [comment]
It seems (we need to investigate deeper) that the request are processed in batch, one of the entities persists a new one (formally not allowed - I know), which triggers batch processing again. But this picks up the original batch. So if delete 1 was done, 2 is busy, creates a new entity, processing of the batch continues at position 3 causing the skipped delete.

**Comment by rbygrave** [comment]
Just to say, that an option is to turn off cascade on the transaction  `Transaction.setPersistCascade(false)` and perform all the deletes explicitly in code (traverse the graph and perform the deletes in the correct order explicitly in code).

It might not be a good idea for the use case here but just throwing it out there as an option.

**Comment by tbee** [comment]
It turns out to be a bit more subtle; in the PreDelete of the number 2 delete, the bean prepares the audit record. It needs to populate that with data and as such it lazy loads a date. This triggers abatchFlush. So it is not the persist.

**Comment by rbygrave** [comment]
Just a thought, on the transaction, there is the option to turn off flushOnQuery.  So you could check turning that on.

**Comment by tbee** [comment]
Since we are in a container managed transaction setting (WildFly), configuring individual transactions is problematic.

**Comment by tbee** [comment]
We temporarily have a custom JtaTransactionManager until we can upgrade to EBean 13. It appears setting this on a newly created JtaTransaction solves the issue:

```java
        newTrans.setBatchMode(false);
        newTrans.setBatchOnCascade(false);
```

It would be nice if this is possible in EBean's standard JtaTransactionManager somehow. I'll try and see what this will do in the larger testset.

**Comment by tbee** [comment]
An EBean JdbcTransaction has one BatchControl instance. If the transaction is flushed, and within processing that flush a second flush call is made, how should it deal with that? 

I feel that it should should not reflush the original batch. So when flushing, should the BatchControl maybe be replaced with a new instance? Or some other kind of logic marking what is already being flushed.

**Comment by rbygrave** [comment]
>  If the transaction is flushed, and within processing that flush a second flush call is made, how should it deal with that?

With version 13.21.0 there is this change in BatchControl https://github.com/ebean-orm/ebean/pull/3148 ... which uses `transaction.setFlushOnQuery(false);` and then resets it back to the original value. So this prevents a flush() getting invoked during a flush().

Not sure if that is the exact same issue but it sounds really similar. Perhaps you could try applying the same change to the 12.x version you are using via a patch and see if that fixes it.

**Comment by rbygrave** [comment]
> NB2: setFlushOnQuery(false) does not work in our case, because at some point the audit record is persisted and that still triggers the second flush.

So we might need a failing test for this then. See if it fails on 13.x and then we can ponder how that can apply to 12.x.

**Comment by tbee** [comment]
I've got this patched for now. We're totally planning on upgrading to EBean 13 once we upgrade Java to 11+. I would suggest to pick this up then. That will make fixing this much easier.

**Comment by rbygrave** [comment]
Ok cool. May as well close this for now then.

**Comment by tbee** [comment]
We're trying to upgrade to EB14 and it seems this issue is still present. I'll create a new one to not confuse things.
