### ISSUE TITLE
MetricsAsJson produces incorrect JSON (=does not quote special characters)

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#3209]
## Expected behavior

When collecting metrics with `collectMetrics().asJson()` I expect that a valid json is returned

## Actual behavior

We have a raw query:
```java
setRaw("json_field = replace(json_field , '\"type\":\"Foo\"', '\"type\":\"Bar\"')").update()
```
in our application. The query itself is irrelevant, only the fact, that it contains `"` is important here

### Steps to reproduce

The SQL is appended without quoting here
https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/meta/MetricsAsJson.java#L149
and results in a metric json that looks like this
```json
   "sql" : "update table set json_field = replace(json_field , '"type":"Foo"', '"type":"Bar"')"
```
which is invalid.

We need some quoting and I'm thinking about what would be the easiest or most efficient way.
- do a bunch of replaces (`str.replace("\\", "\\\\").replace("\"", "\\\"").replace("\b", "\\b").replace("\f", "\\f").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t");`)
- delegate to a Json-libary
- port [Escape.java](https://github.com/avaje/avaje-jsonb/blob/main/jsonb/src/main/java/io/avaje/jsonb/stream/Escape.java) from avaje-jsonb or similar

**Comment by rbygrave** [comment]
We can go with using string replace for now. This can be replaced with avaje-jsonb later on.
