### ISSUE TITLE
Ebean-generated Elasticsearch Query Lacks Support for Nested Fields in @DocStore Models

### ISSUE THREAD

**Issue by kristinnsnaer** [ebean-orm/ebean#3219]
## Expected behavior

When performing a full-text search on nested fields in Elasticsearch using Ebean's query language for a model with @DocStore and has a field marked with the `@DocEmbedded` annotation, Ebean should generate an Elasticsearch query that uses the `nested` query type to search within the nested fields.

```json
{
  "track_total_hits": true,
  "size": 9,
  "sort": [
    {
      "whenCreated": {
        "order": "desc"
      }
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "nested": {
            "path": "inputFieldValues",
            "query": {
              "bool": {
                "must": [
                  {
                    "simple_query_string": {
                      "query": "john",
                      "fields": ["inputFieldValues.value"]
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```

## Actual behavior

Ebean's generated Elasticsearch query does not use the `nested` query type, leading to inaccurate search results since Elasticsearch nested fields require special querying.

```json
{
  "track_total_hits": true,
  "size": 9,
  "sort": [
    {
      "whenCreated": {
        "order": "desc"
      }
    }
  ],
  "query": {
    "bool": {
      "should": [
        {
          "simple_query_string": {
            "query": "hí",
            "fields": [
              "inputFieldValues.value"
            ],
            "default_operator": "and"
          }
        }
      ]
    }
  }
}
```

### Steps to reproduce
Given to be using ElasticSearch with Ebean

1. Mark a model with `@DocStore`
2. Mark a field in that model that is OneToMany with a `@DocEmbedded` annotation for a nested field.
2. Use the following Ebean Kotlin code to query for a specific string within the nested field.

```java
val textMatch = TextSimple()
    .fields("inputFieldValues.value")
    .opAnd();
QDPass()
     .text()
     .textSimple(query, textMatch);
```

3. Observe the generated Elasticsearch query.

Is there something I'm missing here?
If there is no solution and as I've seen that Ebean is dropping the ElasticSearch integration can I do the Elastic request manually and map it to the entity?

**Comment by rbygrave** [comment]
Did you look into the code to see how you could do this?  Any luck there?

**Comment by rbygrave** [comment]
Let's close this for now and re-open it when you come back with some comments and feedback.
