### ISSUE TITLE
Updating from ebean 13.6.5 to a version > 13.18.0 Breaks

### ISSUE THREAD

**Issue by Brian-Hofmann** [ebean-orm/ebean#3226]
I'm in the process of updating ebean in my Spring project. Whenever I run my project with a version later than 13.18.0, I get the following error when I run a where clause:

```java
NoSuchMethodError: "pathToQueryBean".setProfileLocation(io.ebean.ProfileLocation)
```

which is called from one of the generated Query Beans.

The java line looks something like this:

```java
    return new QMyEntity().where().list.contains(item).findOneOrEmpty();
```

I noticed in the release notes going to 3.19.0 that some methods from the ProfileLocation class were removed since they were deprecated. Perhaps this had something to do with it since 3.18.0 works fine in my application.

Was there a new way to configure the DB in the 3.19+ versions? I am using the DatabaseConfig class.

Extra info:
Java 11
Spring 2.7.16

## Expected behavior
The project runs without errors when calling a Query Bean where clause

## Actual behavior
There is a NoSuchMethodError

### Steps to reproduce
Load an ebean version greater than 3.18.0 in a Java Spring project. Run a query similar to the one above.

Thanks in advance for your help!

**Comment by rbygrave** [comment]
> NoSuchMethodError: "pathToQueryBean".setProfileLocation(io.ebean.ProfileLocation)

Was the enhancement ebean-agent / ebean-maven-plugin / ebean maven tile updated at the same time?

See https://ebean.io/docs/getting-started/maven

**Comment by Brian-Hofmann** [comment]
Yes I am using that plugin. It is also at 13.22.0

![image](https://github.com/ebean-orm/ebean/assets/37916393/e5e037e0-728e-49a8-bbc1-2f118079b231)

**Comment by rob-bygrave** [comment]
Is there explicit `ebean.mf` manifest file in src/main/resources ?  

Are you able to git clone  https://github.com/ebean-orm-examples/example-minimal and `mvn clean verify` that project ?

Are you then able to bump that example-minimal that latest ebean version and `mvn clean verify`?

**Comment by Brian-Hofmann** [comment]
There is no ebean.mf file there but I will try cloning the minimal repo

**Comment by Brian-Hofmann** [comment]
Ah figured it out! Checking for the ebean.mf file got me looking for cached files. Looks like the intelliJ generated ".idea" folder had a cached version of the "ebean-plugin.xml" file which was set to the old 13.6.5 version. It must have not updated that file despite my maven cleans and plugin update. I deleted the file and reran a clean install which populated the correct plugin file in .idea folder. That got it to work.
