### ISSUE TITLE
Query Bean Generator Generates Non-Compilable Code When Entity Uses @Embeddable Inner Class For Primary Key Type

### ISSUE THREAD

**Issue by raphaelNguyen** [ebean-orm/ebean#3234]
## Expected behavior
Generated query bean should compile when `@Entity` class uses `@Embeddable` inner class for primary key.

## Actual behavior
When generating the query bean for entities that use `@Embeddable` inner class for primary keys (e.g. `embedded.example.OrderItem` with embeddable primary key class `embedded.example.OrderItem.Key`), it generates the following non-compilable code.
 * A `Q<ENTITY_NAME>$<EMBEDDABLE_CLASS_NAME>` class is generated for the embeddable primary key class but this class is not referenced by any of the generated code (e.g. `QOrderItem$Key.java` is generated under the package path `query` for class `Key`).
 * The generated `query.Q<ENTITY_NAME>` class references a non-existent `Q<EMBEDDABLE_CLASS_NAME>` class without an import clause possibly expecting it to be in the same package (e.g. `query.QOrderItem` refers to the class `QKey`)

### Steps to reproduce
ebean version: `13.22.1`
Please refer to example project https://github.com/integrated-application-development/query-bean-generator-issue.

**Comment by rbygrave** [comment]
404 page not found for the link above.

**Comment by rbygrave** [comment]
Need to see how this is different from https://github.com/ebean-orm/ebean/blob/master/ebean-querybean/src/test/java/org/example/domain/MyInner.java#L14-L35

**Comment by raphaelNguyen** [comment]
Hi @rbygrave. My apologies. I created the repo in private mode and forgot to make it public after I posted the issue. Please try again now.

I've taken a look at the inner class example you gave and the only difference I can see is that I have a single if field of the inner type which I annotated with `@EmbeddedId` while you have 2 fields annotated with `@Id`.

Is the example the preferred way to model primary key in ebean?

**Comment by rbygrave** [comment]
Yeah cool. I have reproduced it and fixed it. Thanks !!

**Comment by rbygrave** [comment]
> Is the example the preferred way to model primary key in ebean?

I would not say that its not preferred but pretty close to 50/50 with no major advantages for either style as I see it.

**Comment by raphaelNguyen** [comment]
Thanks @rbygrave for the quick fix!
