### ISSUE TITLE
QueryBeans: Entities can not have same name as some Ebean API classes

### ISSUE THREAD

**Issue by jnehlmeier** [ebean-orm/ebean#3251]
## Expected behavior

Code should compile

## Actual behavior

Compile error

### Steps to reproduce

```java
@Entity
public class Transaction {
  @Id long id;
}
```

```console
public final class QTransaction extends TQRootBean<Transaction,QTransaction>

class myEntities.Transaction collides with interface io.ebean.Transaction
```
- Class `myEntities.Transaction` is imported because of `TQRootBean`.
- Interface `io.ebean.Transaction` is imported because of generated constructor `QTransaction(Transaction transaction)` to use a given transaction.

Either ebean API types or user types should be referenced full qualified without import statements in generated code.

**Comment by jnehlmeier** [comment]
I just tried latest ebean and noticed that in generated `Q` classes still some ebean packages are imported.

If I create an entity named `TQRootBean` or `TQAssocBean` the generated code is broken. For example Entity `TQRootBean` would generate:
```
import entities.TQRootBean;
import io.ebean.typequery.TQRootBean;

public final class QTQRootBean extends TQRootBean<TQRootBean,QTQRootBean>
```

**Comment by rbygrave** [comment]
Refer to https://github.com/ebean-orm/ebean/pull/3280 for removing the use of imports for `TQRootBean`
