### ISSUE TITLE
Static inner embeddable class breaks query bean generation

### ISSUE THREAD

**Issue by jnehlmeier** [ebean-orm/ebean#3267]
## Expected behavior

Code generation should work

## Actual behavior

Invalid code generated

### Steps to reproduce

```java
@Entity
public class MyEntity {

  // composite primary key
  @Embeddable
  public static class Id implements Serializable {
    Long entity2;
    Long entity3;
    // hashcode.. equals..
  }

  @EmbeddedId
  Id id;

}
```

In `com.example.entities.ebean.query.assoc.QAssocMyEntity` a broken import `com.example.entities.ebean.MyEntity.query.assoc.QAssocId` is generated. I think the generated code should be placed next to `QAssocMyEntity` but needs to be prefixed with the enclosing entity name, e.g. `QAssocMyEntity_QAssocId`, to not conflict with other static inner classes of other entities in the same package.

**Comment by rbygrave** [comment]
This does not look like the latest version is being used?  What version is this?

The assoc package is no longer used so this looks like older generation here.

**Comment by jnehlmeier** [comment]
I think 13.20.x is being used currently. Trying to update tomorrow.

**Comment by rbygrave** [comment]
You updated and it was fixed right?

**Comment by jnehlmeier** [comment]
No I haven't updated yet and tried it. Had to solve something else last week.

**Comment by jnehlmeier** [comment]
@rbygrave I tried it now using latest Ebean and it generates `MyEntity$Id` directly in the `query` package and imports are fine.
