### ISSUE TITLE
Allow 'on delete cascade'

### ISSUE THREAD

**Issue by macruch** [ebean-orm/ebean#3292]
## Expected behavior
the possibility that `on delete cascade` can be generated

## Actual behavior
somewhere in the documentation I found that `on delete restrict` is by intention in order to avoid unwanted deletion directly on the database. Instead ebaen does automatically do delete statements on the children before the parent is deleted. 

### why do I want this?
when the relation is a clear ownership relation I would like to model this clearly in the schema and I want to be able that all depending entries are delete when I delete the 'root'
This makes it easier to maintain the database and I also prefer that the database is doing the job itself instead that the framework if firing several statements to achieve the same. 

I could change the generation result in the changeset but in the generated db-init script it will always use 'restrict' and it is very likely to miss the change for every new initial schema script.

I found some hibernate annotation https://stackoverflow.com/questions/13347233/generate-on-delete-cascade-using-ebean which are not working. And even so, I do not want hibernate dependencies in my project.

### suggestion
provide some attribute on the migration model xml or provide some annotation or annotation attribute, so the adjustment just needs to be done once.

**Comment by rob-bygrave** [comment]
Try `@DbForeignKey(onDelete=ConstraintMode.CASCADE)`

That is an ebean specific `io.ebean.annotation.DbForeignKey ` annotation.

**Comment by macruch** [comment]
thanks, this is exactly doing what I want. I haven't found this in the documentation, even I was looking for. 
Can I update the documentation or how is the process? I Would at least mention it here https://ebean.io/docs/mapping/

**Comment by rob-bygrave** [comment]
> Can I update the documentation

Yes, there is the "Edit Page" link at the bottom of the page ... click on that and create and submit a PR to the website-source git repo.
