### ISSUE TITLE
Query bean fails to compile when ebean entity class is named Alias

### ISSUE THREAD

**Issue by SchlauFuchs** [ebean-orm/ebean#3337]
## Expected behavior
No compile failure

## Actual behavior
Fails to compile:
```txt
[project]\build\generated\source\kapt\main\[package]\model\query\QAlias.java:64: error: no suitable constructor found for TQRootBean(Class<[package].model.query.QAlias.Alias>)
    super(Alias.class);
    ^
    constructor TQRootBean.TQRootBean(Class<[package].model.Alias>) is not applicable
      (argument mismatch; Class<[package].model.query.QAlias.Alias> cannot be converted to Class<[package].model.Alias>)
```
### Steps to reproduce
gradle kotlin project with ebeans plugin 13.20.0 and ebeans version 13.23.2-jakarta

```kotlin
@Entity
@Table(name = @Entity
@Table(name = "abc_alias")
class Alias(
    @Id
    val id: Int = CommonDataService.allocateId("abc_alias"), // sequence generator
    val sequence: Int = 1,
    val surname: String,
    val other_names: String?,
    val ttin_id: Int,
    val source_type: String,
    val source_id: Int,
) : Model() {
    companion object Find : Finder<Int, Alias>(Alias::class.java)
})
```
fails during compile.Java

IMHO this can be mitigated by use of fully qualified classes in the generated code.

**Comment by rob-bygrave** [comment]
BTW: The the `val id: Int = CommonDataService.allocateId("abc_alias"), // sequence generator` ... looks like a bad idea to me. Ebean can hold sequence next values in memory to allocate the next one. Are you really sure you want this?

**Comment by SchlauFuchs** [comment]
This one is sadly a necessity, as we are in the process of replacing a
legacy app (a windows fat client) that runs in parallel to our service and
this service is reserving a sequence based on a table name. The relevant
tables and code seems to be older than the idea of a database internal
sequence generator, on an Informix database.

**Comment by rob-bygrave** [comment]
Yeah cool.  Er, does that mean this app is using Informix? Ebean does not have a specific platform for Informix per say so I presume using the generic platform is working out ok and probably there is no use of ebean DDL generation (which is often platform specific).

**Comment by SchlauFuchs** [comment]
We will probably find out soon if it is feasible ;)
