### ISSUE TITLE
About custom SQL dialect

### ISSUE THREAD

**Issue by PassXml** [ebean-orm/ebean#3359]
Hello, I'm interested in creating a custom SQL dialect. Could you guide me on which documents or code examples I should start with? I'd also like to know how to write my own SQL dialect class and register it.

**Comment by rob-bygrave** [comment]
Hi, Does the scope into docker test containers? does it include DDL generation? What is the database / does it have interesting types, identity &/or sequence, sql history support etc.

Under platforms there are platform specific `io.ebean.config.dbplatform.DatabasePlatform` and that deals with types (that map differently to standard + uuid, json etc), identity, sequence, SqlLimiter aka limit/offset etc , sql history.

There is `io.ebeaninternal.server.expression.platform.DbExpressionHandler` which handles database specific expressions for json expressions, array contains, array isEmpty and bitwise expressions.
[when I look at this I see this needs an improvement to work with service loading an externally provided implementation]

There is `io.ebeaninternal.dbmigration.ddlgeneration.PlatformDdlBuilder` which chooses the platform specific DDL generation (but this isn't easy to extend externally to ebean-ddl-generator, I feel that if we want DDL generation support we are better trying to contribute that into ebean-ddl-generator).

There is the `ebean-test-containers` project to support starting and initialisating the various databases for testing purposes. Although not strictly required per say for myself I see this as very important for long term developer productivity. So I'd suggesting if possible that you identify the docker commands that are used to start a docker container for this database and commands used to setup the database (create database, create user etc).

 I'd suggest you start by looking at https://github.com/ebean-orm/ebean/tree/master/platforms ... and looking at a database in there which is similar to the one you are wanting support for.

There is also the option of adding a set of expressions to be used with query beans to extend the StdOperators - https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/StdOperators.java
... we should add an example for PostGIS, that would be helpful.

We can also have platform specific `@Formula` when we just want platform specific formula in the entity mapping.

BTW: DDL is imo often where the work is, the rest of it is relatively easy to add especially if you want to contribute it back into ebean.

**Comment by PassXml** [comment]
Yes, I want to understand the underlying logic of Ebean, and I think starting with its SQL dialect is the best choice. Moreover, adding some database features should also be a very interesting task.
