### ISSUE TITLE
Disabling batching through configuration

### ISSUE THREAD

**Issue by tbee** [ebean-orm/ebean#3364]
It would be great to be able to disable batching completely through configuration.

Our patched JtaTransactionManager:

```java
        ...
        // "wrap" it in a Ebean specific JtaTransaction
        String txnId = String.valueOf(System.currentTimeMillis());
        JtaTransaction newTrans = new JtaTransaction(txnId, true, ut, dataSource(), transactionManager);

        // patch - make configurable?
        newTrans.setBatchMode(false);
        newTrans.setBatchOnCascade(false);
        ....
```

**Comment by rob-bygrave** [comment]
Huh?   You can already do that, so I don't understand what you mean here.

https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java#L236-L243
https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java#L856
https://github.com/ebean-orm/ebean/blob/master/ebean-api/src/main/java/io/ebean/config/DatabaseConfig.java#L845

**Comment by tbee** [comment]
You are right, I had not associated that setting with disabling batching. Sorry.
