### ISSUE TITLE
Question: Reason for transaction not being reused?

### ISSUE THREAD

**Issue by jtammen** [ebean-orm/ebean#3369]
Hello!

First of all, I would like to thank @rob-bygrave (and of course all other contributors!) for the ongoing work on this great piece of software! 🙏

Recently, I have observed some unexpected behaviour in a production environment of an application which uses **Play Framework 2.8.20** with the `PlayEbean` sbt plugin as well as the **Play Ebean module version 6.2.0**.

Which means the app is using **Ebean version 12.16.1**.

There is this kind of flow:

`Controller.action -> Service 1.doSomething ; Service 2.doSomethingElse`

And the code looks sth like this:

```java
public class Controller {
  private final io.ebean.Database database;
  private final Service1 service1;
  private final Service2 service2;

  public Result action(Http.Request request) {
    try (var txn = database.beginTransaction()) {
      ExampleModel bean;
      try {
        bean = service1.doSomething();
      } catch (SomeCheckedException e) {
        // ...
        return badRequest();
      }

      try {
        service2.doSomethingElse(bean);
      } catch (SomeOtherException e) {
        // ...
        return badRequest();
      }

      txn.commit();

      return ok();
    }
  }
}
``` 

```java
public class Service1 {
  public ExampleModel doSomething() throws SomeCheckedException {
    var bean = new ExampleModel();
    bean.insert();
    return bean;
  }
}
```

```java
public class Service2 {
  public void doSomethingElse(ExampleModel bean) throws SomeOtherException {
    // ... do some validation
    if (validationFailed == true) {
      throw new SomeOtherException();
    }
    bean.update();
  }
}
```

What I would expect – and this is also what happens in my development environment! – is that everything is using **the same transaction**, as I am using beginTransaction() and as everything happens in the same thread. As you can see, I am not using `@Transactional`.

In the mentioned production environment, however, I noticed cases where the queries/inserts from Service 1 are being committed, i.e. `bean` is inserted, despite the fact that there was an Exception being thrown in `service2.doSomethingElse()`. From the Ebean logs I can see that both methods seem to use separate transactions... which I cannot wrap my head around!

Does anyone have an idea what could a) cause the different behaviour between the two environments and most importantly b) why the thread-local transaction does not seem to work in production?

As a side note: I am pretty sure that this has worked consistently before. The application has been running fine for the last years. It might have changed after the upgrade of Play/Ebean module, but it is difficult to tell... as I'm not able to reproduce this in my local environment :-/

Thanks for any hints!

**Comment by rob-bygrave** [comment]
I think you should use a debugger and step through the code, and step in for the insert() and update() to see where it obtains the existing transaction.

I think 12.x code will be similar, you'll get to `BeanRequest.createImplicitTransIfRequired()` and that is where it obtains the current transaction (and creates a new implicit transaction if there is no current transaction in scope).

**Comment by rob-bygrave** [comment]
You can also just literally increase the logging for `io.ebean.TXN` and `io.ebean.SQL` - and that will log the transaction begin and end along with a transaction identifier, plus the sql being executed.  https://ebean.io/docs/logging/

**Comment by jnehlmeier** [comment]
> In the code, I added some log statements, where I log database.currentTransaction() as well as io.ebean.DB.currentTransaction(). database is the injected instance of io.ebean.Database. What I don't understand: In the error case, before the call to service2. doSomethingElse(), the value of database.currentTransaction() is actually the ScopeTrans[txn[1001]] – BUT: DB.currentTransaction() is null!
In the "good" case, e.g. Java 17 with enabled debug agent, both methods return the same ScopeTrans[txn[<ID>]]. I assume that DB.getDefault() and the injected Database instance are not the same object. But how could this happen or rather why is this not always the case?!

Ebean has the concept of a single default server. Calling `DB.currentTransaction()` expands to `DB.getDefault().currentTransaction()`. If your injected `database` IS NOT the default database then you will see different results between `database.currentTransaction()` and `DB.currentTransaction()`. 

Do you use multiple databases? If you only use a single database and that database should be the default database then check if `database == DB.getDefault()` holds `true`. If not, then there is likely a race condition somewhere that creates a database instance with the same configuration twice. One is stored as default DB and the other is used during injection.

If something is a default database or not can be controlled via `DatabaseConfig.setDefaultServer(boolean)` / `DatabaseConfig.defaultServer(boolean)`. By default it is `true`.

**Comment by jnehlmeier** [comment]
@jtammen Maybe set a breakpoint in `DefaultServer` constructor that does not halt the JVM but instead logs a stack trace. Even though you said enabling Java debugging in order to set breakpoints fixes the issue, it might only fix the issue if you actually stop at a breakpoint. So I would try it with non-stopping breakpoints.

**Comment by rPraml** [comment]
It seems, that there is a timing issue/race condition. It would explain why an update of apache-poi (which is not related to ebean at all) can change the behaviour. (the lib needs some microseconds longer to load)

You see in the logs that there are two ebean servers started. Does this happen also on your dev instance? If so, put a breakpoint to the line where the log is generated and check the two stack traces
