### ISSUE TITLE
LimitOffsetPagedList add getTotalCount cache

### ISSUE THREAD

**Issue by spinachomes** [ebean-orm/ebean#3370]
I suggest LimitOffsetPagedList.java cache  getTotalCount method result, so getList method may directly return empty list  to avoid an unnecessary query when getTotalCount had done and It's result is equal to Zero.

**Comment by rbygrave** [comment]
Not sure about this in that it's designed to be able to run the 2 queries in parallel. So I don't think it's worth it.  If you want to prepare a PR for what you were thinking about I'd have a look?
