### ISSUE TITLE
ddl-generator: Identity for PK is always generated

### ISSUE THREAD

**Issue by magicprinc** [ebean-orm/ebean#3399]
I generate ID in my App in java code, so my id column is declared in entity class as:
```
@Id
Long id;
```
but DdlGenerator generates such columns as:
`id bigint identity(1,1) not null,`
instead of expected:
`id bigint not null,`

MSSQL doesn't allow then insert values into column id, because id is an identity column.

The same is true for MySQL (identity related keywords are added).

see
`io.ebeaninternal.dbmigration.model.MTableIdentity#fromCreateTable`
`io.ebeaninternal.dbmigration.ddlgeneration.platform.BaseTableIdentity#identity`

**Comment by rob-bygrave** [comment]
Use `ebean.idGeneratorAutomatic=false` or set it via `DatabaseConfig.setIdGeneratorAutomatic(false)`

This defaults to true and means that `@Id` properties use either `Identity` or `Sequence` based on the DatabasePlatform. Turning this off means that when those are needed an explicit `@GeneratedValue` is required.

**Comment by rob-bygrave** [comment]
The above **_globally_** turns off ebeans implicit behaviour. An alternative for the case that MOST entities use Identity or Sequence and only a few are application controlled identity values, then we can use ebean specific `@Identity(type=APPLICATION)` so:

```java
@Id @Identity(type=APPLICATION)
Long id;
```

**Comment by magicprinc** [comment]
I love your project. You have everything: beyond anyone could dream of 🤝🔥

I have recently modernized a legacy project. And among other things, I have replaced jOOQ by Ebean. The code is more concise and readable now.

**Comment by rob-bygrave** [comment]
Thanks for that, it's great getting feedback.   There is some missing documentation on this which should be added at: https://ebean.io/docs/mapping/jpa/id#generated-value ... so I'll look to do that.

Cheers, Rob.

**Comment by rbygrave** [comment]
Ok, I've update the website documentation.  We can close this now.
