### ISSUE TITLE
Ebean-Data (auto generated repositories)?

### ISSUE THREAD

**Issue by magicprinc** [ebean-orm/ebean#3400]
Ebean is a great project and has almost everything one needs or wants. 
The only advantage of Spring Data JPA left is its auto-generated repositories (The programmer declares an interface, and Spring Data generates the implementation according to the meaning hidden in the method name. IDEA helps to write such names). 
What do you think about this Spring Data feature?
Do you have any plans to support this?

PS: Quarkus has implemented part of it, to help migrate from Spring (google: Quarkus spring data JPA).
BTW, It is a good idea to test (to fix, create extension) and advertise Ebean's compatibility with Quarkus. Many people are tired of Spring and are trying to escape. 
As start: https://github.com/smallrye/jandex
And another idea: Quarkus Panache could have some ideas worth to borrow (just impromptu, no practical experience with Panache)

PPS: I mean: query creation from method names.
```java
public interface UserRepository extends Repository<User, Long> {
  List<User> findByEmailAddressAndLastname(String emailAddress, String lastName);
  List<Employees> findFirst5ByFirstNameStartsWithOrderByFirstName(String firstNameStartsWith);
}
```

PPPS: I am not sure, if it is actually a good thing:
Too much magic and syntactic sugar are bad for the health :-)

**Comment by rbygrave** [comment]
> What do you think about this Spring Data feature?

I personally have never liked this feature. The 2 main reasons being that:
- It omits the "only select what you need" / "optimise the projection" aspect of a query and pretty much promotes the "select everything on the root bean + lazy load as necessary" instead. In general there are a lot of query options like locking, non-trivial predicates, conditional predicates, L2 cache etc and I don't think this approach deals with any of those query options nicely.
- It works for simple queries but gets ugly for anything beyond that. It terms of a "sweet spot" it has a narrow "sweet spot" and then when you hit the point that you want more control over the query you are faced with having to **_completely change the technique_** being used. As a Dev you are working along using this and then you hit a wall and have to completely change the approach - it isn't a smooth graduated approach that works from the simplest query to the most interesting query.


> Do you have any plans to support this?

No I don't. I do know that a lot of people really like it but those people also don't know about query beans.


> Quarkus Panache could have some ideas worth to borrow

Yes, although I think we've already done that (or they've copied a feature we already had). One thing we don't talk about is that ebean has the mode where we can just use public fields on entity beans (omit getters and setters) and ebean enhancement will automatically modify that field access to method access and get full normal functionality in terms of lazy loading and dirty checking etc.

I don't think there is anything outstanding I saw in Panache that we desire but I'll have another look some day in case they have added something.

**Comment by rbygrave** [comment]
Ok, I think we can close this for now. More comments are welcome etc if anyone has anything else to add.
