### ISSUE TITLE
Fields are null when I use rawSql for fetch an @Entity with fetchType = lazy

### ISSUE THREAD

**Issue by deverlex** [ebean-orm/ebean#3454]
Hi, 

I created sql for query an Entity that contain an other Entity with FetchType = lazy.
My model for query
```java
public class DebtTransaction extends AppModel {
    @Id
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    private Debt debt;
}
```

I created an RawSql as below:
```java
RawSql rawSql = RawSqlBuilder.parse(sql).columnMapping("dt.id", "id").create();
```
I was set
```java
 ....query().fetch("debt").findList()
```
but all fields (without id field) of the Debt is null

How to load all fields of the other Entity when I use setRawSql in my query data in Ebean?

Ebean version: 13.26.1

**Comment by rbygrave** [comment]
> How to load all fields of the other Entity when I use setRawSql in my query data in Ebean?

Change `.fetch("debt")` to be `.fetchQuery("debt")` so

```java
query().fetchQuery("debt").findList();
```

**Comment by rbygrave** [comment]
I think we can close this right?

**Comment by rbygrave** [comment]
Closing for now, reopen if needed.
