### ISSUE TITLE
About BeanQueryAdapter 

### ISSUE THREAD

**Issue by PassXml** [ebean-orm/ebean#3458]
## Expected behavior

I am dynamically adding conditions in the preQuery method of BeanQueryAdapter, but I've encountered a situation where this condition exists across multiple tables during a fetch query, necessitating the addition of a prefix. However, for single-table queries, this prefix is not required. How can I determine if the prefix is effective and what the prefix name is?

```sql
select t0.id,
       t0.node_id,
       t0.id,
       t0.name,
       t1.node_id
from t_event_type t0
         left join t_event_built_even_code_ref t1 on t1.event_type_id = t0.id
where t0.id = '97ccff2f-e5da-473c-9ab0-278d7a616ee3'
  and (node_id is null or node_id = any (1, 2))
order by t0.id
```

**and (node_id is null or node_id = any (1, 2))**

The current situation is this... I hope he adds a prefix.

**Comment by PassXml** [comment]
Through debugging, I've traced that the prefix names are all "t0," but it seems that these prefixes are initialized when the QBean is first instantiated.

**Comment by rbygrave** [comment]
Can you show us the code in BeanQueryAdapter, and perhaps how the `node_id` is modelled?  It looks like  a raw() expression is being used with the column name and the "logical property name" could be used instead (e.g. `nodeId` or `node.id`)

**Comment by PassXml** [comment]
> Can you show us the code in BeanQueryAdapter, and perhaps how the `node_id` is modelled? It looks like a raw() expression is being used with the column name and the "logical property name" could be used instead (e.g. `nodeId` or `node.id`)

Yes, the `node_Id` is the raw expression, and the logical attribute name is `nodeId`. Over the weekend, I tried using `nodeId` and discovered that the framework can automatically add table prefixes, which is fantastic. Does the prefixing happen during the SQL generation phase?

**Comment by rbygrave** [comment]
> Does the prefixing happen during the SQL generation phase?

Yes.

Just to clarify it's actually more ... "changing a logical property path into appropriate table alias + column ... including the automatic addition of the appropriate joins if necessary"

e.g. "contact.email"
e.g. "billingAddress.country.code"
e.g. "nodeId"

Those are all "logical property paths" that can be verified as valid paths relative to the root type of the query, and those are translated to "table alias + column ... including the automatic addition of the appropriate joins if necessary".

**Comment by PassXml** [comment]
thx
