### ISSUE TITLE
Suspend creating new Transaction before existing ends

### ISSUE THREAD

**Issue by PromanSEW** [ebean-orm/ebean#3510]
I don't know bug or feature request it is. I want to wait before current transaction ends, and only after that create new transaction.
`TxScope.requiresNew()` does negative to my needs, `required` just uses existing transaction
I used `DB.updateAll(beanList)`, but got some exceptions like that:
```text
PersistenceException: Error: ERROR: deadlock detected
Detail:
Process 208370 waits for ShareLock on transaction 35047083; blocked by process 208371.
Process 208371 waits for ShareLock on transaction 35047084; blocked by process 208370.
Hint: See server log for query details.
Where: while updating tuple (3,245) in relation "tour_stats"
```
Current code that produces deadlock (no explicit transactions used):
```java
var beanList = DB.find(SomeBean.class).query().where().eq("prop_id", 42).findList();
// some modifications...
DB.updateAll(beanList);
```
If the first line is being called again (for other HTTP request that fetches the same rows) and also tries update them while previous updating is still running, there is deadlock, as I mean.
I wanted to use transactions for locking rows before they updated, and after fetch actual data, but I don't know how. Please help.

Here is my code, that "fixes" the problem, but I suspect that is wrong.
```java
try (var transaction = DB.beginTransaction()) {
  var beanList = DB.find(SomeBean.class).query().usingTransaction(transaction).where().eq("prop_id", 42).withLock(NO_KEY_UPDATE).findList();
  // some modifications...
  DB.getDefault().updateAll(beanList, transaction);
  transaction.commit();
}
```
PostgreSQL 15, Ebean 15.1.0

**Comment by PromanSEW** [comment]
Please convert to discussion, I missed that :(

**Comment by PromanSEW** [comment]
`DB.saveAll` and `DB.updateAll` are extremely slow scrap, again. 10 rows are inserting/updating TEN SECONDS, WTF? Reduced to 10-50 ms by single string request with multiple  `INSERT/UPDATE` separated by `;`

**Comment by rbygrave** [comment]
> DB.saveAll and DB.updateAll are extremely slow scrap, again. 10 rows are inserting/updating TEN SECONDS, WTF? 

Please be careful here. There might be an issue but saveAll() and updateAll() are not it, something else is impacting that.

> Reduced to 10-50 ms by single string request with multiple  INSERT/UPDATE separated by ;

10ms is actually slow. 

Note that creating a single string etc is imo very bad general advice due to the impact on PreparedStatements.

WRT inserts in particular, pay attention to identity options (like Postgres CACHE option) and note that sequences nextval involve some contention so that are absolutely ways to use sequence nextval incorrectly.
