### ISSUE TITLE
ENH: Multi-tenant support via database schema  (database schema per tenant)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#493]
This probably requires 2 changes:
1. Add an interface that at runtime per request tells us the schema to use. You supply an implementation to ServerConfig ...

``` java

public interface MultiTenantSchema {

  /**
   * Return the DB schema that should be used for this request.  Typically use a 
   * ThreadLocal / context to determine the current user and hence their schema.
   */
  String getTenantSchema();

}

```
1. Provide 3 implementation options:
- Tenant per schema
- Tenant per database
- Add a tenantId column in all tables

**Comment by IvanAR** [comment]
When do you estimate do this? I'm really interest about it.

**Comment by rbygrave** [comment]
Not sure. Please ask again in a week, by which time I hopefully will be
close to clearing the elastic search integration.

Cheers, Rob.

**Comment by oexza** [comment]
+1 oh my! how this feature is so needed

**Comment by oexza** [comment]
hey rob any chance in the world this is coming soon? :)

**Comment by rbygrave** [comment]
Yes'ish.

It is not a sponsored feature so I need to do it in my 20% time. So right now it is competing against some cleanup I want to do and 'performance monitoring'. 

The cleanup work is:
- Support autotune to writing back to the original autotune file (Just to make it easier to use)
- Support easier generation of "Finders" in maven (Probably maven plugin)
- Pull out class path scanning internals replacing with 'avaje-class-path-scanner'
This work puts us in a position to support running DB Migration (without FlywayDB for example as there are some things I don't like about how that works).  It also puts us in a position to support migration of ElasticSearch indexes (in a automated fashion like DB migration).

Performance monitoring is important for many reasons. Ebean has collecting the performance metrics for many years but we ideally have a nice way to collect and display those metrics.

It is possible multi-tenant support bumps the performance monitoring enhancements. 

If you ask this question again in a weeks time then I might be able to give you a real answer but that said I need to earn brownie points with the wife (been working too hard) so I'm not sure how much cleanup I'll get done (as that is now all after hours work now).

Cheers, Rob.

**Comment by oexza** [comment]
lol i totally understand (especially the brownie points :smile: , )
and i must say, its amazing to me how with the time constraints you
can singularly churn out bug fixes and add new features  at the rate
you do. It just beats me!.

Ebean is my go to ORM for most things these days and multi tenancy is
a feature i find the need for a lot (hence my continued asking)  and i
believe a good part of the Ebean community share my sentiment so:

"It is possible multi-tenant support bumps the performance monitoring
enhancements"

if it won't be too disruptive to your plans, i hope it does bump it
:smile: (and i totally respect if it can't).
if i understood the internals of Ebean enough i would submit PRs to
help. Anyways thanks again for this boon called Ebean!

**Comment by stijn-scorius** [comment]
Hi Rob,

I see this issue/future got the label Sponsor Me. About how much dollars/euros do we talk?

Cheers,

From a Ebean user/lover since 2013

**Comment by rbygrave** [comment]
I have a flat rate of USD $500 per feature.  This feature got a willing sponsor just 2 weeks ago so ... I'm not sure.  I've been away and haven't got into this work yet with the plan to kick into Postgis support first in the next couple of days. 

Cheers, Rob.

**Comment by rbygrave** [comment]
Examples:
https://github.com/ebean-orm-examples/example-multi-tenancy-db
https://github.com/ebean-orm-examples/example-multi-tenancy-schema
https://github.com/ebean-orm-examples/example-multi-tenancy-partition

Yes, I need to work on some documentation for this...
