### ISSUE TITLE
JPA2 - @OneToMany or @ManyToOne not supported inside @Embeddables

### ISSUE THREAD

**Issue by asouza** [ebean-orm/ebean#52]
I tried to migrate a system from Hibernate to Ebean and this was one of the biggest problem!.

**Comment by rbygrave** [comment]
I would like to gather examples of when people have used or wanted this feature.

Specifically, @Embeddable beans do not have Identity (no @Id property) and as such I wonder when it makes sense for these embeddable beans to contain @OneToMany related embeddables. I can image the use of a @ManyToOne related Embeddable but @OneToMany implies the use of relationship/foreign key and this sounds like a bad idea for this case.

Thanks, Rob.

**Comment by robaho** [comment]
I think the @ManyToOne is necessary, see https://groups.google.com/forum/#!topic/ebean/pMTAwX2mNAE

**Comment by rbygrave** [comment]
Closing with PR - Support @ManyToOne inside @Embeddables - fix for #52 #1608
