### ISSUE TITLE
ENH: Improve exception handling such that more specific types of exceptions can be detected such as constraint violation  

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#528]
So as per this discussion here:
https://groups.google.com/forum/#!topic/ebean/EGkhd3f4oTs

The need is because this is a good thing to do but also generally there is a race condition (between different db activity) so there is no real way of preventing this type of code ... where you need to detect if the error was constraint violation for example and handle that specific case.

**Comment by rbygrave** [comment]
The JPA spec currently has no such suppport and the JPA-SPEC JIRA currently has no such ticket (but I did find https://java.net/jira/browse/JPA_SPEC-80).

It looks to me that Spring JDBC probably have the best / well tested existing design for this issue.
References:
- https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/resources/org/springframework/jdbc/support/sql-error-codes.xml
- org.springframework.jdbc.support.SQLErrorCodesFactory

An alternative is to work off the first 2 characters of the SQLState code as per:
http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt
http://stackoverflow.com/questions/1988570/how-to-catch-a-specific-exception-in-jdbc
However, it is nice to differentiate between duplicate key and data integrity violation which looks like the limitation here.

Something close to the Spring JDBC approach would provide flexible mapping so to me that looks best.

**Comment by rbygrave** [comment]
The exceptions look like:
CannotSerializeTransactionException extends PessimisticLockingFailureException 
DeadlockLoserDataAccessException extends PessimisticLockingFailureException 
CannotAcquireLockException extends PessimisticLockingFailureException 

TransientDataAccessResourceException extends TransientDataAccessException 

DataAccessResourceFailureException extends NonTransientDataAccessResourceException 
PermissionDeniedDataAccessException extends NonTransientDataAccessException 
DataIntegrityViolationException extends NonTransientDataAccessException 
DuplicateKeyException extends DataIntegrityViolationException 

InvalidResultSetAccessException extends InvalidDataAccessResourceUsageException 
BadSqlGrammarException extends InvalidDataAccessResourceUsageException

**Comment by rbygrave** [comment]
I'd probably look to map this into:

PersistenceIntegrityException  
PersistenceDuplicateKeyException extends PersistenceIntegrityException 
PersistenceGrammarException 
+ 3 PessimisticLockException's ....
+ the rest

I think the exception hierarchy should be kept simple and yet still provide DB agnostic error handling and that seems compelling here - access to a DB agnostic code that can be custom mapped is sufficient and likely better than a hierarchy that is too specific.

**Comment by rbygrave** [comment]
FYI: Logged as JPA_SPEC-126

**Comment by ksperling** [comment]
I'm currently using an enum that can derive itself from SQL state similar to Spring's https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/support/SQLStateSQLExceptionTranslator.java

I'm not sure if you're planning to do the actual mapping via an XML file like Spring... I think a nicer approach might be to just implement this logic in the relevant `DatabasePlatform` sub-class.

One other feature that would be really helpful is to have the ability to find the column that a duplicate key error relates to. It seems the only way to do this is via some hacky string processing of the exception message (which is what I'm doing currently), but at least by delegating that to the `DatabasePlatform` as well that would be encapsulated in a single, testable place per database.

Do you see this as depending on JPA actually defining these exceptions or are you planning to go ahead with ebean-defined ones (analogous to Spring)?

**Comment by rbygrave** [comment]
*> I think a nicer approach might be to just implement this logic in the
relevant DatabasePlatform sub-class.*
Yes perhaps. I was not unhappy with the xml approach ala spring but I need
to look at it again in detail, it's been a while since I originally looked
into this.




*>  find the column that a duplicate key error relates to ... but at least
by delegating that to the DatabasePlatform as well that would be*
Quite right.



*> Do you see this as depending on JPA actually defining these exceptions*

We can't wait for JPA at this rate. I've been monitoring the JPA JIRA etc
and nothing is happening.  When JPA eventually brings out the exceptions we
can then look to migrate etc but that might be a long time.  From memory
Spring went a bit overboard with their exception hierarchy but yes.

**Comment by rbygrave** [comment]
I'm working on this in conjunction with adding "for update nowait" and "for update skip locked".

The exceptions are:
```java
AcquireLockException extends PessimisticLockException
DataIntegrityException extends PersistenceException
DuplicateKeyException extends DataIntegrityException
```

These are determined using SQLState code ... with each DatabasePlatform defining the how the SQLState codes map to these specific error types.

Postgres example:
```java
    this.exceptionTranslator =
      new SqlErrorCodes()
        .addAcquireLock("55P03")
        .addDuplicateKey("23505")
        .addDataIntegrity("23000","23502","23503","23514")
        .build();
```

I have this code basically ready but I am pondering the use of JPA RollbackException.  That is, my code change currently tries to keep the specific PersistenceExceptions above where as strict JPA spec compliance means commit() ought to throw RollbackException.

The issue with RollbackException is that with JDBC batch and non-batch mode ... we get the exceptions happening at execution time OR and commit/flush time.  If we are JPA strict compliance with RollbackException we get what I think is odd behavior where we lose the specific Exceptions if we have JDBC batch turned on.  

Anyway, pondering this for a day or so but I'm leaning towards keeping the specific exceptions and hence not always wrapping with RollbackException on commit().

**Comment by buckfeng** [comment]
in the latest example-java8 on github, the ProductTest.java class obtainWithLock() method threw NullPointerException at the line other.getName().  it appeared that the  query return null instead of throwing an exception.

```
private boolean obtainWithLock(Query<Product> queryById) {
    Transaction otherTxn1 = Ebean.getDefaultServer().createTransaction();
    try {
      Product other = Ebean.getDefaultServer().findUnique(queryById, otherTxn1);
      other.getName();
      return true;
    } catch (AcquireLockException e) {
      log.info("Failed to obtain lock" + e.getMessage());
      return false;

    } finally {
      otherTxn1.end();
    }
}
```
