### ISSUE TITLE
#718 Removed PagedList.getPageIndex() - Can it be added back?

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/ebean#820]
## Expected behavior

When we use _PagedList_, we have to know the index (or number) of the current page to know which number to print on HTML page. In major case, pagination is not just a _prev_ and a _next_ button.

## Actual behavior

Method to get current page has been removed since [b2a3f0c99b](https://github.com/ebean-orm/ebean/commit/b2a3f0c99b81cc5e5fac45bee7c6d1452decc3c8)

### Steps to reproduce

Just use last version of ebean with _PagedList._

**Comment by rbygrave** [comment]
Of course #718 was an explicit and deliberate change to the API.  You would like to have getPageIndex() added back to the API for PagedList - yes, that seems reasonable enough.
