### ISSUE TITLE
CQueryIteratorSimple not working with consecutive calls to hasNext() - ie. without matching calls to next()

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/ebean#821]
## Expected behavior

_hasNext()_ method must check if next result exists without fetching it or moving iterator to next.

## Actual behavior

The next result is fetched and the current result was lost.

## Steps to reproduce

Using `Ebean 8.2.3`

```java
final QueryIterator<OrderModel> queryIterator = OrderModel.find
                .where()
                .eq("contract", contract)
                .setMaxRows(3)
                .findIterate();
Logger.debug("hasNext? {}", queryIterator.hasNext());  // Must return true
Logger.debug("hasNext? {}", queryIterator.hasNext());  // Must return true
Logger.debug("hasNext? {}", queryIterator.hasNext());  // Must return true
Logger.debug("hasNext? {}", queryIterator.hasNext());  // Must return true
Logger.debug("hasNext? {}", queryIterator.hasNext());  // Must return true
```

```console
[debug] application - hasNext? true
[debug] application - hasNext? true
[debug] application - hasNext? true
[debug] application - hasNext? false
[debug] application - hasNext? false
```

## Possible workarounds

Possible quick workarounds :

1. Only use _CQueryIteratorWithBuffer_ (CQuery.java line 573)
2. Change CQuery.java _hasNext()_ line 512 behavior (must dont use _readNextBean()_ when _CQueryIteratorSimple_ is used)
3. Fix _CQueryIteratorSimple.java_ to have a buffer of size = 1
4. (not sure) Check why the variable _iterateBufferSize_ (CQuery.java line 195) is always set to -1

**Comment by 0xbaadf00d** [comment]
If you don't have enough time to fix tis critical issue. I can propose a Pull Request if you want ?

**Comment by rbygrave** [comment]
Hi, I think I have just pushed a good fix for this so we can go with that. Cheers.
