### ISSUE TITLE
EbeanServer.getBeanId(entity) does not trigger jdbc batch flush - when bean inserted with jdbc batch mode

### ISSUE THREAD

**Issue by icode** [ebean-orm/ebean#822]
## Expected behavior
`EbeanServer.getBeanId(entity)` should fetch id

## Actual behavior
get field value

### Steps to reproduce

When using JDBC batch mode - e.g.  @Transaction(batchSize=10) 

```java
 OrderModel model = new OrderModel();
 model.setName("test");

 // this insert does not execute immediately in jdbc batch mode 
 server.insert(model);

 // we need getBeanId() ... to trigger the flush of the jdbc batch
 notNull(server.getBeanId(model)); // now return null
```

**Comment by rbygrave** [comment]
Fixed - getBeanId() now triggers the JDBC batch flush.

Internal note: Each bean property has a "get with intercept" and "get without intercept" method.  This fix was that getBeanId() changed to use the "get with intercept".
