### ISSUE TITLE
ENH: Add support for AttributeConverter from JPA 2.1

### ISSUE THREAD

**Issue by salvadormarcos** [ebean-orm/ebean#827]
It would be very interesting if Ebean ORM supports AttributeConverter from JPA 2.1

**Comment by rbygrave** [comment]
Well yes'ish, Ebean already has ScalarTypeConverter to wrap and unwrap scalar types and some of reasons people are using AttributeConverter is not that great in that it can negatively effect DDL generation, cross DB support, JSON support etc.

I've seen them used for Enums, Encryption, Java8 Time types, UUID, Array types, JSON ... all these have built in support in Ebean already and I believe that is much better in terms of DDL support and integration to other ORM features.

So yes'ish ... but I believe people should really explain what they are trying to do on the discussion group and they might find a better option already exists (use ScalarTypeConverter, create your own ScalarType etc).
