### ISSUE TITLE
Introduction page and the navigation links.

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#838]
I was searching using Google for something related to Ebean, and I landed on this page : http://ebean-orm.github.io/docs/introduction 
The links on the right side broken !
---

P.S: The documentation at all need really a lot of efforts, fixing examples, provide example, provide documentation for features and so on, hopefully it is on plan, documentation is the real market for this nice library.

**Comment by rbygrave** [comment]
Thanks.  That introduction page was not supposed to be there ... it was accidentally left around after a site reorganisation.  

So yes, in this case I have actually deleted the page (and some others as well).

Cheers, Rob.
