### ISSUE TITLE
batch insert does not work

### ISSUE THREAD

**Issue by lzhang32** [ebean-orm/ebean#840]
Hi,

I am using Ebean (PlayEbean V.1.0.0) for MySQL. And I found that batch insert seem not work for me.
A similar problem is at http://stackoverflow.com/questions/32274481/ebean-batch-not-working

My code snippet is as follows. Note that I have JdbcTransaction and try to turn off auto-commit 
for MySQL by "transaction.getConnection().setAutoCommit(false);". It does not work.
In transaction object, the "autocommit" value is still "true".

Any suggestions?  how can I set "autocommit" to false?  

` EbeanServer ebeanServer = Ebean.getServer(null);
    Transaction transaction = ebeanServer.beginTransaction();
    try {

      **transaction.getConnection().setAutoCommit(false);**

      transaction.setPersistCascade(false);
      transaction.setBatchMode(true);
      transaction.setBatchSize(100);
      transaction.setBatchGetGeneratedKeys(false);

      for (ProjectFeature projectFeature : projectFeatures ) {
         ebeanServer.save(projectFeature);
      }
      transaction.commit();

    } catch(Exception ex) {
       LOG.error("ERROR in batchInsertProjectFeatures : " + ex);
    
    } finally {
      transaction.end();
    }`

**Comment by rbygrave** [comment]
As per the policy stated at http://ebean-orm.github.io/support ... questions must first go to the Ebean google group.

Thanks, Rob.

**Comment by lzhang32** [comment]
Got it. I will close this issue first.
