### ISSUE TITLE
Add soft delete related callbacks

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/ebean#846]
Relative to #841, is it possible to add two other callbacks `preSoftDelete` and `postSoftDelete`? Because, when soft delete is used, developer maybe don't want to perform same callback actions when `.delete()` and when `.save()` are called.

**Comment by rbygrave** [comment]
So change:

- Adds preSoftDelete() and postSoftDelete() to the BeanPersistController (and default noop implementations on BeanPersistAdapter).

- Adds softDeleted() to BeanPersistListener and AbstractBeanPersistListener

**Comment by PierreAdam** [comment]
Would it be possible to add two annotation like ```@PreUpdate```, ```@PreRemove```, ... that can be used directly on a model method ? 
So that ```@PreSoftDelete``` and ```@PostSoftDelete``` can be specific to each models like with ```@PreUpdate```

By the way, do you have an example to how register a object ```BeanPersistAdapter``` to an existing instance of ```EbeanServer```. As in my case i'm not sure I can create the configuration manually as I'm using play framework and that the server is initialized by the library.

**Comment by rbygrave** [comment]
See https://github.com/ebean-orm/ebean/issues/904

> example to how register a object BeanPersistAdapter to an existing instance of EbeanServer.

It can be explicitly added to the ServerConfig via add(Class) or add(BeanPersistController).  If classpath  scanning is used (to find entity beans etc) then note that the scanning also finds BeanPersistControllers, ScalarTypes etc and automatically registers them.

**Comment by PierreAdam** [comment]
Hi @rbygrave,
Yes that's what I've done. It just would be nice to be able to pass through the annotations like for the rest of the Pre / Post.

**Comment by rbygrave** [comment]
> annotations like for the rest of the Pre / Post.

That is what you can do with #904 - it's just been done.

**Comment by PierreAdam** [comment]
Oh ok my bad !
Thanks for the reply and the work :)
