### ISSUE TITLE
same ManyToMany in different model fails.

### ISSUE THREAD

**Issue by ZeerDonker** [ebean-orm/ebean#848]
## Expected behavior

Updating the ebean library to provide depreciation warnings and later sensible errors on an update.

Being able to reach through the orm, the same many to many relationship from either model.

## Actual behavior

Not being able to reach through the orm, the same many to many relationship from either model, after the following bug fix. 
https://github.com/ebean-orm/ebean/commit/788a200d166e892781c852f65ba413823fd70148 

The error also doesn't make any sense in this context. Since it is and should be the same intersection/join table, just selected from the other table. 

### Steps to reproduce
Issue causing the issue. 
https://github.com/ebean-orm/ebean/commit/788a200d166e892781c852f65ba413823fd70148 

```java
  // some java code
@Entity
public class Mail {
    @Id @GeneratedValue private int id;
    private String subject;
    private String body;

    @ManyToMany 
    @JoinTable(name = "mail_inbox_user")
    private List<User> inbox; 
        //Getters and Setters
        ...
}
@Entity
public class User {
    @Id @GeneratedValue int id;

    @ManyToMany (cascade ={CascadeType.ALL})
    @JoinTable(name = "mail_inbox_user")
    private List<Mail> inbox; 

        //Getters and Setters
        ...
}
```

```console
  Error in custom provider, java.lang.IllegalStateException: Property models.User.inbox has duplicate ManyToMany intersection table mail_inbox_user. Please use @JoinTable to define unique table to use
 ```

**Comment by dastultz** [comment]
On Tue, Nov 1, 2016 at 8:03 AM, ZeerDonker <notifications@github.com> wrote:

>
> Being able to reach through the orm, the same many to many relationship
> from either model.
>
You need to decide which side of the relationship should be the "owner".
Model that relationship as you did for User (which I picked as the owner),
then change Mail.inbox to:

@ManyToMany(mappedBy = "inbox")
(remove the @JoinTable)

/Daryl

**Comment by ZeerDonker** [comment]
Thanks
