### ISSUE TITLE
AbstractNamingConvention.getTableName inheritance logic differs from InheritInfo

### ISSUE THREAD

**Issue by ksperling** [ebean-orm/ebean#849]
I've got a type hierarchy with multiple levels of inheritance. The root class is annotated with

```
@Entity
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="type", discriminatorType=DiscriminatorType.STRING, length=4)
```

For classes that derive *indirectly* from the root entity class, ebean ends up using the wrong table name. This seems to be because `AbstractNamingConvention.getTableName` does it's own thing to figure out what's going on with inheritance, and requires an explicit `@Inheritance` annotation on the immediate super class, rather than relying on the `InheritInfo` / `DeployInheritInfo` tree that's already been built and checked by `BeanDescriptorManager`.

## Expected behavior

The table name of the root entity should be used. `createDeployBeanInfo` should probably not even delegate to the naming strategy at all at this point; the table details should be taken directly from the root entity.

## Actual behavior

`AbstractNamingConvention` doesn't see an `@Inheritance` label on the immediate super class and assumes that no inheritance is in play.

The behaviour is the same on 7.12.1 and 8.5.1

**Comment by ksperling** [comment]
Putting `@Inheritance` on every (non-leaf) entity class in the hierarchy seems to work as a workaround.

**Comment by rbygrave** [comment]
Test case:

Have a root inheritance entity bean without a @Table annotation.
```java
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "species")
public abstract class Animal {
``` 
Have a grand-child entity bean without an @Inheritance annotation
```java
@Entity
@DiscriminatorValue("BDG")
public class BigDog extends Dog {
```

The BigDog BeanDescriptor ends up with the incorrect base table (which it should inherit from Animal).
