### ISSUE TITLE
Unit tests fails since last commits

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/ebean#865]
Hi,

Since two last commits (b581c893ecc595283bde87bb3d96d1ba6b0ea3ff and d05b59343235c419785e5c8f9ae76d65a55e2f4f). It seems unit tests fails with PostgreSQL.

![image](https://cloud.githubusercontent.com/assets/1005086/20050698/12c7eef2-a4cb-11e6-830a-15644ffb42b9.png)

More details at https://travis-ci.org/ebean-orm/ebean/builds/173814362

**Comment by rbygrave** [comment]
Yes.  Travis emails me when I break the build.  In this case I commented out:

ebean.ddl.generate=true
ebean.ddl.run=true

... which Postgres needs to run the tests of course - silly me.
