### ISSUE TITLE
How can I exclude id property from generated SQL?

### ISSUE THREAD

**Issue by komajunjun** [ebean-orm/ebean#938]
The generated SQL automatically select ID column, I want to exclude it. How can I do? Is it a bug?

**Comment by dastultz** [comment]
On Tue, Jan 3, 2017 at 3:52 AM, jason <notifications@github.com> wrote:

> The generated SQL automatically select ID column, I want to exclude it.
> How can I do? Is it a bug?
>
Questions and discussion should take place in the Google Group, not the
Github issue tracker.

**Comment by rbygrave** [comment]
Closing - covered on google group.
