### ISSUE TITLE
@Transactional( type = TxType.MANDATORY ) creates a new transaction even if there is one available

### ISSUE THREAD

**Issue by io-levant** [ebean-orm/ebean#941]
`@Transactional( type = TxType.MANDATORY )` creates a new transaction even if there is one available.

With (but found with 7.* artifacts as well):
- io.ebean | ebean | 10.1.3
- io.ebean | ebean-maven-plugin | 10.1.2

## Expected behavior

Calling a method decorated with `@Transactional( type = TxType.MANDATORY )` should result in Ebean using the underlying transaction (or throwing an exception if there is no existing transaction).

## Actual behavior

Even if there is an underlying transaction, Ebean creates a new one (as if it was `@Transactional( type = TxType.REQUIRES_NEW )`).

### Steps to reproduce

```java
@Transactional
public class C {
	@Transactional( type = TxType.MANDATORY )
	public void run( ) {
		logCT( );
	}

	void logCT( ) {
		System.out.println( " > C " + Ebean.currentTransaction( ) );
	}
}
```

```java
@Transactional
public class P {
	public void run( ) {
		logCT( );
		new C( ).run( );
		logCT( );
		new C( ).run( );
		logCT( );
	}

	void logCT( ) {
		System.out.println( "P " + Ebean.currentTransaction( ) );
	}
}
```

```console
P txn[1009] 
 > C txn[1010] 
P txn[1009] 
 > C txn[1011] 
P txn[1009]
```

**Comment by rbygrave** [comment]
Thanks, fixed with the commit above.
