### ISSUE TITLE
DdlGenerator#generateCreateAllDdl generates multiple 'CREATE SEQUENCE' statement if @MappedSuperclass has common sequence

### ISSUE THREAD

**Issue by eyasuyuki** [ebean-orm/ebean#953]
I want to use common sequence for deferent entities.

```
@MappedSuperclass
public abstract class IdBase extends Model {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_base_gen")
    @SequenceGenerator(name="id_base_gen", sequenceName = "id_base_gen")
    protected Long id;
(snip)
```
```
@Entity
@Table(name = "a_data")
public class AData extends IdBase {
    @Column(name = "data", columnDefinition = "text")
    @JsonProperty("data")
    private String data;

//(snip)
```
```
@Entity
@Table(name = "b_data")
public class BData extends IdBase {
    @Column(name = "data", columnDefinition = "text")
    @JsonProperty("data")
    private String data;

//(snip)
```

generated ddl:
```
create table a_data (
  id                            bigint not null,
  data                          text,
  constraint pk_a_data primary key (id)
);
create sequence id_base_gen;

create table b_data (
  id                            bigint not null,
  data                          text,
  constraint pk_b_data primary key (id)
);
create sequence id_base_gen;

/* (snip) */
```

Play 2.5 framework's Evolution execute these DDL, when I got this error.

```
We got the following error: ERROR: relation "id_base_gen" already exists [ERROR:0, SQLSTATE:42P07], while trying to run this SQL script:
```

## Expected behavior

Do not generate same sequence twice.

## Actual behavior

Generates same 'CREATE SEQUENCE' DDL by entity.

### Steps to reproduce

See to of this issue.

**Comment by rbygrave** [comment]
Note that I highly recommend NOT sharing sequences across tables (so the mapping above is something I would recommend not doing).  Sharing sequences increases contention - it can sometimes be low contention but still it is not a great idea.

Also note that Ebean will "do the right thing" based on the database platform so generally speaking if you removed the `@GeneratedValue` and `@SequenceGenerator` altogether and are using a DatabasePlatform that prefers sequences Ebean will generate them (like Oracle). 

Which database are you using?

**Comment by 0xbaadf00d** [comment]
Hi,

What version of Ebean and Play-Ebean are you using ?

**Comment by eyasuyuki** [comment]
I use Ebean 8.2.3, sbt-play-ebean 3.1.0.

**Comment by eyasuyuki** [comment]
And I use PostgreSQL 9.6.1.

**Comment by 0xbaadf00d** [comment]
@eyasuyuki Could you upgrade to Ebean 10.x by using [payintech/play-ebean](https://github.com/payintech/play-ebean) fork ? Maybe your issue will be resolved.

But yes, I'm agree with @rbygrave, sharing sequence across multiple table is a very bad practice and can lead to strange behaviours.

**Comment by rbygrave** [comment]
I'm marking this as "won't fix" and going to close this issue.  I strongly believe it is a bad idea to share sequences as this is trying to do.

A strong case for sharing sequences has to be made to reopen this issue.

Thanks, Rob.
