### ISSUE TITLE
RawSqlBuilder with a WITH query

### ISSUE THREAD

**Issue by PierreAdam** [ebean-orm/ebean#954]
## Expected behavior
When creating a ``RawSql`` object with ``RawSqlBuilder.parse(...).create();`` it would work if you start with a ``WITH`` instruction.
And of course, if you're using a postgresql database.
Documentation of the syntax  : https://www.postgresql.org/docs/9.1/static/queries-with.html 

## Actual behavior
Got an error saying that the expression is "Expected to start with "select"

### Steps to reproduce

``` java
final RawSql rawSql = RawSqlBuilder
    .parse("WITH t1 AS (\n" +
        "    SELECT\n" +
        "      fk_id,\n" +
        "      COUNT(1) AS count\n" +
        "    FROM tableA\n" +
        "    GROUP BY\n" +
        "      fk_id\n" +
        ")\n" +
        "SELECT\n" +
        "  tableB.id,\n" +
        "  tableB.fk_id,\n" +
        "  tableB.value,\n" +
        "FROM tableB\n" +
        "  LEFT JOIN t1 ON t1.fk_id = tableB.fk_id\n" +
        "WHERE\n" +
        "  (tableB.value IS NULL OR tableB.value != t1.count)\n")
    .create();

final ExpressionList<TableBModel> query = TableBModel.find.query().setRawSql(rawSql).where();
```

I was wondering if that kind of behavior is possible in Ebean ? If not, is there an other way to define that ``WITH``

**Comment by rbygrave** [comment]
You should use `EbeanServer.findNative()` ... that should work.

**Comment by PierreAdam** [comment]
Ok I will try that ! Thanks for the information.
