### ISSUE TITLE
Ebean DOCs - not actual example

### ISSUE THREAD

**Issue by 58a36f** [ebean-orm/ebean#959]
Hello,

I was trying to implement paging into my querries , but I was following example on 

[http://ebean-orm.github.io/docs/query/features](url)

```
PagedList<Order> pagedList
  = ebeanServer.find(Order.class)
  .where().eq("status", Order.Status.NEW)
  .order().asc("id")
  .findPagedList(0, 100);

  // Optional: initiate the loading of the total
  // row count in a background thread
  pagedList.loadRowCount();

  // fetch and return the list in the foreground thread
  List<Order> orders = pagedList.getList();

    // get the total row count (from the future)
    int totalRowCount = pagedList.getTotalRowCount();
```

But with latest versions findPagedList(0, 100); does not exists anymore instead example should use `Query.setFirstRow(int) and Query.setMaxRows(int)`

**Comment by rbygrave** [comment]
Please post questions to the Ebean google group as per the policy stated here:
http://ebean-orm.github.io/support

Thanks.
