### ISSUE TITLE
Versionned Model

### ISSUE THREAD

**Issue by HannahJSwystun** [ebean-orm/ebean#961]
Hello Rob and everyone,

Thank you for all releases for this nice entity models and upgrades. :)

Im looking to make a model versionned, and here is my request 👍 

1- Model : 

```
@Entity
@Table(name = "analysis_parameters")
public class Analysis_Parameters extends Model 
{

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "analysis_id")
    public Analysis analysis;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "parameters_id")
    public Parameters parameters;

    @Column(name = "version")
    @Version 
    int version;

    @Column(name = "result")
    public String result; 
```

I would like to auto_increment property VERSION when new parameters are added to the same analysis for example 👍 

![sans titre](https://cloud.githubusercontent.com/assets/20491664/22424922/b209e10c-e6f0-11e6-96f5-e6fe9a34a01a.png)

Thank you so much.

**Comment by adis-me** [comment]
Info: same question posted on SO: http://stackoverflow.com/questions/41937295/versioned-model-ebean-property-version-incrementable

**Comment by HannahJSwystun** [comment]
it is me :)

2017-01-30 19:56 GMT+00:00 Adis Corovic <notifications@github.com>:

**Comment by rbygrave** [comment]
As per the policy here (http://ebean-orm.github.io/support) for this project we do not want or allow questions to be posted as github issues.

Thanks.
