### ISSUE TITLE
FOR UPDATE queries are not honored when beans are already cached

### ISSUE THREAD

**Issue by xunnanxu** [ebean-orm/ebean#970]
## Expected behavior
a SELECT FOR UPDATE query (which acquires ROW SHARE lock) should be treated separately without hitting the bean L2 cache.

## Actual behavior
If the bean is already cached implicitly through a many-to-one relationship, a following FOR UPDATE query would hit the bean cache and thus won't actually lock the row properly.

### Steps to reproduce

```
public EntityA extends Model {

    @Id
    Long id;

    @ManyToOne
    @JoinColumn(name = "b_id")
    EntityB entityB;

}

public EntityB extends Model {

    @Id
    Long id;

}

// this caches B
EntityA.find.byId(1L);

// this is returned from cache and lock isn't acquired
EntityB.find.setForUpdate(true).where().eq("id", 1L).findUnique();

```

```console
select t0.id c0, t0.b_id c4 from entity_as t0 where t0.id = '1'
select t0.id c0 from entity_bs t0 where t0.id = '1'

// no for update
```

**Comment by rbygrave** [comment]
Yes, I am happy with this.  Any query that has `setForUpdate(true)` should not use L2 cache.
