### ISSUE TITLE
Fix website, update version shown on home and releases pages (update to pull version for io.ebean package)

### ISSUE THREAD

**Issue by benmccann** [ebean-orm/ebean#972]
http://ebean-orm.github.io/ and http://ebean-orm.github.io/releases should read `10.1.6` instead of `9.5.1`

**Comment by rbygrave** [comment]
Website fixed.  

Versions now pulled using io.ebean package ... and hence now updated to 10.1.6

Thanks, Rob.

**Comment by benmccann** [comment]
Thanks!
