### ISSUE TITLE
ENH: Add ability to specify a join and alias to use with a specific predicate expression

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#98]
Could this be a possible enhancement?

Consider the following syntax (or something similar, the assignment of a specific alias is the key):

Query query =
Ebean.find(Asset.class)
.join("attributes", "attributes.definitionId, attributes.value", "a1")
.join("attributes", "attributes.definitionId, attributes.value", "a2")
.where()
.eq("a1.definitionId", 57L)
.eq("a1.value", "Quux")
.conjunction()
.eq("a2.definitionId", 56L)
.eq("a2.value", "Foo")
.query();

Refer to: https://groups.google.com/forum/?fromgroups#!topic/ebean/7S6xWMIzNF4

**Comment by maherm** [comment]
Any news on this issue? Or another way to achieve something like the example above? I am currently struggling with the exact same problem...

**Comment by rbygrave** [comment]
The effort is targeted towards ElasticSearch/L3 followed by performance monitoring.  This would follow those (so maybe 2 months away).

At the moment you probably need to look at using RawSql to work around this issue.

**Comment by maherm** [comment]
Okay, thanks for your answer.

**Comment by rbygrave** [comment]
Also note that findNative() is always an option in this sort of case.

**Comment by rbygrave** [comment]
In reviewing this issue, I don't think we are going to add this feature.

The workaround for multiple joins to support multiple predicates currently would be to go to findNative() which is reasonable and I don't see the demand for this feature.

If people hit this issue and really don't want to use the workaround they can push the case for this again.

Closing for now.
