### ISSUE TITLE
Java 8 Optional - findOne() / findOneOrEmpty() ?

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/ebean#996]
## Expected behavior

Returning Java 8 `Optional<? extends Model>` when using the method `findUnique` to allow usage of fallback like `orElse` or `orElseGet` and avoiding the direct  usage of `if (x != null)`

More information about Optional at [Official Java 8 documentation](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html).

## Actual behavior

The method `findUnique` return an instance of the requested model or null.

**Comment by dastultz** [comment]
On Tue, Mar 14, 2017 at 4:29 AM, Thibault Meyer <notifications@github.com>
wrote:

> Expected behavior
>
> Returning Java 8 Optional<? extends Model>
>
>
> This issue reads like a bug report. I would say it's a feature request. I
think it's a good idea but it is of course a  "breaking" API change that
will require a lot of work to patch things up, thus should be considered
carefully.

Also, I think your suggestion is too focused, it should be Optional<T>
where T is the type the Query is returning.

/Daryl

**Comment by rbygrave** [comment]
So at this point I confess I'm not that keen on Optional myself. That is, Optional is an approach (and will  be the only approach for Java for some time and will get better when the JVM adds support for values types) but I am **_much_** more convinced by the Kotlin approach as a long term perspective. 

If you look at findUnique() it is annotated with `@Nullable` which provides IDEs like IntelliJ IDEA the prompt at compile time to check for nulll ... and is compatible with use in Kotlin (null aware).

Now, what we could do is add a second method that returned Optional<T>.  That is not ideal from the perspective of having 2 methods that do pretty much the same thing.  Are there any other APIs that provide 2 find methods?

We would be looking at having:

```java
   -- our existing method
   T findUnique()

  -- Add this ??
  Optional<T> findOptional()
``` 

Also note that Spring Data uses `findOne()` ... which I think you could say is a better method name than findUnique(). Hmmm.

**Comment by rbygrave** [comment]
How about:

```java
// add to be more consistent with spring data
T findOne()

// add providing optional return 
Optional<T> findOrEmpty()

// existing method, deprecate over time in favor of the above 2
T findUnique()

```

**Comment by 0xbaadf00d** [comment]
spring-data have Java 8 binding too. https://github.com/spring-projects/spring-data-examples/blob/34fe9d2720e9402db7708b9101011266d9e00d5a/jpa/java8/README.md

**Comment by dastultz** [comment]
On Fri, Mar 31, 2017 at 5:30 AM, Rob Bygrave <notifications@github.com>
wrote:

> How about:
>
> // add to be more consistent with spring dataT findOne()
>
>
I prefer Spring Data's way:

Optional<T> findOne()


@Nullable which provides IDEs like IntelliJ IDEA the prompt at compile time
> to check for null


I don't want to get off topic, but how is this done? Best I can get are
warning decorations in the editor. I'd be happy with errors in the
"Problems" tab, but ideal would be a way to fail a Gradle build.

/Daryl

**Comment by rbygrave** [comment]
> spring-data have Java 8 binding

Yes, but they are not supporting both there.

> I prefer Spring Data's way:

Sure, but you are possibly not a Kotlin user right.  

That is, if you use Kotlin then you don't want the optional as it is unnecessary, extra reference cost (until we have value objects in the jvm) and not as consistent wrt null safe navigation like customer?.address?.city 

imo If Kotlin didn't exist we'd just return the Optional<T>

>  but ideal would be a way to fail a Gradle build.

It won't compile in Kotlin.  Kotlin compiler sees the @Nullable on the result of the findUnique() and forces you to check for null.

```kotlin
    val customer = Customer.byId(12L)

    // this does not compile in Kotlin ... as customer is known to be a nullable type
    customer.name

    // we need to use ? ...
    customer?.name

    // or check for null ...
   if (customer != null) {
      val name = customer.name
   }
```

**Comment by dastultz** [comment]
On Fri, Mar 31, 2017 at 7:58 AM, Rob Bygrave <notifications@github.com>
wrote:

>
> I prefer Spring Data's way:
>
> Sure, but you are possibly not a Kotlin user right.
>

No, it's all I can do to get on Java 8 :-)

I appreciate you are able to work in Kotlin. I'd probably prefer it myself,
but it's pretty tough to sell to management. It's your project so you can
do what you want, if you want to make it more of a Kotlin tool than a Java
tool...

Kotlin users can still call findUnique(), so adding Optional<T> findOne
doesn't seem to be in conflict.

/Daryl

**Comment by rbygrave** [comment]
Yes. Java is still good, getting better and will be around for a long time. 

Currently as I see it:
- Only having one method returning Optional<T> is not great (for Kotlin people).
- That means we probably should have 2 methods

- findUnique() & findOne() ... not sure I like that combo myself. In 2 years time we might regret that I think
- findOne() & findOrEmpty() ... seems a better combo

Maybe someone has a better suggestion.

**Comment by corrspt** [comment]
I'm with @rbygrave on the `findOrEmpty` (especially if further methods returning `Optional` are also named "XXXorEmpty" for consistency). I could also  live with `findOptional` but I like findOrEmpty better.

**Comment by dastultz** [comment]
On Fri, Mar 31, 2017 at 9:19 AM, Rob Bygrave <notifications@github.com>
wrote:
>
>
>    -
>
>    findOne() & findOrEmpty() ... seems a better combo
>
> findOrEmpty() doesn't convey quantity. I suggest findOneOrEmpty().

/Daryl

**Comment by rbygrave** [comment]
So at this point I think we have the options:
1. findOne() & findOrEmpty()
2. findOne() & findOneOrEmpty()
3. findOne() & findOptional()

I think they are all reasonable, my gut likes the first one.

**Comment by 0xbaadf00d** [comment]
+1 for the first one

**Comment by dastultz** [comment]
On Sat, Apr 1, 2017 at 12:55 AM, Rob Bygrave <notifications@github.com>
wrote:

> So at this point I think we have the options:
>
>    1. findOne() & findOrEmpty()
>    2. findOne() & findOneOrEmpty()
>    3. findOne() & findOptional()
>
>
> We don't *need* findOne() as we already have findUnique(). findOne() was
proposed as name consistent with Spring Data, but it isn't, Spring Data's
findOne() returns Optional. I don't have much experience with Spring Data,
but it seems to me people would end up using Spring Data's findOne() with
Ebean's findOrEmpty() which I don't think is the intent.

The correlate of findOne() is findOneOrEmpty(). The correlate of
findOrEmpty() is simply find(). So #1 is not consistent. I am not convinced
findOne() is any improvement. This issue is originally about findUnique()
returning null vs Optional. If we don't want to change findUnique() to
return Optional, we could add findUniqueOrEmpty(), again because findOne()
is not actually consistent with Spring Data.

Myself, I have a lot of findById() methods that return null that I am in
the process of converting to return Optional. It isn't difficult to simply
add "Optional.ofNullable()" around the existing code. I'm not against
adding a "find singular" method that returns an Optional, I just don't
think we need it, and if we add it I want the name to be consistent.

So among the 3 options presented, I'm +1 for #2, or maybe I'm more than +1
as I am an Ebean Council member.

I'd be happier with option #4. findUnique() and findUniqueOrEmpty().

/Daryl

**Comment by rbygrave** [comment]
>  option #4. findUnique() and findUniqueOrEmpty().

Cool. I think we can ponder for a few days and see how we feel then.


> findOne() was proposed as name consistent with Spring Data, but it isn't, Spring Data's
findOne() returns Optional.

Yes it is actually.  Springs CrudRepository has: `T findOne()` it does not return `Optional<T>`.  
http://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#findOne-ID-

I believe what Spring did was give developers the ability to extend a `Repository` with our own method that returns an Optional.  
http://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/Repository.html
... there is no `Optional<T> findOne()` there, but you are allowed to extend and add it yourself. However, if you create a  `Optional<T> findOne()` that will clash with the existing method on `CrudRepository` so to do that we'd have to extend `Repository` and that means we lose the features of `CrudRepository` and `PagingAndSortingRepository` - that is a bit lame.


>  I am not convinced findOne() is any improvement. 

I think there are 2 arguments for it.
1.  It makes the Ebean API more consistent with Spring data
2.  I think findOne() provides a slightly better name for the "find first / max rows 1" case.

Personally I've seen quite a bit of Spring data use.  I'd say that Spring data fills relatively important gaps in JPA (like Paging queries via PagingAndSortingRepository).   

Ebean lines up reasonably closely with Spring data CrudRepository / PagingAndSortingRepository API.  Spring data hides/manages the EntityManager so the API lines up pretty closely to Ebean with save(), delete(), findOne(), paging queries  etc.

**Comment by dastultz** [comment]
On Sun, Apr 2, 2017 at 4:36 AM, Rob Bygrave <notifications@github.com>
wrote:

> option #4 <https://github.com/ebean-orm/ebean/issues/4>. findUnique() and
> findUniqueOrEmpty().
>
> Cool. I think we can ponder for a few days and see how we feel then.
>
> findOne() was proposed as name consistent with Spring Data, but it isn't,
> Spring Data's
> findOne() returns Optional.
>
> Yes it is actually. Springs CrudRepository has: T findOne() it does not
> return Optional<T>.
>
OK, Thibault posted this link earlier in the thread:
https://github.com/spring-projects/spring-data-examples/blob/34fe9d2720e9402db7708b9101011266d9e00d5a/jpa/java8/README.md

which shows findOne returning Optional, so an understandable
misinterpretation on my part.

> I think there are 2 arguments for it.
>
>    1. It makes the Ebean API more consistent with Spring data
>    2. I think findOne() provides a slightly better name for the "find
>    first / max rows 1" case.
>
> Now that I understand that Thibault's post was an extension to Spring Data
and not core Spring Data I retract by statement that Ebean findOne() is
inconsistent with Spring Data findOne(). I still maintain that
findOneOrEmpty() is the correlate. I've not heard an argument for why
findOrEmpty() is better, just that people "like it". In today's world of
super-smart IDEs, "less typing" isn't a very strong argument.
Self-documenting code is better.

/Daryl

**Comment by rbygrave** [comment]
So personally I am leaning towards:
- findOne()
- findOneOrEmpty()

There was some decent discussion on this topic in the Kotlin forums.  As I see it there is no perfect answer here.  We could also just leave it as is but we are the only API I know that uses findUnique() per say ... so getting closer to spring data API makes sense to me.
