### ISSUE TITLE
TypeReflectHelper does not resolve type variables correctly in non-trivial cases

### ISSUE THREAD

**Issue by ksperling** [ebean-orm/ebean#997]
## Expected behavior

* `TypeReflectHelper` should work when the interface holding the type variables in question is implemented indirectly by a super-class
* `TypeReflectHelper` should work when a type variable is in turn bound to another type variable.

For example

```
public class ProtobufConverter<M extends Message<M, ?>> implements ScalarTypeConverter<M, byte[]> { ... }
public final class RichTextConverter extends ProtobufConverter<RichText> {};
```

One simple fix would be to use https://github.com/jhalterman/typetools instead of `TypeReflectHelper` (if adding any dependencies to the ebean core is undesirable the single `TypeResolver` class provided by typetools could be added into the project directly either at build time or manually.)

As an aside, it would be neat if ebean supported generic converters like `ProtobufConverter` without creating a sub-class for each concrete type I need to map, but this would require resolving the type bound as well as an (optional) 2-arg version of `wrapValue` that gets the concrete type being mapped to provided to it at runtime (based on the declared type of the entity property being mapped). All in all probably too much complexity.

## Actual behavior

* `TypeReflectHelper.getParamType` only looks at direct interfaces
* After fixing `getParamType` to traverse up the hierarchy, `getParams` will then fail if the bound value is itself a `java.lang.reflect.TypeVariable`

### Steps to reproduce

```console
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
	at io.ebeaninternal.server.type.TypeReflectHelper.getClass(TypeReflectHelper.java:24)
	at io.ebeaninternal.server.type.TypeReflectHelper.getParams(TypeReflectHelper.java:13)
	at io.ebeaninternal.server.type.DefaultTypeManager.initialiseScalarConverters(DefaultTypeManager.java:701)
	at io.ebeaninternal.server.type.DefaultTypeManager.<init>(DefaultTypeManager.java:200)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:133)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:130)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:1)
	at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)```

**Comment by rbygrave** [comment]
Hi @ksperling , Did you get around this issue some way or still looking for a fix/improvement here?
Cheers, Rob.

**Comment by ksperling** [comment]
Well, a workaround that works is to re-declare the `ScalarTypeConverter` interface on the concrete class, however I think replacing TypeResolve with the TypeResolver from typetools would still be a good idea as it'll "Just Work" in these cases.

**Comment by rbygrave** [comment]
> I think replacing TypeResolve with the TypeResolver from typetools would still be a good idea 

Yes. That is what we have done just now. We have got a cut down version of TypeResolver to support what we need without the lamda support (and hence without the use of sun.misc.Unsafe that it had).

Tests passing - considering fixed.

**Comment by rbygrave** [comment]
... and thanks for that work Karsten.  Made it a pretty fast and easy thing to fix (even if it took me a while to get to it).

Cheers, Rob.
